Repository tensorflow/tensorflow, pull requests merged in 2018-06, with the labels that each got.

#19678 Manual roll back of PR #19443, because it causes the Raspberry Pi build to fail
  tensorflow/core/platform/default/build_config.bzl
  tensorflow/tensorflow.bzl
  tensorflow/tools/api/generator/BUILD
Labels: cla: yes

#19636 docker: update cuDNN to 7.1.4.18
  tensorflow/tools/docker/Dockerfile.devel-gpu
  tensorflow/tools/docker/Dockerfile.gpu
Labels: awaiting testing (then merge), cla: yes

#19599 BUILD: dont force stripping
  configure.py
  tensorflow/BUILD
Labels: awaiting testing (then merge), cla: yes

#19699 [Intel MKL] Finished support for bad usernames in the CI build scripts.
  tensorflow/tools/ci_build/builds/with_the_same_user
  tensorflow/tools/ci_build/ci_build.sh
Labels: cla: yes

#19703 Updating version for 1.9.0-rc0.
  tensorflow/core/public/version.h
  tensorflow/docs_src/get_started/eager.md
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/docker/Dockerfile.devel
  tensorflow/tools/docker/Dockerfile.devel-cpu-mkl
  tensorflow/tools/docker/Dockerfile.devel-gpu
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#19609 Add a note that stop_gradient in moments does not change the gradient
  tensorflow/python/ops/nn_impl.py
Labels: awaiting testing (then merge), cla: yes

#17885 make toco build for android
  tensorflow/contrib/lite/toco/toco_port.cc
  tensorflow/contrib/lite/toco/toco_port.h
Labels: awaiting review, cla: yes, comp:lite

#18423 Fix print function with tf_logging.info to keep consistence
  tensorflow/contrib/fused_conv/python/ops/fused_conv2d_bias_activation_op_test.py
  tensorflow/python/kernel_tests/betainc_op_test.py
  tensorflow/python/kernel_tests/conv_ops_test.py
  tensorflow/python/kernel_tests/pooling_ops_test.py
  tensorflow/tools/quantization/quantize_graph_test.py
Labels: cla: yes

#18783 Switch from tf.contrib.metrics to tf.metrics
  tensorflow/contrib/slim/python/slim/evaluation_test.py
  tensorflow/contrib/tensor_forest/client/eval_metrics.py
Labels: cla: yes

#19638 Update WORKSPACE
  WORKSPACE
Labels: cla: yes

#19542 Support session config in tf.contrib.predictor
  tensorflow/contrib/predictor/contrib_estimator_predictor.py
  tensorflow/contrib/predictor/core_estimator_predictor.py
  tensorflow/contrib/predictor/predictor_factories.py
  tensorflow/contrib/predictor/predictor_factories_test.py
  tensorflow/contrib/predictor/saved_model_predictor.py
Labels: awaiting testing (then merge), cla: yes

#19537 Add batch support for random tf.image.random_flip_*
  tensorflow/python/ops/image_ops_impl.py
  tensorflow/python/ops/image_ops_test.py
Labels: awaiting testing (then merge), cla: yes

#19356 check grpc_testlib_server before start subprocess
  tensorflow/core/distributed_runtime/rpc/grpc_testlib.cc
Labels: awaiting testing (then merge), cla: yes

#19689 fix typo
  tensorflow/contrib/metrics/python/ops/metric_ops.py
  tensorflow/python/ops/nn_impl.py
Labels: awaiting testing (then merge), cla: yes

#16993 Fix broken link in tfmobile documentation
  tensorflow/docs_src/mobile/linking_libs.md
Labels: awaiting testing (then merge), cla: yes

#17898 Fix the quantized table order by float value for easy reading
  tensorflow/docs_src/performance/quantization.md
Labels: awaiting review, cla: yes

#19221 fix docstring
  tensorflow/python/ops/variable_scope.py
Labels: awaiting testing (then merge), cla: yes

#18348 Fix some minor incorrect anchor links
  tensorflow/docs_src/install/install_sources.md
Labels: awaiting testing (then merge), cla: yes

#19336 Fallback to dynamic loader even if HADOOP_HDFS_HOME is not defined
  tensorflow/core/platform/hadoop/hadoop_file_system.cc
Labels: cla: yes

#19278 Fix fake quantization link
  tensorflow/contrib/quantize/README.md
Labels: cla: yes

#18968 Update mobile prepare models documentation
  tensorflow/docs_src/mobile/prepare_models.md
Labels: cla: yes

#19713 Replace direct download link with bazel mirror (mirror.bazel.build)
  tensorflow/contrib/lite/download_dependencies.sh
  tensorflow/contrib/makefile/download_dependencies.sh
Labels: cla: yes

#19335 fix iris example to work with python3
  tensorflow/examples/learn/iris.py
Labels: awaiting testing (then merge), cla: yes

#19724 Add int16 support for `tf.as_string`
  tensorflow/core/kernels/as_string_op.cc
  tensorflow/core/ops/string_ops.cc
  tensorflow/python/kernel_tests/as_string_op_test.py
Labels: cla: yes

#19714 Add complex numbers to the supported data types for UnsortedSegmentProd
  tensorflow/core/ops/math_ops.cc
  tensorflow/python/kernel_tests/segment_reduction_ops_test.py
Labels: cla: yes

#18854 Fix variance initialisers
  tensorflow/python/keras/initializers_test.py
  tensorflow/python/kernel_tests/init_ops_test.py
  tensorflow/python/ops/init_ops.py
Labels: awaiting testing (then merge), cla: yes

#18926 Add globs from Lambda before building it
  tensorflow/python/estimator/keras_test.py
  tensorflow/python/keras/layers/core.py
Labels: awaiting testing (then merge), cla: yes

#18948 DOC: add more explanation for auxiliary_name_scope
  tensorflow/python/ops/variable_scope.py
Labels: awaiting testing (then merge), cla: yes

#19328 Fix issue in Keras model complie with float64 mode
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/models_test.py
Labels: awaiting testing (then merge), cla: yes

#19634 Fix redundancy in RELEASE.md
  RELEASE.md
Labels: cla: yes

#19711 Remove duplicate imports
  tensorflow/contrib/ffmpeg/__init__.py
  tensorflow/contrib/ffmpeg/ffmpeg_ops.py
Labels: cla: yes

#19650 Add support of string split behavior compatible with python's `str.split`
  tensorflow/core/api_def/base_api/api_def_StringSplitV2.pbtxt
  tensorflow/core/api_def/python_api/api_def_StringSplitV2.pbtxt
  tensorflow/core/kernels/string_split_op.cc
  tensorflow/core/ops/string_ops.cc
  tensorflow/python/kernel_tests/string_split_op_test.py
  tensorflow/python/ops/string_ops.py
  tensorflow/tools/api/golden/tensorflow.strings.pbtxt
Labels: cla: yes

#15337 added crucial documentation on SELU activation
  tensorflow/core/api_def/base_api/api_def_Selu.pbtxt
  tensorflow/go/op/wrappers.go
  tensorflow/python/keras/activations.py
Labels: awaiting testing (then merge), cla: yes

#19635 Fix mismatch of shape restriction in DrawBoundingBoxes
  tensorflow/core/ops/image_ops.cc
Labels: awaiting testing (then merge), cla: yes

#19753 Expose `tf.broadcast_to` op
  tensorflow/contrib/framework/__init__.py
  tensorflow/core/api_def/python_api/api_def_BroadcastTo.pbtxt
  tensorflow/tools/api/golden/tensorflow.pbtxt
Labels: API review, cla: yes

#19651 Fix incorrect documentation for `tf.reduce_any`/`tf.reduce_all`
  tensorflow/python/ops/math_ops.py
Labels: cla: yes

#19649 Add normalizer_fn support for sequence_numeric_column
  tensorflow/contrib/feature_column/python/feature_column/sequence_feature_column.py
  tensorflow/contrib/feature_column/python/feature_column/sequence_feature_column_test.py
Labels: awaiting review, cla: yes

#16520 Periodic resample operation gradients and optimization
  tensorflow/contrib/periodic_resample/BUILD
  tensorflow/contrib/periodic_resample/kernels/periodic_resample_op.cc
  tensorflow/contrib/periodic_resample/kernels/periodic_resample_op.h
  tensorflow/contrib/periodic_resample/ops/array_ops.cc
  tensorflow/contrib/periodic_resample/ops/array_ops_test.cc
  tensorflow/contrib/periodic_resample/python/kernel_tests/periodic_resample_op_test.py
  tensorflow/contrib/periodic_resample/python/ops/periodic_resample_op.py
Labels: awaiting testing (then merge), cla: yes

#19708 [XLA] Explicitly use ::xla::Layout
  tensorflow/compiler/xla/service/pattern_matcher.h
Labels: awaiting testing (then merge), cla: yes

#19702 Updating release notes for r1.9.
  RELEASE.md
Labels: cla: yes

#19780 Change order of installations.
  tensorflow/tools/ci_build/install/install_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
Labels: cla: yes

#19781 Fixing the adamax_test rtol to be more lenient.
  tensorflow/contrib/opt/python/training/adamax_test.py
Labels: cla: yes

#19782 Fix for Raspberry Pi build breakage
  tensorflow/contrib/lite/toco/toco_port.cc
Labels: cla: yes

#19786 contrib/eagerpython/datasets: Resource naming workaround.
  tensorflow/contrib/eager/python/datasets.py
Labels: cla: yes

#19767 Update install_linux.md
  tensorflow/docs_src/install/install_linux.md
Labels: awaiting testing (then merge), cla: yes

#19662 Add C++ no gradient for Floor operation.
  tensorflow/cc/gradients/math_grad.cc
Labels: awaiting testing (then merge), cla: yes

#19788 Cherrypicks2
  tensorflow/contrib/eager/python/datasets.py
  tensorflow/contrib/opt/python/training/adamax_test.py
  tensorflow/tools/ci_build/install/install_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
Labels: cla: yes

#19793 Adding the autograph operators dependency to the pip package.
  tensorflow/tools/pip_package/BUILD
Labels: awaiting testing (then merge), cla: yes

#19805 Fix failing tests.
  tensorflow/contrib/autograph/__init__.py
Labels: cla: yes

#19804 Update backprop.py
  tensorflow/python/eager/backprop.py
Labels: awaiting testing (then merge), cla: yes

#19796 TFLite: fix format mismatching warning.
  tensorflow/contrib/lite/examples/minimal/minimal.cc
Labels: awaiting testing (then merge), cla: yes, comp:lite

#19815 Update __init__.py
  tensorflow/contrib/autograph/__init__.py
Labels: awaiting testing (then merge), cla: yes

#19817 Iteritems is deprecated in python 3. Using items instead.
  tensorflow/contrib/distribute/python/cross_tower_ops_test.py
Labels: cla: yes

#19818 Fixing the setuptools issue for pip builds.
  tensorflow/tools/ci_build/builds/pip.sh
Labels: cla: yes

#19819 Force downgrade setuptools for tests after tf whl is installed.
  tensorflow/tools/ci_build/builds/pip.sh
Labels: cla: yes

#19789 Removed unneeded file copy that was causing failure in Pi builds
  tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
Labels: cla: yes

#19820 Adding a constraint for the setuptools version.
  tensorflow/tools/ci_build/builds/pip.sh
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#19790 Adding the autograph operators dependency to the pip package.
  tensorflow/tools/pip_package/BUILD
Labels: awaiting testing (then merge), cla: yes

#19794 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes

#19841 Consolidate `tf.data` release notes.
  RELEASE.md
Labels: cla: yes

#19719 Mentioned Visual C++ 2015 dependency for Windows JNI library
  tensorflow/docs_src/install/install_java.md
Labels: awaiting testing (then merge), cla: yes

#19707 [Intel MKL] Bootstrapping MKL test infrastructure
  tensorflow/tools/ci_build/linux/mkl/basic-mkl-test.sh
Labels: cla: yes, stat:awaiting response

#18628 Add decode uint16 PNG images support for tf.image.decode_image.
  tensorflow/python/ops/image_ops_impl.py
  tensorflow/python/ops/image_ops_test.py
  tensorflow/tools/api/golden/tensorflow.image.pbtxt
Labels: awaiting testing (then merge), cla: yes

#19846 Update RELEASE.md for tfdbg bug fix in 1.9.0
  RELEASE.md
Labels: cla: yes

#19860 Skipped the check that fails due to overflow error as float128 dataty…
  tensorflow/contrib/distributions/python/kernel_tests/bijectors/sinh_arcsinh_bijector_test.py
Labels: awaiting testing (then merge), cla: yes

#19844 Added the tutorials link
  README.md
Labels: awaiting testing (then merge), cla: yes

#19866 Update RELEASE.md (r1.9) for tfdbg and XLA
  RELEASE.md
Labels: cla: yes

#19870 Fix logging issue in remapper.cc and Linking issue with scoped_allocator_optimizer
  tensorflow/core/grappler/optimizers/BUILD
  tensorflow/core/grappler/optimizers/remapper.cc
Labels: cla: yes

#19769 [XLA] Allow the tuple simplifier to operate on only subcomputations
  tensorflow/compiler/xla/service/tuple_simplifier.cc
  tensorflow/compiler/xla/service/tuple_simplifier.h
  tensorflow/compiler/xla/service/tuple_simplifier_test.cc
Labels: awaiting testing (then merge), cla: yes

#19869 [Intel MKL] Remove use of absl::string_view
  tensorflow/core/util/mkl_util.h
Labels: cla: yes

#19902 Disable tensorflow/python/estimator:keras_test on Windows
  tensorflow/python/estimator/BUILD
Labels: cla: yes

#19923 Fix typo
  tensorflow/contrib/eager/python/examples/notebooks/4_high_level.ipynb
Labels: cla: yes

#19941 [Java] Remove @Generated annotation by notice
  tensorflow/java/src/gen/cc/op_generator.cc
Labels: awaiting testing (then merge), cla: yes

#19925 release 1.9-rc1 cherry-pick request: opt out of saving tpu graph
  tensorflow/contrib/tpu/python/tpu/tpu_estimator.py
Labels: cla: yes

#19878 Require same shape for `x` and `y` in shape function of `ApproximateEqual`
  tensorflow/core/ops/math_ops.cc
  tensorflow/python/ops/math_ops_test.py
Labels: awaiting testing (then merge), cla: yes

#19754 INTEL-MKL: MKL primitive reuse for conv2d fwd op - refactoring per PR suggestion
  tensorflow/core/kernels/mkl_conv_ops.cc
  tensorflow/core/util/mkl_util.h
Labels: awaiting testing (then merge), cla: yes

#19985 Fixed compilation error (undefined reference to LLVMInitializePowerPC…
  tensorflow/compiler/xla/service/cpu/BUILD
Labels: awaiting testing (then merge), cla: yes

#19983 Fix for compilation failure in gdr_server_lib.cc
  tensorflow/contrib/gdr/gdr_server_lib.cc
Labels: awaiting testing (then merge), cla: yes

#19942 Make implementation of GrpcServer::Init with Collective Ops compatible with calls in contrib/mpi
  tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc
  tensorflow/core/distributed_runtime/rpc/grpc_server_lib.h
Labels: awaiting testing (then merge), cla: yes

#19990 Remove duplicate import in linear_equations.py
  tensorflow/contrib/solvers/python/ops/linear_equations.py
Labels: awaiting testing (then merge), cla: yes

#19978 [XLA] Change the visibility of the graph builder
  tensorflow/compiler/xla/service/BUILD
Labels: awaiting testing (then merge), cla: yes

#19993 Fix build issue on mac with python-3.7.10 and clang-9.1.0
  tensorflow/contrib/lite/python/interpreter_wrapper/interpreter_wrapper.h
  tensorflow/python/lib/core/numpy.h
  tensorflow/python/lib/core/py_util.cc
Labels: cla: yes

#19977 r1.9-rc2 cherry-pick request: Documentation for Raspberry Pi installation
  tensorflow/docs_src/install/index.md
  tensorflow/docs_src/install/install_raspbian.md
Labels: awaiting review, cla: yes

#19867 1.9-rc0 cherry-pick request: Keras symbol visibility, and `Dataset` evaluation fixes.
  tensorflow/python/keras/__init__.py
  tensorflow/python/keras/engine/training_eager.py
  tensorflow/python/keras/engine/training_eager_test.py
  tensorflow/python/keras/integration_test.py
  tensorflow/python/keras/losses.py
  tensorflow/python/ops/init_ops.py
  tensorflow/tools/api/golden/tensorflow.keras.initializers.constant.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.identity.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.normal.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.ones.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.orthogonal.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.random_normal.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.random_uniform.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.truncated_normal.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.uniform.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.initializers.zeros.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.losses.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.metrics.pbtxt
Labels: cla: yes

#19960 r1.9-rc1 cherry-pick request: Fix module docstrings
  tensorflow/tools/api/generator/BUILD
  tensorflow/tools/api/generator/create_python_api.py
  tensorflow/tools/api/generator/doc_srcs.py
  tensorflow/tools/api/generator/doc_srcs_test.py
Labels: cla: yes

#19963 Check to ensure the Cloud TPU is ready before resolving.
  tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py
  tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver_test.py
Labels: awaiting review, cla: yes

#19994 Update tensorboard dependency to 1.9.x
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#17438 Add optimizers with decoupled weight decay.
  tensorflow/contrib/opt/BUILD
  tensorflow/contrib/opt/__init__.py
  tensorflow/contrib/opt/python/training/weight_decay_optimizers.py
  tensorflow/contrib/opt/python/training/weight_decay_optimizers_test.py
Labels: awaiting testing (then merge), cla: yes

#19997 r1.9-rc1 cherry-pick request: Keras save_weights fix
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/engine/saving_test.py
Labels: awaiting review, cla: yes

#19999 r1.9-rc1 cherry-pick request: bugfix/memory leak fix
  tensorflow/python/eager/pywrap_tfe_src.cc
Labels: awaiting testing (then merge), cla: yes

#19980 Space handling in equation parameter of tf.einsum
  tensorflow/python/ops/special_math_ops.py
  tensorflow/python/ops/special_math_ops_test.py
Labels: awaiting testing (then merge), cla: yes

#19188 Add TensorFlow ecosystem Spark and Hadoop jars to Maven deployment
  tensorflow/java/maven/.gitignore
  tensorflow/java/maven/README.md
  tensorflow/java/maven/hadoop/pom.xml
  tensorflow/java/maven/pom.xml
  tensorflow/java/maven/run_inside_container.sh
  tensorflow/java/maven/spark-connector/pom.xml
Labels: awaiting testing (then merge), cla: yes

#19972 Removed unnecessary copying of dict
  tensorflow/python/estimator/export/export.py
Labels: awaiting testing (then merge), cla: yes

#19953 tensorflow/go: operation attribute getters
  tensorflow/go/attrs.go
  tensorflow/go/attrs_test.go
Labels: awaiting testing (then merge), cla: yes

#20002 Make GCS ops work in open source
  tensorflow/contrib/cloud/__init__.py
  tensorflow/contrib/cloud/kernels/BUILD
  tensorflow/contrib/cloud/ops/gcs_config_ops.cc
  tensorflow/core/api_def/base_api/api_def_GcsConfigureBlockCache.pbtxt
  tensorflow/core/api_def/base_api/api_def_GcsConfigureCredentials.pbtxt
  tensorflow/core/platform/cloud/gcs_file_system.cc
  tensorflow/core/platform/default/build_config.bzl
Labels: cla: yes

#19976 BestExporter cherry-pick request for r1.9: Only calls compare function if values were read from event file
  tensorflow/python/estimator/exporter.py
  tensorflow/python/estimator/exporter_test.py
Labels: awaiting testing (then merge), cla: yes

#19929 Fix merge layers in tf.keras
  tensorflow/python/keras/layers/__init__.py
  tensorflow/python/keras/layers/merge.py
  tensorflow/tools/api/golden/tensorflow.keras.layers.-minimum.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.layers.-subtract.pbtxt
  tensorflow/tools/api/golden/tensorflow.keras.layers.pbtxt
Labels: awaiting testing (then merge), cla: yes

#20017 Sync package version of double-conversion between bazel and cmake
  tensorflow/contrib/cmake/external/double_conversion.cmake
Labels: cla: yes

#20027 Fix git_tag_override option in gen_git_source.py.
  tensorflow/tools/git/gen_git_source.py
Labels: cla: yes

#20036 Update debugger.md
  tensorflow/docs_src/programmers_guide/debugger.md
Labels: cla: yes

#20033 Invalid Python example in baseline.py
  tensorflow/python/estimator/canned/baseline.py
Labels: cla: yes

#19966 opencv interop fix: exclude libjpeg symbols from libtensorflow_framew…
  tensorflow/BUILD
  tensorflow/tf_framework_version_script.lds
Labels: cla: yes

#20025 Fix missing header in aarch64 Nvidia Jetson
  tensorflow/contrib/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
Labels: awaiting testing (then merge), cla: yes

#20037 [Intel MKL] Bootstrapping MKL+GPU test
  tensorflow/tools/ci_build/linux/gpu/run_mkl.sh
  tensorflow/tools/ci_build/linux/mkl/basic-mkl-gpu-test.sh
Labels: awaiting review, cla: yes

#20044 contrib: autograph/constrained_optimization: minor spelling tweaks
  tensorflow/contrib/autograph/converters/control_flow.py
  tensorflow/contrib/autograph/operators/control_flow.py
  tensorflow/contrib/autograph/pyct/static_analysis/cfg.py
  tensorflow/contrib/autograph/pyct/transformer.py
  tensorflow/contrib/constrained_optimization/README.md
Labels: cla: yes

#20063 Fix: DepthwiseConv2D fails when bias is enabled
  tensorflow/python/keras/layers/convolutional.py
  tensorflow/python/keras/layers/convolutional_test.py
Labels: awaiting testing (then merge), cla: yes

#19309 Generate Java graph building API from @Operator annotated classes
  tensorflow/core/api_def/BUILD
  tensorflow/core/api_def/java_api/api_def_Assert.pbtxt
  tensorflow/core/api_def/java_api/api_def_Const.pbtxt
  tensorflow/core/api_def/java_api/api_def_Switch.pbtxt
  tensorflow/java/BUILD
  tensorflow/java/src/gen/cc/op_generator.cc
  tensorflow/java/src/gen/cc/op_specs.cc
  tensorflow/java/src/gen/cc/op_specs.h
  tensorflow/java/src/gen/java/org/tensorflow/processor/OperatorProcessor.java
  tensorflow/workspace.bzl
Labels: awaiting testing (then merge), cla: yes

#20051 Add mirror for nasm in workspace.bzl
  tensorflow/workspace.bzl
Labels: awaiting testing (then merge), cla: yes

#20048 fix TF_GraphImportGraphDefWithResults and TF_GraphImportGraphDefWithR…
  tensorflow/c/c_api.cc
Labels: awaiting review, cla: yes

#14853 Automate download and unzip of the model file
  tensorflow/contrib/lite/java/demo/app/build.gradle
  tensorflow/docs_src/mobile/tflite/demo_android.md
Labels: awaiting testing (then merge), cla: yes, comp:lite

#20065 [Intel MKL] Fixing MKL graph layout pass test
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: awaiting testing (then merge), cla: yes

#20097 r1.9 cherry-pick request: Fix keras guide (docs only)
  tensorflow/docs_src/programmers_guide/keras.md
Labels: cla: yes

#20101 Add missing Eager relnotes for TensorFlow 1.9.
  RELEASE.md
Labels: cla: yes

#20084 Neural Machine Translation with Attention
  tensorflow/contrib/eager/python/examples/nmt_with_attention/NMT_with_Attention.ipynb
Labels: awaiting testing (then merge), cla: yes

#19545 [tfgan] Add possibility to export GANEstimator saved model
  tensorflow/contrib/gan/python/estimator/python/head_impl.py
  tensorflow/contrib/gan/python/estimator/python/head_test.py
Labels: awaiting review, awaiting testing (then merge), cla: yes

#20104 Changing the colab link to the right one
  tensorflow/contrib/eager/python/examples/nmt_with_attention/NMT_with_Attention.ipynb
Labels: cla: yes

#20107 Update tb-nightly dep to >= 1.10.0a0, < 1.11.0a0
  tensorflow/tools/pip_package/setup.py
Labels: awaiting testing (then merge), cla: yes

#20123 Fix warning in constrained_optimization test
  tensorflow/contrib/constrained_optimization/python/swap_regret_optimizer.py
Labels: awaiting testing (then merge), cla: yes

#17814 Add resize_image_aspect_with_pad method
  tensorflow/python/ops/image_ops_impl.py
  tensorflow/python/ops/image_ops_test.py
  tensorflow/tools/api/golden/tensorflow.image.pbtxt
Labels: awaiting testing (then merge), cla: yes

#20129 Cleanup NMT notebook, fix image links
  tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb
Labels: cla: yes

#20127 Fix kCall comparison
  tensorflow/compiler/xla/service/hlo_instruction.cc
  tensorflow/compiler/xla/service/hlo_instruction_test.cc
Labels: awaiting testing (then merge), cla: yes

#20130 [GCS] Typo in ConfigureGcsHook.
  tensorflow/contrib/cloud/python/ops/gcs_config_ops.py
Labels: cla: yes

#20152 Remove duplicate imports in dynamic_stitch_op_test.py
  tensorflow/python/kernel_tests/dynamic_stitch_op_test.py
Labels: cla: yes

#20163 Move external/ directory in pip package.
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: cla: yes

#20151 fixed typo in docstring
  tensorflow/python/training/checkpoint_utils.py
Labels: awaiting testing (then merge), cla: yes

#20165 Removed tfe
  tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb
Labels: awaiting testing (then merge), cla: yes

#20102 cpu and gpu Dockerfiles for ppc64le
  tensorflow/tools/ci_build/Dockerfile.cpu.ppc64le
  tensorflow/tools/ci_build/Dockerfile.gpu.ppc64le
  tensorflow/tools/ci_build/ci_build.sh
  tensorflow/tools/ci_build/ci_parameterized_build.sh
  tensorflow/tools/ci_build/install/install_bazel_from_source.sh
  tensorflow/tools/ci_build/install/install_buildifier_from_source.sh
  tensorflow/tools/ci_build/install/install_golang_ppc64le.sh
Labels: awaiting testing (then merge), cla: yes

#19715 [CMAKE] Improve cmake build for MKL and MKL-DNN on Windows
  .gitignore
  tensorflow/contrib/cmake/CMakeLists.txt
  tensorflow/contrib/cmake/external/mkl.cmake
  tensorflow/contrib/cmake/external/mkldnn.cmake
  tensorflow/contrib/cmake/tf_python.cmake
  tensorflow/contrib/cmake/tf_shared_lib.cmake
  tensorflow/core/common_runtime/mkl_cpu_allocator.cc
  tensorflow/core/platform/windows/port.cc
Labels: awaiting testing (then merge), cla: yes

#20180 Fix a typo
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
Labels: awaiting testing (then merge), cla: yes

#18545 fix command line example package path
  tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md
Labels: awaiting testing (then merge), cla: yes, comp:lite

#20153 Fix OOB check for result_index in header generation
  tensorflow/compiler/aot/codegen.cc
Labels: awaiting testing (then merge), cla: yes

#20172 Update Keras datasets file handling
  tensorflow/python/keras/datasets/boston_housing.py
  tensorflow/python/keras/datasets/mnist.py
  tensorflow/python/keras/datasets/reuters.py
Labels: awaiting testing (then merge), cla: yes

#20195 Move external/ directory in pip package.
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: awaiting testing (then merge), cla: yes

#20204 1.9.0rc2 cherry-pick request: [tf.data] Properly export `choose_from_datasets()`
  tensorflow/contrib/data/__init__.py
Labels: cla: yes

#20202 Fix doc discrepancy in tf.scatter_add
  tensorflow/python/ops/state_ops.py
Labels: cla: yes

#20181 Update curl library to curl-7.60.0
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: awaiting review, cla: yes

#20182 Update jsoncpp to 1.8.4
  tensorflow/core/platform/cloud/oauth_client.cc
  tensorflow/core/profiler/internal/tfprof_timeline.cc
  tensorflow/workspace.bzl
  third_party/jsoncpp.BUILD
Labels: awaiting review, cla: yes

#20184 Update lmdb to 0.9.22
  tensorflow/workspace.bzl
Labels: awaiting review, cla: yes

#20186 Update flatbuffers to 1.9.0
  tensorflow/workspace.bzl
  third_party/flatbuffers/flatbuffers.BUILD
Labels: awaiting review, cla: yes

#19871 Dynamic ops
  configure.py
  tensorflow/contrib/tensorrt/BUILD
  tensorflow/contrib/tensorrt/convert/convert_graph.cc
  tensorflow/contrib/tensorrt/convert/convert_graph.h
  tensorflow/contrib/tensorrt/convert/convert_nodes.cc
  tensorflow/contrib/tensorrt/convert/convert_nodes.h
  tensorflow/contrib/tensorrt/convert/trt_optimization_pass.cc
  tensorflow/contrib/tensorrt/convert/trt_optimization_pass.h
  tensorflow/contrib/tensorrt/convert/utils.h
  tensorflow/contrib/tensorrt/kernels/trt_calib_op.cc
  tensorflow/contrib/tensorrt/kernels/trt_calib_op.h
  tensorflow/contrib/tensorrt/kernels/trt_engine_op.cc
  tensorflow/contrib/tensorrt/kernels/trt_engine_op.h
  tensorflow/contrib/tensorrt/ops/trt_calib_op.cc
  tensorflow/contrib/tensorrt/ops/trt_engine_op.cc
  tensorflow/contrib/tensorrt/python/trt_convert.py
  tensorflow/contrib/tensorrt/resources/trt_allocator.cc
  tensorflow/contrib/tensorrt/resources/trt_allocator.h
  tensorflow/contrib/tensorrt/resources/trt_int8_calibrator.cc
  tensorflow/contrib/tensorrt/resources/trt_int8_calibrator.h
  tensorflow/contrib/tensorrt/resources/trt_resources.h
  tensorflow/contrib/tensorrt/segment/segment.h
  tensorflow/contrib/tensorrt/shape_fn/trt_shfn.cc
  tensorflow/contrib/tensorrt/test/test_tftrt.py
  tensorflow/contrib/tensorrt/trt_conversion.i
Labels: awaiting testing (then merge), cla: yes

#20185 Update re2 to versioned release 2018-04-01
  tensorflow/workspace.bzl
Labels: awaiting review, cla: yes

#20226 Update libxsmm from 1.8.1 to 1.9
  tensorflow/tools/lib_package/BUILD
  tensorflow/tools/pip_package/BUILD
  tensorflow/workspace.bzl
  third_party/libxsmm.BUILD
Labels: awaiting review, cla: yes

#20224 Update abseil-py to v0.2.2
  tensorflow/workspace.bzl
Labels: awaiting review, cla: yes

#20223 Allow stride > window_size for sliding_window_batch
  tensorflow/contrib/data/python/kernel_tests/slide_dataset_op_test.py
  tensorflow/contrib/data/python/ops/sliding.py
  tensorflow/core/api_def/base_api/api_def_SlideDataset.pbtxt
  tensorflow/core/kernels/data/slide_dataset_op.cc
Labels: awaiting testing (then merge), cla: yes

#20189 Install h5py on ppc64le required for keras_app...
  tensorflow/tools/ci_build/Dockerfile.cpu.ppc64le
  tensorflow/tools/ci_build/Dockerfile.gpu.ppc64le
  tensorflow/tools/ci_build/install/install_hdf5_ppc64le.sh
Labels: awaiting testing (then merge), cla: yes

#20207 Build sqlite3 with json1 extension
  tensorflow/core/lib/db/sqlite_test.cc
  third_party/sqlite.BUILD
Labels: awaiting testing (then merge), cla: yes

#20122 Fix CMAKE build issue on Linux
  tensorflow/contrib/cmake/CMakeLists.txt
  tensorflow/contrib/cmake/external/boringssl.cmake
  tensorflow/contrib/cmake/tf_core_framework.cmake
  tensorflow/contrib/cmake/tf_core_kernels.cmake
Labels: awaiting review, cla: yes

#20230 fixes estimator model_fn signature in python docs
  tensorflow/python/estimator/model_fn.py
Labels: awaiting testing (then merge), cla: yes

#20220 Attempt to make sense of reasoning for loss
  tensorflow/docs_src/programmers_guide/custom_estimators.md
Labels: awaiting testing (then merge), cla: yes

#19663 Add gradient for operation 'SparseSlice'
  tensorflow/core/api_def/base_api/api_def_SparseSliceGrad.pbtxt
  tensorflow/core/api_def/python_api/api_def_SparseSliceGrad.pbtxt
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/sparse_slice_grad_op.cc
  tensorflow/core/ops/sparse_ops.cc
  tensorflow/core/ops/sparse_ops_test.cc
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/sparse_slice_op_test.py
  tensorflow/python/ops/sparse_grad.py
Labels: awaiting testing (then merge), cla: yes
