Repository tensorflow/tensorflow, pull requests merged in 2018-08, with the labels that each got.

#21281 Add Cloud Bigtable user docs for TF 1.10 release
  tensorflow/contrib/bigtable/README.md
  tensorflow/contrib/bigtable/__init__.py
  tensorflow/contrib/bigtable/kernels/bigtable_kernels.cc
  tensorflow/contrib/bigtable/kernels/bigtable_lib.cc
  tensorflow/contrib/bigtable/python/kernel_tests/bigtable_ops_test.py
  tensorflow/contrib/bigtable/python/ops/bigtable_api.py
  tensorflow/contrib/cloud/README.md
  tensorflow/contrib/cloud/__init__.py
Labels: cla: yes

#20034 Improve S3 filesystem read performance
  tensorflow/core/platform/s3/s3_file_system.cc
Labels: cla: yes, ready to pull

#21063 Remove unneeded s3_crypto[.cc,.h] files
  tensorflow/core/platform/s3/s3_crypto.cc
  tensorflow/core/platform/s3/s3_crypto.h
Labels: cla: yes, ready to pull

#21292 Allow for python3.5 and 3.6 builds for MacOS.
  tensorflow/tools/ci_build/ci_parameterized_build.sh
Labels: cla: yes

#21288 fix the function name in the gide of custom estimator
  tensorflow/docs_src/guide/custom_estimators.md
Labels: cla: yes, ready to pull

#21119 Add PATCH_COMMAND to eigen.cmake (fix #19198)
  tensorflow/contrib/cmake/external/eigen.cmake
Labels: cla: yes, ready to pull

#21002 Hardcode Protobuf library version in contrib/makefiles
  tensorflow/contrib/makefile/download_dependencies.sh
Labels: cla: yes, ready to pull

#21369 Fix the pip install TLS issue for pip test builds.
  tensorflow/tools/ci_build/builds/pip.sh
Labels: cla: yes

#21021 Add C++ gradients for some image operators.
  tensorflow/cc/BUILD
  tensorflow/cc/framework/gradient_checker.cc
  tensorflow/cc/gradients/image_grad.cc
  tensorflow/cc/gradients/image_grad_test.cc
Labels: cla: yes, ready to pull

#20056 Handle checking of all export fields in single function
  tensorflow/python/estimator/export/export.py
  tensorflow/python/estimator/export/export_test.py
Labels: cla: yes, ready to pull

#21151 Fix compilation error due to typo
  tensorflow/contrib/gdr/gdr_memory_manager.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21386 Fix the name property for the _UnreadVariable class in eager mode
  tensorflow/python/ops/resource_variable_ops.py
Labels: cla: yes, ready to pull

#21256 Fix typo in docstring of is_tensor
  tensorflow/python/framework/tensor_util.py
Labels: cla: yes, ready to pull

#20735 [tfgan] Remove outdated estimator TODO
  tensorflow/contrib/gan/python/estimator/python/gan_estimator_impl.py
Labels: cla: yes, ready to pull

#21049 [XLA] Allow the iota test to be disabled with a manifest file
  tensorflow/compiler/xla/tests/iota_test.cc
Labels: cla: yes, ready to pull

#21065 Disable sdca test on all GPU builds.
  tensorflow/contrib/linear_optimizer/BUILD
Labels: cla: yes, ready to pull

#21360 Minor doc enhancement in CheckpointSaverHook
  tensorflow/python/training/basic_session_run_hooks.py
Labels: awaiting review, cla: yes, ready to pull

#21420 Merge pull request #21386 from ageron:fix_unread_var_name
  tensorflow/python/ops/resource_variable_ops.py
Labels: cla: yes

#21419 Updating the version to 1.10 final.
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#20540 [Bazel] Bump boringssl version
  tensorflow/workspace.bzl
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20419 Removed duplicated line in bazel.rc
  tools/bazel.rc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20988 [tflite label_image] get output size from output tensor
  tensorflow/contrib/lite/examples/label_image/label_image.cc
  tensorflow/contrib/lite/examples/label_image/label_image.h
Labels: cla: yes, ready to pull

#20928 Add gradient for tensorflow::ops::Fill
  tensorflow/cc/gradients/array_grad.cc
  tensorflow/cc/gradients/array_grad_test.cc
Labels: cla: yes, ready to pull

#21452 ConfigProto.experimental.num_dev_to_dev_copy_streams defaults to 0
  tensorflow/core/common_runtime/gpu/gpu_device.cc
  tensorflow/core/protobuf/config.proto
Labels: cla: yes

#21387 Fix issue with tf.nn.relu6 grad in eager
  tensorflow/python/eager/pywrap_tfe_src.cc
Labels: cla: yes, ready to pull

#21453 Cheery pick TFLite iOS build fix into 1.10 branch
  tensorflow/contrib/lite/Makefile
  tensorflow/contrib/lite/build_ios_universal_lib.sh
  tensorflow/contrib/lite/download_dependencies.sh
Labels: cla: yes

#20708 [ROCm] add scratch memory size in AlgorithmDesc
  tensorflow/stream_executor/cuda/cuda_dnn.cc
  tensorflow/stream_executor/dnn.h
Labels: cla: yes, ready to pull

#21425 Refactor dependencies so keras_support can be imported directly.
  tensorflow/contrib/BUILD
  tensorflow/contrib/cmake/python_protos.txt
  tensorflow/contrib/distribute/python/BUILD
  tensorflow/contrib/tpu/BUILD
  tensorflow/contrib/tpu/__init__.py
  tensorflow/contrib/tpu/python/tpu/keras_support.py
Labels: cla: yes

#20578 [Intel MKL] Adding support for python3 to MKL Dockerfile
  tensorflow/tools/docker/Dockerfile.mkl
Labels: cla: yes, ready to pull

#21102 [INTEL MKL] Using MKL DNN sgemm
  tensorflow/core/kernels/matmul_op.cc
  tensorflow/core/kernels/mkl_matmul_op.cc
Labels: cla: yes, ready to pull

#21370 [Intel MKL] Updating artifact references in Readme.md.
  README.md
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21289 Add extra log for failing to load variables
  tensorflow/cc/saved_model/loader.cc
Labels: cla: yes, kokoro:run, ready to pull

#21443 Fix incorrect reference to version compatibility
  tensorflow/docs_src/install/install_go.md
Labels: cla: yes, ready to pull, type:docs

#21378 lib / pip_package: only include licenses if option is enabled
  tensorflow/tools/lib_package/BUILD
  tensorflow/tools/pip_package/BUILD
Labels: cla: yes, ready to pull

#20497 Fix int64 to int truncation in std::accumulate
  tensorflow/compiler/xla/array.h
  tensorflow/compiler/xla/service/indexed_array_analysis.cc
Labels: cla: yes, ready to pull

#21232 Fix typo: host_src -> gpu_src for inter-gpu copy
  tensorflow/stream_executor/stream_executor_internal.h
Labels: cla: yes, ready to pull

#20876 Small typo fix
  tensorflow/python/data/ops/iterator_ops.py
Labels: cla: yes, kokoro:run, ready to pull

#19947 [XLA] Skip float16 adam_tests.
  tensorflow/compiler/tests/adam_test.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20432 Fix broken Android demo app download links
  tensorflow/examples/android/README.md
Labels: cla: yes, ready to pull

#20364 Add JavaScript to list of languages not covered by the backwards compatibility guarantee
  tensorflow/docs_src/guide/version_compat.md
Labels: cla: yes, ready to pull

#21201 [CMAKE] Add MKL to PATH
  tensorflow/contrib/cmake/tf_python.cmake
Labels: cla: yes, ready to pull

#21423 Fix bazel issue with jpeg lib on arm v7
  third_party/jpeg/jpeg.BUILD
Labels: cla: yes, ready to pull

#21139 [CMake] tf_tests.py | Add CheckExists
  tensorflow/contrib/cmake/tf_tests.cmake
Labels: cla: yes, ready to pull

#20958 [XLA] Disable tests which do a windowed reduction on a scalar sized window
  tensorflow/compiler/xla/tests/reduce_window_test.cc
Labels: cla: yes, ready to pull

#21144 Fix typo: accidently -> accidentally.
  tensorflow/compiler/xla/service/layout_assignment.cc
Labels: cla: yes, ready to pull

#20477 Fix matrix_inverse_tril_test handling the inverse of 0
  tensorflow/contrib/distributions/python/kernel_tests/bijectors/matrix_inverse_tril_test.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20541 [Bazel/MSVC] Make Kafka builds on Windows
  tensorflow/contrib/kafka/kernels/kafka_dataset_ops.cc
  third_party/kafka/BUILD
Labels: cla: yes, ready to pull

#21319 [tf.py_func()] Check Python interpreter state before call
  tensorflow/python/lib/core/py_func.cc
Labels: cla: yes, ready to pull

#21146 A faster BatchSelectFunctor for tf.where on CPU.
  tensorflow/core/kernels/cwise_op_select.cc
  tensorflow/python/kernel_tests/where_op_test.py
Labels: cla: yes, ready to pull

#20077 Some enhancement on S3 file system error processing
  tensorflow/core/platform/s3/s3_file_system.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21424 Fix readme formatting
  tensorflow/docs_src/install/install_raspbian.md
Labels: cla: yes, ready to pull

#21527 Update install source docs.
  tensorflow/docs_src/install/install_sources.md
Labels: cla: yes, ready to pull

#21445 Fix incorrect doc in sparse_softmax_cross_entropy_with_logits
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, ready to pull

#21495 Merge r1.10 back to master.
  RELEASE.md
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull

#21539 def_file_filter: Fix a bug when VC path is not found
  tensorflow/tools/def_file_filter/def_file_filter_configure.bzl
Labels: cla: yes, ready to pull

#21529 docs_src: minor spelling tweaks
  tensorflow/docs_src/community/index.md
  tensorflow/docs_src/deploy/s3.md
  tensorflow/docs_src/extend/adding_an_op.md
  tensorflow/docs_src/extend/index.md
  tensorflow/docs_src/guide/debugger.md
  tensorflow/docs_src/performance/xla/operation_semantics.md
Labels: cla: yes, ready to pull

#21020 [tf.contrib.slim] Update documentation in evaluation.py
  tensorflow/contrib/slim/python/slim/evaluation.py
Labels: cla: yes, ready to pull

#21329 Update README.md
  README.md
Labels: cla: yes, ready to pull

#19653 Add C++ SegmentSum gradient operation.
  tensorflow/cc/gradients/math_grad.cc
  tensorflow/cc/gradients/math_grad_test.cc
Labels: cla: yes, ready to pull

#21533 Fix incorrect doc in tf.layers.dense
  tensorflow/python/layers/core.py
Labels: cla: yes, ready to pull

#21422 Don't include -lpthread for android
  tensorflow/core/BUILD
Labels: cla: yes, ready to pull

#21191 Use correct hash_bucket_size parameter
  tensorflow/docs_src/guide/feature_columns.md
Labels: awaiting review, cla: yes, ready to pull

#21521 [Docs] Update iOS selective registration docs
  tensorflow/examples/ios/README.md
Labels: cla: yes, ready to pull

#20479 bugfix: cleanup CondContext at exception
  tensorflow/python/ops/control_flow_ops.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20066 [Intel-MKL] Support for N-D Transpose using MKL-DNN
  tensorflow/compiler/tf2xla/kernels/BUILD
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/mkl_transpose_op.cc
  tensorflow/core/kernels/transpose_op.cc
  tensorflow/core/kernels/transpose_op.h
Labels: cla: yes, ready to pull

#21535 typo fix for rpi.md
  tensorflow/contrib/lite/g3doc/rpi.md
Labels: cla: yes, ready to pull

#20039 contrib.graph_editor.transform.copy_op_handler: fix for pruning
  tensorflow/contrib/graph_editor/transform.py
Labels: cla: yes, ready to pull

#21541 Fix nn_test.py on AVX512 builds
  tensorflow/python/ops/nn_test.py
Labels: cla: yes, ready to pull

#21519 Fix warning in image_ops_test
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, ready to pull

#21428 tf.clip_by_global_norm raise exception when use_norm = inf
  tensorflow/python/kernel_tests/clip_ops_test.py
  tensorflow/python/ops/clip_ops.py
Labels: cla: yes, ready to pull

#21286 Improve estimator.py doc-strings
  tensorflow/python/estimator/estimator.py
Labels: cla: yes, stat:awaiting response

#21451 Delete confusing comment related to missing output Variable
  tensorflow/contrib/factorization/python/ops/kmeans.py
Labels: cla: yes, ready to pull

#20538 [Bazel/MSVC] Enable png SIMD for MSVC
  third_party/png.BUILD
Labels: cla: yes, ready to pull

#21177 [Intel MKL] Adding support for MPI and Horovod to MKL containers
  tensorflow/tools/docker/Dockerfile.devel-mkl-horovod
  tensorflow/tools/docker/Dockerfile.mkl-horovod
  tensorflow/tools/docker/parameterized_docker_build.sh
Labels: awaiting review, cla: yes, ready to pull

#18953 Update is_windows() to allow mingw shells
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: cla: yes, ready to pull

#21546 [Intel MKL] Adding keras pip packages to MKL container builds.
  tensorflow/tools/docker/Dockerfile.devel-mkl
Labels: cla: yes, ready to pull

#21499 CUDA and CUDNN paths for debian
  configure.py
  third_party/gpus/cuda_configure.bzl
Labels: cla: yes, ready to pull

#21560 Fix typo: compatbility => compatibility
  tensorflow/python/keras/callbacks.py
  tensorflow/python/ops/losses/losses_impl.py
  tensorflow/python/summary/summary.py
  tensorflow/python/summary/writer/writer.py
Labels: cla: yes, ready to pull

#20114 hash table more types
  tensorflow/core/kernels/lookup_table_op.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21494 support IndexedSlices in `add_n`
  tensorflow/python/ops/math_ops.py
Labels: cla: yes, ready to pull

#20003 Make it possible to disable bazel symbol stripping
  configure.py
Labels: cla: yes, ready to pull

#18866 fix for AR not being defined.
  tensorflow/contrib/makefile/compile_nsync.sh
Labels: awaiting testing (then merge), cla: yes, ready to pull

#18992 fix cmake windows py27 import fail
  tensorflow/__init__.py
  tensorflow/contrib/cmake/python_modules.txt
Labels: cla: yes, ready to pull

#21640 [Intel MKL] Fixing a build issue
  tensorflow/core/platform/default/build_config.bzl
Labels: cla: yes, ready to pull

#18959 Use `get_cosine_decay_fn` to match the description
  tensorflow/contrib/opt/python/training/powersign.py
Labels: cla: yes, ready to pull

#21776 Testing with Dockerfile numpy version downgraded.
  tensorflow/tools/docker/Dockerfile.devel
  tensorflow/tools/docker/Dockerfile.devel-gpu
  tensorflow/tools/docker/Dockerfile.gpu
Labels: cla: yes

#21774 Use if_ngraph to exclude ngraph licence rules in default build.
  tensorflow/tools/pip_package/BUILD
Labels: cla: yes, ready to pull

#21733 Update SparseTensor docstring
  tensorflow/python/framework/sparse_tensor.py
Labels: cla: yes, ready to pull

#21784 register gpu kernel for div_no_nan
  tensorflow/core/kernels/cwise_op_div.cc
  tensorflow/core/kernels/cwise_op_gpu_div.cu.cc
  tensorflow/python/ops/math_ops_test.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21806 Add whl file to .gitignore.
  .gitignore
Labels: cla: yes, ready to pull

#21770 Rename the artifact IDs for TensorFlow ecosystem jars
  tensorflow/java/maven/pom.xml
  tensorflow/java/maven/run_inside_container.sh
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
  tensorflow/java/maven/tensorflow-hadoop/pom.xml
Labels: cla: yes, ready to pull

#19792 Correcting the number of flop for MatMul
  tensorflow/python/kernel_tests/matmul_op_test.py
  tensorflow/python/ops/math_ops.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21812 Adding release notes for 1.10.1.
  RELEASE.md
Labels: cla: yes

#21773 Update the version 1.10.1 patch release.
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#21764 Fixed broken link to Estimators page
  tensorflow/docs_src/guide/saved_model.md
Labels: cla: yes, ready to pull

#21709 Cherry-picks for Keras on Cloud TPUs
  tensorflow/contrib/tpu/python/tpu/keras_support.py
Labels: cla: yes, ready to pull

#21821 [Intel MKL] Intel Optimizations for TensorFlow* 1.10.0 released.
  README.md
Labels: cla: yes, ready to pull

#20239 apply gpu memory fraction option to static memory analysis during identifying memory swap candidates
  tensorflow/core/grappler/clusters/virtual_cluster.cc
Labels: cla: yes, ready to pull

#21827 add div_no_nan in the math section of user_guide
  tensorflow/docs_src/api_guides/python/math_ops.md
Labels: cla: yes, ready to pull

#21283 Improve readability of Tensor::CheckType error output
  tensorflow/core/framework/tensor.cc
Labels: cla: yes, ready to pull

#21209 ignore cmake build artifacts
  .gitignore
Labels: cla: yes, ready to pull

#21462 RNN.call should get initial state from full input spec
  tensorflow/python/keras/layers/recurrent.py
  tensorflow/python/keras/layers/wrappers.py
  tensorflow/python/keras/utils/multi_gpu_utils_test.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21857 Readme
  README.md
Labels: cla: yes, ready to pull, stat:awaiting response

#21766 Fix compilation failure with RDMA+GDR
  tensorflow/contrib/gdr/gdr_memory_manager.cc
Labels: cla: yes, ready to pull

#21694 [INTEL MKL] Upgrade mkldnn to 0.16 for bazel build
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull

#21665 [Intel MKL] Static code analysis tool fixes.
  tensorflow/core/common_runtime/mkl_cpu_allocator.h
  tensorflow/core/graph/mkl_graph_util.h
  tensorflow/core/graph/mkl_layout_pass.cc
Labels: cla: yes, ready to pull

#21890 Fix pix2pix_eager.ipynb image resize method
  tensorflow/contrib/eager/python/examples/pix2pix/pix2pix_eager.ipynb
Labels: cla: yes, ready to pull

#21950 Fix possible memory leak
  tensorflow/core/common_runtime/executor.cc
Labels: cla: yes, ready to pull

#21981 MKL DNN: Softmax dim fix: Supporting 1D to 5D tensors, address the regression of CI
  tensorflow/core/kernels/mkl_softmax_op.cc
Labels: cla: yes, ready to pull

#21970 tf.errors.OpError and its subclasses are pickleable
  tensorflow/python/framework/errors_impl.py
  tensorflow/python/framework/errors_test.py
Labels: cla: yes, ready to pull
