Repository tensorflow/tensorflow, pull requests merged in 2018-07, with the labels that each got.

#20234 Make sure calibrator don't miss last batch
  tensorflow/contrib/tensorrt/convert/convert_graph.cc
  tensorflow/contrib/tensorrt/resources/trt_int8_calibrator.cc
  tensorflow/contrib/tensorrt/resources/trt_int8_calibrator.h
Labels: cla: yes

#19712 Add KinesisDataset support for tensorflow Dataset
  configure.py
  tensorflow/BUILD
  tensorflow/contrib/BUILD
  tensorflow/contrib/cmake/python_modules.txt
  tensorflow/contrib/kinesis/BUILD
  tensorflow/contrib/kinesis/__init__.py
  tensorflow/contrib/kinesis/kernels/kinesis_dataset_ops.cc
  tensorflow/contrib/kinesis/ops/dataset_ops.cc
  tensorflow/contrib/kinesis/python/kernel_tests/kinesis_test.py
  tensorflow/contrib/kinesis/python/ops/kinesis_dataset_ops.py
  tensorflow/contrib/kinesis/python/ops/kinesis_op_loader.py
  tensorflow/core/platform/default/build_config.bzl
  tensorflow/core/platform/s3/BUILD
  tensorflow/core/platform/s3/aws_crypto.cc
  tensorflow/core/platform/s3/aws_crypto.h
  tensorflow/core/platform/s3/s3_file_system.cc
  third_party/aws.BUILD
Labels: cla: yes

#20460 Reapplying #20295
  tensorflow/contrib/tensorrt/trt_conversion.i
Labels: cla: yes

#20474 Exclude importing tensorflow.contrib.cloud on Windows
  tensorflow/contrib/__init__.py
Labels: cla: yes

#20458 Update Google Python Style Guide link
  CONTRIBUTING.md
Labels: cla: yes

#18771 make safe_embedding_lookup_sparse method public and clean duplicate codes
  tensorflow/contrib/layers/python/layers/embedding_ops_test.py
  tensorflow/python/BUILD
  tensorflow/python/feature_column/feature_column.py
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/embedding_ops_test.py
  tensorflow/python/ops/embedding_ops.py
  tensorflow/tools/api/golden/tensorflow.nn.pbtxt
Labels: awaiting review, cla: yes

#20374 Update beam_search_decoder.py
  tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py
Labels: cla: yes

#19388 Pandas input fn accepts DataFrame for Y
  tensorflow/python/estimator/inputs/pandas_io.py
  tensorflow/python/estimator/inputs/pandas_io_test.py
Labels: awaiting testing (then merge), cla: yes

#20486 Reapplying #20254
  tensorflow/workspace.bzl
Labels: awaiting testing (then merge), cla: yes

#20360 Fix gradient of nccl_ops
  tensorflow/contrib/nccl/python/ops/nccl_ops.py
Labels: awaiting testing (then merge), cla: yes

#19882 Merge weight column of duplicated indices for indicator_column
  tensorflow/python/feature_column/feature_column.py
  tensorflow/python/feature_column/feature_column_test.py
Labels: awaiting testing (then merge), cla: yes

#20489 Match for -path instead of -name
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: cla: yes

#20437 Advise batch_normalization with model_to_estimator
  tensorflow/docs_src/guide/keras.md
Labels: cla: yes

#20526 Move get_started to tutorials and rearrange
  tensorflow/docs_src/get_started/eager.md
  tensorflow/docs_src/get_started/index.md
  tensorflow/docs_src/get_started/leftnav_files
  tensorflow/docs_src/guide/datasets_for_estimators.md
  tensorflow/docs_src/guide/debugger.md
  tensorflow/docs_src/guide/eager.md
  tensorflow/docs_src/guide/graphs.md
  tensorflow/docs_src/guide/tensorboard_histograms.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_raspbian.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/docs_src/install/install_windows.md
  tensorflow/docs_src/mobile/mobile_intro.md
  tensorflow/docs_src/mobile/tflite/devguide.md
  tensorflow/docs_src/tutorials/_index.yaml
  tensorflow/docs_src/tutorials/_toc.yaml
  tensorflow/docs_src/tutorials/eager/custom_training_walkthrough.md
  tensorflow/docs_src/tutorials/eager/index.md
  tensorflow/docs_src/tutorials/image_retraining.md
  tensorflow/docs_src/tutorials/images/deep_cnn.md
  tensorflow/docs_src/tutorials/images/image_recognition.md
  tensorflow/docs_src/tutorials/images/layers.md
  tensorflow/docs_src/tutorials/index.md
  tensorflow/docs_src/tutorials/keras/basic_classification.md
  tensorflow/docs_src/tutorials/keras/basic_regression.md
  tensorflow/docs_src/tutorials/keras/basic_text_classification.md
  tensorflow/docs_src/tutorials/keras/index.md
  tensorflow/docs_src/tutorials/keras/overfit_and_underfit.md
  tensorflow/docs_src/tutorials/keras/save_and_restore_models.md
  tensorflow/docs_src/tutorials/leftnav_files
  tensorflow/docs_src/tutorials/next_steps.md
  tensorflow/docs_src/tutorials/non-ml/mandelbrot.md
  tensorflow/docs_src/tutorials/non-ml/pdes.md
  tensorflow/docs_src/tutorials/representation/kernel_methods.md
  tensorflow/docs_src/tutorials/representation/linear.md
  tensorflow/docs_src/tutorials/representation/wide.md
  tensorflow/docs_src/tutorials/representation/wide_and_deep.md
  tensorflow/docs_src/tutorials/representation/word2vec.md
  tensorflow/docs_src/tutorials/seq2seq.md
  tensorflow/docs_src/tutorials/sequences/audio_recognition.md
  tensorflow/docs_src/tutorials/sequences/recurrent.md
  tensorflow/docs_src/tutorials/sequences/recurrent_quickdraw.md
Labels: cla: yes

#20530 Add tflite performance page
  tensorflow/docs_src/mobile/leftnav_files
  tensorflow/docs_src/mobile/tflite/performance.md
Labels: cla: yes

#20513 Update grpc to v1.13.0
  tensorflow/workspace.bzl
Labels: cla: yes

#20190 INTEL-MKL: MKL primitive reuse for reorder op
  tensorflow/core/kernels/mkl_aggregate_ops.cc
  tensorflow/core/kernels/mkl_concat_op.cc
  tensorflow/core/kernels/mkl_conv_ops.cc
  tensorflow/core/kernels/mkl_lrn_op.cc
  tensorflow/core/kernels/mkl_reshape_op.cc
  tensorflow/core/kernels/mkl_tfconv_op.h
  tensorflow/core/util/mkl_util.h
Labels: awaiting testing (then merge), cla: yes

#20534 Reapplying #20285 for the fix to convert_graph.cc
  tensorflow/contrib/tensorrt/convert/convert_graph.cc
Labels: cla: yes

#19399 INTEL-MKL: Enhance Mkl conv2d backward (filter and input) ops with primitive reuse
  tensorflow/core/kernels/mkl_conv_grad_filter_ops.cc
  tensorflow/core/kernels/mkl_conv_grad_input_ops.cc
  tensorflow/core/kernels/mkl_conv_ops.h
Labels: awaiting testing (then merge), cla: yes

#20596 Remove unused gcp and hdfs config flags, as these are on by default now.
  tensorflow/tools/ci_build/ci_parameterized_build.sh
  tensorflow/tools/ci_build/ci_sanity.sh
Labels: cla: yes

#20593 Updating the version to 1.9.0 official.
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#20581 Update sqlite to 2.24.0
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull

#20455 fix bug in maxout function
  tensorflow/contrib/layers/python/layers/layers.py
Labels: awaiting review, cla: yes

#20649 Update 1_basic.ipynb
  tensorflow/contrib/eager/python/examples/workshop/1_basic.ipynb
Labels: cla: yes, ready to pull

#20612 Fix: Typo in the release note
  RELEASE.md
Labels: cla: yes, ready to pull

#20429 Image Captioning with Attention in TensorFlow Eager Execution
  tensorflow/contrib/eager/python/examples/generative_examples/image_captioning_with_attention.ipynb
Labels: awaiting review, cla: yes, ready to pull

#20637 Update deploy docs to use Minio distributed mode as well
  tensorflow/docs_src/deploy/s3.md
Labels: cla: yes, ready to pull

#20558 Resolve issue 17698: Session JNI interface has memory leak
  tensorflow/java/src/main/native/session_jni.cc
Labels: cla: yes, ready to pull

#20616 Correct CUDA v9.0 download link
  tensorflow/python/platform/self_check.py
Labels: cla: yes, ready to pull

#20227 Update gflags from f8a0efe to v2.2.1
  tensorflow/workspace.bzl
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20652 Update cython to 0.28.4
  tensorflow/workspace.bzl
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20654 Required import for workshop notebook
  tensorflow/contrib/autograph/examples/notebooks/workshop.ipynb
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20641 Fix typos
  tensorflow/contrib/data/python/ops/prefetching_ops.py
  tensorflow/contrib/distribute/python/multi_worker_strategy.py
  tensorflow/contrib/mixed_precision/python/loss_scale_optimizer.py
  tensorflow/python/eager/function.py
  tensorflow/python/kernel_tests/init_ops_test.py
  tensorflow/python/ops/functional_ops.py
  tensorflow/python/ops/parallel_for/pfor.py
  tensorflow/python/ops/script_ops.py
Labels: cla: yes, ready to pull

#20617 Fix unused status error in convert_graph.cc
  tensorflow/contrib/tensorrt/convert/convert_graph.cc
Labels: cla: yes, ready to pull

#20705 Match for path instead of name
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: cla: yes, ready to pull

#20685 Use FastBoundsCheck in roll_op.cc
  tensorflow/core/kernels/roll_op.cc
Labels: cla: yes, ready to pull

#20599 Typo in taskset for CPU affinity
  tensorflow/contrib/lite/tools/benchmark/README.md
Labels: cla: yes, ready to pull

#20678 Fix a couple typos
  tensorflow/contrib/copy_graph/python/util/copy_elements.py
Labels: cla: yes, ready to pull

#20760 Fix invalid link in security advisories page
  tensorflow/security/index.md
Labels: cla: yes, ready to pull

#20665 Fix masking of beam ids in gather_tree_from_array
  tensorflow/contrib/seq2seq/python/kernel_tests/beam_search_decoder_test.py
  tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py
Labels: cla: yes, ready to pull

#20725 Fix incorrect link in security advisory TFSA-2018-001
  tensorflow/security/advisory/tfsa-2018-001.md
Labels: cla: yes, ready to pull

#20754 [XLA][AMDGPU] use AddrSpaceCast to access GlobalVariable on AMDGPU
  tensorflow/compiler/xla/service/gpu/hlo_to_ir_bindings.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20759 [XLA:GPU] let GpuTransferManager take different StreamExecutor and LLVM Compiler
  tensorflow/compiler/xla/service/gpu/gpu_transfer_manager.cc
  tensorflow/compiler/xla/service/gpu/gpu_transfer_manager.h
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20542 [MSVC] Disable C++ exceptions
  tensorflow/contrib/cmake/CMakeLists.txt
  tensorflow/tensorflow.bzl
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20794 Add all keep nodes to output lists
  tensorflow/contrib/tensorrt/convert/trt_optimization_pass.cc
Labels: cla: yes, ready to pull

#20595 Make protocol used in estimator customizable.
  tensorflow/contrib/learn/python/learn/estimators/run_config.py
  tensorflow/core/protobuf/tensorflow_server.proto
  tensorflow/python/estimator/run_config.py
  tensorflow/python/estimator/training.py
  tensorflow/python/estimator/training_test.py
  tensorflow/python/training/server_lib.py
  tensorflow/tools/api/golden/tensorflow.estimator.-run-config.pbtxt
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20706 [ROCm] Interface changes for pooling APIs in StreamExecutor
  tensorflow/stream_executor/cuda/cuda_dnn.cc
  tensorflow/stream_executor/cuda/cuda_dnn.h
  tensorflow/stream_executor/dnn.h
  tensorflow/stream_executor/stream.cc
  tensorflow/stream_executor/stream.h
Labels: cla: yes, ready to pull

#20603 Fix the order of adding const nodes, and avoid adding them multiple times.
  tensorflow/contrib/tensorrt/convert/convert_graph.cc
  tensorflow/contrib/tensorrt/test/tf_trt_integration_test.py
Labels: cla: yes, ready to pull

#20855 Update version strings for 1.10
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/docker/Dockerfile.devel
  tensorflow/tools/docker/Dockerfile.devel-gpu
  tensorflow/tools/docker/Dockerfile.devel-mkl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#20810 Adding MKL DNN license from Intel's repo
  third_party/mkl_dnn/LICENSE
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20851 Add support for possible extra : in input names
  tensorflow/contrib/tensorrt/convert/trt_optimization_pass.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20863 R1.10 cherry-pick request: Fix tensorrt conversion to ignore all preserved nodes
  tensorflow/contrib/tensorrt/convert/trt_optimization_pass.cc
Labels: cla: yes

#20742 [tf.keras] Fix deprecated use of normal distribution in initializers
  tensorflow/python/keras/initializers.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20864 NCCL 2.x document updates and removal of license file
  configure.py
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/docker/Dockerfile.devel-gpu
  third_party/nccl/nccl_configure.bzl
Labels: cla: yes

#20807 Fix bug inside boston.py in boosted_trees with python 3
  tensorflow/contrib/boosted_trees/estimator_batch/custom_export_strategy.py
  tensorflow/contrib/boosted_trees/examples/boston.py
Labels: cla: yes, ready to pull

#20849 Add initial draft of RELEASE notes for 1.10.
  RELEASE.md
Labels: cla: yes

#20752 [XLA:GPU] rename GpuCompiler to NVPTXCompiler
  tensorflow/compiler/xla/service/gpu/BUILD
  tensorflow/compiler/xla/service/gpu/gpu_transfer_manager.cc
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/BUILD
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/nvptx_backend_lib.cc
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/nvptx_backend_lib.h
  tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc
  tensorflow/compiler/xla/service/gpu/nvptx_compiler.h
Labels: cla: yes, ready to pull

#20893 Link lib and header where ./configure expects
  tensorflow/tools/ci_build/Dockerfile.gpu
Labels: cla: yes

#20894 Update bazel version in docs
  tensorflow/docs_src/install/install_sources.md
Labels: cla: yes

#20840 Omit some operations if only one para is kLogZero
  tensorflow/core/util/ctc/ctc_loss_util.h
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20853 Improvement of shape function in HistogramFixedWidth
  tensorflow/core/ops/math_ops.cc
  tensorflow/core/ops/math_ops_test.cc
  tensorflow/python/ops/histogram_ops_test.py
Labels: cla: yes, ready to pull

#20820 [tfgan] Fix assertion in regularization loss unittest
  tensorflow/contrib/gan/python/train_test.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20898 Print errors during bazel tests.
  tensorflow/tools/ci_build/builds/run_pip_tests.sh
Labels: cla: yes

#20895 NCCL 2.x Release notes section updated.
  RELEASE.md
Labels: cla: yes

#20875 make TFLite kernel tests work again
  tensorflow/contrib/lite/kernels/pow_test.cc
Labels: cla: yes, comp:lite, ready to pull

#20793 [XLA:GPU] avoid hard coded CUDA PlatformId
  tensorflow/compiler/jit/kernels/xla_launch_op.cc
Labels: cla: yes, ready to pull

#20847 Describe that the semantics of gfile are different.
  tensorflow/python/platform/gfile.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20931 Fix tf_trt_integration_test in py3
  tensorflow/contrib/tensorrt/test/tf_trt_integration_test.py
Labels: cla: yes, ready to pull

#20675 rename interfaces in StreamInterface and StreamExecutorInterface to support both CUDA and ROCm
  tensorflow/contrib/nccl/kernels/nccl_manager.cc
  tensorflow/contrib/tensorrt/custom_plugin_examples/inc_op_kernel.cu.cc
  tensorflow/contrib/tensorrt/kernels/trt_engine_op.cc
  tensorflow/core/common_runtime/gpu/gpu_device.cc
  tensorflow/core/kernels/cuda_solvers.cc
  tensorflow/core/util/cuda_launch_config.h
  tensorflow/stream_executor/cuda/cuda_gpu_executor.cc
  tensorflow/stream_executor/cuda/cuda_gpu_executor.h
  tensorflow/stream_executor/cuda/cuda_stream.h
  tensorflow/stream_executor/host/host_gpu_executor.h
  tensorflow/stream_executor/host/host_stream.h
  tensorflow/stream_executor/stream_executor_internal.h
Labels: cla: yes, ready to pull

#20945 Fix examples_test.sh script which was broken by added debug_keras test.
  tensorflow/python/debug/examples/examples_test.sh
Labels: cla: yes

#20821 Use FastBoundsCheck in ArgMax kernel op
  tensorflow/core/kernels/argmax_op.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20977 Fix typo in install_python3.6_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
Labels: cla: yes

#20946 Update RELNOTE formatting.
  RELEASE.md
Labels: cla: yes

#20911 Edit a link to notebooks directory
  tensorflow/tools/docker/notebooks/1_hello_tensorflow.ipynb
Labels: cla: yes, ready to pull

#20889 Documentation update
  tensorflow/contrib/lite/python/tflite_convert.py
Labels: cla: yes, ready to pull

#20927 Recommend the user site, no sudo
  tensorflow/docs_src/install/install_linux.md
Labels: cla: yes, ready to pull

#20287 update the py/py3 toolchain config
  third_party/toolchains/cpus/py/BUILD
  third_party/toolchains/cpus/py3/BUILD
Labels: cla: yes, ready to pull, stat:awaiting response

#19330 [XLA] Don't do int64 tests for devices which do not support int64
  tensorflow/compiler/tests/binary_ops_test.py
Labels: cla: yes, ready to pull

#20932 Remove usage of remove_undocumented from core parallel_for.
  tensorflow/python/ops/parallel_for/__init__.py
Labels: cla: yes, ready to pull

#20953 Reset the unique_ptr instead of releasing it which cause memory leak
  tensorflow/contrib/tensorrt/plugin/trt_plugin_factory.cc
Labels: cla: yes, ready to pull

#20861 [Intel MKL] Adding support for MKL builds with AVX2.
  tensorflow/tools/ci_build/linux/mkl/build-dev-container.sh
Labels: cla: yes, ready to pull

#20520 Update calling of expand_dims with axis
  tensorflow/contrib/learn/python/learn/estimators/head.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20957 Update keras.md
  tensorflow/docs_src/guide/keras.md
Labels: cla: yes, ready to pull

#20636 [INTEL MKL] Enabled reorder primitive reuse for conv backprop
  tensorflow/core/kernels/mkl_conv_grad_filter_ops.cc
  tensorflow/core/kernels/mkl_conv_grad_input_ops.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20965 Typo in tf.Session fixed
  tensorflow/docs_src/performance/performance_guide.md
Labels: cla: yes, ready to pull

#21003 Disable sdca_ops test on GPU.
  tensorflow/contrib/linear_optimizer/BUILD
Labels: cla: yes

#21004 Hardcode Protobuf library version in contrib/makefiles (r1.10 branch)
  tensorflow/contrib/makefile/download_dependencies.sh
Labels: cla: yes

#20508 [Update debugger.md] Fix error in sample code
  tensorflow/docs_src/guide/debugger.md
Labels: cla: yes, ready to pull

#20512 Update .gitignore for cmake generated file
  .gitignore
Labels: awaiting testing (then merge), cla: yes, ready to pull

#15469 Compute test accuracy in batches to avoid OOM on GPUs
  tensorflow/examples/tutorials/mnist/mnist_deep.py
Labels: cla: yes, ready to pull

#20934 Add additional shape validation for QuantizedAdd
  tensorflow/core/ops/math_ops.cc
  tensorflow/core/ops/math_ops_test.cc
Labels: cla: yes, ready to pull

#20923 Floating point type issue when computing extract images patches gradient
  tensorflow/python/ops/array_grad.py
Labels: cla: yes, ready to pull

#20939 Improve error messages for gather_nd and scatter_nd
  tensorflow/core/kernels/gather_nd_op.cc
  tensorflow/core/kernels/scatter_nd_op.cc
  tensorflow/core/kernels/scatter_nd_op_test.cc
  tensorflow/python/kernel_tests/gather_nd_op_test.py
  tensorflow/python/kernel_tests/scatter_nd_ops_test.py
Labels: cla: yes, kokoro:run, ready to pull

#20993 Update fold_old_batch_norms.cc
  tensorflow/tools/graph_transforms/fold_old_batch_norms.cc
Labels: cla: yes, ready to pull

#20981 Link lib and header where ./configure expects
  tensorflow/tools/ci_build/Dockerfile.gpu
Labels: cla: yes, ready to pull

#21010 Add no_pip_gpu to the sdca test.
  tensorflow/contrib/linear_optimizer/BUILD
Labels: cla: yes

#20970 Update or-tools to v6.7.2
  tensorflow/workspace.bzl
Labels: cla: yes, kokoro:run, ready to pull

#21012 Fix typo in windows build scripts.
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes

#21017 fixed build error on gcc-7
  tensorflow/compiler/xla/service/gpu/xfeed_queue.h
Labels: cla: yes, ready to pull

#21064 Fix some minor typo/formatting in 1.10 release notes.
  RELEASE.md
Labels: cla: yes

#20736 Putting batch_axis,seq_axis instead batch_dim, seq_dim according
  tensorflow/python/ops/rnn.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21027 Update Go README with working bazel config flag
  tensorflow/go/README.md
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21028 Fixed typo in TOCO command line doc
  tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20763 New Feature: #12686 SoftmaxCrossEntropyWithLogits gradient function
  tensorflow/cc/gradients/nn_grad.cc
  tensorflow/cc/gradients/nn_grad_test.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20159 Cast: support casting to and from quantized types
  tensorflow/core/framework/tensor.h
  tensorflow/core/kernels/cast_op.cc
  tensorflow/core/kernels/cast_op.h
  tensorflow/core/kernels/cast_op_test.cc
  tensorflow/python/kernel_tests/distributions/util_test.py
Labels: cla: yes, ready to pull

#20985 Update saver.py
  tensorflow/python/training/saver.py
Labels: cla: yes, ready to pull

#21080 fix typo
  tensorflow/contrib/lite/toco/tflite/export_test.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21087 Replace `NWHC` with `NHWC`
  tensorflow/python/kernel_tests/depthwise_conv_op_test.py
  tensorflow/python/kernel_tests/neon_depthwise_conv_op_test.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21171 Fix contrib in r1.10
  WORKSPACE
  configure.py
  tensorflow/contrib/lite/BUILD
  tensorflow/contrib/lite/delegates/eager/BUILD
  tensorflow/contrib/lite/delegates/nnapi/BUILD
  tensorflow/contrib/lite/examples/label_image/BUILD
  tensorflow/contrib/lite/java/BUILD
  tensorflow/contrib/lite/java/ovic/BUILD
  tensorflow/contrib/lite/kernels/BUILD
  tensorflow/contrib/lite/kernels/internal/BUILD
  tensorflow/contrib/lite/models/smartreply/BUILD
  tensorflow/contrib/lite/profiling/BUILD
  tensorflow/contrib/lite/python/BUILD
  tensorflow/contrib/lite/schema/BUILD
  tensorflow/contrib/lite/schema/builtin_ops_header/BUILD
  tensorflow/contrib/lite/testing/BUILD
  tensorflow/contrib/lite/toco/BUILD
  tensorflow/contrib/lite/toco/graph_transformations/tests/BUILD
  tensorflow/contrib/lite/toco/python/BUILD
  tensorflow/contrib/lite/toco/tensorflow_graph_matching/BUILD
  tensorflow/contrib/lite/toco/tflite/BUILD
  tensorflow/contrib/lite/tools/BUILD
  tensorflow/contrib/lite/tools/benchmark/BUILD
  tensorflow/tools/ci_build/ci_sanity.sh
  tensorflow/tools/ci_build/install/install_bazel.sh
  tensorflow/tools/ci_build/install/install_bazel_from_source.sh
  tensorflow/tools/ci_build/windows/bazel/bazel_test_lib.sh
  tensorflow/tools/docker/Dockerfile.devel
  tensorflow/tools/docker/Dockerfile.devel-gpu
  tensorflow/tools/docker/Dockerfile.devel-gpu-cuda9-cudnn7
Labels: cla: yes

#21106 1.10.0-rc1 cherry-pick request: Update tensorboard dependency to 1.10.x
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#20711 Fix copied buffer
  tensorflow/contrib/lite/allocation.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull

#20744 Fix for issue# 20361 - changed the test cases' inputs and expected su…
  tensorflow/contrib/lite/kernels/resize_bilinear_test.cc
Labels: awaiting testing (then merge), cla: yes, comp:lite, ready to pull

#21179 Reverting the numpy version for the Docker tests and builds.
  tensorflow/tools/docker/Dockerfile
  tensorflow/tools/docker/Dockerfile.devel
  tensorflow/tools/docker/Dockerfile.devel-gpu
  tensorflow/tools/docker/Dockerfile.gpu
Labels: cla: yes, ready to pull

#21246 Fix test breakages for rc1.
  tensorflow/tools/ci_build/install/install_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
Labels: cla: yes

#21249 Adding a less than constraint on numpy.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#21140 [Intel MKL] Removing old MKL development Dockerfile
  tensorflow/tools/docker/Dockerfile.devel-cpu-mkl
Labels: awaiting testing (then merge), cla: yes, ready to pull

#21147 support CI_DOCKER_BUILD_EXTRA_PARAMS for ci_build.sh
  tensorflow/tools/ci_build/ci_build.sh
Labels: cla: yes, ready to pull

#21212 Fix epoch loss calculation in "NMT with attention" colab notebook
  tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb
Labels: cla: yes, ready to pull

#21258 Fix Linux XLA build status link
  README.md
Labels: cla: yes, ready to pull

#21235 [XLA] Give test an independent name
  tensorflow/compiler/xla/tests/outfeed_in_nested_computation_test.cc
Labels: cla: yes, ready to pull

#20686 Implement GetCurrentClockCycle and GetCycleCounterFrequencyImpl for Windows
  tensorflow/core/platform/profile_utils/cpu_utils.cc
  tensorflow/core/platform/profile_utils/cpu_utils.h
Labels: cla: yes, ready to pull
