Repository tensorflow/tensorflow, pull requests merged in 2018-03, with the labels that each got.

#17318 Cross ent logits
  tensorflow/python/ops/nn_impl.py
Labels: cla: yes

#17357 Fix some minor typos in get_started docs to keep consistent
  tensorflow/docs_src/get_started/checkpoints.md
Labels: cla: yes

#17004 MKL: cifar 10 divergance fix and batchnorm unit test fix
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
  tensorflow/core/kernels/mkl_relu_op.cc
Labels: awaiting testing (then merge), cla: yes

#17235 Clean up output formatting of saved_model_cli.py
  tensorflow/docs_src/programmers_guide/saved_model.md
  tensorflow/python/tools/saved_model_cli.py
  tensorflow/python/tools/saved_model_cli_test.py
Labels: awaiting testing (then merge), cla: yes

#17309 Scaffolding for int8 calibration in TF-TRT
  tensorflow/contrib/tensorrt/BUILD
  tensorflow/contrib/tensorrt/kernels/trt_calib_op.cc
  tensorflow/contrib/tensorrt/kernels/trt_calib_op.h
  tensorflow/contrib/tensorrt/ops/trt_calib_op.cc
  tensorflow/contrib/tensorrt/resources/trt_int8_calibrator.cc
  tensorflow/contrib/tensorrt/resources/trt_int8_calibrator.h
  tensorflow/contrib/tensorrt/resources/trt_resource_manager.cc
  tensorflow/contrib/tensorrt/resources/trt_resource_manager.h
  tensorflow/contrib/tensorrt/resources/trt_resources.h
Labels: awaiting testing (then merge), cla: yes

#17335 Fix markdown error in documentation.
  tensorflow/docs_src/install/install_sources.md
  tensorflow/docs_src/install/install_windows.md
Labels: awaiting testing (then merge), cla: yes

#17365 Fix the error activation function link in custom_estimators.md
  tensorflow/docs_src/get_started/custom_estimators.md
Labels: awaiting testing (then merge), cla: yes

#16306 Add LINM (Loop Invariant Node Motion) optimization pass in GraphOptim…
  tensorflow/core/grappler/optimizers/BUILD
  tensorflow/core/grappler/optimizers/loop_optimizer.cc
  tensorflow/core/grappler/optimizers/loop_optimizer.h
  tensorflow/core/grappler/optimizers/loop_optimizer_test.cc
  tensorflow/core/grappler/optimizers/meta_optimizer.cc
Labels: awaiting testing (then merge), cla: yes

#17371 minor spelling tweaks for contrib/verbs docs
  tensorflow/contrib/verbs/README.md
  tensorflow/contrib/verbs/patch_notes_verbs_with_0_copies.md
Labels: cla: yes

#13991 Support fold batch norm for atrous conv2d
  tensorflow/tools/graph_transforms/fold_old_batch_norms.cc
  tensorflow/tools/graph_transforms/fold_old_batch_norms_test.cc
Labels: awaiting testing (then merge), cla: yes

#17425 Correct reporter name.
  SECURITY.md
Labels: awaiting testing (then merge), cla: yes

#17428 Correct capitalization
  SECURITY.md
Labels: cla: yes

#17346 Add default whl file location and minor update comments
  tensorflow/tools/dist_test/README.md
  tensorflow/tools/dist_test/local_test.sh
Labels: awaiting review, cla: yes

#16431 Lite: Supporting Raspberry Pi.
  tensorflow/contrib/lite/Makefile
  tensorflow/contrib/lite/build_rpi_lib.sh
  tensorflow/contrib/lite/g3doc/rpi.md
  tensorflow/contrib/lite/rpi_makefile.inc
Labels: awaiting testing (then merge), cla: yes, comp:lite

#17449 Branch 187892975
  tensorflow/compiler/xla/service/gpu/BUILD
  tensorflow/compiler/xla/service/gpu/fusion_merger.cc
  tensorflow/compiler/xla/service/gpu/fusion_merger_test.cc
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc
  tensorflow/compiler/xla/service/instruction_fusion.cc
  tensorflow/compiler/xla/service/llvm_ir/ir_array.cc
  tensorflow/contrib/bayesflow/BUILD
  tensorflow/contrib/bayesflow/python/kernel_tests/halton_sequence_test.py
  tensorflow/contrib/bayesflow/python/ops/halton_sequence_impl.py
  tensorflow/contrib/estimator/__init__.py
  tensorflow/contrib/framework/__init__.py
  tensorflow/contrib/lite/README.md
  tensorflow/contrib/lite/kernels/internal/BUILD
  tensorflow/contrib/lite/kernels/internal/mfcc.cc
  tensorflow/contrib/lite/kernels/internal/mfcc.h
  tensorflow/contrib/lite/kernels/internal/mfcc_dct.cc
  tensorflow/contrib/lite/kernels/internal/mfcc_dct.h
  tensorflow/contrib/lite/kernels/internal/mfcc_mel_filterbank.cc
  tensorflow/contrib/lite/kernels/internal/mfcc_mel_filterbank.h
  tensorflow/contrib/lite/kernels/internal/quantization_util.h
  tensorflow/contrib/lite/kernels/internal/spectrogram.cc
  tensorflow/contrib/lite/kernels/internal/spectrogram.h
  tensorflow/contrib/lite/kernels/test_util.h
  tensorflow/contrib/py2tf/converters/logical_expressions.py
  tensorflow/contrib/py2tf/converters/logical_expressions_test.py
  tensorflow/contrib/py2tf/impl/conversion.py
  tensorflow/contrib/tpu/ops/tpu_configuration_ops.cc
  tensorflow/core/common_runtime/graph_runner.cc
  tensorflow/core/common_runtime/graph_runner.h
  tensorflow/core/framework/function.proto
  tensorflow/core/kernels/segment_reduction_ops.cc
  tensorflow/docs_src/get_started/custom_estimators.md
  tensorflow/docs_src/mobile/android_build.md
  tensorflow/docs_src/mobile/optimizing.md
  tensorflow/docs_src/programmers_guide/datasets.md
  tensorflow/docs_src/programmers_guide/debugger.md
  tensorflow/docs_src/programmers_guide/faq.md
  tensorflow/docs_src/programmers_guide/graphs.md
  tensorflow/docs_src/tutorials/layers.md
  tensorflow/python/estimator/canned/head_test.py
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/init_ops_test.py
  tensorflow/python/kernel_tests/segment_reduction_ops_test.py
  tensorflow/python/ops/init_ops.py
  tensorflow/python/ops/nn_ops.py
  tensorflow/python/saved_model/builder_impl.py
  tensorflow/python/saved_model/saved_model_test.py
  tensorflow/python/training/device_setter.py
  tensorflow/tools/integration_tests/gcs_smoke_test/BUILD
Labels: cla: yes

#16659 Windows: Enable tensorflow/contrib in Bazel build
  configure.py
  tensorflow/contrib/BUILD
  tensorflow/contrib/__init__.py
  tensorflow/contrib/boosted_trees/lib/utils/batch_features.h
  tensorflow/contrib/distributions/BUILD
  tensorflow/contrib/eager/python/BUILD
  tensorflow/contrib/eager/python/examples/linear_regression/BUILD
  tensorflow/contrib/gan/BUILD
  tensorflow/contrib/kfac/python/kernel_tests/BUILD
  tensorflow/contrib/labeled_tensor/BUILD
  tensorflow/contrib/layers/BUILD
  tensorflow/contrib/learn/BUILD
  tensorflow/contrib/lookup/BUILD
  tensorflow/contrib/py2tf/converters/BUILD
  tensorflow/contrib/py2tf/utils/BUILD
  tensorflow/contrib/remote_fused_graph/pylib/BUILD
  tensorflow/contrib/saved_model/BUILD
  tensorflow/contrib/session_bundle/BUILD
  tensorflow/contrib/slim/python/slim/data/BUILD
  tensorflow/contrib/tensor_forest/BUILD
  tensorflow/contrib/tensorboard/BUILD
  tensorflow/contrib/timeseries/examples/BUILD
  tensorflow/contrib/timeseries/python/timeseries/BUILD
  tensorflow/contrib/timeseries/python/timeseries/state_space_models/BUILD
  tensorflow/contrib/tpu/BUILD
  tensorflow/contrib/util/loader.py
  tensorflow/core/framework/dataset.h
  tensorflow/core/lib/core/stringpiece.cc
  tensorflow/core/lib/core/stringpiece.h
  tensorflow/core/platform/tracing.h
  tensorflow/python/BUILD
  tensorflow/python/debug/BUILD
  tensorflow/python/keras/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/tensorflow.bzl
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/def_file_filter/BUILD
  tensorflow/tools/def_file_filter/BUILD.tpl
  tensorflow/tools/def_file_filter/def_file_filter.py.tpl
  tensorflow/tools/def_file_filter/def_file_filter_configure.bzl
  tensorflow/tools/pip_package/BUILD
  tensorflow/workspace.bzl
Labels: awaiting testing (then merge), cla: yes

#17474 Windows: Use cc_import to import python lib properly
  third_party/py/BUILD.tpl
Labels: cla: yes

#17450 Updating the cuda compute info and avx info for Windows.
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_windows.md
Labels: cla: yes

#17391 Tensorrt improvements
  configure.py
  tensorflow/contrib/tensorrt/BUILD
  tensorflow/contrib/tensorrt/README.md
  tensorflow/contrib/tensorrt/convert/convert_graph.cc
  tensorflow/contrib/tensorrt/convert/convert_graph.h
  tensorflow/contrib/tensorrt/convert/convert_nodes.cc
  tensorflow/contrib/tensorrt/convert/convert_nodes.h
  tensorflow/contrib/tensorrt/kernels/trt_calib_op.cc
  tensorflow/contrib/tensorrt/kernels/trt_engine_op.cc
  tensorflow/contrib/tensorrt/log/trt_logger.cc
  tensorflow/contrib/tensorrt/log/trt_logger.h
  tensorflow/contrib/tensorrt/python/__init__.py
  tensorflow/contrib/tensorrt/python/trt_convert.py
  tensorflow/contrib/tensorrt/resources/trt_int8_calibrator.cc
  tensorflow/contrib/tensorrt/resources/trt_int8_calibrator.h
  tensorflow/contrib/tensorrt/test/test_tftrt.py
  tensorflow/contrib/tensorrt/trt_conversion.i
Labels: awaiting testing (then merge), cla: yes

#16123 add rolling window batch operation for tf.data.Dataset
  tensorflow/contrib/data/__init__.py
  tensorflow/contrib/data/python/kernel_tests/BUILD
  tensorflow/contrib/data/python/kernel_tests/slide_dataset_op_test.py
  tensorflow/contrib/data/python/ops/BUILD
  tensorflow/contrib/data/python/ops/sliding.py
  tensorflow/core/api_def/base_api/api_def_SlideDataset.pbtxt
  tensorflow/core/kernels/data/BUILD
  tensorflow/core/kernels/data/slide_dataset_op.cc
  tensorflow/core/ops/dataset_ops.cc
Labels: cla: yes, stalled, stat:awaiting response

#17345 Fix error : ConvNDLSTMCell does not pass name parameter
  tensorflow/contrib/rnn/python/ops/rnn_cell.py
Labels: awaiting testing (then merge), cla: yes

#17385 MKL: Removing unnecessary check for reorder
  tensorflow/core/kernels/mkl_input_conversion_op.cc
Labels: awaiting testing (then merge), cla: yes

#17532 Merge 1.6 back to master.
  tensorflow/contrib/factorization/BUILD
  tensorflow/contrib/learn/BUILD
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/docs_src/install/install_windows.md
  tensorflow/tools/pip_package/setup.py
Labels: cla: no

#17521 Making dockerhub the primary installation location.
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
Labels: cla: yes

#17416 Fix cmake Dockerfile issue on Linux
  tensorflow/tools/ci_build/Dockerfile.cmake
Labels: cla: yes

#17418 Fix build issue with KafkaDataset
  tensorflow/contrib/BUILD
  tensorflow/contrib/kafka/BUILD
  tensorflow/contrib/kafka/kernels/kafka_dataset_ops.cc
  tensorflow/contrib/kafka/ops/dataset_ops.cc
  tensorflow/contrib/kafka/python/ops/kafka_dataset_ops.py
  tensorflow/contrib/kafka/python/ops/kafka_op_loader.py
  tensorflow/tools/pip_package/BUILD
  third_party/kafka/BUILD
Labels: cla: yes

#17205 Update TrainingSpec and EvalSpec pydoc
  tensorflow/python/estimator/training.py
Labels: cla: yes

#17276 Supplement Linear Model Tutorial on how trained model to make predictions
  tensorflow/docs_src/tutorials/wide.md
Labels: cla: yes

#17225 Change unicode() --> six.text_type() for Python 3
  tensorflow/tools/test/upload_test_benchmarks.py
Labels: cla: yes

#17162 Fix build issues when having packed git refs.
  tensorflow/tools/git/gen_git_source.py
Labels: awaiting review, cla: yes

#16989 Fix a bug in tf.strided_slice()
  tensorflow/contrib/lite/kernels/strided_slice.cc
Labels: cla: yes

#16974 Fix typo in datasets/imdb.py
  tensorflow/python/keras/_impl/keras/datasets/imdb.py
Labels: awaiting testing (then merge), cla: yes

#16978 [XLA] Allow 3rd party backends to subclass the generic transfer manager
  tensorflow/compiler/xla/service/generic_transfer_manager.cc
Labels: awaiting testing (then merge), cla: yes

#16977 [XLA] Add header and macros to allow these tests to be disabled in a manifest
  tensorflow/compiler/xla/tests/convolution_test.cc
Labels: awaiting testing (then merge), cla: yes

#17536 Branch 188272354
  tensorflow/contrib/bayesflow/python/kernel_tests/hmc_test.py
  tensorflow/contrib/bayesflow/python/ops/hmc.py
  tensorflow/contrib/bayesflow/python/ops/hmc_impl.py
  tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py
  tensorflow/contrib/data/__init__.py
  tensorflow/contrib/data/python/kernel_tests/BUILD
  tensorflow/contrib/data/python/kernel_tests/reader_dataset_ops_test.py
  tensorflow/contrib/data/python/ops/BUILD
  tensorflow/contrib/data/python/ops/readers.py
  tensorflow/contrib/eager/python/checkpointable_utils.py
  tensorflow/contrib/eager/python/checkpointable_utils_test.py
  tensorflow/contrib/lite/kernels/internal/BUILD
  tensorflow/contrib/lite/kernels/internal/quantization_util.h
  tensorflow/contrib/lite/kernels/internal/quantization_util_test.cc
  tensorflow/contrib/lite/kernels/internal/types.h
  tensorflow/contrib/lite/toco/BUILD
  tensorflow/contrib/lite/toco/model.h
  tensorflow/contrib/lite/toco/tooling_util.h
  tensorflow/contrib/tpu/python/tpu/datasets.py
  tensorflow/contrib/tpu/python/tpu/datasets_test.py
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/function_ops.cc
  tensorflow/python/__init__.py
  tensorflow/python/eager/context.py
  tensorflow/python/framework/ops.py
  tensorflow/python/kernel_tests/py_func_test.py
  tensorflow/python/lib/core/py_util.cc
  tensorflow/python/ops/script_ops.py
  tensorflow/tools/api/golden/tensorflow.pbtxt
  tensorflow/tools/graph_transforms/BUILD
  tensorflow/tools/graph_transforms/fake_quantize_training.cc
  tensorflow/tools/graph_transforms/fake_quantize_training_test.cc
  tensorflow/tools/graph_transforms/remove_ema.cc
  tensorflow/tools/graph_transforms/remove_ema_test.cc
Labels: cla: yes

#17414 Add missing `#define OMPI_SKIP_MPICXX`
  tensorflow/contrib/mpi/mpi_utils.h
Labels: cla: yes

#17543 Revert "Update external protobuf codebase version for Windows cmake b…
  tensorflow/contrib/cmake/external/protobuf.cmake
  tensorflow/core/distributed_runtime/tensor_coding.cc
Labels: cla: yes

#17567 Update tensorrt import exception.
  tensorflow/contrib/tensorrt/BUILD
  tensorflow/contrib/tensorrt/__init__.py
Labels: cla: yes

#17547 Exclude kafka on Windows
  tensorflow/contrib/BUILD
  tensorflow/contrib/kafka/BUILD
Labels: cla: yes

#17572 Update version string to 1.7.0rc0 everywhere.
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/docker/Dockerfile.devel
  tensorflow/tools/docker/Dockerfile.devel-cpu-mkl
  tensorflow/tools/docker/Dockerfile.devel-gpu
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#17578 Disable checkpointable_utils_test
  tensorflow/contrib/eager/python/BUILD
Labels: cla: yes

#17580 Make spinn_test less flaky
  tensorflow/contrib/eager/python/examples/spinn/spinn_test.py
Labels: cla: yes

#17575 Fix pylint error in single_return.py
  tensorflow/contrib/py2tf/converters/single_return.py
Labels: cla: yes

#17581 Fix cmake build errors for Linux
  tensorflow/contrib/cmake/external/grpc.cmake
Labels: cla: yes

#17577 Hide `os` from docs generator
  tensorflow/contrib/__init__.py
Labels: cla: yes

#17576 Hide `os` from docs generator.
  tensorflow/contrib/__init__.py
Labels: cla: yes

#17546 fix some compilation errors on MSVC if IS_SLIM_BUILD
  tensorflow/core/lib/io/record_reader.cc
  tensorflow/core/lib/io/record_reader.h
Labels: cla: yes

#17453 Fix broken link pointing to vulnerability reporting/SECURITY.md
  tensorflow/docs_src/community/welcome.md
Labels: cla: yes

#17160 [Intel MKL-DNN]: added MKLDNN dilated convolution support
  tensorflow/core/graph/mkl_layout_pass.cc
  tensorflow/core/kernels/mkl_conv_grad_filter_ops.cc
  tensorflow/core/kernels/mkl_conv_grad_input_ops.cc
  tensorflow/core/kernels/mkl_conv_ops.cc
  tensorflow/core/kernels/mkl_conv_ops.h
  tensorflow/core/ops/nn_ops.cc
  tensorflow/python/kernel_tests/conv_ops_test.py
Labels: cla: yes

#17596 Fix pylint error in single_return.py
  tensorflow/contrib/py2tf/converters/single_return.py
Labels: cla: yes

#17598 Including the original path to find bazel.
  tensorflow/tools/ci_build/osx/libtensorflow_cpu.sh
Labels: cla: yes

#17599 Disable tensorflow/contrib/learn:monitors_test for pip gpu
  tensorflow/contrib/learn/BUILD
Labels: cla: yes

#17606 Include links to new announce@ list
  README.md
  tensorflow/docs_src/community/welcome.md
Labels: cla: yes

#17617 Fix mac installation documentation error
  tensorflow/docs_src/install/install_mac.md
Labels: awaiting testing (then merge), cla: yes

#17597 SECURITY.md: minor sp, permisisons->permissions
  SECURITY.md
Labels: cla: yes

#17604 Fix broken graphviz download link and change to https
  tensorflow/docs_src/performance/xla/jit.md
Labels: cla: yes

#17283 Fix bug 17175
  tensorflow/python/ops/special_math_ops.py
  tensorflow/python/ops/special_math_ops_test.py
Labels: awaiting testing (then merge), cla: yes

#17100 Minor improvements to `estimator.predict()` docs
  tensorflow/python/estimator/estimator.py
Labels: awaiting testing (then merge), cla: yes

#17063 Add wheel dependency to cmake README
  tensorflow/contrib/cmake/README.md
Labels: awaiting review, awaiting testing (then merge), cla: yes

#17574 Correct curly brace typo
  tensorflow/docs_src/get_started/get_started_for_beginners.md
Labels: cla: yes

#17583 Update RELEASE.md
  RELEASE.md
Labels: cla: yes

#17367 Enable CUDNN_TENSOR_OP_MATH for fp16 RNNs
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes

#17529 Add scan command to saved_model_cli to check for security sensitive ops.
  tensorflow/python/tools/saved_model_cli.py
  tensorflow/python/tools/saved_model_cli_test.py
Labels: cla: yes

#17661 contrib/quantize: minor spelling
  tensorflow/contrib/quantize/python/fold_batch_norms.py
  tensorflow/contrib/quantize/python/quant_ops.py
  tensorflow/contrib/quantize/python/quantize.py
  tensorflow/contrib/quantize/python/quantize_graph.py
  tensorflow/contrib/quantize/python/quantize_parameterized_test.py
  tensorflow/contrib/quantize/python/quantize_test.py
Labels: cla: yes

#17660 Make tensorflow/python:framework_importer_test large
  tensorflow/python/BUILD
Labels: cla: yes

#17610 [CMake]Exclude duplicate tests from ${tf_test_src_simple}
  tensorflow/contrib/cmake/tf_tests.cmake
Labels: cla: yes

#17605 MKL DNN: fix the TF1.6 speed issue by fixing MKL DNN LRN taking the optimum path
  tensorflow/core/graph/mkl_layout_pass.cc
Labels: awaiting testing (then merge), cla: yes

#17508 jpeg.BUILD: Use --cpu instead of --android_cpu
  third_party/jpeg/jpeg.BUILD
Labels: cla: yes

#17531 contrib/lite: spelling/code tweaks
  tensorflow/contrib/lite/arena_planner.h
  tensorflow/contrib/lite/builtin_ops.h
  tensorflow/contrib/lite/error_reporter.h
  tensorflow/contrib/lite/interpreter.h
  tensorflow/contrib/lite/interpreter_test.cc
  tensorflow/contrib/lite/kernels/conv.cc
  tensorflow/contrib/lite/kernels/depthwise_conv.cc
  tensorflow/contrib/lite/kernels/fully_connected.cc
  tensorflow/contrib/lite/kernels/kernel_util.h
  tensorflow/contrib/lite/kernels/lsh_projection.cc
  tensorflow/contrib/lite/kernels/lstm.cc
  tensorflow/contrib/lite/kernels/reshape.cc
  tensorflow/contrib/lite/kernels/reshape_test.cc
  tensorflow/contrib/lite/kernels/test_util.cc
  tensorflow/contrib/lite/kernels/unidirectional_sequence_lstm.cc
  tensorflow/contrib/lite/memory_planner.h
  tensorflow/contrib/lite/model.h
  tensorflow/contrib/lite/nnapi/NeuralNetworksShim.h
  tensorflow/contrib/lite/simple_memory_arena.cc
  tensorflow/contrib/lite/simple_memory_arena.h
Labels: cla: yes, comp:lite

#17655 Fix the script entry point for freeze_graph.
  tensorflow/python/tools/freeze_graph.py
  tensorflow/tools/pip_package/setup.py
Labels: awaiting testing (then merge), cla: yes

#17496 Cherrypicks for 1.5
  tensorflow/core/common_runtime/executor.cc
  tensorflow/core/kernels/strided_slice_op.cc
  tensorflow/python/kernel_tests/array_ops_test.py
  tensorflow/workspace.bzl
Labels: awaiting testing (then merge), cla: yes

#17649 Fix broken links in tutorial/layers
  tensorflow/docs_src/tutorials/layers.md
Labels: awaiting testing (then merge), cla: yes

#17640 Fix TensorBoard tutorial links to the wrong MNIST tutorial example code
  tensorflow/docs_src/programmers_guide/summaries_and_tensorboard.md
Labels: awaiting testing (then merge), cla: yes

#17636 Fix broken link in programmers_guide/faq and some minor format
  tensorflow/docs_src/programmers_guide/faq.md
Labels: awaiting testing (then merge), cla: yes

#17594 Fix the broken link of tf-learn's iris tutorial also some format and typo
  tensorflow/docs_src/programmers_guide/debugger.md
Labels: awaiting testing (then merge), cla: yes

#17524 Improvements for Android TV
  tensorflow/contrib/makefile/README.md
  tensorflow/examples/android/AndroidManifest.xml
  tensorflow/examples/android/src/org/tensorflow/demo/CameraActivity.java
  tensorflow/examples/android/src/org/tensorflow/demo/StylizeActivity.java
Labels: awaiting testing (then merge), cla: yes

#17481 Update wide.md
  tensorflow/docs_src/tutorials/wide.md
Labels: awaiting testing (then merge), cla: yes

#17466 fix typo
  tensorflow/contrib/predictor/predictor_factories.py
Labels: awaiting testing (then merge), cla: yes

#17685 Fix format issue in ffmpeg
  tensorflow/contrib/ffmpeg/default/ffmpeg_lib.cc
Labels: cla: yes

#17678 Fix broken link of tf.train.Example in recurrent_quickdraw.md
  tensorflow/docs_src/tutorials/recurrent_quickdraw.md
Labels: cla: yes

#17681 Fix warning in embedding_ops
  tensorflow/contrib/layers/python/layers/embedding_ops.py
  tensorflow/contrib/learn/python/learn/ops/embeddings_ops.py
Labels: cla: yes, kokoro:force-run

#17665 Fix link
  tensorflow/python/ops/nn_ops.py
Labels: awaiting testing (then merge), cla: yes

#17570 Run selective registration tool even if it's just been built
  tensorflow/contrib/makefile/build_all_ios.sh
Labels: awaiting testing (then merge), cla: yes

#17561 Fix the messed up list format in using_tpu.md
  tensorflow/docs_src/programmers_guide/using_tpu.md
Labels: awaiting testing (then merge), cla: yes

#17697 Fix issue of tf.gfile.Exists with Unicode on Windows
  tensorflow/core/platform/windows/windows_file_system.cc
  tensorflow/python/lib/io/file_io_test.py
Labels: cla: yes

#17591 Support other dtypes in BeamSearchDecoder initialization
  tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py
Labels: awaiting review, cla: yes

#17711 Fix broken link of TensorFlow Debugger (tfdbg) in layers tutorials
  tensorflow/docs_src/tutorials/layers.md
Labels: cla: yes

#17680 1.7.0rc1 cherry-pick request: Fixes a race condition in function instantiation.
  tensorflow/core/common_runtime/function.cc
  tensorflow/python/data/kernel_tests/filter_dataset_op_test.py
Labels: cla: yes

#14986 improvement in the tf.nn.raw_rnn documentation
  tensorflow/python/ops/rnn.py
Labels: awaiting testing (then merge), cla: yes

#17495 Updating version for 1.5.1 patch release.
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/pip_package/setup.py
Labels: awaiting testing (then merge), cla: yes

#17723 Pin the version of cuDNN used in Dockerfile.gpu
  tensorflow/tools/docker/Dockerfile.gpu
Labels: awaiting testing (then merge), cla: yes

#17630 Fix broken link in kernel method tutorial
  tensorflow/docs_src/tutorials/kernel_methods.md
Labels: awaiting testing (then merge), cla: yes

#17503 set default values of args in print_tensors_in_checkpoint_file
  tensorflow/python/tools/inspect_checkpoint.py
Labels: awaiting testing (then merge), cla: yes

#17409 TensorRT support for ARM architectures
  third_party/tensorrt/tensorrt_configure.bzl
Labels: awaiting testing (then merge), cla: yes

#17406 updating documentation
  tensorflow/contrib/rnn/python/ops/lstm_ops.py
Labels: awaiting testing (then merge), cla: yes

#17402 Add missing spaces in multiline strings
  tensorflow/contrib/framework/python/ops/arg_scope.py
  tensorflow/contrib/grid_rnn/python/ops/grid_rnn_cell.py
  tensorflow/contrib/kfac/python/ops/optimizer.py
  tensorflow/contrib/layers/python/layers/encoders.py
  tensorflow/contrib/learn/python/learn/estimators/estimator.py
  tensorflow/contrib/learn/python/learn/experiment.py
  tensorflow/contrib/lite/schema/upgrade_schema.py
  tensorflow/contrib/metrics/python/ops/metric_ops.py
  tensorflow/python/keras/_impl/keras/engine/training.py
  tensorflow/python/keras/_impl/keras/layers/recurrent.py
  tensorflow/python/keras/_impl/keras/utils/generic_utils.py
  tensorflow/python/layers/base.py
  tensorflow/tools/compatibility/tf_upgrade.py
  tensorflow/tools/dist_test/python/mnist_replica.py
Labels: awaiting testing (then merge), cla: yes

#17376 Fix nsync build issue
  tensorflow/contrib/makefile/build_all_ios.sh
Labels: awaiting testing (then merge), cla: yes

#17701 contrib/tpu: minor spelling tweaks
  tensorflow/contrib/tpu/ops/tpu_embedding_ops.cc
  tensorflow/contrib/tpu/python/tpu/device_assignment.py
  tensorflow/contrib/tpu/python/tpu/tpu_config.py
  tensorflow/contrib/tpu/python/tpu/tpu_context.py
  tensorflow/contrib/tpu/python/tpu/tpu_estimator.py
  tensorflow/contrib/tpu/python/tpu/training_loop.py
Labels: awaiting testing (then merge), cla: yes

#17434 Fix typo
  SECURITY.md
Labels: cla: yes

#17726 contrib/gan: minor spelling tweaks
  tensorflow/contrib/gan/python/eval/python/classifier_metrics_impl.py
  tensorflow/contrib/gan/python/eval/python/sliced_wasserstein_impl.py
  tensorflow/contrib/gan/python/features/python/conditioning_utils_impl.py
  tensorflow/contrib/gan/python/features/python/random_tensor_pool_impl.py
  tensorflow/contrib/gan/python/features/python/virtual_batchnorm_test.py
Labels: awaiting testing (then merge), cla: yes

#17724 Update ios.md
  tensorflow/contrib/lite/g3doc/ios.md
Labels: awaiting testing (then merge), cla: yes

#17722 Update README.md
  tensorflow/contrib/lite/README.md
Labels: awaiting testing (then merge), cla: yes

#17719 Elaborate on documentation for using tf.layers.batch_normalization
  tensorflow/python/layers/normalization.py
Labels: awaiting testing (then merge), cla: yes

#17725 Patch release notes
  RELEASE.md
Labels: cla: yes

#17712 update doc for tf.train.Saver() max_to_keep argument to resolve #17554
  tensorflow/python/training/saver.py
Labels: awaiting testing (then merge), cla: yes

#17704 atrous_conv2d doc fix newline
  tensorflow/python/ops/nn_ops.py
Labels: awaiting testing (then merge), cla: yes

#17573 contrib/lite: add missing include assert.h (spectrogram.cc)
  tensorflow/contrib/lite/kernels/internal/spectrogram.cc
Labels: awaiting testing (then merge), cla: yes, comp:lite

#17505 Modify a typo for the HandwrittenConv of conv_ops_test.
  tensorflow/core/kernels/conv_ops_test.cc
Labels: awaiting testing (then merge), cla: yes

#17741 Fix broken link of performance guide for the `tf.data` API
  tensorflow/docs_src/performance/performance_guide.md
Labels: awaiting testing (then merge), cla: yes

#17737 README.cmd typo.
  tensorflow/contrib/slim/README.md
Labels: awaiting testing (then merge), cla: yes

#17638 minor edit
  tensorflow/docs_src/tutorials/image_retraining.md
Labels: awaiting testing (then merge), cla: yes

#17750 using finally in tf_record_iterator()
  tensorflow/python/lib/io/tf_record.py
Labels: awaiting testing (then merge), cla: yes

#17751 MKL DNN: fix the TF1.6 speed issue by fixing MKL DNN LRN taking the optimum path (#17605)
  tensorflow/core/graph/mkl_layout_pass.cc
Labels: cla: yes

#17745 Cast return value that caused warning
  tensorflow/core/util/stat_summarizer.h
Labels: awaiting testing (then merge), cla: yes

#17513 Fix minor typo in saved_model.md
  tensorflow/docs_src/programmers_guide/saved_model.md
Labels: awaiting testing (then merge), cla: yes

#17696 Update documentation
  tensorflow/contrib/tensorrt/README.md
Labels: awaiting testing (then merge), cla: yes

#17781 1.7.0rc2 cherry-pick request: Fixes a bug in `tf.contrib.data.map_and_batch()` shape inference
  tensorflow/contrib/data/python/kernel_tests/batch_dataset_op_test.py
  tensorflow/contrib/data/python/ops/batching.py
Labels: cla: yes

#16909 Add doc on the order of eigenvalues returned by tf.self_adjoint_eig
  tensorflow/core/api_def/base_api/api_def_SelfAdjointEig.pbtxt
  tensorflow/core/api_def/base_api/api_def_SelfAdjointEigV2.pbtxt
  tensorflow/python/ops/linalg_ops.py
Labels: awaiting testing (then merge), cla: yes

#17776 Fix incorrect link of checkpoint files in CNN tutorials
  tensorflow/docs_src/tutorials/deep_cnn.md
Labels: awaiting testing (then merge), cla: yes

#17759 Fix typo
  tensorflow/tools/graph_transforms/fold_old_batch_norms_test.cc
Labels: awaiting testing (then merge), cla: yes

#17764 Add missing linking libs for iOS
  tensorflow/examples/ios/README.md
Labels: awaiting testing (then merge), cla: yes

#17786 Update version strings for 1.7.0-rc1
  tensorflow/core/public/version.h
  tensorflow/docs_src/install/install_c.md
  tensorflow/docs_src/install/install_go.md
  tensorflow/docs_src/install/install_java.md
  tensorflow/docs_src/install/install_linux.md
  tensorflow/docs_src/install/install_mac.md
  tensorflow/docs_src/install/install_sources.md
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#17668 Fix to 'Model' object has no attribute '_container_nodes' error when using tf.keras.utils.plot_model().
  tensorflow/python/keras/_impl/keras/utils/vis_utils.py
Labels: awaiting review, cla: yes

#16134 Added training parameter to batch_normalization
  tensorflow/examples/learn/resnet.py
Labels: awaiting testing (then merge), cla: yes

#17775 MKL Fixed timeline_test unit test failure, changed the test so that
  tensorflow/python/client/timeline_test.py
Labels: awaiting testing (then merge), cla: yes

#17805 minor formatting fix in random_uniform documentation
  tensorflow/python/ops/random_ops.py
Labels: cla: yes

#13312 Support TensorArray in BeamSearchDecoder state.
  tensorflow/contrib/seq2seq/python/kernel_tests/attention_wrapper_test.py
  tensorflow/contrib/seq2seq/python/kernel_tests/beam_search_decoder_test.py
  tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py
  tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py
Labels: awaiting testing (then merge), cla: yes

#17806 Simplify `rejection_resample` test to remove unnecessary iterator initialization
  tensorflow/contrib/data/python/kernel_tests/resample_test.py
Labels: cla: yes

#17829 Fix typos in `resampling.py`.
  tensorflow/contrib/data/python/ops/resampling.py
Labels: cla: yes

#16301 Update README.md
  tensorflow/contrib/lite/README.md
Labels: awaiting review, cla: yes

#14251 Add int64 support of `axis` (`Tidx`) for ConcatV2
  tensorflow/core/kernels/concat_op.cc
  tensorflow/python/kernel_tests/concat_op_test.py
Labels: awaiting testing (then merge), cla: yes

#17840 Adds missing protobuf dep to tf.contrib.data ops.
  tensorflow/contrib/data/BUILD
Labels: cla: yes

#17455 Don't use NCHW or NHCW in tf.layers.conv1d
  tensorflow/python/ops/nn_ops.py
Labels: awaiting review, cla: yes

#17772 [update TensorRT converter]
  tensorflow/contrib/tensorrt/convert/convert_graph.cc
  tensorflow/contrib/tensorrt/convert/convert_nodes.cc
Labels: awaiting testing (then merge), cla: yes

#17848 Disable kmeans test on mac.
  tensorflow/contrib/learn/BUILD
Labels: cla: yes

#17857 improve fp16 tftrt prediction
  tensorflow/contrib/tensorrt/convert/convert_nodes.cc
Labels: awaiting testing (then merge), cla: yes

#16133 Add training parameter to dropout to make it work
  tensorflow/examples/learn/mnist.py
Labels: awaiting testing (then merge), cla: yes

#17864 Revert "Adds missing protobuf dep to tf.contrib.data ops. (#17840)"
  tensorflow/contrib/data/BUILD
Labels: cla: yes

#17858 Fix dataset resampling bug introduced by a bug in datasets itself. fixes #16606
  tensorflow/contrib/data/python/kernel_tests/resample_test.py
  tensorflow/contrib/data/python/ops/resampling.py
Labels: cla: yes

#17157 LoggingTensorHook to read from runconfig in Estimator
  tensorflow/python/estimator/estimator.py
  tensorflow/python/estimator/run_config.py
Labels: awaiting testing (then merge), cla: yes

#17871 Branch 189819449
  tensorflow/compiler/xla/service/hlo.proto
  tensorflow/compiler/xla/service/hlo_computation.cc
  tensorflow/compiler/xla/service/hlo_computation.h
  tensorflow/compiler/xla/service/hlo_instruction.cc
  tensorflow/compiler/xla/service/hlo_instruction.h
  tensorflow/compiler/xla/service/hlo_module.cc
  tensorflow/contrib/data/python/ops/counter.py
  tensorflow/contrib/distributions/BUILD
  tensorflow/contrib/distributions/python/kernel_tests/statistical_testing_test.py
  tensorflow/contrib/lite/python/interpreter.py
  tensorflow/contrib/lite/python/interpreter_test.py
  tensorflow/contrib/lite/python/interpreter_wrapper/interpreter_wrapper.cc
  tensorflow/contrib/lite/python/interpreter_wrapper/interpreter_wrapper.h
  tensorflow/python/framework/test_util.py
  tensorflow/python/keras/BUILD
Labels: cla: yes

#17874 Revert "Fix dataset resampling bug introduced by a bug in datasets itself. fixes #16606 "
  tensorflow/contrib/data/python/kernel_tests/resample_test.py
  tensorflow/contrib/data/python/ops/resampling.py
Labels: cla: yes

#17870 Fix windows GPU build scripts.
  tensorflow/tools/ci_build/windows/gpu/cmake/run_build.bat
Labels: cla: yes

#17774 Revert "Windows: Enable tensorflow/contrib in Bazel build (#16659)"
  configure.py
  tensorflow/contrib/BUILD
  tensorflow/contrib/__init__.py
  tensorflow/contrib/boosted_trees/lib/utils/batch_features.h
  tensorflow/contrib/distributions/BUILD
  tensorflow/contrib/eager/python/BUILD
  tensorflow/contrib/eager/python/examples/linear_regression/BUILD
  tensorflow/contrib/gan/BUILD
  tensorflow/contrib/kfac/python/kernel_tests/BUILD
  tensorflow/contrib/labeled_tensor/BUILD
  tensorflow/contrib/layers/BUILD
  tensorflow/contrib/learn/BUILD
  tensorflow/contrib/lookup/BUILD
  tensorflow/contrib/py2tf/converters/BUILD
  tensorflow/contrib/py2tf/utils/BUILD
  tensorflow/contrib/remote_fused_graph/pylib/BUILD
  tensorflow/contrib/saved_model/BUILD
  tensorflow/contrib/session_bundle/BUILD
  tensorflow/contrib/slim/python/slim/data/BUILD
  tensorflow/contrib/tensor_forest/BUILD
  tensorflow/contrib/tensorboard/BUILD
  tensorflow/contrib/timeseries/examples/BUILD
  tensorflow/contrib/timeseries/python/timeseries/BUILD
  tensorflow/contrib/timeseries/python/timeseries/state_space_models/BUILD
  tensorflow/contrib/tpu/BUILD
  tensorflow/contrib/util/loader.py
  tensorflow/core/framework/dataset.h
  tensorflow/core/lib/core/stringpiece.cc
  tensorflow/core/lib/core/stringpiece.h
  tensorflow/core/platform/tracing.h
  tensorflow/python/BUILD
  tensorflow/python/debug/BUILD
  tensorflow/python/keras/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/tensorflow.bzl
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/def_file_filter/BUILD
  tensorflow/tools/def_file_filter/BUILD.tpl
  tensorflow/tools/def_file_filter/def_file_filter.py.tpl
  tensorflow/tools/def_file_filter/def_file_filter_configure.bzl
  tensorflow/tools/pip_package/BUILD
  tensorflow/workspace.bzl
Labels: cla: yes

#17899 Branch 189913309
  tensorflow/compiler/xla/client/executable_build_options.cc
  tensorflow/compiler/xla/client/executable_build_options.h
  tensorflow/compiler/xla/client/xla_client/xla_builder.cc
  tensorflow/compiler/xla/client/xla_client/xla_builder.h
  tensorflow/compiler/xla/python/local_computation_builder.i
  tensorflow/compiler/xla/python/numpy_bridge.cc
  tensorflow/compiler/xla/python/numpy_bridge.h
  tensorflow/compiler/xla/python/xla_client.py
  tensorflow/compiler/xla/service/gpu/BUILD
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.h
  tensorflow/compiler/xla/service/gpu/memset_thunk.cc
  tensorflow/compiler/xla/service/gpu/memset_thunk.h
  tensorflow/compiler/xla/service/gpu/thunk.h
  tensorflow/compiler/xla/service/hlo.proto
  tensorflow/compiler/xla/service/hlo_computation.cc
  tensorflow/compiler/xla/service/hlo_computation.h
  tensorflow/compiler/xla/service/hlo_instruction.cc
  tensorflow/compiler/xla/service/hlo_instruction.h
  tensorflow/compiler/xla/service/hlo_module.cc
  tensorflow/compiler/xla/service/hlo_rematerialization.cc
  tensorflow/compiler/xla/service/hlo_rematerialization.h
  tensorflow/compiler/xla/service/hlo_rematerialization_test.cc
  tensorflow/compiler/xla/service/hlo_scheduling.cc
  tensorflow/compiler/xla/service/hlo_scheduling.h
  tensorflow/compiler/xla/service/hlo_scheduling_test.cc
  tensorflow/compiler/xla/service/local_service.cc
  tensorflow/compiler/xla/tests/reduce_test.cc
  tensorflow/compiler/xla/tests/reduce_window_test.cc
  tensorflow/contrib/eager/python/network.py
  tensorflow/contrib/framework/python/ops/critical_section_ops.py
  tensorflow/contrib/framework/python/ops/critical_section_test.py
  tensorflow/contrib/opt/python/training/multitask_optimizer_wrapper.py
  tensorflow/contrib/py2tf/converters/lists.py
  tensorflow/core/common_runtime/graph_execution_state.cc
  tensorflow/core/common_runtime/graph_execution_state.h
  tensorflow/core/graph/subgraph.cc
  tensorflow/core/graph/subgraph.h
  tensorflow/core/kernels/avgpooling_op.cc
  tensorflow/core/ops/data_flow_ops.cc
  tensorflow/core/platform/cloud/BUILD
  tensorflow/core/platform/cloud/fake_env.cc
  tensorflow/core/platform/cloud/fake_env.h
  tensorflow/core/platform/cloud/gce_env_utils.cc
  tensorflow/core/platform/cloud/gce_env_utils.h
  tensorflow/core/platform/cloud/gcp_env_utils_test.cc
  tensorflow/core/platform/cloud/google_auth_provider.cc
  tensorflow/core/platform/cloud/google_auth_provider.h
  tensorflow/core/platform/cloud/google_auth_provider_test.cc
  tensorflow/core/platform/env.h
  tensorflow/docs_src/install/install_linux.md
  tensorflow/python/framework/importer.py
  tensorflow/python/framework/importer_test.py
  tensorflow/python/framework/ops.py
  tensorflow/python/framework/ops_test.py
  tensorflow/python/keras/_impl/keras/backend.py
  tensorflow/python/kernel_tests/variable_scope_test.py
  tensorflow/python/ops/template.py
  tensorflow/python/ops/variable_scope.py
  tensorflow/python/training/saver.py
Labels: cla: yes

#17896 Fix dataset resampling bug introduced by a bug in datasets itself. fixes #16606
  tensorflow/contrib/data/python/kernel_tests/resample_test.py
  tensorflow/contrib/data/python/ops/resampling.py
Labels: cla: yes

#17808 Fix broken internal anchor link in rnn quickdraw tutorial
  tensorflow/docs_src/tutorials/recurrent_quickdraw.md
Labels: awaiting testing (then merge), cla: yes

#17812 Fix two external anchor link in kernel method tutorial
  tensorflow/docs_src/tutorials/kernel_methods.md
Labels: awaiting testing (then merge), cla: yes

#17551 SYCL with ComputeCpp: local_config_sycl has multiple matches
  third_party/sycl/sycl/BUILD.tpl
Labels: awaiting review, cla: yes

#17394 add support for other cpu type(aarch64) for tensorRT
  configure.py
Labels: awaiting review, cla: yes
