Repository tensorflow/tensorflow, pull requests merged in 2019-01, with the labels that each got.

#24664 [TF port] Disable tests for GetCurrentCpu() on iOS/OS X because MacOS…
  tensorflow/core/platform/port_test.cc
  tensorflow/core/platform/posix/port.cc
Labels: cla: yes

#24630 [XLA] Allow the reducewindow -> reduce optimization to be disabled
  tensorflow/compiler/xla/service/algebraic_simplifier.cc
  tensorflow/compiler/xla/service/algebraic_simplifier.h
Labels: cla: yes, ready to pull, size:L

#24638 Fix C++14-compat warning in pattern_matcher.h
  tensorflow/compiler/xla/service/pattern_matcher.h
Labels: cla: yes, ready to pull, size:XS

#24651 Unused variable removed from softmax_op_functor.h
  tensorflow/core/kernels/softmax_op_functor.h
Labels: cla: yes, ready to pull, size:XS

#24629 Fix incorrect display of keras model summary
  tensorflow/python/keras/utils/layer_utils.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#24413 The gradient op of bias_add supports 3/4/5D NCHW format
  tensorflow/core/kernels/bias_op.cc
  tensorflow/core/kernels/bias_op_gpu.cu.cc
  tensorflow/core/kernels/bias_op_gpu.h
  tensorflow/python/kernel_tests/bias_op_test.py
  tensorflow/python/ops/nn_grad.py
Labels: cla: yes, ready to pull, size:M

#24689 Cherry pick build fixes.
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/toco/BUILD
  tensorflow/lite/toco/import_tensorflow_test.cc
  tensorflow/lite/toco/toco_convert_test.cc
  tensorflow/lite/toco/toco_port_test.cc
  tensorflow/lite/toco/tooling_util_test.cc
Labels: cla: yes

#24678 Fix quotation typo around "task"
  tensorflow/contrib/distribute/python/mirrored_strategy.py
Labels: cla: yes, ready to pull

#24647 Update eigen library to 88fc23324517 to fix 24457
  tensorflow/workspace.bzl
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#24711 Additional release cherrypicks - cuda 10 docker image & nomac tag handling.
  tensorflow/tools/ci_build/Dockerfile.gpu
  tensorflow/tools/ci_build/Dockerfile.rbe.gpu
  tensorflow/tools/ci_build/builds/run_pip_tests.sh
  tensorflow/tools/ci_build/ci_parameterized_build.sh
  tensorflow/tools/ci_build/osx/cpu/run_contrib.sh
  tensorflow/tools/ci_build/osx/cpu/run_py2_cc_core.sh
Labels: cla: yes

#24700 Update api_def_RegexReplace.pbtxt
  tensorflow/core/api_def/base_api/api_def_RegexReplace.pbtxt
Labels: cla: yes, ready to pull, size:XS

#24461 Initialize only CPU devices in optimize_dataset_op
  tensorflow/core/grappler/grappler_item_builder.cc
Labels: cla: yes, ready to pull, size:XS

#23217 Typo
  tensorflow/lite/examples/label_image/label_image.md
Labels: cla: yes, ready to pull, size:XS

#24666 cloud oauth_client: update for OpenSSL 1.1.0 compatibility
  tensorflow/core/platform/cloud/oauth_client.cc
  tensorflow/core/platform/cloud/oauth_client_test.cc
Labels: cla: yes, ready to pull, size:XS

#14843 Fix crash on closing the app when classifier failed to initialize
  tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/Camera2BasicFragment.java
Labels: cla: yes, ready to pull, size:XS

#24688 Fix several DeprecationWarning: invlid escape sequence
  tensorflow/contrib/kernel_methods/python/losses.py
  tensorflow/contrib/learn/python/learn/learn_io/generator_io_test.py
  tensorflow/contrib/opt/python/training/adam_gs_optimizer.py
  tensorflow/contrib/optimizer_v2/adam.py
  tensorflow/python/client/session_test.py
  tensorflow/python/feature_column/feature_column_test.py
  tensorflow/python/feature_column/feature_column_v2_test.py
  tensorflow/python/kernel_tests/confusion_matrix_test.py
  tensorflow/python/training/adam.py
  tensorflow/tools/ci_build/copy_binary.py
  tensorflow/tools/dist_test/scripts_allreduce/k8s_generate_yaml_lib.py
  third_party/toolchains/preconfig/ubuntu14.04/gcc-nvcc-cuda10.0/windows/msvc_wrapper_for_nvcc.py
  third_party/toolchains/preconfig/ubuntu14.04/gcc-nvcc-cuda9.0/windows/msvc_wrapper_for_nvcc.py
  third_party/toolchains/preconfig/ubuntu14.04/gcc-nvcc/windows/msvc_wrapper_for_nvcc.py
Labels: cla: yes, ready to pull

#22943 [INTEL MKL] Clean up MKL_ML code for BatchNorm op
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
Labels: cla: yes, ready to pull, size:L

#24279 fix typo in scatter_nd_add docstring
  tensorflow/python/ops/state_ops.py
Labels: cla: yes, ready to pull, size:XS

#24247 fix AttributeError: 'module' object has no attribute '???'
  tensorflow/api_template_v1.__init__.py
  tensorflow/contrib/cmake/python_modules.txt
  tensorflow/contrib/cmake/tf_python.cmake
Labels: cla: yes, ready to pull, size:XS

#24708 improve docs of depthwise conv
  tensorflow/python/ops/nn_impl.py
Labels: cla: yes, ready to pull, size:XS

#21397 HParams: Clarify what happens when a new value is input to some methods
  tensorflow/contrib/training/python/training/hparam.py
Labels: cla: yes, ready to pull, size:S, stat:awaiting response

#24766 Cherrypick additional release 1.13 build fixes.
  tensorflow/lite/kernels/internal/resize_bilinear_test.cc
  tensorflow/lite/kernels/sparse_output_fully_connected_test.cc
  tensorflow/lite/toco/BUILD
  tensorflow/lite/toco/import_tensorflow_test.cc
  tensorflow/lite/toco/toco_convert_test.cc
  tensorflow/lite/toco/toco_port.cc
  tensorflow/lite/toco/toco_port.h
  tensorflow/lite/toco/toco_port_test.cc
  tensorflow/lite/toco/tooling_util_test.cc
  tensorflow/tools/git/gen_git_source.py
Labels: cla: yes

#24776 Additional test fixes for 1.13
  tensorflow/lite/kernels/dequantize_test.cc
  tensorflow/lite/testing/BUILD
  tensorflow/tools/git/gen_git_source.py
Labels: cla: yes

#24769 resolved incompatible dimension reshape before feed into final dense …
  tensorflow/contrib/eager/python/examples/rnn_ptb/rnn_ptb.py
Labels: cla: yes, ready to pull, size:XS

#24773 Fixes for rnn_keras_estimator.ipynb
  tensorflow/contrib/autograph/examples/notebooks/rnn_keras_estimator.ipynb
Labels: cla: yes, ready to pull, size:S

#24481 TFTRT: Convert between str and unicode in py2
  tensorflow/contrib/tensorrt/python/trt_convert.py
Labels: cla: yes, ready to pull, size:S

#24652 SynchronousMemcpy changed to SynchronousMemcpyD2H and SynchronousMemcpyH2D
  tensorflow/core/common_runtime/gpu/gpu_debug_allocator.cc
Labels: cla: yes, ready to pull, size:S

#24797 Fix TENSORRT docker image and flaky test.
  tensorflow/contrib/boosted_trees/estimator_batch/estimator_test.py
  tensorflow/tools/ci_build/Dockerfile.gpu
Labels: cla: yes

#24749 r1.13-rc0 cherry-pick request: Fix bug in FuseTransposeMklOpTranspose
  tensorflow/core/graph/mkl_layout_pass.cc
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:mkl

#24810 Various build fixes for 1.13
  tensorflow/lite/python/BUILD
  tensorflow/lite/python/convert.py
  tensorflow/lite/testing/tflite_driver.cc
  tensorflow/lite/toco/python/BUILD
Labels: cla: yes

#24799 Avoid grappler bug by restricting to CPU
  tensorflow/core/grappler/grappler_item_builder.cc
Labels: cla: yes

#24467 fix typo
  tensorflow/java/src/gen/cc/op_gen_main.cc
Labels: cla: yes, ready to pull, size:XS

#24783 [Intel MKL] Remove TensorFlow lite test from the public CI. MKL does not support TF Lite.
  tensorflow/tools/ci_build/linux/cpu/run_mkl.sh
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#24793 Fix astor url to pypi.python.org
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull, size:XS

#24787 Install TensorRT in ci_build dockefile.gpu
  tensorflow/tools/ci_build/Dockerfile.gpu
Labels: cla: yes, ready to pull, size:XS

#24840 Issue/24450: allocate smaller slice length for 32-bit arch
  tensorflow/go/attrs.go
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#24880 Cherrypick disk space debugging changes.
  tensorflow/tools/ci_build/ci_parameterized_build.sh
Labels: cla: no

#24900 Cherry pick of "Fix tensor_utils_test"
  tensorflow/lite/kernels/internal/BUILD
Labels: cla: yes

#24867 fix logic adding generated API directory to tensorflow.__path__
  tensorflow/api_template_v1.__init__.py
Labels: awaiting testing (then merge), cla: yes, ready to pull

#24829 Fix: typo in SavedModelBundle.java
  tensorflow/java/src/main/java/org/tensorflow/SavedModelBundle.java
Labels: cla: yes, ready to pull, size:XS

#24907 Add the data file to the data section in BUILD.
  tensorflow/lite/java/BUILD
Labels: cla: yes

#24902 Cherrypick of "Fix tf_driver_test"
  tensorflow/lite/testing/tf_driver_test.cc
Labels: cla: yes

#24908 More disk space debugging messages.
  tensorflow/tools/ci_build/ci_parameterized_build.sh
Labels: cla: yes

#24909 Cherrypick cl/20190114
  tensorflow/contrib/tensorrt/test/quantization_mnist_test.py
Labels: cla: yes

#24891 fixed typo
  tensorflow/python/eager/backprop.py
Labels: cla: yes, ready to pull, size:XS

#24937 Try to fix gen_git_source.py some more.
  tensorflow/tools/git/gen_git_source.py
Labels: cla: yes

#24733 Fix several DeprecationWarning: invlid escape sequence
  tensorflow/contrib/learn/python/learn/utils/gc_test.py
  tensorflow/contrib/session_bundle/exporter.py
  tensorflow/contrib/session_bundle/gc_test.py
  tensorflow/python/kernel_tests/scatter_nd_ops_test.py
Labels: cla: yes, ready to pull, size:S

#24278 Fix warning caused by to_int32
  tensorflow/python/ops/math_ops.py
Labels: cla: yes, ready to pull, size:XS

#24238 Update tables_initializer to link to guide
  tensorflow/python/ops/lookup_ops.py
Labels: awaiting review, cla: yes, ready to pull, size:XS

#24786 Update docstring for tf.train.init_from_checkpoint
  tensorflow/python/training/checkpoint_utils.py
Labels: cla: yes, ready to pull, size:XS

#24884 Fix warnings in feature_column.py
  tensorflow/python/feature_column/feature_column.py
Labels: awaiting testing (then merge), cla: yes, ready to pull, size:S

#24762 Ensure variables are initialized
  tensorflow/core/util/proto/decode.h
Labels: cla: yes, ready to pull, size:S

#24927 Update options.md
  tensorflow/core/profiler/g3doc/options.md
Labels: cla: yes, ready to pull, size:XS

#24805 [typo] Fix a bazel url typo
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull, size:XS

#24747 Add cuDNN deterministic env variable (only for convolution)
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes, ready to pull, size:S

#24862 r1.13-rc0 cherry-pick request: fix races in TF-TRT integration
  tensorflow/contrib/tensorrt/BUILD
  tensorflow/contrib/tensorrt/convert/convert_nodes.cc
  tensorflow/contrib/tensorrt/convert/convert_nodes.h
  tensorflow/contrib/tensorrt/convert/convert_nodes_test.cc
  tensorflow/contrib/tensorrt/kernels/trt_engine_op.cc
  tensorflow/contrib/tensorrt/kernels/trt_engine_op.h
  tensorflow/contrib/tensorrt/ops/trt_engine_op.cc
  tensorflow/contrib/tensorrt/resources/trt_resources.h
Labels: cla: yes, size:M

#24956 Cherry pick windows build fix and tflite test fixes.
  tensorflow/lite/BUILD
  tensorflow/tools/ci_build/windows/libtensorflow_gpu.sh
Labels: cla: yes

#24748 .numpy() was missing in code example in README.md: tf.add(1, 2) should be tf.add(1, 2).numpy()
  README.md
Labels: cla: yes, ready to pull, size:XS, type:docs

#24345 [XLA] Wrap LCB::GetOrCreateLocalClient with StatusOr<T>
  tensorflow/compiler/xla/python/local_computation_builder.cc
Labels: cla: yes, ready to pull, size:S

#24941 Increase the tolerance value for quantization_mnist_test.
  tensorflow/contrib/tensorrt/test/quantization_mnist_test.py
Labels: cla: yes

#24973 Add tf_cc_test to build file to fix sanity check.
  tensorflow/lite/models/smartreply/BUILD
Labels: cla: yes

#24975 Cherry pick fix to tflite tests.
  tensorflow/lite/models/smartreply/BUILD
  tensorflow/lite/models/smartreply/ops/extract_feature_test.cc
  tensorflow/lite/models/smartreply/ops/normalize_test.cc
  tensorflow/lite/models/smartreply/ops/predict_test.cc
  tensorflow/lite/models/smartreply/predictor_test.cc
Labels: cla: no

#24861 r1.13-rc0 cherry-pick request: Fix --config=mkl performance regression
  tensorflow/core/grappler/optimizers/BUILD
  tensorflow/core/grappler/optimizers/remapper.cc
Labels: awaiting review, cla: yes, size:XS

#24455 upgrade aws-sdk-cpp to the earliest release that enables authentication retries
  third_party/aws/BUILD.bazel
  third_party/aws/workspace.bzl
Labels: cla: yes, ready to pull, size:S

#24625 Fix TypeError when using tf.keras.utils.plot_model
  tensorflow/python/keras/utils/vis_utils.py
Labels: cla: yes, ready to pull, size:XS

#25004 Cherry pick additional test failures.
  tensorflow/lite/build_def.bzl
  tensorflow/lite/schema/BUILD
  tensorflow/lite/testing/BUILD
  tensorflow/lite/tools/benchmark/BUILD
  tensorflow/tools/ci_build/builds/test_user_ops.sh
Labels: cla: yes

#24950 Typo error correction context.py
  tensorflow/python/eager/context.py
Labels: cla: yes, ready to pull, size:XS

#24925 Update README.md
  tensorflow/contrib/quantize/README.md
Labels: cla: yes, ready to pull, size:XS

#24922 Update tf_ops_compatibility.md
  tensorflow/lite/g3doc/tf_ops_compatibility.md
Labels: cla: yes, ready to pull, size:XS

#24947 fix spell mistake
  tensorflow/python/util/nest.py
Labels: cla: yes, ready to pull, size:S

#24978 [XLA:GPU] Make sm_35 the min supported LLVM proc
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/nvptx_backend_lib.cc
Labels: cla: yes, ready to pull, size:XS

#24402 [OpenMP] Fix undeclared identifier in eigen_support.cc
  tensorflow/lite/kernels/eigen_support.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#25014 Fix several more r1.13 related test failures.
  tensorflow/contrib/cudnn_rnn/python/kernel_tests/cudnn_rnn_test.py
  tensorflow/lite/build_def.bzl
  tensorflow/lite/java/BUILD
  tensorflow/lite/models/smartreply/ops/predict.cc
  tensorflow/python/keras/optimizer_v2/optimizer_v2_test.py
Labels: cla: yes

#24970 Fix softmax_cross_entropy issue
  tensorflow/python/ops/losses/losses_impl.py
Labels: cla: yes, ready to pull, size:XS

#25032 Disable jni tests on mac (x86_64 toolchain not compatible with our linker script)
  tensorflow/lite/java/BUILD
  tensorflow/lite/java/ovic/BUILD
Labels: cla: yes

#25084 Added release notes for 1.13 release
  RELEASE.md
Labels: cla: yes

#25125 Cherry pick openssl fix and R fix and update release notes.
  RELEASE.md
  tensorflow/core/platform/cloud/oauth_client.cc
  tensorflow/core/platform/cloud/oauth_client_test.cc
  tensorflow/python/util/deprecation.py
Labels: cla: yes

#23225 Update cast_op_test for ARM behavior
  tensorflow/python/kernel_tests/cast_op_test.py
Labels: cla: yes, ready to pull, size:S

#25017 [XLA/AOT] Add check for --help command line option.
  tensorflow/compiler/aot/tfcompile_main.cc
Labels: cla: yes, ready to pull, size:XS

#24994 Add details for running tests from nightly build images. Closes #24993.
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:XS

#25129 TF Eager profiler_test added test to validate error case
  tensorflow/python/eager/profiler_test.py
Labels: cla: yes, ready to pull, size:XS

#23089 Make shared S3 file system lib linkable
  tensorflow/core/platform/s3/BUILD
Labels: cla: yes, ready to pull, size:XS

#25140 MKL DNN: Cleaning up mkl relu op (removing MKL ML related code)
  tensorflow/core/kernels/mkl_relu_op.cc
Labels: cla: yes, ready to pull, size:L

#25163 TF Contrib typo-error fix
  tensorflow/contrib/cmake/README.md
  tensorflow/contrib/gan/README.md
  tensorflow/contrib/gdr/README.md
  tensorflow/contrib/ignite/README.md
  tensorflow/contrib/learn/README.md
Labels: cla: yes, ready to pull

#25161 replace initialize_all_variables()
  tensorflow/compiler/aot/tests/make_test_graphs.py
  tensorflow/compiler/tests/dense_layer_test.py
  tensorflow/contrib/boosted_trees/python/kernel_tests/model_ops_test.py
  tensorflow/contrib/layers/python/layers/feature_column_ops_test.py
Labels: cla: yes, kokoro:force-run, ready to pull

#25158 Updated README.md
  tensorflow/java/README.md
Labels: cla: yes, kokoro:force-run, ready to pull, size:XS

#25095 Fix a memory leak in MklDnnData.
  tensorflow/core/util/mkl_util.h
Labels: cla: yes, ready to pull, size:XS

#24967 [INTEL MKL] Fix for failure in //tensorflow/core/kernels:eigen_spatial_convolutions_test
  tensorflow/core/kernels/eigen_spatial_convolutions_test.cc
Labels: cla: yes, ready to pull, size:XS

#23381 Fix the issue for class_weight used with tf.dataset
  tensorflow/python/keras/engine/training_utils_test.py
Labels: cla: yes, ready to pull, size:S

#25090 TF Keras saving_utils_test missing test cases add
  tensorflow/python/keras/saving/saving_utils_test.py
Labels: cla: yes, ready to pull, size:S

#25156 Update README.md
  tensorflow/tools/dist_test/README.md
Labels: cla: yes, ready to pull

#25075 [GPU][ROCm] Fix copy rules for ROCm path
  third_party/gpus/cuda_configure.bzl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, ready to pull, size:XS

#24640 Add model_to_dot and print_summary to tf.keras.utils
  tensorflow/python/keras/utils/__init__.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#24932 [XLA][Rematerialization] Add error message
  tensorflow/compiler/xla/service/hlo_rematerialization.cc
Labels: cla: yes, ready to pull, size:M

#25134 Fix init_ops_test on AVX512 builds
  tensorflow/core/kernels/eigen_contraction_kernel.h
Labels: cla: yes, ready to pull, size:XS

#24635 Replace deprecated test_session with cached_session in quantile_ops_test
  tensorflow/python/kernel_tests/boosted_trees/quantile_ops_test.py
Labels: cla: yes, ready to pull, size:XS

#25169 Replace deprecated usage of np.asscalar with np.ndarray.item()
  tensorflow/compiler/xla/python_api/xla_literal.py
  tensorflow/python/framework/fast_tensor_util.pyx
  tensorflow/python/framework/tensor_util.py
  tensorflow/python/kernel_tests/cwise_ops_test.py
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, ready to pull, size:S

#25023 TF device_test additional test cases covers
  tensorflow/python/framework/device_test.py
Labels: cla: yes, ready to pull, size:S

#25201 fix broken links and typo in NMT w/Attention example
  tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb
Labels: cla: yes, ready to pull

#24637 Fix model_to_dot() for Sequential models
  tensorflow/python/keras/utils/vis_utils.py
Labels: cla: yes, ready to pull, size:XS

#24848 TF Keras conv_utils missing test cases add
  tensorflow/python/keras/utils/conv_utils_test.py
Labels: cla: yes, ready to pull, size:M

#24777 Mkl small size allocator fix for reducing lock overhead in critical path
  tensorflow/core/common_runtime/mkl_cpu_allocator.h
Labels: cla: yes, comp:mkl, ready to pull, size:M

#25186 Fix README.md typo error
  tensorflow/lite/tools/benchmark/README.md
Labels: cla: yes, ready to pull, size:XS

#24737 TF Android Example compile warning fixes
  tensorflow/lite/examples/android/app/build.gradle
  tensorflow/lite/examples/android/app/src/main/AndroidManifest.xml
  tensorflow/lite/java/AndroidManifest.xml
Labels: cla: yes, ready to pull, size:XS

#24449 Update doc references to use `tfp.distributions`
  tensorflow/python/ops/distributions/bijector_impl.py
  tensorflow/python/ops/distributions/transformed_distribution.py
Labels: cla: yes, ready to pull, size:M

#25121 [tflite] fix the location of build_ios_universal_lib.sh in TFLite bechmark doc
  tensorflow/lite/tools/benchmark/ios/README.md
Labels: cla: yes, ready to pull, size:XS

#25256 Use efficient squared_difference instead of square(diff)
  tensorflow/contrib/boosted_trees/python/training/functions/gbdt_batch_test.py
  tensorflow/contrib/boosted_trees/python/utils/losses.py
  tensorflow/contrib/distributions/python/ops/inverse_gamma.py
  tensorflow/contrib/eager/python/examples/linear_regression/linear_regression.py
  tensorflow/contrib/eager/python/examples/rnn_colorbot/rnn_colorbot.py
  tensorflow/contrib/factorization/python/ops/gmm_ops.py
  tensorflow/contrib/layers/python/layers/target_column.py
  tensorflow/contrib/learn/python/learn/estimators/head.py
  tensorflow/contrib/losses/python/losses/loss_ops.py
  tensorflow/contrib/losses/python/metric_learning/metric_loss_ops.py
  tensorflow/contrib/metrics/python/ops/metric_ops.py
  tensorflow/contrib/tensor_forest/client/eval_metrics.py
  tensorflow/contrib/timeseries/python/timeseries/ar_model.py
  tensorflow/python/keras/losses.py
  tensorflow/python/keras/metrics.py
  tensorflow/python/keras/utils/kernelized_utils.py
  tensorflow/python/ops/distributions/normal.py
  tensorflow/python/ops/metrics_impl.py
Labels: cla: yes, ready to pull, size:S

#25142 Update RELEASE.md
  RELEASE.md
Labels: cla: yes

#24391 remove KERB_TICKET_CACHE_PATH env
  tensorflow/core/platform/hadoop/hadoop_file_system.cc
Labels: cla: yes, ready to pull, size:S

#25266 Fix TransposeConv op kernel in TensorFlow Lite
  tensorflow/lite/kernels/transpose_conv.cc
Labels: cla: yes

#25048 Fix sparse_to_dense warning in 25043
  tensorflow/python/ops/nn_impl.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#25182 Define _USE_MATH_DEFINES to get math constants for MSVC
  tensorflow/compiler/xla/client/lib/math.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull, size:XS

#25192 Fix incorrect link in the docs
  tensorflow/tools/ci_build/Dockerfile.debian.jessie.cpu
Labels: cla: yes, ready to pull, size:XS

#25268 Cherrypick fixes related to estimator dependency
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#25286 [CP request] Fix GFile tf_export for v2
  tensorflow/python/platform/gfile.py
  tensorflow/tools/api/golden/v1/tensorflow.io.gfile.-g-file.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.io.gfile.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.io.gfile.-g-file.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.io.gfile.pbtxt
  tensorflow/tools/compatibility/renames_v2.py
Labels: cla: yes

#25290 Merge ignite fixes for 1.13
  tensorflow/contrib/ignite/README.md
  tensorflow/contrib/ignite/python/ops/ignite_dataset_ops.py
  tensorflow/contrib/ignite/python/tests/ignite_dataset_test.py
  tensorflow/contrib/kafka/python/kernel_tests/kafka_test.sh
  tensorflow/contrib/kafka/python/ops/kafka_dataset_ops.py
Labels: cla: yes

#25204 Add Estimator release notes to 1.13
  RELEASE.md
Labels: cla: yes, ready to pull

#25261 Replace deprecated usage of np.asscalar with np.ndarray.item()
  tensorflow/compiler/xla/python_api/xla_literal.py
  tensorflow/python/framework/fast_tensor_util.pyx
  tensorflow/python/framework/tensor_util.py
  tensorflow/python/kernel_tests/cwise_ops_test.py
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, ready to pull, size:S

#25297 TFTRT: Capture new logging level introduced by TRT 5.1
  tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc
Labels: cla: yes, ready to pull

#24039 Reserve because we know the size before, helps save reallocation cost.
  tensorflow/cc/tools/freeze_saved_model.cc
Labels: cla: yes, ready to pull, size:XS

#25291 fix for the compiler error with --config=rocm
  tensorflow/stream_executor/rocm/rocm_gpu_executor.cc
Labels: cla: yes, ready to pull, size:XS

#25269 Add deterministic cuDNN max pooling
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes, ready to pull, size:XS

#25219 Replace deprecated test_session with cached_session
  tensorflow/python/ops/image_ops_test.py
Labels: awaiting testing (then merge), cla: yes, ready to pull, size:L

#25354 Do not invoke ROCM toolchain unless -x rocm is specified.
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_rocm.tpl
Labels: cla: yes, ready to pull

#25399 [v1.13][CP Request] Prevent null pointer dereference in decode_gif.
  tensorflow/core/lib/gif/gif_io.cc
Labels: cla: yes
