Repository tensorflow/tensorflow, pull requests merged in 2019-02, with the labels that each got.

#24673 [Intel MKL] Updating the public MKL Dockerfiles to reflect Ubuntu 18.04
  tensorflow/tools/docker/Dockerfile.devel-mkl
  tensorflow/tools/docker/Dockerfile.devel-mkl-horovod
  tensorflow/tools/docker/Dockerfile.mkl
  tensorflow/tools/docker/Dockerfile.mkl-horovod
Labels: cla: yes, comp:mkl, ready to pull, size:M

#25330 Generalize MinMax monotonic optimizer
  tensorflow/core/grappler/op_types.cc
  tensorflow/core/grappler/op_types.h
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
  tensorflow/core/grappler/optimizers/arithmetic_optimizer_test.cc
Labels: cla: yes, ready to pull, size:M

#25318 Updated the README.md file
  tensorflow/lite/tools/accuracy/ilsvrc/README.md
Labels: cla: yes, ready to pull, size:XS

#24740 TF Android Example first time compile and run FileNotFoundException bug fix
  tensorflow/lite/examples/android/app/build.gradle
Labels: cla: yes, ready to pull, size:S

#25267 <release 13>-<rc1> cherry-pick request: Removing spurious warning in tf.data.
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, size:S

#24583 Fix tf.version.GIT_VERSION to return str (instead of bytes)
  tensorflow/tools/git/gen_git_source.py
Labels: cla: yes, ready to pull, size:XS

#25410 Optimize wording in README.md for APIs and their backwards compatibility
  README.md
Labels: cla: yes, ready to pull, size:XS

#25401 [INTEL MKL] Check if filter is a constant only in the forward pass for Depthwise Conv2D.
  tensorflow/core/graph/mkl_layout_pass.cc
  tensorflow/core/kernels/mkl_fused_ops_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#24526 Use rate instead of keep_prob calling dropout in keras
  tensorflow/python/keras/layers/core.py
Labels: cla: yes, ready to pull, size:XS

#21608 avoid url error exception
  tensorflow/python/keras/utils/data_utils.py
Labels: awaiting testing (then merge), cla: yes, ready to pull, size:XS

#23838 Updated PR for "Fold BN after depthwise conv"(#21023)
  tensorflow/tools/graph_transforms/fold_batch_norms.cc
  tensorflow/tools/graph_transforms/fold_batch_norms_test.cc
  tensorflow/tools/graph_transforms/fold_old_batch_norms.cc
  tensorflow/tools/graph_transforms/fold_old_batch_norms_test.cc
Labels: cla: yes, ready to pull, size:M

#25309 Set default TF_BUILD_VERSION to r1.13 on MKL images
  tensorflow/tools/docker/Dockerfile.devel-mkl-horovod
  tensorflow/tools/docker/Dockerfile.mkl
  tensorflow/tools/docker/Dockerfile.mkl-horovod
Labels: awaiting review, cla: yes, comp:mkl, size:XS

#25028 [r1.13] Update kinesis dataset to match v2 API
  tensorflow/contrib/kinesis/python/ops/kinesis_dataset_ops.py
Labels: cla: yes

#25489 Change version to 1.13.0-rc1
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#25491 TFTRT: Fix #if logic for TRT 5.1+
  tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc
Labels: cla: yes, ready to pull

#25497 Revert dataset warning fix as it breaks many tests.
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes

#25498 Fix applications integration test to be compatible with latest release of Keras-Applications
  tensorflow/python/keras/applications/applications_test.py
Labels: cla: yes

#25334 Fix a minor typo
  tensorflow/python/keras/saving/saved_model.py
Labels: cla: yes, ready to pull, size:XS

#21712 ci_build: Upgrade the Python 'six' compatibility module
  tensorflow/tools/ci_build/install/install_pip_packages.sh
Labels: awaiting testing (then merge), cla: yes, ready to pull, size:XS

#25503 Update astor version to fix https://github.com/berkerpeksag/astor/iss…
  tensorflow/workspace.bzl
Labels: awaiting review, cla: yes, prtype:bugfix, size:XS

#25502 [Intel MKL]: Added missing data type for MKL quantized ops
  tensorflow/core/graph/mkl_graph_util.h
Labels: cla: yes, ready to pull, size:XS

#25404 Improves docstring for tf.contrib.nn.conv1d_transpose
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, ready to pull, size:S

#25532 Skip testNonMatchingVariableCreation.
  tensorflow/lite/build_def.bzl
Labels: awaiting review, cla: yes, size:XS

#25438 Support max pooling ops in algorithmic optimizer
  tensorflow/core/grappler/op_types.cc
  tensorflow/core/grappler/op_types.h
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
  tensorflow/core/grappler/optimizers/arithmetic_optimizer_test.cc
Labels: cla: yes, ready to pull, size:M

#25437 Add example code to tf.data.Dataset.filter() documentation
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, ready to pull

#25561 fixed the reuse argument in Dense layer's documentation
  tensorflow/python/layers/core.py
Labels: cla: yes, ready to pull, size:XS

#25335 Bazel: Remove deprecated experimental_shortened_obj_file_path option
  configure.py
Labels: cla: yes, ready to pull, size:XS

#25505 Updated backend.py for the typo error
  tensorflow/python/keras/backend.py
Labels: cla: yes, ready to pull, size:XS

#25547 Update bits.h
  tensorflow/lite/experimental/microfrontend/lib/bits.h
Labels: cla: yes, ready to pull, size:XS

#25545 Update ring.h
  tensorflow/contrib/mpi_collectives/ring.h
Labels: cla: yes, ready to pull, size:XS

#25500 [Intel MKL]: Fixing a failure in conv_ops_test unit test caused by MKL pad fusion
  tensorflow/core/kernels/mkl_conv_ops.h
Labels: cla: yes, ready to pull, size:S

#25562 Update RELEASE.md
  RELEASE.md
Labels: cla: yes

#25510 ci_build: Upgrade the Python 'six' compatibility module
  tensorflow/tools/ci_build/install/install_pip_packages.sh
Labels: cla: yes, ready to pull, size:XS

#25600 Add TF_PACKAGE_VERSION to Dockerfiles that install via pip
  tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/partials/tensorflow.partial.Dockerfile
  tensorflow/tools/dockerfiles/spec.yml
Labels: cla: yes, ready to pull, size:M

#25573 Docstring updated for missed 'Raises"
  tensorflow/python/keras/backend.py
Labels: cla: yes, ready to pull, size:XS

#25612 Typo error fix devguide.md
  tensorflow/lite/g3doc/devguide.md
Labels: cla: yes, ready to pull, size:XS

#25626 Adding Python3.7 to release notes.
  RELEASE.md
Labels: cla: yes

#25535 Bug: Remove reciprocal from monotonic decreasing ops
  tensorflow/core/grappler/op_types.cc
Labels: cla: yes, ready to pull, size:XS

#25482 Fixed a misspelled var name in hlo_cost_analysis.cc comment.
  tensorflow/compiler/xla/service/hlo_cost_analysis.cc
Labels: cla: yes, ready to pull, size:XS

#24088 Configurable AWS logging for S3 filesystem
  tensorflow/core/platform/s3/aws_logging.cc
Labels: cla: yes, ready to pull, size:XS

#25671 Cherry pick fix to 1.13 for python 3
  tensorflow/python/eager/ops_test.py
  tensorflow/python/eager/pywrap_tensor.cc
Labels: cla: yes

#25589 Support for public Ambiq SDK
  tensorflow/lite/experimental/micro/README.md
  tensorflow/lite/experimental/micro/examples/micro_speech/apollo3/pushbutton_main.c
  tensorflow/lite/experimental/micro/tools/make/Makefile
  tensorflow/lite/experimental/micro/tools/make/download_dependencies.sh
  tensorflow/lite/experimental/micro/tools/make/targets/apollo3evb_makefile.inc
Labels: cla: yes, ready to pull, size:M

#25696 Revert timeout for while loop
  tensorflow/core/kernels/control_flow_ops.cc
  tensorflow/python/kernel_tests/control_flow_ops_py_test.py
Labels: cla: yes

#25596 [ROCm][GPU] Finalize ROCm GPU kernels early with -fno-gpu-rdc
  third_party/gpus/crosstool/CROSSTOOL_hipcc.tpl
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_rocm.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, ready to pull, size:M

#25698 Remove deprecation warning on tf.data.v1 functions
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes

#25685 remove unused variable
  tensorflow/python/grappler/item.i
Labels: cla: yes, ready to pull, size:XS

#25633 Mention 'num_parallel_calls' bugfix into 1.13 release note
  RELEASE.md
Labels: cla: yes

#25725 Prepare for rc2 by updating version & fixing tolerance in contrib cudnn test
  tensorflow/contrib/cudnn_rnn/python/kernel_tests/cudnn_rnn_test.py
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#25409 complex64 and complex128 support for tf.decode_raw
  tensorflow/core/kernels/decode_raw_op.cc
  tensorflow/core/ops/parsing_ops.cc
  tensorflow/python/kernel_tests/decode_raw_op_test.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#25065 Removed twice declaration AttrTypeByName
  tensorflow/core/common_runtime/eager/attr_builder.h
Labels: cla: yes, ready to pull, size:XS

#25642 fixed the documentation of glorot_normal according to issue 25564
  tensorflow/python/ops/init_ops.py
Labels: cla: yes, ready to pull, size:XS, type:docs

#20808 Feature requested by issue 18354: No gradient defined for operation DepthwiseConv2dNativeBackpropFilter
  tensorflow/python/ops/nn_grad.py
  tensorflow/python/ops/nn_grad_test.py
Labels: awaiting review, cla: yes, pending merge internally, ready to pull, size:M

#25553 Update docstring parser -> parses
  tensorflow/python/tools/freeze_graph.py
Labels: cla: yes, ready to pull, size:XS

#25770 [Intel MKL] Fix incorrect way to dump optimized graph
  tensorflow/core/common_runtime/optimization_registry.cc
Labels: cla: yes

#25769 Fix regression in XLA in TensorFlow 1.13 RC0, RC1
  tensorflow/compiler/tests/depthwise_conv_op_test.py
  tensorflow/compiler/tf2xla/kernels/conv_op_helpers.cc
Labels: cla: yes, prtype:bugfix

#25737 Update hlo_runner.h
  tensorflow/compiler/xla/service/hlo_runner.h
Labels: cla: yes, ready to pull, size:XS

#25726 [Intel MKL] Fix incorrect way to dump optimized graph
  tensorflow/core/common_runtime/optimization_registry.cc
Labels: cla: yes, ready to pull, size:S

#25739 Update hlo_instruction.h
  tensorflow/compiler/xla/service/hlo_instruction.h
Labels: cla: yes, ready to pull, size:XS

#25740 Update call_graph.h
  tensorflow/compiler/xla/service/call_graph.h
Labels: cla: yes, ready to pull, size:XS

#25738 Update tensor_handle.h
  tensorflow/core/common_runtime/eager/tensor_handle.h
Labels: cla: yes, ready to pull, size:XS

#25782 Update doc for he_normal and lecun_normal according to issue 25564
  tensorflow/python/ops/init_ops.py
Labels: cla: yes, ready to pull, size:S

#25778 Removed warning in sparse_tensor.h
  tensorflow/core/util/sparse/sparse_tensor.h
Labels: cla: yes, ready to pull, size:XS

#25699 [INTEL MKL]: Enable quantization using MKL-DNN
  tensorflow/core/graph/mkl_layout_pass.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#25566 Added mobilenetV2 in keras application test
  tensorflow/python/keras/applications/applications_test.py
Labels: awaiting testing (then merge), cla: yes, ready to pull, size:XS

#25766 TFTRT: Allow FP16 kernels in INT8 mode
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
Labels: cla: yes, ready to pull, size:XS

#25538 Fix misleading comment in layer normalization
  tensorflow/contrib/layers/python/layers/layers.py
Labels: cla: yes, ready to pull, size:XS

#25718 Add Python 3.7 to classifiers (PyPI)
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:XS

#25755 Updated export.cc
  tensorflow/lite/toco/tflite/export.cc
Labels: cla: yes, ready to pull, size:XS

#25717 Removed the warning in optimized_ops.h file
  tensorflow/lite/kernels/internal/optimized/optimized_ops.h
Labels: cla: yes, ready to pull, size:XS

#25741 Update gpu_fusible.h
  tensorflow/compiler/xla/service/gpu/gpu_fusible.h
Labels: cla: yes, ready to pull, size:XS

#25684 Lite: Unpack Operator Negative Axis Support
  tensorflow/lite/kernels/internal/reference/reference_ops.h
  tensorflow/lite/kernels/unpack.cc
  tensorflow/lite/kernels/unpack_test.cc
Labels: cla: yes, ready to pull, size:M

#25815 Replace math_ops.div with math_ops.divide
  tensorflow/python/ops/math_grad.py
Labels: awaiting testing (then merge), cla: yes, ready to pull, size:S

#25793 Disable TensorRT and fix some GPU typos
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/devel-nvidia.partial.Dockerfile
Labels: cla: yes, ready to pull, size:M

#25617 Updated import_tensorflow.cc
  tensorflow/lite/toco/import_tensorflow.cc
Labels: cla: yes, ready to pull, size:XS

#25376 TF Framework ops_test missing test case add
  tensorflow/python/framework/ops_test.py
Labels: cla: yes, ready to pull, size:XS

#25898 TFTRT: Override new 5.1.2 ITensor pure virtual functions
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
Labels: cla: yes, ready to pull, size:S

#25713 Removed redundant code from verifier.cc
  tensorflow/lite/tools/verifier.cc
Labels: cla: yes, ready to pull, size:XS

#25756 Updated export_test.cc
  tensorflow/lite/toco/tflite/export_test.cc
Labels: cla: yes, ready to pull, size:XS

#25750 Updated group_bidirectional_sequence_ops.cc
  tensorflow/lite/toco/graph_transformations/group_bidirectional_sequence_ops.cc
Labels: cla: yes, ready to pull, size:XS

#25758 Changed the type to const
  tensorflow/lite/toco/tflite/export.cc
Labels: cla: yes, ready to pull, size:XS

#25767 Provide a warning for CUDA compute capabilities less than 3.5 when building.
  configure.py
Labels: cla: yes, ready to pull, size:S

#25668 removing extra copy on unordered_set
  tensorflow/cc/framework/gradients.cc
Labels: cla: yes, ready to pull, size:XS

#25900 TFTRT: Don't allow empty tensors
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
Labels: cla: yes, ready to pull

#25905 TFTRT: Override new TRT 5.1 pure virtual functions for FakeITensor
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, ready to pull

#25771 TFTRT: Use IInt8EntropyCalibrator2 for TRT 5.1 onward
  tensorflow/compiler/tf2tensorrt/utils/trt_int8_calibrator.h
Labels: cla: yes, ready to pull, size:XS

#25897 correctly initialize scratch descriptor for gemm autotuning
  tensorflow/compiler/xla/service/gpu/gemm_thunk.cc
  tensorflow/compiler/xla/tests/dot_operation_test.cc
Labels: cla: yes, ready to pull

#25909 Fixed warning in the file
  tensorflow/core/kernels/lookup_util.cc
Labels: cla: yes, ready to pull, size:XS

#25194 Keras added missing test case in image_test
  tensorflow/python/keras/preprocessing/image_test.py
Labels: cla: yes, ready to pull, size:M

#25925 Update utils_impl.py
  tensorflow/python/saved_model/utils_impl.py
Labels: cla: yes, ready to pull, size:XS

#25550 TF Keras merge_test missing test cases add
  tensorflow/python/keras/layers/merge_test.py
Labels: cla: yes, ready to pull, size:M

#25940 removing extra bool array as it is not needed
  tensorflow/cc/framework/gradients.cc
Labels: cla: yes, ready to pull, size:S

#25628 Allow functions of `DistributedVariable`s to implement `custom_gradient`
  tensorflow/python/ops/custom_gradient.py
Labels: cla: yes, ready to pull, size:XS

#25615 Typo error fixed in execute.h
  tensorflow/core/common_runtime/eager/execute.h
Labels: cla: yes, ready to pull, size:XS

#25572 docstring updated
  tensorflow/python/keras/engine/training_utils.py
Labels: cla: yes, ready to pull, size:XS

#25571 TF Ops document updated(unreachable link removed)
  tensorflow/python/ops/ragged/ragged_map_ops.py
Labels: cla: yes, ready to pull, size:XS

#25927 Update profiler.cc
  tensorflow/core/profiler/profiler.cc
Labels: cla: yes, pending merge internally, ready to pull, size:XS

#25879 DOC: Fix typos in readme.
  tensorflow/lite/experimental/micro/README.md
Labels: cla: yes, pending merge internally, ready to pull, size:XS

#25915 Update split_handler_ops.cc
  tensorflow/contrib/boosted_trees/kernels/split_handler_ops.cc
Labels: cla: yes, pending merge internally, ready to pull, size:XS

#25979 [Intel MKL]: Fixing a build issue in mkl_cpu_allocator
  tensorflow/core/common_runtime/mkl_cpu_allocator.h
  tensorflow/core/common_runtime/mkl_cpu_allocator_test.cc
Labels: cla: yes, comp:mkl, pending merge internally, ready to pull

#25928 Update mkl_concat_op.cc
  tensorflow/core/kernels/mkl_concat_op.cc
Labels: cla: yes, pending merge internally, ready to pull, size:XS

#25150 Update profiler ui documentation.
  tensorflow/core/profiler/README.md
Labels: cla: yes, ready to pull, size:XS

#25992 Fix serialization naming for BatchNorm.
  tensorflow/python/keras/layers/serialization.py
  tensorflow/python/keras/layers/serialization_test.py
Labels: cla: yes

#24979 Use safe variance epsilon for float16 layer_norm
  tensorflow/contrib/layers/python/layers/layers.py
  tensorflow/contrib/layers/python/layers/layers_test.py
Labels: cla: yes, pending merge internally, ready to pull, size:S

#26016 Update package version to 1.13.0.
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#25727 Update clip_ops.py
  tensorflow/python/ops/clip_ops.py
Labels: cla: yes, pending merge internally, ready to pull, size:XS

#24245 [Bug Fix]Fix bug of passing different assignment_map object created in each replica thread in init_from_checkpoint
  tensorflow/contrib/distribute/python/checkpoint_utils_test.py
  tensorflow/python/training/checkpoint_utils.py
Labels: cla: yes, ready to pull, size:M

#24092 Update docs for tf.contrib.layers.optimize_loss …
  tensorflow/contrib/layers/python/layers/optimizers.py
Labels: cla: yes, contrib, ready to pull, size:S

#25796 Add tests for TF_CUDNN_DETERMINISTIC
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/cudnn_determinism_test.py
Labels: cla: yes, pending merge internally, ready to pull, size:M

#25188 Fix incorrect link in the docs
  tensorflow/contrib/gan/README.md
Labels: cla: yes, ready to pull, size:XS

#25265 Broken Link
  tensorflow/lite/g3doc/devguide.md
Labels: cla: yes, ready to pull, size:XS

#25803 tf.nn.conv2d_transpose error if output-shape is tuple #25609
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, ready to pull, size:XS

#22557 include <cstring> in a few places that use it
  tensorflow/core/lib/strings/str_util.cc
  tensorflow/core/platform/posix/net.cc
  tensorflow/core/util/command_line_flags.cc
Labels: cla: yes, ready to pull, size:XS

#24746 Fix warning in keras base_layer_utils.py
  tensorflow/python/keras/engine/base_layer_utils.py
Labels: cla: yes, ready to pull, size:XS

#26052 Updated custom_operators.md
  tensorflow/lite/g3doc/custom_operators.md
Labels: cla: yes, ready to pull, size:XS

#26055 Updated tf_ops_compatibility.md
  tensorflow/lite/g3doc/tf_ops_compatibility.md
Labels: cla: yes, ready to pull, size:XS

#26103 1.13.0 cherry-pick request: Update tensorboard dependency to 1.13.x
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#26101 Bump TF version to 1.13.1
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#26066 Added ```python for usage examples
  tensorflow/python/eager/backprop.py
Labels: cla: yes, ready to pull, size:XS

#25906 Removed redundant code from layout_optimizer.cc
  tensorflow/core/grappler/optimizers/layout_optimizer.cc
Labels: cla: yes, ready to pull, size:XS

#26054 Updated profile_buffer_test.cc
  tensorflow/lite/profiling/profile_buffer_test.cc
Labels: cla: yes, ready to pull, size:XS

#26080 Updated lite_test.py
  tensorflow/lite/python/lite_test.py
Labels: cla: yes, ready to pull, size:XS

#26004 FIx CudnnCompatibleLSTM document error
  tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py
Labels: cla: yes, ready to pull, size:XS

#25949 [TF_Java] adding whileLoop method for the Java API
  tensorflow/java/src/main/java/org/tensorflow/Graph.java
  tensorflow/java/src/main/native/graph_jni.cc
  tensorflow/java/src/main/native/graph_jni.h
  tensorflow/java/src/test/java/org/tensorflow/GraphTest.java
Labels: cla: yes, ready to pull, size:L

#26043 Update contributing.md to point to addons
  CONTRIBUTING.md
Labels: awaiting review, cla: yes, ready to pull, size:XS

#26058 Updated hierarchical_tree_broadcaster.cc
  tensorflow/core/common_runtime/hierarchical_tree_broadcaster.cc
Labels: cla: yes, ready to pull, size:XS

#25975 Avoid double hash lookups in multiple places by using returned status from std::unordered_set<>::insert
  tensorflow/cc/framework/gradients.cc
Labels: cla: yes, ready to pull

#25999 Update xla_compilation_device.cc
  tensorflow/compiler/tf2xla/xla_compilation_device.cc
Labels: cla: yes, ready to pull, size:XS

#25962 Fix warning eigen_spatial_convolutions.h
  tensorflow/core/kernels/eigen_spatial_convolutions.h
Labels: cla: yes, ready to pull, size:XS

#25863 fix absl import issue #25282
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, pending merge internally, ready to pull

#24894 Lite: Gather operator test case improvement
  tensorflow/lite/kernels/gather_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#25836 Fixed non-trivial designated initializer error
  tensorflow/lite/toco/tflite/operator_test.cc
Labels: cla: yes, ready to pull

#26056 Updated model_test.cc
  tensorflow/lite/model_test.cc
Labels: cla: yes, ready to pull, size:XS

#25916 Update bigtable_lib.cc
  tensorflow/contrib/bigtable/kernels/bigtable_lib.cc
Labels: cla: yes, pending merge internally, ready to pull, size:XS

#25672 Remove duplicated file of kafka_ops.cc
  tensorflow/contrib/kafka/ops/kafka_ops.cc
Labels: cla: yes, ready to pull, size:S

#25347 Fix variables that seem to not be modified to consts.
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes, pending merge internally, ready to pull, size:M

#25654 Added missing scenarios for the tensor_content
  tensorflow/lite/toco/import_tensorflow_test.cc
Labels: cla: yes, ready to pull, size:M

#25745 TF Keras Negative number test case added for Relu activation
  tensorflow/python/keras/activations_test.py
Labels: cla: yes, ready to pull, size:S

#25982 Update Go test documentation to include all required library files
  tensorflow/go/README.md
Labels: cla: yes, ready to pull

#26064 Reformatted example variables, fixed typo.
  tensorflow/core/ops/math_ops.cc
Labels: 2.0, cla: yes, ready to pull, size:XS, type:docs

#25733 Scalar input shape added for floor and ceil testing
  tensorflow/lite/testing/generate_examples.py
Labels: cla: yes, ready to pull, size:XS

#24613 Fix bug in test_streaming_accuracy.cc
  tensorflow/examples/speech_commands/test_streaming_accuracy.cc
Labels: cla: yes, ready to pull, size:XS

#26106 Fix reference in HParams docstring.
  tensorflow/contrib/training/python/training/hparam.py
Labels: cla: yes, ready to pull

#24315 [TFLite] Minor improvement of static build
  tensorflow/lite/tools/make/Makefile
Labels: cla: yes, ready to pull, size:XS

#25584 Reopen: Generalize MinMax monotonic optimizer
  tensorflow/core/grappler/op_types.cc
  tensorflow/core/grappler/op_types.h
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
  tensorflow/core/grappler/optimizers/arithmetic_optimizer_test.cc
Labels: cla: yes, pending merge internally, ready to pull, size:M

#24718 Update README.md
  tensorflow/contrib/slim/README.md
Labels: cla: yes, ready to pull, size:S

#23532 Correct error messages in graph transforms.
  tensorflow/tools/graph_transforms/README.md
  tensorflow/tools/graph_transforms/remove_attribute.cc
  tensorflow/tools/graph_transforms/rename_attribute.cc
  tensorflow/tools/graph_transforms/rename_op.cc
Labels: cla: yes, ready to pull, size:S

#26111 Updated reshape_test.cc
  tensorflow/lite/kernels/reshape_test.cc
Labels: cla: yes, ready to pull

#24178 Add gradient for tf.extract_volume_patches
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/extract_volume_patches_grad_test.py
  tensorflow/python/ops/array_grad.py
Labels: cla: yes, ready to pull, size:M

#24765 Added missing test case in LinearModel
  tensorflow/python/feature_column/feature_column_v2_test.py
Labels: cla: yes, ready to pull, size:S

#26115 Fix MemoryWriterIterator LOG(WARNING) spacing
  tensorflow/core/kernels/data/cache_dataset_ops.cc
Labels: cla: yes, ready to pull, size:XS
