Repository tensorflow/tensorflow, pull requests merged in 2019-10, with the labels that each got.

#32856 Fix tf.image.*_jpeg_quality docs -- they only accept single image, docs say multiple
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#32747 add missing reverse_sequence docstring
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:M

#32829 fix .so file name error on linux and macos
  tensorflow/java/src/main/java/org/tensorflow/NativeLibrary.java
Labels: cla: yes, ready to pull, size:XS

#32541 [Intel MKL] Disable "Conv3D with stride > 1" cases.
  tensorflow/python/kernel_tests/conv_ops_3d_test.py
Labels: cla: yes, comp:mkl, ready to pull, size:S

#32893 Fix for 32890
  tensorflow/python/ops/nn_impl.py
Labels: cla: yes, ready to pull, size:XS

#32976 Remove unneeded Kineis dependency libraries
  third_party/aws/BUILD.bazel
Labels: cla: yes, ready to pull, size:XS, subtype:bazel

#32922 [INTEL_MKL] Reverting bias cache optimization
  tensorflow/core/kernels/mkl_conv_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#32994 Fix a minor style issue in embedding_ops
  tensorflow/python/ops/embedding_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#32978 Fix the Consistency of shape example
  tensorflow/python/autograph/g3doc/reference/limitations.md
Labels: cla: yes, comp:autograph, ready to pull, size:XS

#32934 Switch MatchingFilesDatasetTest to use TF combinations
  tensorflow/python/data/experimental/kernel_tests/matching_files_test.py
Labels: cla: yes, ready to pull, size:S

#32418 [INTEL MKL] Add primitive cache for mkl concat
  tensorflow/core/kernels/mkl_concat_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:L

#32673 [XLA:GPU][ROCm] Enabling amdgpu backend in XLA unit tests
  tensorflow/compiler/xla/tests/build_defs.bzl
Labels: cla: yes, comp:xla, ready to pull, size:XS

#32969 Improve docs for cmdline
  tensorflow/lite/g3doc/convert/cmdline.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#32958 [r1.15-CherryPick]: RebatchDataset performance fix
  tensorflow/core/kernels/data/experimental/BUILD
  tensorflow/core/kernels/data/experimental/rebatch_dataset_op.cc
  tensorflow/python/data/experimental/kernel_tests/rebatch_dataset_test.py
  tensorflow/python/data/experimental/ops/distribute.py
  tensorflow/python/distribute/input_lib.py
Labels: cla: yes, size:L

#32995 [1.15-rc2 CherryPick]: fix missing dependencies of mlir for tf serving oss build
  tensorflow/compiler/mlir/lite/BUILD
  tensorflow/compiler/mlir/tensorflow/BUILD
Labels: cla: yes, size:XS

#33050 [r1.15-CherryPick]: Expose session_creation_timeout_secs in estimator RunConfig
  tensorflow/contrib/learn/python/learn/estimators/estimator.py
  tensorflow/contrib/learn/python/learn/estimators/run_config.py
  tensorflow/tools/api/golden/v1/tensorflow.estimator.-run-config.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.estimator.tpu.-run-config.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.estimator.-run-config.pbtxt
Labels: cla: yes, size:S

#33056 [r1.15-CherryPIck]:Update version to 1.15.0-rc3
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#31183 Prevent to decompress the speech command dataset every time
  tensorflow/examples/speech_commands/input_data.py
Labels: cla: yes, ready to pull, size:XS

#33004 Update the docstring of tf.strings.substr to cover negative len case
  tensorflow/core/api_def/base_api/api_def_Substr.pbtxt
Labels: cla: yes, ready to pull, size:XS

#33008 fix typos
  tensorflow/lite/toco/tflite/export_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#33033 Update documentation for TFLiteConverterV2
  tensorflow/lite/python/lite.py
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30285 Don't include xmmintrin or related tests on non-x86 systems.
  tensorflow/core/framework/variant_test.cc
Labels: cla: yes, ready to pull, size:XS

#33120 [Cherrypick TF1.15] Fix performance slowdown
  tensorflow/python/util/module_wrapper.py
Labels: cla: yes, size:M

#32613 Removed unnecessary cmsis includes preventing compilation from cloned…
  tensorflow/lite/experimental/micro/tools/make/ext_libs/cmsis.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:M

#29248 Clarified docs of Lambda function on usecase
  tensorflow/python/keras/layers/core.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#33137 Fix for #33134
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#33126 Remove the "nomac" exclusion for FromTensorsTest
  tensorflow/python/data/kernel_tests/BUILD
Labels: cla: yes, comp:data, ready to pull, size:XS

#33097 Fix grad check compatibility
  tensorflow/python/keras/optimizers.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#32370 Update data file so that graph_properties_test passes on big-endian architectures
  tensorflow/core/grappler/costs/graph_properties_testdata/large_function_graph.pbtxt
Labels: cla: yes, comp:grappler, ready to pull, size:S

#31833 Add Measure inference Time
  tensorflow/python/training/evaluation.py
Labels: cla: yes, ready to pull, size:XS

#33064 [Intel Mkl] Upgrade curl to fix CVE-2019-5481 and CVE-2019-5482
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes, ready to pull, size:S

#33109 Update word2vec_basic.py
  tensorflow/examples/tutorials/word2vec/word2vec_basic.py
Labels: cla: yes, ready to pull, size:XS

#33058 [Intel MKL] Fix missing libiomp5 issue due to missing deps.
  tensorflow/tensorflow.bzl
Labels: cla: yes, ready to pull, size:XS

#33017 Fix a comment error in cost estimator
  tensorflow/core/grappler/costs/cost_estimator.h
Labels: cla: yes, comp:grappler, ready to pull, size:XS

#32296 sort NcclManager::Collective participants using device ID
  tensorflow/core/nccl/nccl_manager.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#32854 [API Docs] Add three examples for tf.data.Dataset.from_tensor_slices docs
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, ready to pull, size:S

#32974 MKL DNN: Fix issues with hadoopFileSystem load error message
  tensorflow/core/platform/hadoop/hadoop_file_system.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#32882 Update commands to look for keyword controller in lspci log
  tensorflow/tools/ci_build/linux/rocm/run_cc_core.sh
  tensorflow/tools/ci_build/linux/rocm/run_csb_tests.sh
  tensorflow/tools/ci_build/linux/rocm/run_py3_core.sh
  tensorflow/tools/ci_build/xla/linux/rocm/run_py3.sh
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#31775 Use python3 if available to run gen_git_source.py.
  third_party/git/git_configure.bzl
Labels: cla: yes, ready to pull, size:XS

#33224 [Intel MKL] Update MKLDNN to v0.21.2
  tensorflow/workspace.bzl
  third_party/mkl_dnn/mkldnn.BUILD
Labels: cla: yes, comp:mkl, ready to pull, size:M

#33091 mlir: minor spelling tweaks
  tensorflow/compiler/mlir/g3doc/tf_ops.md
  tensorflow/compiler/mlir/glob_lit_test.bzl
  tensorflow/compiler/mlir/lite/ir/tfl_ops.cc
  tensorflow/compiler/mlir/lite/quantization/quantization_driver.cc
  tensorflow/compiler/mlir/lite/quantization/quantization_utils.h
  tensorflow/compiler/mlir/lite/quantization/tools/op_quant_spec_getters_gen.cc
  tensorflow/compiler/mlir/lite/tf_tfl_translate_cl.h
  tensorflow/compiler/mlir/lite/transforms/extract_ophint.cc
  tensorflow/compiler/mlir/lite/transforms/legalize_ophint_func_op.cc
  tensorflow/compiler/mlir/lite/transforms/load_quantization_recipe.cc
  tensorflow/compiler/mlir/lite/transforms/post_quantize.cc
  tensorflow/compiler/mlir/lite/transforms/split_merged_operands.cc
  tensorflow/compiler/mlir/lite/transforms/trim_functions_tf.cc
  tensorflow/compiler/mlir/lite/utils/lstm_utils.cc
  tensorflow/compiler/mlir/lite/utils/lstm_utils.h
  tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc
  tensorflow/compiler/mlir/tensorflow/transforms/bridge.h
  tensorflow/compiler/mlir/tensorflow/transforms/bridge_pass.cc
  tensorflow/compiler/mlir/tensorflow/transforms/constant_fold.cc
  tensorflow/compiler/mlir/tensorflow/transforms/optimize.cc
  tensorflow/compiler/mlir/tensorflow/translate/executor_to_control_dialect.cc
  tensorflow/compiler/mlir/tensorflow/translate/export_tf_dialect_op.h
  tensorflow/compiler/mlir/tensorflow/translate/import_model.cc
  tensorflow/compiler/mlir/tensorflow/utils/compile_mlir_util.h
  tensorflow/compiler/mlir/tf_mlir_translate_main.cc
  tensorflow/compiler/mlir/xla/hlo_function_importer.cc
Labels: cla: yes, ready to pull, size:M

#32962 Remove left over code
  tensorflow/core/grappler/optimizers/meta_optimizer.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#33263 [r1.15 CherryPick]: Update TensorFlow version to 1.15.0
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#33262 [r1.15 CherryPick]: Add saving of loaded/trained compatibility models in test and fix a c…
  tensorflow/examples/saved_model/integration_tests/use_model_in_sequential_keras.py
  tensorflow/examples/saved_model/integration_tests/use_rnn_cell.py
  tensorflow/examples/saved_model/integration_tests/use_text_embedding_in_dataset.py
  tensorflow/examples/saved_model/integration_tests/use_text_rnn_model.py
  tensorflow/python/saved_model/load.py
Labels: cla: yes, size:S

#33213 [Intel Mkl] Upgrading MKL-DNN to 0.20.6 to fix SGEMM regression
  tensorflow/workspace.bzl
Labels: cla: yes, comp:mkl, size:XS

#33295 Update CONTRIBUTING.md to use in repo pylint style
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:S

#31861 Update release notes for TensorFlow 1.15.0
  RELEASE.md
Labels: cla: yes, size:XS

#33282 Fix a minor typo
  tensorflow/python/framework/errors_impl.py
Labels: cla: yes, ready to pull, size:XS

#32590 [XLA] Add DiagSlice HLO instruction
  tensorflow/compiler/tf2xla/kernels/diag_op.cc
  tensorflow/compiler/tf2xla/kernels/matrix_diag_ops.cc
  tensorflow/compiler/xla/client/lib/matrix.cc
  tensorflow/compiler/xla/client/lib/matrix.h
  tensorflow/compiler/xla/client/lib/matrix_test.cc
  tensorflow/compiler/xla/tests/client_library_test_base.h
Labels: cla: yes, comp:xla, ready to pull, size:L

#32867 Added CMSIS-NN specialization for fully connected op.
  tensorflow/lite/experimental/micro/README.md
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/fully_connected.cc
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/scratch_buffer.cc
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/scratch_buffer.h
  tensorflow/lite/experimental/micro/tools/make/ext_libs/cmsis.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:L

#33324 [Intel MKL] Adding OMP_NUM_THREADS support to mkl tests
  tensorflow/tools/ci_build/linux/cpu/run_mkl.sh
  tensorflow/tools/ci_build/linux/mkl/basic-mkl-test.sh
Labels: cla: yes, comp:mkl, ready to pull, size:S

#33296 Remove tf.enable_eager_execution() in README.md
  README.md
Labels: cla: yes, ready to pull, size:XS

#32374 relocate raise place
  tensorflow/python/ops/image_grad_test.py
Labels: cla: yes, comp:ops, ready to pull, size:M

#33384 Remove unnecessary `else` clauses
  tensorflow/python/autograph/operators/symbols.py
Labels: cla: yes, comp:autograph, ready to pull, size:S

#32749 Improve API doc for ZipDataset
  tensorflow/core/api_def/base_api/api_def_ZipDataset.pbtxt
Labels: cla: yes, comp:data, ready to pull, size:S

#33364 fix typo
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#32955 [INTEL MKL] Fix debug_grappler unit test failure
  tensorflow/python/debug/lib/debug_grappler_test.py
Labels: awaiting testing (then merge), cla: yes, comp:mkl, ready to pull, size:XS

#33111 Use correct casts to get right dimensions on s390x
  tensorflow/core/framework/common_shape_fns.cc
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#33398 Improve docs for make_tensor_proto
  tensorflow/python/framework/tensor_util.py
Labels: cla: yes, ready to pull, size:XS

#32883 [ROCm] Change to pick up rocprim and hipcub libraries from ROCm install
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/bincount_op_gpu.cu.cc
  tensorflow/core/kernels/dynamic_partition_op_gpu.cu.cc
  tensorflow/core/kernels/histogram_op_gpu.cu.cc
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
  tensorflow/core/kernels/scan_ops_gpu.h
  tensorflow/core/kernels/where_op_gpu.cu.h
  tensorflow/tools/ci_build/Dockerfile.rbe.rocm-ubuntu16.04
  tensorflow/tools/ci_build/Dockerfile.rocm
  tensorflow/tools/lib_package/BUILD
  tensorflow/tools/pip_package/BUILD
  tensorflow/workspace.bzl
  third_party/gpus/rocm/BUILD.tpl
  third_party/rocprim.BUILD
Labels: cla: yes, comp:gpu, ready to pull, size:M

#33235 Remove microfrontend/lib from the MICROLITE_CC_HDRS/SRCS.
  tensorflow/lite/experimental/micro/tools/make/Makefile
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#33268 Remove unnecessary comparison in Keras losses
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#33480 Improve tf.make_ndarray() docstring
  tensorflow/python/framework/tensor_util.py
Labels: cla: yes, ready to pull, size:S

#33195 [Intel MKL] fix bias cache accuracy issue.
  tensorflow/core/kernels/mkl_conv_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#33521 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:XS

#33444 [Intel MKL] fix ut check_numerics_callback_test
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#33575 Fix build failures for python 3.8
  tensorflow/python/eager/pywrap_tfe_src.cc
  tensorflow/python/lib/core/bfloat16.cc
  tensorflow/python/lib/core/ndarray_tensor_bridge.cc
Labels: cla: yes, comp:eager, ready to pull, size:XS

#33405 [INTEL MKL] Reuse input tensor in mkl conv2d
  tensorflow/core/kernels/mkl_conv_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#33547 Optimize a data member from map to vector for LoopInvariantNodeMotionOptimizer
  tensorflow/core/grappler/optimizers/loop_optimizer.cc
Labels: cla: yes, ready to pull, size:S

#33021 fix msvc 16.3.0 + cuda 10.1.243 build break
  tensorflow/core/kernels/scatter_nd_op_gpu.cu.cc
Labels: cla: yes, ready to pull, size:XS

#33010 Add tests in TFLite micro for Relu/Relu6 Int8/Uint8/Float
  tensorflow/lite/experimental/micro/kernels/BUILD
  tensorflow/lite/experimental/micro/kernels/activations.cc
  tensorflow/lite/experimental/micro/kernels/activations_test.cc
  tensorflow/lite/experimental/micro/kernels/all_ops_resolver.cc
  tensorflow/lite/experimental/micro/kernels/micro_ops.h
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:L

#33523 Update sqlite to 3.30.1
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull, size:XS

#33643 Remove note about `tf.keras.experimental.export_saved_model`.
  tensorflow/python/keras/engine/network.py
Labels: cla: yes, invalid, ready to pull, size:XS

#33540 [Intel MKL] Improve eager performance for small batch sizes
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
Labels: cla: yes, ready to pull, size:M

#30381 [XLA:GPU][ROCm] Change XLA platform_util to support both CUDA/NVPTX and ROCm/AMDGPU
  tensorflow/compiler/xla/service/platform_util.cc
Labels: cla: yes, comp:xla, ready to pull, size:S

#33701 Add Selu and Softsign to auto mixed precision gray list
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
Labels: cla: yes, ready to pull, size:XS

#33596 Fix for parallel_map_dataset_op_test failure on big endian
  tensorflow/core/kernels/data/parallel_map_dataset_op_test.cc
Labels: cla: yes, ready to pull, size:XS

#33546 Do not use memcpy in Go
  tensorflow/go/graph.go
Labels: cla: yes, ready to pull, size:XS

#33694 Add missing V2 ops to auto mixed precision list
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
Labels: cla: yes, comp:grappler, ready to pull, size:XS

#33221 Update api_def_Unique.pbtxt
  tensorflow/core/api_def/base_api/api_def_Unique.pbtxt
Labels: cla: yes, comp:apis, ready to pull, size:S

#33420 Added CMSIS-NN specialization for int8 depthwise conv op.
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/depthwise_conv.cc
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/fully_connected.cc
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/scratch_buffer.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:M

#33483 Fix small typo in v2.0.0 release note
  RELEASE.md
Labels: cla: yes, ready to pull, size:XS

#33732 [Intel MKL] Refactor MKL Eager from std::vector to std::hashmap for cleaner design
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
Labels: cla: yes, ready to pull, size:M

#33783 fix quantization specification doc error
  tensorflow/lite/g3doc/performance/quantization_spec.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#33773 Add documentation for tf.math.add
  tensorflow/core/ops/math_ops.cc
Labels: cla: yes, comp:ops, ready to pull, size:XS

#33753 Support tensor arguments in clip.
  tensorflow/python/keras/backend.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#33745 Fix typo in wrapper.py
  tensorflow/python/keras/layers/wrappers.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#33728 [INTEL MKL] Fixing inter op default setting in intel.
  tensorflow/core/common_runtime/process_util.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#33530 improve GPU device info output
  tensorflow/core/common_runtime/gpu/gpu_device.cc
Labels: cla: yes, ready to pull, size:S

#33505 loading break due to undefined symbol about constexpr const char*
  tensorflow/core/common_runtime/lower_functional_ops.cc
Labels: cla: yes, ready to pull, size:XS

#33114 define _USE_MATH_DEFINES in hlo_evaluator.cc
  tensorflow/compiler/xla/service/hlo_evaluator.h
Labels: cla: yes, comp:xla, ready to pull, size:XS

#33514 Add a network test application.
  tensorflow/lite/experimental/micro/examples/network_tester/.gitignore
  tensorflow/lite/experimental/micro/examples/network_tester/Makefile.inc
  tensorflow/lite/experimental/micro/examples/network_tester/README.md
  tensorflow/lite/experimental/micro/examples/network_tester/expected_output_data.h
  tensorflow/lite/experimental/micro/examples/network_tester/input_data.h
  tensorflow/lite/experimental/micro/examples/network_tester/network_model.h
  tensorflow/lite/experimental/micro/examples/network_tester/network_tester_test.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:L

#33632 [TF 2.0 API docs] expanding the tf.keras.activations.relu
  tensorflow/python/keras/activations.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#32917 Added invocation and memory allocation checks
  tensorflow/lite/experimental/micro/examples/hello_world/hello_world_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#33652 Release TF Java 1.15
  tensorflow/java/maven/libtensorflow/pom.xml
  tensorflow/java/maven/libtensorflow_jni/pom.xml
  tensorflow/java/maven/libtensorflow_jni_gpu/pom.xml
  tensorflow/java/maven/pom.xml
  tensorflow/java/maven/proto/pom.xml
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
  tensorflow/java/maven/tensorflow-hadoop/pom.xml
  tensorflow/java/maven/tensorflow/pom.xml
Labels: cla: yes, ready to pull, size:S

#31918 Do not make invalid android config with only NDK/SDK configured
  third_party/android/android_configure.bzl
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#33278 Fix some meaningless type qualifier warnings
  tensorflow/core/kernels/cwise_ops.h
Labels: cla: yes, ready to pull, size:M

#33699 suppress unused result in s3_filesystem (-Wunused-result)
  tensorflow/core/platform/s3/s3_file_system.cc
Labels: cla: yes, ready to pull, size:XS

#33350 Consume java_import_external from bazel_tools instead of rules_closure
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull, size:XS, subtype:bazel

#33638 Fix Crash When input_size Is an int
  tensorflow/lite/experimental/examples/lstm/rnn_cell.py
Labels: cla: yes, comp:lite, ready to pull, size:XS

#32466 [ppc64le] Undo setting of OMP_NUM_THREADS
  configure.py
Labels: cla: yes, ready to pull, size:XS

#32494 edit for clearity, changed "implied" to "applied"
  tensorflow/python/keras/preprocessing/image.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#33568 updated code snippets for tensor scatter operation
  tensorflow/core/api_def/base_api/api_def_ScatterNd.pbtxt
  tensorflow/core/api_def/base_api/api_def_TensorScatterAdd.pbtxt
  tensorflow/core/api_def/base_api/api_def_TensorScatterSub.pbtxt
  tensorflow/core/api_def/base_api/api_def_TensorScatterUpdate.pbtxt
Labels: cla: yes, comp:apis, ready to pull, size:S

#33492 add INT8 quantization support for the OP RESIZE_NEAREST_NEIGHBOR
  tensorflow/lite/tools/optimize/operator_property.cc
Labels: cla: yes, comp:lite, prtype:bugfix, ready to pull, size:XS

#33368 Fix missing activation methods
  tensorflow/lite/experimental/micro/kernels/activation_utils.h
Labels: cla: yes, comp:lite, ready to pull, size:S

#33481 fixing documentation for tf.batch_to_space
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#33843 Change android.bzl indentation to 2
  third_party/android/android.bzl.tpl
Labels: cla: yes, ready to pull, size:S
