Repository tensorflow/tensorflow, pull requests merged in 2019-05, with the labels that each got.

#28286 [ROCm] Fix for the broken `--config=rocm` build.
  tensorflow/stream_executor/rocm/rocm_driver.cc
Labels: cla: yes, core, ready to pull, size:XS

#27735 TF utils_test additional test cases covers
  tensorflow/python/layers/utils_test.py
Labels: cla: yes, ready to pull, size:S

#27838 [TF 2.0 docs] Add example for EarlyStopping
  tensorflow/python/keras/callbacks.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#28300 During cuda config detection, make find_cuda_config strip spaces around versions
  third_party/gpus/find_cuda_config.py
Labels: cla: yes, size:XS

#28321 A fix to RequantizationPerChannel Op
  tensorflow/core/kernels/mkl_requantize_per_channel_op.cc
Labels: cla: yes, size:S

#28205 Optimized packet load in gemm_pack_rhs (for Packet16f and Packet8f)
  tensorflow/core/kernels/eigen_spatial_convolutions-inl.h
  third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h
  third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX512.h
Labels: cla: yes, ready to pull, size:L

#28282 Raspberry Pi static lib outpath updated
  tensorflow/lite/g3doc/guide/build_rpi.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#28325 Two TensorRT related cherrypicks
  configure.py
  third_party/gpus/cuda_configure.bzl
Labels: cla: yes, size:XS

#22856 [aarch64] make aws sdk work on aarch64
  tensorflow/BUILD
  third_party/aws/BUILD.bazel
Labels: awaiting testing (then merge), cla: yes, prime, ready to pull, size:XS, type:build/install

#28290 [TF Lite] Add Ruy sources to Makefile
  tensorflow/lite/tools/make/Makefile
Labels: cla: yes, comp:lite, ready to pull, size:S

#28320 GetElasedTimeUs -> GetElapsedTimeUs
  tensorflow/core/platform/default/device_tracer.cc
Labels: cla: yes, ready to pull, size:S

#28312 Tests for PaddedBatchDatasetOp
  tensorflow/core/kernels/data/BUILD
  tensorflow/core/kernels/data/padded_batch_dataset_op_test.cc
Labels: cla: yes, comp:data, ready to pull, size:XL

#27596 Fix doc not displayed properly issue (block) in "predict" function of keras
  tensorflow/python/keras/engine/training.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#28239 Minor docs fix for is_gpu_available
  tensorflow/python/framework/test_util.py
Labels: cla: yes, ready to pull, size:XS

#27723 Title of paper as clickable link
  tensorflow/python/ops/rnn_cell_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#28339 Fix grammar in MirroredStrategy docstring
  tensorflow/python/distribute/mirrored_strategy.py
Labels: cla: yes, ready to pull, size:XS

#28348 Skip a SavedModel captured dataset loading test in v1 on gpu
  tensorflow/python/saved_model/save_test.py
Labels: cla: yes

#28352 Make the --copt=-mavx and --copt=-msse4.2 flags take effect for libtensorflow builds
  tensorflow/tools/ci_build/builds/libtensorflow.sh
Labels: cla: yes, size:XS

#27224 Add deprecation notice to tf.contrib.libsvm
  tensorflow/contrib/libsvm/python/ops/libsvm_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#28319 Update documentation template to match recommendations from doc sprints
  .github/ISSUE_TEMPLATE/20-documentation-issue.md
Labels: cla: yes, ready to pull, size:S

#28166 fix a wrong example in slim README
  tensorflow/contrib/slim/README.md
Labels: cla: yes, ready to pull, size:XS

#28370 [ROCm] Fix for the broken `--config=rocm` build.
  tensorflow/stream_executor/rocm/rocm_driver.cc
Labels: cla: yes, ready to pull, size:XS

#27592 Updated Doc: Change Shape Brackets and Code Formatting
  tensorflow/python/ops/ctc_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#27571 Doc: add example for batch_flatten()
  tensorflow/python/keras/backend.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#28361 remove duplicate code
  tensorflow/compiler/tf2xla/xla_compiler.cc
Labels: cla: yes, ready to pull, size:XS

#28392 [aarch64] make TensorFlow build for aarch64 linux natively with bazel
  tensorflow/core/kernels/BUILD
  tensorflow/lite/experimental/ruy/detect_dotprod.cc
  tensorflow/lite/experimental/ruy/kernel.h
Labels: cla: yes, comp:lite, ready to pull, size:XS

#26753 [ROCm] Enable ROCm support for "shape" ops
  tensorflow/core/kernels/shape_ops.cc
Labels: cla: yes, ready to pull, size:M

#28350 Fix the return dtype of IsZero() function
  tensorflow/core/framework/function_testlib.cc
Labels: cla: yes, ready to pull, size:XS

#28382 [INTEL MKL] Disable MKL Op Rewrite for Conv with padding==EXPLICIT
  tensorflow/core/graph/mkl_layout_pass.cc
Labels: cla: yes, ready to pull, size:S

#26724 [ROCm] Enable ROCm support for "snapshot" op
  tensorflow/core/kernels/snapshot_op.cc
  tensorflow/core/kernels/snapshot_op.h
  tensorflow/core/kernels/snapshot_op_gpu.cu.cc
Labels: cla: yes, ready to pull, size:M

#28383 Change doc issue formatting for plain text display
  .github/ISSUE_TEMPLATE/20-documentation-issue.md
Labels: cla: yes, ready to pull, size:M, type:docs

#26757 [ROCm] Enable ROCm support for the "reverse" op
  tensorflow/core/kernels/reverse_op.cc
  tensorflow/core/kernels/reverse_op_gpu.cu.cc
Labels: cla: yes, ready to pull, size:M

#28368 Use atomic<bool> to guarantee visibility
  tensorflow/core/lib/core/threadpool_test.cc
Labels: cla: yes, core, ready to pull, size:S

#28152 Add example for LR scheduler
  tensorflow/python/keras/callbacks.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#28240 tensorflow/lite/experimental/microfrontend/lib/frontend_memmap_genera…
  tensorflow/lite/experimental/microfrontend/lib/frontend_memmap_generator.c
Labels: cla: yes, comp:lite, ready to pull, size:XS

#28471 verbs: fix compilation error
  tensorflow/contrib/verbs/grpc_verbs_service.cc
  tensorflow/contrib/verbs/grpc_verbs_service.h
Labels: cla: yes, ready to pull, size:XS

#28493 Tests for ShardDatasetOp
  tensorflow/core/kernels/data/BUILD
  tensorflow/core/kernels/data/shard_dataset_op_test.cc
Labels: cla: yes, ready to pull, size:L

#28455 [TF-TRT] Ignore StopGradient ops
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
Labels: cla: yes, ready to pull, size:XS

#28408 fix nccl build bug
  third_party/nccl/nccl_configure.bzl
Labels: cla: yes, ready to pull, size:XS, subtype:bazel

#28574 [INTEL MKL] Code clean - MklSliceOp
  tensorflow/core/kernels/mkl_slice_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#28564 [ROCm] Creating Cuda forwarding alias macros
  tensorflow/core/util/gpu_cuda_alias.h
Labels: cla: yes, ready to pull, size:M

#28478 Read header files as utf-8
  third_party/gpus/find_cuda_config.py
Labels: cla: yes, comp:runtime, ready to pull, size:XS

#28453 [ROCm] Adding ROCm support for the dense update ops
  tensorflow/core/kernels/dense_update_functor.cc
  tensorflow/core/kernels/dense_update_functor_gpu.cu.cc
  tensorflow/core/kernels/dense_update_ops.cc
Labels: cla: yes, ready to pull, size:S

#28566 [ROCm] remove GPU_LAUNCH_KERNEL macro
  tensorflow/core/util/gpu_kernel_helper.h
Labels: cla: yes, size:S

#28562 Documentation update to DeviceSpec
  tensorflow/python/framework/device_spec.py
Labels: cla: yes, ready to pull, size:S

#28576 [INTEL ML] Code clean - Mkl Pooling Ops
  tensorflow/core/kernels/mkl_avgpooling_op.cc
  tensorflow/core/kernels/mkl_maxpooling_op.cc
  tensorflow/core/kernels/mkl_pooling_ops_common.cc
  tensorflow/core/kernels/mkl_pooling_ops_common.h
Labels: cla: yes, comp:mkl, ready to pull, size:L

#28575 [INTEL MKL] Code clean - MklConvOp (fwd)
  tensorflow/core/kernels/mkl_conv_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:L

#28492 [Intel MKL] Disable BFloat16 transpose op
  tensorflow/core/kernels/mkl_transpose_op.cc
Labels: cla: yes, prime, ready to pull, size:S

#27650 Clarified args lists for functions in compat.py
  tensorflow/python/compat/compat.py
Labels: cla: yes, ready to pull, size:S

#28603 Remove cudaGraph API from cuda_runtime_10_0
  tensorflow/stream_executor/cuda/cuda_runtime_10_0.inc
Labels: cla: yes, cuda, ready to pull, size:L

#26400 fix tflite android demo: fix normalization for mobile-net
  tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifierFloatMobileNet.java
Labels: cla: yes, java, ready to pull, size:S

#27821 Update tf_upgrade_v2.py
  tensorflow/tools/compatibility/tf_upgrade_v2.py
Labels: cla: yes, ready to pull, size:XS, type:docs

#26840 [ROCm] Add ROCm macro for Google upstream avgpooling op
  tensorflow/core/kernels/avgpooling_op.cc
  tensorflow/core/kernels/maxpooling_op_gpu.h
  tensorflow/core/kernels/pooling_ops_common_gpu.h
Labels: cla: yes, ready to pull, size:S

#28454 Fix weighted top_k_categorical_accuracy keras metric
  tensorflow/python/keras/metrics.py
  tensorflow/python/keras/metrics_functional_test.py
  tensorflow/python/keras/metrics_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#28567 [ROCm] Forward type names from gpu prefix to cuda prefix
  tensorflow/core/util/gpu_launch_config.h
Labels: cla: yes, cuda, ready to pull, size:M

#26782 Check whether the file descriptor is valid
  tensorflow/core/platform/posix/posix_file_system.cc
Labels: cla: yes, ready to pull, size:XS

#28627 Fixes broken GPU build
  third_party/gpus/find_cuda_config.py
Labels: cla: yes, cuda, ready to pull, size:XS

#25884 TF compilation warning removed
  tensorflow/core/kernels/data/experimental/csv_dataset_op.cc
  tensorflow/core/kernels/data/experimental/map_and_batch_dataset_op.cc
  tensorflow/core/kernels/data/experimental/parse_example_dataset_op.cc
  tensorflow/core/kernels/data/experimental/sliding_window_dataset_op.cc
  tensorflow/core/kernels/data/parallel_interleave_dataset_op.cc
  tensorflow/core/kernels/data/prefetch_dataset_op.cc
  tensorflow/core/kernels/data/shuffle_dataset_op.cc
  tensorflow/core/kernels/data/window_dataset_op.cc
Labels: awaiting testing (then merge), cla: yes, ready to pull, size:S

#28583 Fix a bug in algebraic simplification pass.
  tensorflow/compiler/xla/service/algebraic_simplifier.cc
  tensorflow/compiler/xla/service/algebraic_simplifier_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:S

#27235 tflite/tools/make: remove bashism
  tensorflow/lite/tools/make/Makefile
Labels: cla: yes, comp:lite, ready to pull, size:XS

#28510 PosixFileSystem::CopyFile: Truncate file before overwrite
  tensorflow/core/platform/posix/posix_file_system.cc
Labels: cla: yes, ready to pull, size:XS

#28618 [tflite] make GPU delegate elementwise ops work
  tensorflow/lite/delegates/gpu/common/model_builder.cc
Labels: cla: yes, ready to pull, size:XS

#28612 [ROCm] Adding ROCm support for variable ops
  tensorflow/core/kernels/variable_ops.cc
Labels: cla: yes, ready to pull, size:XS

#28617 Add docstring for v2 version of tf.squeeze()
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, ready to pull, size:S

#27670 TF Keras local_test dataformat compatible test case updated
  tensorflow/python/keras/layers/local_test.py
Labels: cla: yes, comp:keras, ready to pull, size:L

#28641 verbs: fixes GPU build broken by 4c3a1fb
  tensorflow/contrib/verbs/rdma.cc
Labels: cla: yes, ready to pull, size:XS

#28611 [ROCm] Adding ROCm support for the training ops
  tensorflow/core/kernels/training_ops.cc
  tensorflow/core/kernels/training_ops_gpu.cu.cc
Labels: cla: yes, ready to pull, size:S

#25130 Lite: Floor-Div different datatypes supported
  tensorflow/lite/kernels/floor_div.cc
  tensorflow/lite/kernels/floor_div_test.cc
  tensorflow/lite/kernels/register.cc
  tensorflow/lite/toco/tflite/operator.cc
  tensorflow/lite/toco/tflite/operator_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#28683 Enable opening TF source tree with Visual Studio Code
  third_party/toolchains/cpus/arm/BUILD
Labels: cla: yes, ready to pull, size:XS, type:build/install

#27718 Update optimized_ops.h
  tensorflow/lite/kernels/internal/optimized/optimized_ops.h
Labels: cla: yes, comp:lite, ready to pull, size:S

#28486 [INTEL MKL] Reshape bug fix
  tensorflow/core/kernels/mkl_reshape_op.cc
Labels: cla: yes, ready to pull, size:M

#28682 Add tensorflow/addons to v2 converter warning
  tensorflow/tools/compatibility/module_deprecations_v2.py
Labels: cla: yes, ready to pull, size:XS

#28736 Update the flatbuffers md5 checksum to match the update to version 1.11.0
  tensorflow/lite/experimental/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, ready to pull, size:XS

#28717 Upgrade Docker images to Ubuntu 18.04 (Py 3.6)
  tensorflow/tools/dockerfiles/partials/ubuntu/devel-nvidia.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/version.partial.Dockerfile
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#27771 add back-ticks for parameter formatting
  tensorflow/python/ops/signal/mel_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#28461 Fix tf.signal.inverse_stft AttributeError in tf 2.0
  tensorflow/python/ops/signal/spectral_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:XS

#28722 [INTEL MKL] Enable concat for 2D tensors with MKLDNN.
  tensorflow/core/kernels/mkl_concat_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#28723 [INTEL MKL] Remove requantize op fusion from graph_transform.
  tensorflow/tools/graph_transforms/BUILD
  tensorflow/tools/graph_transforms/fuse_quantized_convolution.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#15098 improve tf.saved_model.loader.load exception
  tensorflow/python/saved_model/loader_impl.py
Labels: cla: yes, ready to pull, size:XS

#28670 [ROCm] Adding ROCm support for the "matmul" op
  tensorflow/core/kernels/gpu_utils.h
  tensorflow/core/kernels/matmul_op.cc
  tensorflow/core/kernels/matmul_op.h
Labels: cla: yes, ready to pull, size:S

#28772 Typo in backprop.py
  tensorflow/python/eager/backprop.py
Labels: cla: yes, ready to pull, size:XS

#26830 [micro] change --std=c++11 to -std=c++11 in Makefile.
  tensorflow/lite/experimental/micro/tools/make/Makefile
Labels: cla: yes, comp:lite, ready to pull, size:XS

#27041 Fix incorrect docstring of compression type in `TFRecordOptions`
  tensorflow/python/lib/io/tf_record.py
Labels: cla: yes, ready to pull, size:XS

#27018 Add scalar graph test for Lite NEG
  tensorflow/lite/testing/generate_examples_lib.py
Labels: cla: yes, comp:lite, ready to pull, size:XS

#28633 Fix TensorRT-6 Version Parsing
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, ready to pull, size:S

#28744 Fix ops_testutilcc for GPU tests
  tensorflow/core/kernels/ops_testutil.cc
Labels: cla: yes, comp:ops, ready to pull, size:XS

#28768 Uncomment execution device option in golang bindings
  tensorflow/go/graph.go
Labels: cla: yes, ready to pull, size:S

#23850 Bugfix: remove first arg instead of `self`
  tensorflow/python/util/function_utils.py
Labels: cla: yes, ready to pull, size:XS

#28571 [ROCm] Forward device function name from gpu prefix to cuda prefix
  tensorflow/core/util/gpu_device_functions.h
  tensorflow/core/util/gpu_kernel_helper.h
Labels: cla: yes, cuda, ready to pull, size:L

#28784 [Intel Mkl] Fix for Mkl builds in Ubuntu 18.04 containers
  tensorflow/tools/ci_build/linux/mkl/set-build-env.py
Labels: cla: yes, ready to pull, size:XS

#26896 [ROCm] Added ROCm support for the extract_volume_patches op
  tensorflow/core/kernels/extract_volume_patches_op.cc
  tensorflow/core/kernels/extract_volume_patches_op_gpu.cu.cc
Labels: cla: yes, comp:ops, ready to pull, size:XS

#28771 Bump rocprim version
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull, size:XS

#28483 [TF-TRT] Changes the MatMul converter to use the MatrixMultiplyLayer if possible
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, ready to pull, size:M

#28809 Update nvptx_compiler.cc
  tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc
Labels: cla: yes, cuda, ready to pull, size:XS

#28813 Fix bazel rule for cuda bazel generation from templates
  third_party/gpus/cuda_configure.bzl
Labels: cla: yes, ready to pull, size:XS

#28209 find_cuda: fix crash caused by unicode chars in ldconfig output
  third_party/gpus/find_cuda_config.py
Labels: cla: yes, ready to pull, size:XS

#28816 Formatted backprop.py
  tensorflow/python/eager/backprop.py
Labels: cla: yes, comp:eager, ready to pull, size:S

#26872 Keras test cases added in losses_test
  tensorflow/python/keras/losses_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#26471 Not pass dtype from Glorot initialization
  tensorflow/python/ops/init_ops.py
Labels: cla: yes, ready to pull, size:XS

#28535 1.14-rc0 cherry-pick request: Add cuda runtime 9.0 API to dlopen wrapper.
  tensorflow/stream_executor/cuda/BUILD
  tensorflow/stream_executor/cuda/cuda_runtime_9_0.inc
  tensorflow/stream_executor/cuda/cudart_stub.cc
Labels: cla: yes

#28887 Cherrypicks: error rewriting and fix for deprecation warning
  tensorflow/python/autograph/__init__.py
  tensorflow/python/autograph/core/unsupported_features_checker.py
  tensorflow/python/autograph/impl/api.py
  tensorflow/python/autograph/impl/api_test.py
  tensorflow/python/autograph/impl/conversion.py
  tensorflow/python/autograph/operators/control_flow.py
  tensorflow/python/autograph/operators/control_flow_test.py
  tensorflow/python/autograph/pyct/errors.py
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/def_function_test.py
  tensorflow/python/eager/lift_to_graph.py
  tensorflow/python/framework/func_graph.py
  tensorflow/python/keras/engine/base_layer_test.py
  tensorflow/python/util/compat.py
Labels: cla: yes, size:L

#28889 3 cherrypicks for 1.14
  tensorflow/compiler/tests/BUILD
  tensorflow/compiler/tests/ternary_ops_test.py
  tensorflow/compiler/tf2xla/kernels/select_op.cc
  tensorflow/tools/ci_build/Dockerfile.gpu
  tensorflow/tools/ci_build/Dockerfile.rbe.cuda10.0-cudnn7-ubuntu14.04
  tensorflow/tools/ci_build/Dockerfile.rbe.cuda9.0-cudnn7-ubuntu14.04
  tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/devel-nvidia.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile
  third_party/gpus/find_cuda_config.py
Labels: cla: yes, size:L

#26983 Fix misspellings of "parameter"
  tensorflow/compiler/xla/tests/test_utils_test.cc
  tensorflow/contrib/distribute/python/parameter_server_strategy.py
  tensorflow/lite/toco/dump_graphviz.cc
  tensorflow/python/keras/layers/kernelized.py
Labels: cla: yes, comp:xla, ready to pull, size:XS

#28870 [ROCm] Adding ROCm support for the "resize_bilinear" op
  tensorflow/core/kernels/resize_bilinear_op.cc
  tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc
Labels: cla: yes, ready to pull, size:M

#28864 [ROCm] Adding ROCm support for the random ops
  tensorflow/core/kernels/random_op.cc
  tensorflow/core/kernels/random_op.h
  tensorflow/core/kernels/random_op_gpu.cu.cc
  tensorflow/core/kernels/random_op_gpu.h
Labels: cla: yes, cuda, ready to pull, size:S

#28862 [ROCm] Adding ROCm support for the matrix_triangular_solve op
  tensorflow/core/kernels/matrix_triangular_solve_op.cc
Labels: cla: yes, cuda, ready to pull, size:S

#28810 [ROCm] Fix for the broken `--config=rocm` build.
  tensorflow/stream_executor/rocm/rocm_dnn.cc
  tensorflow/stream_executor/rocm/rocm_dnn.h
Labels: cla: yes, ready to pull, size:S

#25833 Add python and os information in environment capture script
  tools/tf_env_collect.sh
Labels: cla: yes, ready to pull, size:M

#28826 Break the reference between closure tape_grad_fn and flat_result
  tensorflow/python/ops/custom_gradient.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:XS

#28905 Update png_archive version to 1.6.37
  tensorflow/contrib/cmake/external/png.cmake
  tensorflow/workspace.bzl
  third_party/png_fix_rpi.patch
Labels: cla: yes, size:S

#24195 Added comment to Decoder.finalize
  tensorflow/contrib/seq2seq/python/ops/decoder.py
Labels: cla: yes, contrib, ready to pull, size:S

#28908 3 cherrrypicks
  tensorflow/python/debug/BUILD
  tensorflow/python/eager/function_test.py
  tensorflow/python/ops/math_grad.py
  tensorflow/python/util/nest.py
  tensorflow/python/util/nest_test.py
Labels: cla: yes, size:M

#28906 Set the forward-compat date to the future.
  tensorflow/python/compat/compat.py
Labels: cla: yes, size:XS

#28913 Remove data dependencies so that these two tests can be built
  tensorflow/lite/toco/python/BUILD
  tensorflow/python/autograph/pyct/BUILD
Labels: cla: yes, size:XS

#28914 Move the optimizer name scope from model.training to optimizer
  tensorflow/contrib/distribute/python/optimizer_v2_test.py
  tensorflow/python/distribute/minimize_loss_test.py
  tensorflow/python/distribute/single_loss_example.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/optimizer_v2/optimizer_v2.py
  tensorflow/python/training/tracking/util_test.py
Labels: cla: yes, size:M

#28910 [Docs] Fix typo in Cropping2D example
  tensorflow/python/keras/layers/convolutional.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#28916 Fix a segfault in StreamExecutorMemoryAllocator in a multi-GPU case
  tensorflow/stream_executor/stream_executor_pimpl.cc
Labels: cla: yes, size:XS

#28927 Two more fixes
  tensorflow/python/keras/layers/recurrent.py
  tensorflow/tools/def_file_filter/def_file_filter.py.tpl
  third_party/gpus/cuda/BUILD.windows.tpl
Labels: cla: yes, size:S

#28878 [TF-TRT] Avoid padding calculations when not needed
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
Labels: cla: yes, ready to pull, size:S

#28896 Fix an error in doc string of conv2d_transpose_v2
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#28943 Two more cherrypicks
  tensorflow/python/kernel_tests/gather_op_test.py
  tensorflow/python/ops/array_ops.py
  tensorflow/tools/compatibility/all_renames_v2.py
Labels: cla: yes, size:M

#26423 [TF 2.0 API docs] Creating the tf.keras.losses.poisson documentation
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#28946 Update doc.go
  tensorflow/go/doc.go
Labels: cla: yes, ready to pull, size:XS, type:docs

#26078 add clear user instructions for dataset.prefetch
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, ready to pull, size:XS

#27533 Fix logdet documentation error
  tensorflow/python/ops/linalg/linalg_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#28686 BUGFIX:
  tensorflow/core/kernels/adjust_hsv_gpu.cu.h
Labels: cla: yes, prtype:bugfix, ready to pull, size:M

#28873 [ROCm] Adding ROCm support for tile ops
  tensorflow/core/kernels/tile_functor.h
  tensorflow/core/kernels/tile_functor_gpu.h
  tensorflow/core/kernels/tile_functor_gpu_bool.cu.cc
  tensorflow/core/kernels/tile_functor_gpu_complex128.cu.cc
  tensorflow/core/kernels/tile_functor_gpu_complex64.cu.cc
  tensorflow/core/kernels/tile_functor_gpu_double.cu.cc
  tensorflow/core/kernels/tile_functor_gpu_float.cu.cc
  tensorflow/core/kernels/tile_functor_gpu_half.cu.cc
  tensorflow/core/kernels/tile_functor_gpu_int16.cu.cc
  tensorflow/core/kernels/tile_functor_gpu_int32.cu.cc
  tensorflow/core/kernels/tile_functor_gpu_int64.cu.cc
  tensorflow/core/kernels/tile_ops.cc
  tensorflow/core/kernels/tile_ops_gpu_impl.h
  tensorflow/core/kernels/tile_ops_gpu_impl_1.cu.cc
  tensorflow/core/kernels/tile_ops_gpu_impl_2.cu.cc
  tensorflow/core/kernels/tile_ops_gpu_impl_3.cu.cc
  tensorflow/core/kernels/tile_ops_gpu_impl_4.cu.cc
  tensorflow/core/kernels/tile_ops_gpu_impl_5.cu.cc
  tensorflow/core/kernels/tile_ops_gpu_impl_6.cu.cc
  tensorflow/core/kernels/tile_ops_gpu_impl_7.cu.cc
  tensorflow/core/kernels/tile_ops_gpu_impl_8.cu.cc
Labels: cla: yes, ready to pull, size:M

#28960 Release r1.14rc0 cherry-pick request: make tensorflow-gpu work on machine w/o CUDA setup
  tensorflow/core/common_runtime/gpu/gpu_device.cc
  tensorflow/stream_executor/platform/default/BUILD
  tensorflow/stream_executor/platform/default/dlopen_checker.cc
  tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc
  tensorflow/stream_executor/platform/default/dso_loader.h
Labels: cla: yes, release, size:M

#28965 3 more cherrypicks
  tensorflow/compiler/tf2xla/functionalize_control_flow.cc
  tensorflow/core/api_def/base_api/api_def_TPUReplicate.pbtxt
  tensorflow/core/ops/compat/ops_history.v1.pbtxt
  tensorflow/core/ops/compat/ops_history.v2.pbtxt
  tensorflow/core/ops/tpu_replication_ops.cc
  tensorflow/python/framework/convert_to_constants.py
  tensorflow/python/framework/convert_to_constants_test.py
  tensorflow/python/kernel_tests/variables_test.py
  tensorflow/python/ops/metrics_impl.py
  tensorflow/python/ops/resource_variable_ops.py
  tensorflow/python/ops/variables.py
  tensorflow/tools/api/golden/v1/tensorflow.-variable.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.-variable.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: cla: yes, size:L

#28911 Update BUILD.bazel
  third_party/aws/BUILD.bazel
Labels: cla: yes, ready to pull, size:XS

#28594 [doc] fix an error in the comment.
  tensorflow/python/layers/base.py
Labels: cla: yes, ready to pull, size:XS

#28970 BUG: tf.function cannot handle exception raised by custom op
  tensorflow/python/autograph/pyct/BUILD
  tensorflow/python/autograph/pyct/errors.py
  tensorflow/python/autograph/pyct/errors_test.py
Labels: cla: yes, size:M

#28974 Cherry-pick for fixes for dotprod detection on iOS
  tensorflow/lite/experimental/ruy/detect_dotprod.cc
  tensorflow/lite/experimental/ruy/path.h
Labels: cla: yes, size:S

#28973 Two cherrypicks
  tensorflow/contrib/makefile/download_dependencies.sh
  tensorflow/python/kernel_tests/BUILD
  tensorflow/workspace.bzl
Labels: cla: yes, size:S

#28964 Corrected log-format to %s. Removes build-warning
  tensorflow/lite/nnapi/nnapi_implementation.cc
Labels: cla: yes, ready to pull, size:XS

#26008 Lite: Softmax Op Refactored
  tensorflow/lite/kernels/activations.cc
Labels: cla: yes, comp:lite, ready to pull, size:L

#28978 NotImplementedError needs to be raised
  tensorflow/python/keras/metrics.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#26317 Fixes issue #26276 - Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: awaiting review, cla: yes, prtype:bugfix, ready to pull, size:XS

#26067 Updated description & example usage
  tensorflow/lite/python/lite.py
Labels: cla: yes, comp:lite, ready to pull, size:XS

#28986 Re-add 1.14 release notes
  RELEASE.md
Labels: cla: yes, size:M

#28984 Refactor some logic into IsRootEnter and IsRootExit
  tensorflow/compiler/jit/deadness_analysis.cc
Labels: cla: yes, ready to pull, size:S

#24648 Removed kOutput variable which was not used
  tensorflow/lite/kernels/expand_dims.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#29000 Remove encoding kwarg passed to bytes
  tensorflow/tools/git/gen_git_source.py
Labels: cla: yes, size:XS

#29003 Undo https://github.com/tensorflow/tensorflow/pull/29000
  tensorflow/tools/git/gen_git_source.py
Labels: cla: yes, size:XS

#28776 Add support for handling uint32 and uint64 dtypes in batch_util CopySliceToElement and MaybeMoveSliceToElement
  tensorflow/core/kernels/data/dataset_test_base.cc
  tensorflow/core/kernels/data/tensor_slice_dataset_op_test.cc
  tensorflow/core/util/batch_util.cc
  tensorflow/python/data/kernel_tests/from_tensor_slices_test.py
  tensorflow/python/data/kernel_tests/unbatch_test.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#29004 Use future.bytes so we can pass in an encoding
  tensorflow/tools/ci_build/install/install_pip_packages.sh
  tensorflow/tools/git/gen_git_source.py
Labels: cla: yes, size:XS

#28450 [ROCm] Adding ROCm support for "sparse_tensor_dense_matmul" op
  tensorflow/core/kernels/sparse_tensor_dense_matmul_op.cc
  tensorflow/core/kernels/sparse_tensor_dense_matmul_op_gpu.cu.cc
Labels: cla: yes, ready to pull, size:L

#29001 Install apt-transport-https and ca-certificates in install_bootstrap_…
  tensorflow/tools/ci_build/install/install_bootstrap_deb_packages.sh
Labels: cla: yes, size:XS

#29009 Change jessie-backports url to archive.debian.org
  tensorflow/tools/ci_build/Dockerfile.debian.jessie.cpu
Labels: cla: yes, size:XS

#29010 archive.debian.net -> archive.debian.org
  tensorflow/tools/ci_build/Dockerfile.debian.jessie.cpu
Labels: cla: yes, size:XS
