Repository tensorflow/tensorflow, pull requests merged in 2019-11, with the labels that each got.

#33698 Add missing V2/V3 ops to grappler op types
  tensorflow/core/grappler/op_types.cc
  tensorflow/core/grappler/op_types.h
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
  tensorflow/core/grappler/optimizers/arithmetic_optimizer_test.cc
Labels: cla: yes, comp:grappler, ready to pull, size:S

#33610 fix tf.data.Dataset size inferring issue in TF 2.0 keras training loop
  tensorflow/python/keras/engine/training_v2.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#33580 Throw error on build_pip_package --cpu --gpu
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: cla: yes, ready to pull, size:XS

#33930 Update TensorFlow README: expand pip install guide, add Udacity courses to Resources
  README.md
Labels: cla: yes, ready to pull, size:XS

#34018 [Intel MKL] Fixing performance regression in eager mode
  tensorflow/core/common_runtime/eager/BUILD
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#33999 Fix typos
  tensorflow/python/tpu/tpu.py
Labels: cla: yes, ready to pull, size:XS

#33703 [Intel MKL]code cleanup
  tensorflow/core/grappler/optimizers/remapper.cc
Labels: cla: yes, comp:grappler, ready to pull, size:S

#34049 Do not assume order on std::unordered_map
  tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op_test.cc
Labels: cla: yes, ready to pull, size:S

#34051 Decrease tolerance of TF-TRT python tests for TFv2
  tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py
Labels: cla: yes, ready to pull, size:XS

#34054 [INTEL MKL] Fix Eigen related compilation error.
  tensorflow/core/kernels/mkl_concat_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#30590 add i386 architecture
  tensorflow/lite/tools/make/build_ios_universal_lib.sh
Labels: awaiting review, cla: yes, comp:lite, ready to pull, size:XS

#33953 Fix TensorFlow on Python 3.8 logger issue
  tensorflow/python/platform/tf_logging.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#33157 Enable quantized Div for toco
  tensorflow/lite/toco/graph_transformations/quantize.cc
Labels: cla: yes, comp:lite, prtype:bugfix, ready to pull, size:XS

#32021 Changes to support ci_build/install scripts with Ubuntu 18.04 docker …
  tensorflow/tools/ci_build/install/install_deb_packages.sh
  tensorflow/tools/ci_build/install/install_pip_packages.sh
Labels: cla: yes, ready to pull, size:S, type:build/install

#33276 update linear to mel documentation
  tensorflow/python/ops/signal/mel_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#34105 [Intel MKL] Compilation Fix in a test
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite_test.cc
Labels: cla: yes, ready to pull, size:XS

#34160 [r2.1-CherryPick]: Fixing compilation error in MKL eager test
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite_test.cc
Labels: cla: yes, size:XS

#34170 [r2.1:Cherrypick] Add a missing line for compute in toolchain and Re-add the supported CUDA compute capabilities into the toolchain
  third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.1/clang/bin/crosstool_wrapper_driver_is_not_gcc
Labels: cla: yes, size:XS

#34172 [r2.1:Cherrypick] Export Keras preprocessing layers in tf.keras.layers.experimental.
  tensorflow/python/keras/engine/base_preprocessing_layer.py
  tensorflow/python/keras/layers/__init__.py
  tensorflow/python/keras/layers/preprocessing/normalization.py
  tensorflow/python/keras/layers/preprocessing/normalization_v1.py
  tensorflow/python/keras/layers/preprocessing/text_vectorization.py
  tensorflow/python/keras/layers/preprocessing/text_vectorization_v1.py
  tensorflow/python/tools/api/generator/api_init_files.bzl
  tensorflow/python/tools/api/generator/api_init_files_v1.bzl
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-normalization.__metaclass__.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-normalization.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-preprocessing-layer.__metaclass__.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-preprocessing-layer.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-text-vectorization.__metaclass__.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-text-vectorization.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-normalization.__metaclass__.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-normalization.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-preprocessing-layer.__metaclass__.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-preprocessing-layer.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-text-vectorization.__metaclass__.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-text-vectorization.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.pbtxt
Labels: cla: yes, size:XL

#33854 Add device annotations to gradient_function
  tensorflow/python/eager/backprop.py
  tensorflow/python/eager/device_placement_test.py
  tensorflow/python/eager/pywrap_tfe_src.cc
Labels: cla: yes, comp:ops, ready to pull, size:S

#34161 Assert shapes
  tensorflow/python/ops/check_ops.py
Labels: cla: yes, ready to pull, size:S

#34014 Improve math_ops.py docs
  tensorflow/python/ops/math_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#34173 [r2.1:Cherrypick] Run Model.*_on_batch using tf.function where appropriate.
  tensorflow/python/keras/engine/base_layer_test.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/engine/training_v2_utils.py
  tensorflow/python/keras/saving/saved_model/saved_model_test.py
Labels: cla: yes, size:M

#34175 [r2.1:Cherrypick] Fix flaky doctest.
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, size:S

#34180 Fix bug in output ordering from interleave with num_parallel_calls
  tensorflow/core/kernels/data/parallel_interleave_dataset_op.cc
  tensorflow/core/kernels/data/parallel_interleave_dataset_op_test.cc
Labels: cla: yes, size:M

#33553 fixed cond with grouped summaries in one branch
  tensorflow/python/ops/control_flow_ops.py
  tensorflow/python/ops/control_flow_ops_test.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#34208 Add XLA context to the function cache key
  tensorflow/python/eager/function.py
Labels: cla: yes, size:S

#33404 [INTEL MKL] Reimplement CompareMklDnnLayouts
  tensorflow/core/util/mkl_util.h
Labels: cla: yes, comp:mkl, ready to pull, size:M

#34202 Remove adding of /usr/bin to compiler paths
  third_party/gpus/cuda_configure.bzl
Labels: cla: yes, comp:gpu, ready to pull, size:S

#34209 Update README.md
  README.md
Labels: cla: yes, ready to pull, size:S

#34252 Cherrypicks r63 jv
  tensorflow/lite/BUILD
  tensorflow/lite/experimental/c/BUILD
  tensorflow/lite/kernels/BUILD
  tensorflow/tensorflow.bzl
Labels: cla: yes, size:XS

#34241 2.1-RC0 cherry-pick request: [tf.data] Improving detection of infinitely repeated datasets in the presence of errors.
  tensorflow/core/framework/dataset.cc
  tensorflow/core/framework/dataset.h
  tensorflow/core/kernels/data/shuffle_dataset_op.cc
  tensorflow/python/data/kernel_tests/shuffle_test.py
  tensorflow/python/eager/context.py
Labels: cla: yes, size:M

#34063 [Intel MKL] add missing attr
  tensorflow/core/ops/mkl_nn_ops.cc
  tensorflow/core/ops/nn_ops.cc
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: API review, cla: yes, comp:mkl, ready to pull, size:S

#34162 Updated DeviceSpec docstring and fixed typos
  tensorflow/python/framework/device_spec.py
Labels: cla: yes, ready to pull, size:S

#34240 Updated documentation in image_ops_impl.py
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:M

#32648 [Intel MKL] Transpose + Maxpool3D + Transpose fusion
  tensorflow/core/graph/mkl_layout_pass.cc
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:L

#33284 Fix android demo build
  tensorflow/tools/ci_build/builds/android.sh
Labels: cla: yes, ready to pull, size:XS

#34109 Don't compile CUDA kernels in debug mode.
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl
  third_party/gpus/crosstool/windows/msvc_wrapper_for_nvcc.py.tpl
Labels: cla: yes, ready to pull, size:XS

#34236 Add `all` support for autograph with dataset
  tensorflow/python/autograph/operators/py_builtins.py
  tensorflow/python/autograph/operators/py_builtins_test.py
Labels: cla: yes, comp:autograph, ready to pull, size:M

#34294 Fix buildifier errors
  tensorflow/c/kernels/BUILD
  tensorflow/compiler/jit/BUILD
  tensorflow/compiler/xla/BUILD
  tensorflow/core/debug/BUILD
  tensorflow/core/profiler/internal/BUILD
  tensorflow/core/profiler/internal/gpu/BUILD
  tensorflow/lite/delegates/gpu/metal/BUILD
  tensorflow/lite/delegates/gpu/metal/kernels/BUILD
Labels: cla: yes, size:S

#34079 Update activations.py
  tensorflow/python/keras/activations.py
Labels: cla: yes, ready to pull, size:S

#34279 2.1-RC0 cherry-pick request: [tf.data] Improvements to cancellation logic.
  tensorflow/core/framework/dataset.cc
  tensorflow/core/framework/dataset.h
  tensorflow/core/kernels/data/experimental/ignore_errors_dataset_op.cc
  tensorflow/core/kernels/data/iterator_ops.h
  tensorflow/core/kernels/data/parallel_map_dataset_op.cc
  tensorflow/core/kernels/data/prefetch_dataset_op.cc
Labels: cla: yes, size:M

#34281 Support LogicalDevice in MirroredStrategy config
  tensorflow/python/distribute/device_util.py
  tensorflow/python/distribute/mirrored_strategy.py
  tensorflow/python/distribute/remote_mirrored_strategy_eager_test.py
  tensorflow/python/eager/context.py
  tensorflow/python/tpu/tpu_system_metadata.py
Labels: cla: yes, size:M

#34292 2.1-RC0 cherry-pick request: [tf.data] iterator life cycle management bug fix
  tensorflow/python/data/ops/iterator_ops.py
  tensorflow/python/data/ops/multi_device_iterator_ops.py
Labels: cla: yes, size:S

#34261 [Intel MKL] Fix memory leak
  tensorflow/core/kernels/mkl_conv_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#34245 2.1-rc0 cherry-pick request: "Rollback ruy avx2/avx512 changes to fix accuracy regression."
  tensorflow/lite/experimental/ruy/pack_avx2.cc
  tensorflow/lite/experimental/ruy/pack_avx512.cc
Labels: cla: yes, size:L

#34259 fix debug_events_writer: avoid possible NULL pointer dereference
  tensorflow/core/util/debug_events_writer.cc
Labels: cla: yes, ready to pull, size:XS

#34206 Update docs of map_fn
  tensorflow/python/ops/map_fn.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#34249 Update version numbers for TensorFlow 2.1.0-rc0
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#34325 Fix the performance regression for model.predict for non-tpu strategy.
  tensorflow/python/keras/engine/training_v2.py
  tensorflow/python/keras/engine/training_v2_utils.py
  tensorflow/python/keras/engine/training_v2_utils_test.py
Labels: cla: yes, size:M

#34327 [r2.1:Cherrypick]Update the TF CUDA version to 10.1
  configure.py
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py2_full/nightly_release.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py2_full/nonpip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py2_full/nonpip_v1.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py2_full/pip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py2_full/pip_v1.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py35_full/nightly_release.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py35_full/nonpip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py35_full/nonpip_v1.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py35_full/pip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py35_full/pip_v1.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py36_full/nightly_release.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py36_full/nonpip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py36_full/nonpip_v1.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py36_full/pip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py36_full/pip_v1.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py37_full/nightly_release.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py37_full/nonpip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py37_full/nonpip_v1.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py37_full/pip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_py37_full/pip_v1.sh
Labels: cla: yes, size:S

#34359 Updating/setting xcode version to 10.3
  tensorflow/tools/ci_build/release/macos/cpu_py2_full/nonpip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py2_full/pip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py35_full/nonpip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py35_full/pip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py36_full/nonpip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py36_full/pip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py37_full/nonpip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py37_full/pip.sh
Labels: cla: yes, size:S

#33954 Update import_pb_to_tensorboard.py script to be compatible with TF2.0 saved_model files #8854
  tensorflow/python/tools/import_pb_to_tensorboard.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#34387 MKL DNN: Fixing mkl compilation failure for commit e154f44
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
Labels: cla: yes, ready to pull, size:XS

#33846 Grappler: Remove FusedBatchNorm from NeverForwardsInputs list
  tensorflow/core/grappler/op_types.cc
Labels: cla: yes, comp:grappler, ready to pull, size:XS

#34389 Fixes #34194 - tf.size() documentation
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#34403 Fix 2 failing tests
  tensorflow/python/eager/backprop_test.py
  tensorflow/python/kernel_tests/matrix_exponential_op_test.py
Labels: cla: yes, size:XS

#24706 LIBXSMM in TensorFlow broken due to TensorFlow API changes
  tensorflow/core/kernels/conv_grad_filter_ops.cc
  tensorflow/core/kernels/conv_grad_input_ops.cc
  tensorflow/core/kernels/conv_ops.cc
  tensorflow/core/kernels/sparse_matmul_op.cc
  tensorflow/core/kernels/xsmm_conv2d.cc
  tensorflow/core/kernels/xsmm_conv2d_test.cc
  tensorflow/workspace.bzl
  third_party/libxsmm.BUILD
Labels: cla: yes, ready to pull, size:L

#34383 Improve tf.batch_to_space documentation. Refer issue #34005
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, ready to pull, size:M

#34397 Fix typos in gradients_impl.py code examples
  tensorflow/python/ops/gradients_impl.py
Labels: cla: yes, ready to pull, size:XS

#34422 Fixes issue #34398, equation from BTRS paper
  tensorflow/core/kernels/random_binomial_op.cc
Labels: cla: yes, ready to pull, size:XS

#34412 Added missing xla lowering operations.
  tensorflow/compiler/mlir/xla/tests/hlo-legalize-to-lhlo.mlir
  tensorflow/compiler/mlir/xla/transforms/hlo_legalize_to_lhlo.cc
Labels: cla: yes, ready to pull, size:M

#31997 Limit the number of statements in exception raising test blocks to 1
  tensorflow/python/feature_column/sequence_feature_column_test.py
Labels: cla: yes, ready to pull, size:S

#33367 Upate dockerfiles/README.md for usages of `--gpus all`
  tensorflow/tools/dockerfiles/README.md
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#26988 Refactoring comparisons invoke calls
  tensorflow/lite/kernels/comparisons.cc
Labels: cla: yes, comp:lite, ready to pull, size:L

#34394 Google upstream r21 with required fixes
  tensorflow/core/kernels/training_ops.cc
  tensorflow/core/kernels/training_ops_gpu.cu.cc
  tensorflow/python/eager/forwardprop_test.py
  tensorflow/python/keras/layers/image_preprocessing_test.py
  tensorflow/python/keras/optimizer_v2/adadelta_test.py
  tensorflow/python/keras/optimizer_v2/adagrad_test.py
  tensorflow/python/keras/optimizer_v2/rmsprop_test.py
  tensorflow/python/ops/special_math_ops_test.py
  tensorflow/tools/ci_build/Dockerfile.rocm
  tensorflow/tools/ci_build/builds/docker_test.sh
  tensorflow/tools/ci_build/ci_build.sh
  third_party/gpus/crosstool/BUILD.rocm.tpl
  third_party/toolchains/preconfig/ubuntu16.04/gcc5-rocm/BUILD
Labels: cla: yes, size:M

#34419 Switch to NDK API level 21
  configure.py
  tensorflow/lite/g3doc/guide/android.md
  tensorflow/tools/ci_build/Dockerfile.android
  tensorflow/tools/ci_build/builds/builds_common.sh
Labels: cla: yes, size:XS

#34465 [r2.1:Cherrypick]Support /d2ReducedOptimizeHugeFunctions on Windows when TF_VC_VERSION=16.4
  configure.py
Labels: cla: yes, size:S

#33845 Fix for CMSIS-NN operator. Merge from ref conv.cc.
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/conv.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#34164 Added reference kernel fallback for conv
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/conv.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#34471 Fix bug in NCCL broadcast wrapper
  tensorflow/core/nccl/nccl_manager.cc
Labels: cla: yes, ready to pull, size:XS

#34493 Fix nested function inside XLA context.
  tensorflow/python/eager/function.py
Labels: cla: yes, size:S

#34472 Allow building two pip cpu packages on macos.
  tensorflow/tools/ci_build/builds/pip_new.sh
  tensorflow/tools/ci_build/release/macos/cpu_py2_full/pip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py35_full/pip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py36_full/pip.sh
  tensorflow/tools/ci_build/release/macos/cpu_py37_full/pip.sh
Labels: cla: yes, size:M

#34497 Make docker has the same bazel version as the env that invokes it.
  tensorflow/tools/ci_build/builds/docker_cpu_pip.sh
  tensorflow/tools/ci_build/release/ubuntu_16/gpu_pip_on_cpu/build.sh
Labels: cla: yes, size:XS

#34495 [tf.data] Fix OOM when tf.data map_and_batch is used with num_paralle…
  tensorflow/core/kernels/data/experimental/BUILD
  tensorflow/core/kernels/data/experimental/map_and_batch_dataset_op.cc
Labels: cla: yes, size:S

#34494 [r2.1:Cherrypick]Change default CUDA version on Windows to 10.1.
  tensorflow/tools/ci_build/release/common_win.bat
Labels: cla: yes, size:XS

#34320 [ROCm] Update ROCm CI builds to use ROCm 2.8
  tensorflow/tools/ci_build/Dockerfile.rocm
  tensorflow/tools/ci_build/builds/docker_test.sh
  tensorflow/tools/ci_build/ci_build.sh
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#33990 Update README.md for community ppc64le 2.x links
  README.md
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#34467 Fix: typo in tensorflow/compiler/xla/g3doc/shapes.md
  tensorflow/compiler/xla/g3doc/shapes.md
Labels: cla: yes, comp:xla, ready to pull, size:XS

#34505 Cherrypicks for r2.1
  tensorflow/tools/ci_build/builds/docker_cpu_pip.sh
  tensorflow/tools/ci_build/builds/pip_new.sh
Labels: cla: yes, size:S

#34476 Fix error message in python/training/supervisor.py
  tensorflow/python/training/supervisor.py
Labels: cla: yes, ready to pull, size:XS

#34516 Allow evaluator not in cluster_spec, to be consistent with legacy Estimator
  tensorflow/python/distribute/multi_worker_util.py
  tensorflow/python/distribute/multi_worker_util_test.py
Labels: cla: yes, size:S

#34468 Make test tag filters behave as intended
  configure.py
Labels: cla: yes, ready to pull, size:S

#34533 [r2.1:Cherrypick]Override EIGEN strong inline for release builds as well.
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes, size:XS

#34168 Added reference kernel fallback for the fully_connected kernel
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/fully_connected.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#34411 Fix compile error in Tensorflow Lite Micro.
  tensorflow/lite/experimental/micro/kernels/activation_utils.h
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XS

#34596 Update windows release build script to create the correct pip package…
  tensorflow/tools/ci_build/release/windows/cpu_py35_full/release.bat
  tensorflow/tools/ci_build/release/windows/cpu_py36_full/release.bat
  tensorflow/tools/ci_build/release/windows/cpu_py37_full/release.bat
  tensorflow/tools/ci_build/release/windows/gpu_py35_full/nightly.bat
  tensorflow/tools/ci_build/release/windows/gpu_py35_full/release_pip_rename.sh
  tensorflow/tools/ci_build/release/windows/gpu_py35_full/release_v1.bat
  tensorflow/tools/ci_build/release/windows/gpu_py36_full/release.bat
  tensorflow/tools/ci_build/release/windows/gpu_py36_full/release_pip_rename.sh
  tensorflow/tools/ci_build/release/windows/gpu_py36_full/release_v1.bat
  tensorflow/tools/ci_build/release/windows/gpu_py37_full/release.bat
  tensorflow/tools/ci_build/release/windows/gpu_py37_full/release_pip_rename.sh
  tensorflow/tools/ci_build/release/windows/gpu_py37_full/release_v1.bat
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes, size:M

#34593 Allows Keras TensorLikeDataAdapter to handle pandas series and datafr…
  tensorflow/python/keras/engine/data_adapter.py
  tensorflow/python/keras/engine/data_adapter_test.py
Labels: cla: yes, size:M

#34246 Update release notes for TensorFlow 2.1.0
  RELEASE.md
Labels: cla: yes, size:XS

#31296 add api doc
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:M

#34285 [Intel MKL] Adding BFloat16 unit tests for MKL layout pass
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XL

#34623 Fix bug in if -v check.
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes, size:XS

#34167 Added reference kernel fallback for depthwise_conv
  tensorflow/lite/experimental/micro/kernels/cmsis-nn/depthwise_conv.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#34626 Move gpu script update to the correct file.
  tensorflow/tools/ci_build/release/windows/gpu_py35_full/nightly.bat
  tensorflow/tools/ci_build/release/windows/gpu_py35_full/release.bat
Labels: cla: yes, size:S

#34630 [Inte MKL]Fix MatMul and Elu fusion issue relate to #33451.
  tensorflow/core/kernels/mkl_matmul_ops_common.h
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#34535 [Intel MKL] Fixing a bug in Elu Op
  tensorflow/core/kernels/mkl_conv_ops.cc
  tensorflow/core/kernels/mkl_fused_ops_test.cc
Labels: cla: yes, ready to pull, size:S

#34367 Implement Tell method of SnappyInputBuffer class.
  tensorflow/core/lib/io/snappy/snappy_buffers_test.cc
  tensorflow/core/lib/io/snappy/snappy_inputbuffer.cc
  tensorflow/core/lib/io/snappy/snappy_inputbuffer.h
Labels: cla: yes, ready to pull, size:M

#34601 Relocate comment in resize_bilinear kernel
  tensorflow/core/kernels/resize_bilinear_op.cc
Labels: cla: yes, ready to pull, size:XS

#34597 Always use real exp when scaling in linalg.expm
  tensorflow/python/ops/linalg/linalg_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30667 Add kZlib to compression namespace
  tensorflow/core/lib/io/compression.cc
  tensorflow/core/lib/io/compression.h
  tensorflow/core/lib/io/record_reader.cc
  tensorflow/core/lib/io/record_writer.cc
Labels: cla: yes, ready to pull, size:XS

#34108 TfLite GL delegate is built with visibility hidden
  tensorflow/lite/delegates/gpu/BUILD
Labels: cla: yes, comp:lite, prtype:bugfix, ready to pull, size:S

#32605 [xla] fix xla build on cuda devices without nccl
  tensorflow/compiler/xla/service/gpu/BUILD
Labels: cla: yes, comp:xla, ready to pull, size:XS

#34104 [ROCm] Fix for the broken ROCm CSB.
  tensorflow/python/keras/layers/image_preprocessing_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S
