Repository tensorflow/tensorflow, pull requests merged in 2019-12, with the labels that each got.

#34121 Update documentation of tf.debugging.assert_shapes
  tensorflow/python/ops/check_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#34653 [ROCm] Fix for the broken ROCm CSB - 191127
  tensorflow/python/ops/linalg/linear_operator_test_util.py
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#34730 Fix misformatted markdown in Model.fit docstring
  tensorflow/python/keras/engine/training.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#33166 minor spelling tweaks under mlir
  tensorflow/compiler/mlir/lite/flatbuffer_translate.cc
  tensorflow/compiler/mlir/lite/ir/tfl_ops.cc
  tensorflow/compiler/mlir/lite/ir/tfl_ops.td
  tensorflow/compiler/mlir/lite/quantization/import_quant_stats_pass.cc
  tensorflow/compiler/mlir/lite/quantization/quantization.td
  tensorflow/compiler/mlir/lite/quantization/quantization_traits.h
  tensorflow/compiler/mlir/lite/quantization/quantization_utils.h
  tensorflow/compiler/mlir/lite/tests/canonicalize.mlir
  tensorflow/compiler/mlir/lite/tests/extract-ophint.mlir
  tensorflow/compiler/mlir/lite/tests/ops.mlir
  tensorflow/compiler/mlir/lite/tests/optimize.mlir
  tensorflow/compiler/mlir/lite/tf_tfl_translate_cl.cc
  tensorflow/compiler/mlir/lite/transforms/extract_ophint.cc
  tensorflow/compiler/mlir/lite/transforms/legalize_ophint_func_op.cc
  tensorflow/compiler/mlir/lite/transforms/prepare_composite_functions_tf.cc
  tensorflow/compiler/mlir/lite/transforms/prepare_quantize.cc
  tensorflow/compiler/mlir/lite/transforms/prepare_tf.cc
  tensorflow/compiler/mlir/lite/transforms/unroll_batch_matmul.cc
  tensorflow/compiler/mlir/lite/utils/lstm_utils.h
  tensorflow/compiler/mlir/runlit.site.cfg.py
  tensorflow/compiler/mlir/tensorflow/ir/dialect_registration.cc
  tensorflow/compiler/mlir/tensorflow/ir/tf_op_base.td
  tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc
  tensorflow/compiler/mlir/tensorflow/ir/tf_ops.h
  tensorflow/compiler/mlir/tensorflow/tests/cluster_formation.mlir
  tensorflow/compiler/mlir/tensorflow/tests/tf_executor_ops_invalid.mlir
  tensorflow/compiler/mlir/tensorflow/transforms/tf_graph_optimization_pass.cc
  tensorflow/compiler/mlir/tensorflow/translate/import_model.cc
  tensorflow/compiler/mlir/tensorflow/utils/compile_mlir_util_test.cc
  tensorflow/compiler/mlir/xla/ir/hlo_ops.cc
  tensorflow/compiler/mlir/xla/ir/hlo_ops_base.td
  tensorflow/compiler/mlir/xla/mlir_hlo_to_hlo.cc
Labels: cla: yes, ready to pull, size:M

#34050 [ROCm] Fix for the broken ROCm CSB.
  tensorflow/core/kernels/training_ops.cc
  tensorflow/core/kernels/training_ops_gpu.cu.cc
  tensorflow/python/keras/optimizer_v2/adadelta_test.py
  tensorflow/python/keras/optimizer_v2/adagrad_test.py
  tensorflow/python/keras/optimizer_v2/rmsprop_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:M

#34288 Move TensorRT builder configs to converter build function
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h
Labels: cla: yes, ready to pull, size:M

#27825 TFLite: Div op Neon optimization
  tensorflow/lite/kernels/internal/optimized/optimized_ops.h
Labels: cla: yes, comp:lite, ready to pull, size:M

#34627 Improve resize_bilinear CPU back-prop kernel comment
  tensorflow/core/kernels/resize_bilinear_op.cc
Labels: cla: yes, comp:ops, ready to pull, size:S

#33971 [Lite] Support Int8 Unpack Operator
  tensorflow/lite/tools/optimize/BUILD
  tensorflow/lite/tools/optimize/operator_property.cc
  tensorflow/lite/tools/optimize/quantize_model_test.cc
  tensorflow/lite/tools/optimize/test_util.cc
  tensorflow/lite/tools/optimize/test_util.h
  tensorflow/lite/tools/optimize/testdata/unpack.bin
Labels: cla: yes, comp:lite, ready to pull, size:S

#34792 Update systemlibs protobuf vars
  third_party/systemlibs/protobuf.BUILD
  third_party/systemlibs/protobuf.bzl
Labels: cla: yes, ready to pull, size:XS

#34662 <release 2.1>-<rc1> cherry-pick request: update tflite op versions
  tensorflow/lite/toco/tflite/op_version.cc
Labels: cla: yes, size:XS

#34822 [r2.1 cherry-pick] Fix pip package API generation
  tensorflow/api_template.__init__.py
  tensorflow/api_template_v1.__init__.py
  tensorflow/python/tools/api/generator/create_python_api.py
  tensorflow/python/tools/api/generator/create_python_api_test.py
  tensorflow/virtual_root_template_v1.__init__.py
  tensorflow/virtual_root_template_v2.__init__.py
Labels: cla: yes, size:M

#33583 [XLA:GPU] Expand batchnorm inference by default
  tensorflow/compiler/xla/debug_options_flags.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#34824 Fix typo in TFLite quantization spec
  tensorflow/lite/g3doc/performance/quantization_spec.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#34509 Add networking related headers in pip wheel
  tensorflow/tools/pip_package/BUILD
Labels: cla: yes, ready to pull, size:XS

#34764 Set --incompatible_remove_legacy_whole_archive to False
  .bazelrc
Labels: cla: yes, size:S

#34654 [r2.1:Cherrypick][Intel MKL] Fixing a bug in Elu Op
  tensorflow/core/kernels/mkl_conv_ops.cc
  tensorflow/core/kernels/mkl_fused_ops_test.cc
Labels: cla: yes, size:S

#34746 lite/microfrontend: fix FilterbankState unsigned type missmatch
  tensorflow/lite/experimental/microfrontend/lib/filterbank.c
Labels: cla: yes, comp:lite, ready to pull, size:XS

#34842 Fix for https://github.com/tensorflow/tensorflow/issues/34117
  tensorflow/BUILD
  tensorflow/tensorflow.bzl
Labels: cla: yes, size:S

#34875 Update image_ops_impl.py
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, ready to pull, size:XS

#34847 Fix `invalid syntax` error when `import carla` is present
  tensorflow/python/framework/python_op_gen_internal.cc
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#34881 [Intel MKL] Fixing MKL broken README links and updating with 1.15 and 2.0 links
  README.md
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#34835 Fix segfault in error handling
  tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc
Labels: cla: yes, ready to pull, size:XS

#34832 Remove code owners for tf.contrib modules
  CODEOWNERS
Labels: cla: yes, ready to pull, size:M

#34910 Add Estimator release notes.
  RELEASE.md
Labels: cla: yes, size:XS

#34883 [r2.1:Cherrypick] Include build_config.bzl in Tensorflow 2.1 rc
  tensorflow/core/platform/build_config.bzl
Labels: cla: yes, size:M

#34885 Make nccl bindings compilable with cuda 10.2
  third_party/nccl/build_defs.bzl.tpl
  third_party/nccl/nccl_configure.bzl
Labels: cla: yes, ready to pull, size:S

#34915 [r2.1 Cherrypick] Eigen update for fixing the Windows builds
  tensorflow/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_google.h
  tensorflow/lite/kernels/internal/optimized/eigen_tensor_reduced_instantiations_oss.h
  tensorflow/python/keras/activations.py
  tensorflow/workspace.bzl
Labels: cla: yes, size:S

#34918 [r2.1 Cherrypick]:Override EIGEN strong inline for release builds as well.
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes, size:XS

#34917 [r2.1 Cherrypick]: Group variable initialization when calling lift_to_graph.
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/def_function_test.py
Labels: cla: yes, size:S

#34914 Update version numbers for TensorFlow 2.1.0-rc1
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#34969 Fix the estimator version.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#34265 Updating metrics_export_meta_graph.pb for fixing //tensorflow/python:framework_meta_graph_test
  tensorflow/python/framework/testdata/metrics_export_meta_graph.pb
Labels: cla: yes, ready to pull, size:S

#34959 Add release note about CUDA 10.1 and cuDNN 7.6
  RELEASE.md
Labels: cla: yes, size:XS

#34970 [r2.1 Cherrypick] Correct number of output shapes written by SavedModel and Update keras standardization code to error out when a namedtuple is encountered.
  tensorflow/python/framework/ops.py
  tensorflow/python/keras/engine/data_adapter.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/engine/training_test.py
  tensorflow/python/keras/engine/training_v2.py
  tensorflow/python/saved_model/save_test.py
Labels: cla: yes, size:M

#34971 Throw an explicit error if calling TPUStrategy in eager mode
  tensorflow/python/distribute/tpu_strategy.py
Labels: cla: yes, size:M

#34974 [r2.1 Cherrypick]: Support DistributionStrategy in LossScaleGradientTape, take 2.
  tensorflow/python/BUILD
  tensorflow/python/training/experimental/loss_scaling_gradient_tape.py
  tensorflow/python/training/experimental/loss_scaling_gradient_tape_test.py
Labels: cla: yes, size:L

#34887 Add info about TF_DETERMINISTIC_OPS to version 2.1 release notes
  RELEASE.md
Labels: cla: yes, size:XS

#34979 [r2.1 Cherrypick] Remove name-based Variable handling in keras Lambda layers, and add detailed exceptions and warnings for unsafe corner cases.
  tensorflow/python/keras/layers/core.py
  tensorflow/python/keras/layers/core_test.py
Labels: cla: yes, size:M

#35005 [r2.1:Cherrypick] Expose ndtri and erfinv under tf.math.ndtri and tf.math.erfinv.
  tensorflow/core/api_def/python_api/api_def_Erfinv.pbtxt
  tensorflow/core/api_def/python_api/api_def_Ndtri.pbtxt
  tensorflow/python/ops/math_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.math.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.math.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.pbtxt
Labels: cla: yes, size:M

#34911 Fix dynamic display for PyCharm
  tensorflow/python/keras/utils/generic_utils.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#35082 Add survey to README.md
  README.md
Labels: cla: yes, ready to pull, size:XS

#35019 Relax shapes for Keras _on_batch functions.
  tensorflow/python/keras/engine/training_v2_utils.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#35039 [XLA][AMDGPU] Add GemmRewriter into AMDGPU HLO optimization pipeline.
  tensorflow/compiler/xla/service/gpu/BUILD
  tensorflow/compiler/xla/service/gpu/amdgpu_compiler.cc
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#34941 Add documentation for undocumented exception
  tensorflow/python/autograph/impl/conversion.py
Labels: cla: yes, ready to pull, size:XS

#35001 Added Updated command
  README.md
Labels: cla: yes, ready to pull, size:S

#34884 add usage examples
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#34836 Avoid code duplication by calling pyo() method
  tensorflow/python/lib/core/pybind11_lib.h
Labels: cla: yes, ready to pull, size:XS

#35021 Pass experimental_relax_shapes to instance methods decorated with `tf.function`.
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/def_function_test.py
  tensorflow/python/eager/function.py
  tensorflow/python/eager/function_test.py
Labels: cla: yes, comp:eager, prtype:bugfix, ready to pull, size:XS

#33229 Load saved custom Loss class
  tensorflow/python/keras/saving/saving_utils.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#35034 Fix compilation of hwloc
  third_party/hwloc/BUILD.bazel
  third_party/hwloc/static-components.h
Labels: cla: yes, ready to pull, size:S

#34973 Ensure sorted=true in top_k converter
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
Labels: cla: yes, ready to pull, size:XS

#35166 Updating Readme.md with a link to new user survey
  README.md
Labels: cla: yes, ready to pull, size:S

#34770 [ROCm] eigen patch needed for HIP header changes
  third_party/eigen3/gpu_packet_math.patch
Labels: cla: yes, comp:gpu, ready to pull, size:M

#34978 Disable tests tagged 'v1only' on v2 builds
  configure.py
Labels: cla: yes, ready to pull, size:S

#35097 Update ref link for docs
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#34529 Correctly access the vocab_size
  tensorflow/python/keras/layers/preprocessing/text_vectorization.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#35139 Fix build breaks for S3 unit test
  tensorflow/core/platform/s3/s3_file_system_test.cc
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#34807 Fix deprecation warnings in image_ops by replacing div with divide or floordiv
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#33443 Fixes Issue #26197
  tensorflow/python/keras/__init__.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#34972 Docs: Update Readme.md to reflect pip package changes with TF 2.1
  README.md
Labels: cla: yes, ready to pull, size:S

#35234 Revert "[r2.1 cherry-pick] Fix pip package API generation"
  tensorflow/api_template.__init__.py
  tensorflow/api_template_v1.__init__.py
  tensorflow/python/tools/api/generator/create_python_api.py
  tensorflow/python/tools/api/generator/create_python_api_test.py
  tensorflow/virtual_root_template_v1.__init__.py
  tensorflow/virtual_root_template_v2.__init__.py
Labels: cla: yes, size:M

#35091 [GPU][ROCm] Fix hip-clang build
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#35265 R2.1 Release Notes: Move section on tf.debugging.enable_check_numerics to own subsection
  RELEASE.md
Labels: cla: yes, size:XL

#35232 fixes 35136
  tensorflow/python/keras/layers/dense_attention.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#35270 Revert "Revert "[r2.1 cherry-pick] Fix pip package API generation""
  tensorflow/api_template.__init__.py
  tensorflow/api_template_v1.__init__.py
  tensorflow/python/tools/api/generator/create_python_api.py
  tensorflow/python/tools/api/generator/create_python_api_test.py
  tensorflow/virtual_root_template_v1.__init__.py
  tensorflow/virtual_root_template_v2.__init__.py
Labels: cla: yes, size:M

#35271 Fixing an issue where scipy and tensorflow cannot be imported at the …
  tensorflow/tensorflow.bzl
Labels: cla: yes, size:S

#35078 [INTEL MKL] Fix quantize accuracy loss
  tensorflow/core/kernels/mkl_quantize_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#35278 Pin scipy to 1.4.1.
  tensorflow/tools/ci_build/builds/pip_new.sh
  tensorflow/tools/ci_build/install/install_centos_pip_packages.sh
  tensorflow/tools/ci_build/install/install_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:S

#35284 Revert "<release 2.1>-<rc1> cherry-pick request: update tflite op versions"
  tensorflow/lite/toco/tflite/op_version.cc
Labels: cla: yes, size:XS

#35282 2.1 cherry-pick request: Fix doc formatting in dataset_ops.py
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, size:XS

#35291 Fix compilation crash of replay_computation
  tensorflow/compiler/xla/tools/replay_computation.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#35263 [XLALite] Print the name that should be used to enable it.
  tensorflow/compiler/jit/mark_for_compilation_pass.cc
Labels: cla: yes, ready to pull, size:XS

#35256 Add support of hadoop archive
  tensorflow/core/platform/hadoop/hadoop_file_system.cc
  tensorflow/core/platform/hadoop/hadoop_file_system.h
  tensorflow/core/platform/hadoop/hadoop_file_system_test.cc
Labels: cla: yes, ready to pull, size:M

#35235 [r2.1 Cherrypick] Pass experimental_relax_shapes to instance methods decorated with `tf.function` and Relax shapes for Keras _on_batch functions.
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/def_function_test.py
  tensorflow/python/eager/function.py
  tensorflow/python/eager/function_test.py
  tensorflow/python/keras/engine/training_v2_utils.py
Labels: cla: yes, size:S

#35255 Fix typos conv2d, conv2d_v2 docstrings
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#35269 fix model.compile docstring to match Keras
  tensorflow/python/keras/engine/training.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#35201 [Intel MKL] Fixed a bug in mkl_conv2d constant filter caching which c…
  tensorflow/core/kernels/mkl_conv_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#35313 Revert "Set --incompatible_remove_legacy_whole_archive to False"
  .bazelrc
Labels: cla: yes, size:S

#35312 Revert "Revert "<release 2.1>-<rc1> cherry-pick request: update tflite op versions""
  tensorflow/lite/toco/tflite/op_version.cc
Labels: cla: yes, size:XS

#35289 For python2, pin scipy to 1.2.2 (latest released).
  tensorflow/tools/ci_build/builds/pip_new.sh
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#35315 Revert "Revert "Set --incompatible_remove_legacy_whole_archive to False""
  .bazelrc
Labels: cla: yes, size:S

#35163 Cherrypick Windows DLL warning changes and related notes
  RELEASE.md
  tensorflow/python/platform/self_check.py
  tensorflow/tensorflow.bzl
Labels: cla: yes, size:S

#35006 Fix version 2.1 release note regarding TF_DETERMINISTIC_OPS
  RELEASE.md
Labels: cla: yes, size:XS

#35069 [r2.1 Cherrypick] Edit release notes
  RELEASE.md
Labels: cla: yes, size:S

#35066 [r2.1 Cherrypick] Unify V1/2 layer naming in internal imports
  tensorflow/python/keras/layers/__init__.py
  tensorflow/python/keras/layers/cudnn_recurrent_test.py
  tensorflow/python/keras/layers/rnn_cell_wrapper_v2_test.py
  tensorflow/python/keras/saving/hdf5_format_test.py
  tensorflow/python/layers/normalization.py
Labels: cla: yes, size:M

#35041 [r2.1 Cherrypick]: Unexpose LossScaleGradientTape.
  tensorflow/python/training/experimental/loss_scaling_gradient_tape.py
  tensorflow/tools/api/golden/v2/tensorflow.mixed_precision.experimental.-loss-scale-gradient-tape.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.mixed_precision.experimental.pbtxt
Labels: cla: yes, size:S

#35273 Update version numbers for TensorFlow 2.1.0-rc2
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#35322 Fix segfault when attempting to convert string to float16.
  tensorflow/python/BUILD
  tensorflow/python/framework/constant_op_test.py
  tensorflow/python/lib/core/py_seq_tensor.cc
Labels: cla: yes, size:M

#35324 Update RELEASE.md
  RELEASE.md
Labels: cla: yes, size:S

#35238 [ROCm][r2.1] eigen patch needed for HIP header changes
  third_party/eigen3/gpu_packet_math.patch
Labels: cla: yes, size:M

#35321 Super small update for CONTRIBUTING.md tensorflow/tensorflow
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:XS

#35296 Missing UnPack Op added
  tensorflow/lite/c/builtin_op_data_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#35323 Use std::vector instead of C arrays for TestParams
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, ready to pull, size:M

#35367 Explicit horovod spec and update CUDA to 10.1
  tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/devel-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/devel-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile
  tensorflow/tools/dockerfiles/spec.yml
Labels: cla: yes, ready to pull, size:M

#35328 query replaced with value
  tensorflow/python/keras/layers/dense_attention.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#34138 fixed KeyError issue for tf.Module.variables
  tensorflow/python/util/nest.py
Labels: cla: yes, ready to pull, size:XS

#35038 [Intel MKL] Updating MKL layout pass unit test with bfloat16 support - 2
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XL

#35098 add usage examples/doctests
  tensorflow/python/ops/check_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#35331 Fix bug in documentation of tf.while_loop.parallel_iterations
  tensorflow/python/ops/control_flow_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:XS

#35434 Install extra TensorRT dependency
  tensorflow/tools/dockerfiles/partials/ubuntu/devel-nvidia.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile
Labels: cla: yes, ready to pull, size:XS

#35436 Pin libcublas10=10.2.1.243-1
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/devel-nvidia.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile
Labels: cla: yes, ready to pull, size:M

#33025 makes possible to move stderr on run_shell at configure.py and non show traceback message when find site packages
  configure.py
Labels: cla: yes, ready to pull, size:S

#35279 Better warning log on allocation failures.
  tensorflow/core/framework/cpu_allocator_impl.cc
Labels: cla: yes, ready to pull, size:XS

#35293 Added usage example for tf.image.rgb_to_yiq
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S
