Repository tensorflow/tensorflow, pull requests merged in 2019-07, with the labels that each got.

#29773 added examples for math.argmax
  tensorflow/python/ops/math_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30147 [ROCm] Adding ROCm support for the map_stage_op
  tensorflow/core/kernels/map_stage_op.cc
Labels: cla: yes, ready to pull, size:S

#30219 [XLA] Add required header
  tensorflow/compiler/xla/service/hlo_verifier_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#29814 grappler: Also recompute LeakyRelu
  tensorflow/core/grappler/optimizers/memory_optimizer.cc
Labels: cla: yes, comp:grappler, ready to pull, size:S

#30225 [ROCm] Adding ROCm support for the transpose op
  tensorflow/core/kernels/transpose_functor_gpu.cu.cc
  tensorflow/core/kernels/transpose_op.cc
Labels: cla: yes, ready to pull, size:S

#30237 [ROCm] Adding ROCm support for the fused_batch_norm op
  tensorflow/core/kernels/fused_batch_norm_op.cc
  tensorflow/core/kernels/fused_batch_norm_op.cu.cc
  tensorflow/core/kernels/fused_batch_norm_op.h
Labels: cla: yes, cuda, ready to pull, size:S

#30098 usage example added in extract glimpse
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30140 Fix funcdef lookup in auto_mixed_precision grappler pass
  tensorflow/core/grappler/optimizers/auto_mixed_precision.cc
  tensorflow/python/grappler/auto_mixed_precision_test.py
Labels: cla: yes, ready to pull, size:M

#29660 Corrected wrong output
  tensorflow/python/ops/histogram_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#30139 [ROCm] Adding ROCm support to gemm strided batched interface
  tensorflow/stream_executor/rocm/rocm_blas.cc
Labels: cla: yes, comp:gpu, ready to pull, size:L

#30264 [INTEL MKL] Fix "redundant-transpose removal" related UT failures.
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#30043 fix metal build
  tensorflow/lite/delegates/gpu/metal_delegate.mm
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30236 1.14.1 cherry-pick request: Add contents of wrapped module __dict__ to DeprecationWrapper __dict__.
  tensorflow/python/util/deprecation_wrapper.py
  tensorflow/python/util/deprecation_wrapper_test.py
  tensorflow/tools/api/tests/BUILD
  tensorflow/tools/api/tests/deprecation_test.py
  tensorflow/tools/api/tests/module_test.py
Labels: cla: yes, size:M

#30257 Update docstring of raises for tf.clip_by_norm
  tensorflow/python/ops/clip_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#30245 [docs] Fixes docs for weighted_cross_entropy_with_logits
  tensorflow/python/ops/nn_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30209 Add amp and TRT changes to 1.14 release notes
  RELEASE.md
Labels: cla: yes, size:XS

#30327 Cherry-picked from master e43b94649d3e1ac5d538e4eca9166b899511d681.
  tensorflow/core/platform/cloud/gcs_file_system.cc
  tensorflow/core/platform/cloud/gcs_file_system.h
  tensorflow/core/platform/cloud/gcs_file_system_test.cc
Labels: cla: yes, size:L

#29928 [ROCm] Adding ROCm support for segment_reduction_ops
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/segment_reduction_ops.cc
  tensorflow/core/kernels/segment_reduction_ops.h
  tensorflow/core/kernels/segment_reduction_ops_gpu.cu.cc
Labels: cla: yes, comp:gpu, ready to pull, size:M

#30241 [INTEL_MKL] Changed 4 unit tests because of the node label changes re…
  tensorflow/core/kernels/mkl_fused_ops_test.cc
  tensorflow/core/kernels/mkl_quantized_conv_ops_perchannel_test.cc
  tensorflow/core/kernels/mkl_quantized_conv_ops_test.cc
  tensorflow/core/kernels/mkl_quantized_pooling_ops_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#30296 Fixed a broken URL in TF Lite iOS Benchmark doc
  tensorflow/lite/tools/benchmark/ios/README.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30312 [ROCm] Add gfx908 into supported AMD GCN ISA version list
  tensorflow/core/common_runtime/gpu/gpu_device.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#30322 [ROCm] Adding ROCm support for the batch_matmul op
  tensorflow/core/kernels/batch_matmul_op_complex.cc
  tensorflow/core/kernels/batch_matmul_op_impl.h
  tensorflow/core/kernels/batch_matmul_op_real.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30320 Fix bug in GpuAtomicCasHelper
  tensorflow/core/util/gpu_device_functions.h
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#30328 [ROCm] Fix for the broken `--config=rocm` build
  third_party/eigen3/gpu_packet_math.patch
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30138 Optimized packet load in gemm_pack_rhs (Packet16f/8f) for CuboidConv
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/eigen_convolution_helpers.h
  tensorflow/core/kernels/eigen_cuboid_convolution.h
  tensorflow/core/kernels/eigen_spatial_convolutions-inl.h
Labels: cla: yes, ready to pull, size:L

#30155 Fix bug in cudnn_fused_conv_rewriter.
  tensorflow/compiler/xla/service/gpu/cudnn_fused_conv_rewriter.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#30358 [ROCm] Adding ROCm support for batch_to_space op
  tensorflow/core/kernels/batchtospace_op.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#30399 [Lite] Accuracy tool compilation issue fix
  tensorflow/lite/tools/accuracy/ilsvrc/imagenet_model_evaluator.h
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30337 [LITE]Fix array leak during resize o/p
  tensorflow/lite/kernels/fill.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30354 [ROCm] Adding ROCm support for the functional ops
  tensorflow/core/kernels/functional_ops.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#30373 add -lm to mlir-tblgen linkopts
  third_party/mlir/BUILD
Labels: cla: yes, ready to pull, size:XS

#30369 Fixing missed saving of "interpolation" parameter in UpSampling2D layer
  tensorflow/python/keras/layers/convolutional.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#30364 [ROCm] Addding ROCm support for pooling ops...part two
  tensorflow/core/kernels/pooling_ops_common.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#27863 Log failure reason in org.tensorflow.TensorFlow.init()
  tensorflow/java/src/main/java/org/tensorflow/TensorFlow.java
Labels: awaiting review, cla: yes, java, ready to pull, size:XS

#30452 Update kissfft to fix stdint.h issue on Windows
  third_party/kissfft/workspace.bzl
Labels: cla: yes, ready to pull, size:XS

#30255 Use environment markers for enum34
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:XS

#30414 [Lite] num_ranks option brings to user through cmd line parameter
  tensorflow/lite/tools/accuracy/ilsvrc/README.md
  tensorflow/lite/tools/accuracy/ilsvrc/imagenet_model_evaluator.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30538 [R1.14] Use environment markers for enum34
  tensorflow/tools/pip_package/setup.py
Labels: size:XS

#30508 add test value of test_default_value_saved_as_tuple and test_dtype_should_be_string_or_integer
  tensorflow/python/feature_column/feature_column_v2_test.py
Labels: cla: yes, ready to pull, size:S

#30541 Add pip_new.sh as our release scripts now use it.
  tensorflow/tools/ci_build/builds/pip_new.sh
Labels: cla: yes, size:L

#30504 [ROCm] Skipping subtests that check support for NAN propagation in the NN ops
  tensorflow/python/kernel_tests/pooling_ops_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30506 [ROCm] Skipping subtests that check bit pattern result from zero division
  tensorflow/python/kernel_tests/zero_division_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#30496 [ROCm] Skipping subtests that check GPU stream tracing/profiling.
  tensorflow/python/client/timeline_test.py
  tensorflow/python/profiler/internal/run_metadata_test.py
  tensorflow/python/profiler/profile_context_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30497 [ROCm] Skipping subtests that check support for the Cholesky and QR ops
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/ops/control_flow_ops_test.py
  tensorflow/python/ops/init_ops_test.py
  tensorflow/python/ops/init_ops_v2_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30505 [ROCm] Skipping subtests that check support for int8x4 type (on the GPU)
  tensorflow/python/kernel_tests/relu_op_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#30279 Fix macos makefile build
  tensorflow/contrib/makefile/Makefile
Labels: cla: yes, ready to pull, size:XS

#30502 [ROCm] Skipping subtests that check support for Pooling Ops with 3D tensors
  tensorflow/python/eager/backprop_test.py
  tensorflow/python/keras/backend_test.py
  tensorflow/python/keras/layers/pooling_test.py
  tensorflow/python/kernel_tests/pool_test.py
  tensorflow/python/ops/nn_test.py
  tensorflow/python/ops/parallel_for/control_flow_ops_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30288 Intel MKL : Fixed variable initialization, pass Clockworks and fixed Clang format
  tensorflow/core/kernels/mkl_concat_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#30294 [Intel MKL] Fix klockworks issue
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#30543 Fix the related docs for MatchingFilesOp
  tensorflow/core/api_def/base_api/api_def_MatchingFiles.pbtxt
  tensorflow/go/op/wrappers.go
  tensorflow/python/training/input.py
Labels: cla: yes, comp:data, ready to pull, size:XS

#29935 Correction in keras.layers.Reshape
  tensorflow/python/keras/layers/core.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#30379 [XLA:GPU][ROCm] Register ROCm platform on XLA computation placer
  tensorflow/compiler/xla/service/computation_placer.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#30193 Fix URL in docstring
  tensorflow/python/platform/test.py
Labels: cla: yes, ready to pull, size:XS

#30428 Add missing closing paren in keras optimizer_v2 docs
  tensorflow/python/keras/optimizer_v2/optimizer_v2.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#30544 Bring release notes from recent releases back into master
  RELEASE.md
Labels: cla: yes, ready to pull, size:M

#30325 Consider integer division/remainder by constant scalar as cheap.
  tensorflow/compiler/xla/service/gpu/BUILD
  tensorflow/compiler/xla/service/gpu/instruction_fusion.cc
  tensorflow/compiler/xla/service/gpu/instruction_fusion_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:M

#30569 Fix #30526: raise `ValueError` when using modular arithmetic with negative integers and `Dimension`
  tensorflow/python/framework/tensor_shape.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30559 Fix numpy warning with numpy 1.17.0+
  tensorflow/python/framework/dtypes.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#29925 [ROCm] Adding ROCm support for resource_variable_ops
  tensorflow/core/kernels/resource_variable_ops.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30573 Disable a bunch of tests to unblock patch release
  tensorflow/contrib/bayesflow/BUILD
  tensorflow/contrib/boosted_trees/BUILD
  tensorflow/contrib/boosted_trees/estimator_batch/BUILD
  tensorflow/contrib/compiler/BUILD
  tensorflow/examples/adding_an_op/BUILD
  tensorflow/python/BUILD
  tensorflow/python/data/experimental/kernel_tests/BUILD
  tensorflow/python/eager/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/distributions/BUILD
  tensorflow/python/tools/BUILD
  tensorflow/python/training/checkpointable/BUILD
Labels: cla: yes, size:S

#30582 Run buildifier on files from #30573
  tensorflow/contrib/boosted_trees/BUILD
  tensorflow/examples/adding_an_op/BUILD
Labels: cla: yes, size:XS

#30583 Changes to build files for patch release
  tensorflow/tools/ci_build/Dockerfile.debian.jessie.cpu
  tensorflow/tools/ci_build/ci_parameterized_build.sh
  tensorflow/tools/ci_build/ci_sanity.sh
  tensorflow/tools/pip_package/check_load_py_test.py
  tensorflow/tools/pip_package/pip_smoke_test.py
Labels: cla: yes, size:S

#30584 Disable some more tests before patch release
  tensorflow/examples/adding_an_op/BUILD
  tensorflow/examples/speech_commands/BUILD
  tensorflow/tools/common/BUILD
  tensorflow/tools/docs/BUILD
Labels: cla: yes, size:S

#30470 Fix eager session testing with GC
  tensorflow/java/src/main/java/org/tensorflow/EagerSession.java
  tensorflow/java/src/test/java/org/tensorflow/EagerSessionTest.java
Labels: cla: yes, ready to pull, size:M

#30377 [XLA:GPU][ROCm] Emit llvm::Intrinsic::nvvm_atomic_load_add_f32 only on NVPTX
  tensorflow/compiler/xla/service/gpu/ir_emitter.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#30101 Tf-TRT minor test fixes
  tensorflow/python/compiler/tensorrt/test/const_broadcast_test.py
  tensorflow/python/compiler/tensorrt/test/quantization_mnist_test.py
Labels: cla: yes, comp:gpu, size:S

#30578 [ROCm] Adding ROCm support for the bias op
  tensorflow/core/kernels/bias_op.cc
  tensorflow/core/kernels/bias_op_gpu.cu.cc
Labels: cla: yes, comp:gpu, ready to pull, size:M

#30570 [INTEL MKL] Fixed quantized matmul unit test.
  tensorflow/core/kernels/mkl_qmatmul_op_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#30568 fixed data type inconsistency for tf.keras.datasets.cifar10.load_data
  tensorflow/python/keras/datasets/cifar10.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#30338 [LITE]BugFix non-string type causes memleak for two outputs
  tensorflow/lite/models/smartreply/ops/extract_feature.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30607 Little fix in docstring for DynamicRnnEstimator
  tensorflow/contrib/learn/python/learn/estimators/dynamic_rnn_estimator.py
Labels: cla: yes, ready to pull, size:XS

#30626 Remove `set -ex` on `ci_sanity.sh`
  tensorflow/tools/ci_build/ci_sanity.sh
Labels: cla: yes, size:XS

#30628 Fix linker error
  tensorflow/compiler/jit/xla_compilation_cache.cc
Labels: cla: yes, size:XS

#30627 Fix visibility of a few targets
  tensorflow/BUILD
  tensorflow/python/BUILD
  tensorflow/tools/api/golden/BUILD
  tensorflow/tools/api/lib/BUILD
  tensorflow/tools/common/BUILD
Labels: cla: yes, size:S

#30588 [mlir] fix two trivial typos in comments
  tensorflow/compiler/mlir/lite/transforms/prepare_quantize.cc
Labels: cla: yes, ready to pull, size:XS

#30058 Correct the size of downsampledFrame
  tensorflow/examples/android/src/org/tensorflow/demo/tracking/ObjectTracker.java
Labels: cla: yes, ready to pull, size:XS

#30519 Fix linking error of CoreFoundation for iOS
  tensorflow/contrib/makefile/Makefile
Labels: cla: yes, ready to pull, size:XS

#30651 Add one more flag for Bazel compatibility.
  tensorflow/tools/ci_build/ci_sanity.sh
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
  tensorflow/tools/pip_package/check_load_py_test.py
  tensorflow/tools/pip_package/pip_smoke_test.py
Labels: cla: yes, size:S

#29333 [TF 2.0 API Docs] tf.image.adjust_saturation
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30654 [mlir] enable Affine Dialect in tf-opt
  tensorflow/compiler/mlir/BUILD
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#30106 Fix math type setting in CudnnConvolutionDescriptor
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes, comp:gpu, kokoro:force-run, ready to pull, size:M

#30656 Fix incorrect get_link_flags on Mac
  tensorflow/python/platform/sysconfig.py
Labels: cla: yes, ready to pull, size:XS

#30522 [MICRO] Fix for custom operator
  tensorflow/lite/experimental/micro/micro_mutable_op_resolver.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#29322 [TF 2.0 API Docs] tf.image.adjust_contrast
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, ready to pull, size:XS

#30677 Remove additional bazel flags in pip_smoke_test
  tensorflow/tools/pip_package/pip_smoke_test.py
Labels: cla: yes, size:S

#30662 [R1.14] Fix incorrect get_link_flags on Mac
  tensorflow/python/platform/sysconfig.py
Labels: cla: yes, size:XS

#30688 Disable some tests in tools/
  tensorflow/compiler/tests/BUILD
  tensorflow/python/BUILD
  tensorflow/python/eager/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/tools/compatibility/BUILD
  tensorflow/tools/dist_test/scripts/BUILD
Labels: cla: yes, size:S

#30709 Final fixes for the patch release
  tensorflow/python/tools/api/generator/api_gen.bzl
  tensorflow/tools/dist_test/scripts/BUILD
  tensorflow/tools/pip_package/pip_smoke_test.py
Labels: cla: yes, size:S

#30696 [Intel MKL] Fix UT failure of 'NodeRewrite_BiasAddGrad_Positive1'.
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#30668 [INTEL MKL] Reverting a change from an earlier commit.
  tensorflow/core/kernels/mkl_pooling_ops_common.h
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#30516 [Intel MKL] Fix 4 autograph unit test failures (Intel MKL public ci: …
  tensorflow/tools/ci_build/linux/cpu/run_mkl.sh
  tensorflow/tools/ci_build/linux/cpu/run_py2_core.sh
Labels: cla: yes, ready to pull, size:XS

#30719 Use "numpy >= 1.16.0, < 2.0" to fix #25636
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#30720 Use "numpy >= 1.16.0, < 2.0" to fix #25636
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#30386 [INTEL MKL] Enabling MKL support for FusedBatchNormV3
  tensorflow/core/graph/mkl_layout_pass.cc
  tensorflow/core/graph/mkl_layout_pass_test.cc
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
  tensorflow/core/ops/mkl_nn_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:L

#30718 Use "numpy >= 1.16.0, < 2.0" to fix #25636
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:XS

#30603 release TF Java 1.14.0 (except tensorflow-android)
  tensorflow/java/maven/libtensorflow/pom.xml
  tensorflow/java/maven/libtensorflow_jni/pom.xml
  tensorflow/java/maven/libtensorflow_jni_gpu/pom.xml
  tensorflow/java/maven/pom.xml
  tensorflow/java/maven/proto/pom.xml
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
  tensorflow/java/maven/tensorflow-hadoop/pom.xml
  tensorflow/java/maven/tensorflow/pom.xml
Labels: cla: yes, java, ready to pull, size:S

#30663 Fix incorrect example in tf.data.Dataset.window
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, ready to pull, size:XS

#30613 [ROCm] Re-enabling ROCm support for the average pooling op
  tensorflow/core/kernels/avgpooling_op.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30614 [ROCm] Adding ROCm support for the einsum op
  tensorflow/core/kernels/einsum_op.cc
  tensorflow/core/kernels/einsum_op.h
  tensorflow/core/kernels/einsum_op_gpu.cu.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30618 [ROCm] Adding ROCm support for the stateful_random ops
  tensorflow/core/kernels/stateful_random_ops_cpu_gpu.h
  tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc
  tensorflow/core/lib/random/philox_random.h
Labels: cla: yes, comp:gpu, ready to pull, size:S

#30683 Corrected rendering for docs in tf.Print
  tensorflow/python/ops/logging_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30681 Spellcheck @CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:XS

#30669 [INTEL MKL] Fix to the unit test "print_selective_registration_header_test"
  tensorflow/python/tools/print_selective_registration_header_test.py
Labels: cla: yes, ready to pull, size:XS

#29224 Fast 3DY reduction when the middle dim Y is large but X and Z are small
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
Labels: cla: yes, core, ready to pull, size:M

#29939 lite: fix buffer overrun of "std::vector<int> sorted_indices".
  tensorflow/lite/kernels/detection_postprocess.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30760 Remove use_resource from v2 Variable doc
  tensorflow/python/ops/variables.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30817 Add default eager session
  tensorflow/java/src/gen/java/org/tensorflow/processor/OperatorProcessor.java
  tensorflow/java/src/main/java/org/tensorflow/EagerSession.java
  tensorflow/java/src/test/java/org/tensorflow/EagerSessionTest.java
Labels: cla: no, size:M

#30819 Update release notes for TensorFlow 1.14.1
  RELEASE.md
Labels: cla: yes, size:XS

#30821 Update version numbers for TensorFlow 1.14.1
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#30692 Extending documentation for tf.data.Dataset.map()
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, ready to pull, size:S

#30765 Add the missing comma
  tensorflow/python/ops/parallel_for/pfor.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#30823 [ROCm] Fix for the broken `--config=rocm` build
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
Labels: cla: yes, kokoro:force-run, ready to pull, size:S

#30824 Remove dead link.
  tensorflow/contrib/graph_editor/__init__.py
Labels: cla: yes, ready to pull, size:XS

#30500 [ROCm] Skipping subtests that check support for float64 type in the NN ops
  tensorflow/python/kernel_tests/conv1d_test.py
  tensorflow/python/kernel_tests/conv_ops_3d_test.py
  tensorflow/python/kernel_tests/conv_ops_test.py
  tensorflow/python/kernel_tests/depthwise_conv_op_test.py
  tensorflow/python/kernel_tests/pooling_ops_test.py
  tensorflow/python/ops/nn_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:M

#30724 Fix MPI configuration
  configure.py
Labels: cla: yes, ready to pull, size:XS

#29440 add allow_pickle for reuters
  tensorflow/python/keras/datasets/reuters.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#30860 Copy cluster_def from TPUClusterResolver to session config
  tensorflow/python/tpu/tpu_strategy_util.py
Labels: cla: yes, size:XS

#30859 Allow Metric objects to be called with DistributionStrategy.
  tensorflow/python/keras/distribute/distribute_strategy_test.py
  tensorflow/python/keras/distribute/distributed_training_utils.py
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/base_layer_utils.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/metrics.py
Labels: cla: yes, size:M

#30805 Make the output format the same as printf above line.
  tensorflow/core/common_runtime/placer.cc
Labels: cla: yes, ready to pull, size:XS

#30761 Phase 1 of XLA int8 convolution on CUDA.
  tensorflow/compiler/xla/service/hlo_evaluator_typed_visitor.h
  tensorflow/compiler/xla/service/hlo_verifier.cc
Labels: cla: yes, comp:xla, size:M

#29981 Added support to CUDNN Rnn V2 in Keras APIs
  tensorflow/python/keras/layers/cudnn_recurrent.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#30733 [Intel MKL] Fixing static scan issue in mkl_layout_pass.cc
  tensorflow/core/graph/mkl_layout_pass.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#30931 [INTEL MKL] Build failure fix for MKL-DNN v1.x
  third_party/mkl_dnn/mkldnn.BUILD
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#30940 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:XS

#30890 Fix for unit test failure
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#30933 Fix large (>4GB) files reading on windows
  tensorflow/core/platform/windows/windows_file_system.cc
Labels: cla: yes, ready to pull, size:XS

#30920 Update metric_ops.py for incorrect docstring
  tensorflow/contrib/metrics/python/ops/metric_ops.py
Labels: cla: yes, ready to pull, size:XS

#29880 Reuse DeviceNameUtils::LocalName
  tensorflow/core/distributed_runtime/BUILD
  tensorflow/core/distributed_runtime/remote_device.cc
Labels: cla: yes, ready to pull, size:S

#30902 Format tf.function's error message when input and signature does not match
  tensorflow/python/eager/function.py
Labels: cla: yes, comp:eager, ready to pull, size:S

#29320 [TF 2.0 API Docs] tf.image.adjust_brightness
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:XS

#30941 Update 1.14 behavioral changes to mention...
  RELEASE.md
Labels: cla: yes, ready to pull, size:XS, type:docs

#30510 Validate max_batch_size only in static mode
  tensorflow/compiler/tf2tensorrt/convert/trt_optimization_pass.cc
Labels: cla: yes, ready to pull, size:S

#30962 [INTEL_MKL] Updated the test analyzer_cli_test.py to be compatible with recent changes in the graph rewrite logic for MKL-DNN support, which changes the name of and attributes of some ops, such as MatMul. etc.
  tensorflow/python/debug/cli/analyzer_cli_test.py
Labels: cla: yes, comp:mkl, ready to pull, size:M

#31002 Add support for TensorRT precision mode in lowercase
  tensorflow/python/compiler/tensorrt/trt_convert.py
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#30911 tensorflow-gpu without nvidia-runtime.
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/devel-nvidia.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile
Labels: cla: yes, ready to pull, size:M

#30648 Improving the documentation of learning_rate_scheduler.py
  tensorflow/python/keras/optimizer_v2/learning_rate_schedule.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#30258 Fix KeyError when validation_data was given as a dict
  tensorflow/python/keras/engine/training_arrays.py
  tensorflow/python/keras/engine/training_arrays_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#30853 Update README.md - specify Arduino IDE version
  tensorflow/lite/experimental/micro/examples/hello_world/README.md
Labels: cla: yes, comp:lite, ready to pull, size:S

#30987 Delete the parameter allow_soft_placement in function AssignDevice
  tensorflow/core/common_runtime/colocation_graph.cc
  tensorflow/core/common_runtime/colocation_graph.h
Labels: cla: yes, comp:runtime, ready to pull, size:XS

#31041 1.14 cherrypicks to fix the regression of TF-TRT precision_mode regression
  tensorflow/python/compiler/tensorrt/trt_convert.py
Labels: cla: yes, size:XS

#30463 Update loss docstrings to match behavior.
  tensorflow/python/keras/losses.py
  tensorflow/python/ops/losses/loss_reduction.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#29331 [TF 2.0 API Docs] tf.image.adjust_jpeg_quality
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#30923 [tflite] fix a typo in evaluation tool doc
  tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/README.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30997 Do not force NHWC->NCHW conversion in backward pooling kernels
  tensorflow/core/kernels/pooling_ops_common.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#31079 Simplify code for TensorListConcatLists shape inference
  tensorflow/core/ops/list_ops.cc
Labels: cla: yes, comp:ops, ready to pull, size:S

#31037 Fix incorrect usage of execution plan in GPU delegate
  tensorflow/lite/delegates/gpu/common/model_builder.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#31080 Avoid potential undefined behavior
  tensorflow/core/profiler/internal/tfprof_stats.cc
Labels: cla: yes, ready to pull, size:XS

#31078 Avoid return without freeing a pointer
  tensorflow/c/c_api_experimental.cc
  tensorflow/c/eager/c_api.cc
  tensorflow/core/kernels/stack.cc
  tensorflow/core/profiler/internal/tfprof_code.cc
  tensorflow/lite/toco/import_tensorflow.cc
Labels: cla: yes, ready to pull, size:M

#31133 [ROCm] Fix for the broken `--config=rocm` build
  tensorflow/core/kernels/pooling_ops_common.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#31076 Fix unique_ptr type
  tensorflow/contrib/ignite/kernels/dataset/ignite_dataset_iterator.cc
  tensorflow/contrib/ignite/kernels/dataset/ignite_dataset_iterator.h
Labels: cla: yes, comp:data, ready to pull, size:XS
