Repository tensorflow/tensorflow, pull requests merged in 2019-04, with the labels that each got.

#27359 [INTEL MKL] Revert changes in mkl_concat_op.
  tensorflow/core/kernels/mkl_concat_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#27239 Documentation for tf.bitcast
  tensorflow/core/api_def/base_api/api_def_Bitcast.pbtxt
Labels: cla: yes, comp:apis, ready to pull, size:S

#24366 Remove bazel installation from install_pi_toolchain.sh
  tensorflow/tools/ci_build/install/install_pi_python3_toolchain.sh
  tensorflow/tools/ci_build/install/install_pi_toolchain.sh
Labels: cla: yes, ready to pull, size:S

#25141 RELEASE.md typos
  RELEASE.md
Labels: cla: yes, ready to pull, size:S

#27372 TF Lite zeros_like_test death test case added
  tensorflow/lite/kernels/zeros_like_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#27387 remove the dequantize op test until the op is enabled
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:ops, ready to pull, size:S

#27371 TfLite unpack_test test case refactor
  tensorflow/lite/kernels/unpack_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#27388 [Intel MKL] Fixing Windows build with MKL-DNN support
  tensorflow/core/kernels/mkl_conv_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#27397 Shrink README.md logo
  README.md
Labels: cla: yes, ready to pull, size:XS

#27424 Api doc updated for BatchToSpaceND
  tensorflow/core/api_def/base_api/api_def_BatchToSpaceND.pbtxt
Labels: cla: yes, comp:apis, ready to pull, size:XS

#27370 TfLite tile_test test case refactor
  tensorflow/lite/kernels/tile_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#27006 Removed references to _ref types in documentation.
  tensorflow/python/framework/dtypes.py
Labels: cla: yes, ready to pull, size:XS

#26181 [TF Java] Adds support for adding control inputs via Ops API
  tensorflow/java/src/gen/cc/op_generator.cc
  tensorflow/java/src/gen/java/org/tensorflow/processor/OperatorProcessor.java
  tensorflow/java/src/main/java/org/tensorflow/op/Scope.java
  tensorflow/java/src/test/java/org/tensorflow/op/core/GeneratedOperationsTest.java
Labels: cla: yes, ready to pull, size:M

#27399 Pull support for latest Bazel version
  configure.py
Labels: cla: yes, ready to pull, size:XS

#24767 Enhanced Operator overriding Eager testcase
  tensorflow/python/eager/ops_test.py
Labels: cla: yes, ready to pull, size:S

#27407 Added different activation types, bias, padding
  tensorflow/lite/kernels/conv_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#27293 Documentation for tf.math.add_n
  tensorflow/python/ops/math_ops.py
Labels: cla: yes, ready to pull, size:S

#27243 TF Lite added missing axis test cases for ArgMinMax
  tensorflow/lite/kernels/arg_min_max.cc
  tensorflow/lite/kernels/arg_min_max_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#27391 Tests for InterleaveDatasetOp
  tensorflow/core/kernels/data/BUILD
  tensorflow/core/kernels/data/interleave_dataset_op_test.cc
Labels: cla: yes, comp:data, ready to pull, size:L

#27358 Fix an overflow issue in bfc_allocator.
  tensorflow/core/common_runtime/bfc_allocator.h
Labels: cla: yes, ready to pull, size:XS

#27481 Fixed a Typo
  tensorflow/tools/docs/generate2.py
Labels: cla: yes, ready to pull, size:XS

#27513 Fix doc in Makefile of lite
  tensorflow/lite/tools/make/Makefile
Labels: cla: yes, comp:lite, ready to pull, size:XS

#27514 Fix typo in generated temporary placeholder name
  tensorflow/python/eager/lift_to_graph.py
Labels: cla: yes, ready to pull, size:XS

#27522 [Intel MKL] Graph Transform tool fold_old_batchnorms biasadd node bug
  tensorflow/tools/graph_transforms/fold_old_batch_norms.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#27515 Fix configure.py to properly compare "X.Y.Z" with "X.Y"
  configure.py
Labels: 2.0, cla: yes, size:XS

#27213 Add fp32 accumulation for depthwise convolutions
  tensorflow/core/kernels/depthwise_conv_op_gpu.h
Labels: cla: yes, comp:ops, ready to pull, size:S

#27396 [Intel MKL] BatchMatMulV2 op support
  tensorflow/core/kernels/mkl_batch_matmul_op.cc
Labels: cla: yes, comp:ops, ready to pull, size:S

#25774 Update license year
  LICENSE
Labels: cla: yes, ready to pull, size:XS

#27550 Fixing capitalization of PyPi.
  README.md
Labels: cla: yes, ready to pull, size:XS

#27011 Add missing args in description for LSTM and GRU
  tensorflow/python/keras/layers/recurrent.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#26822 Provides example for tf.argsort and tf.sort
  tensorflow/python/ops/sort_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#26641 Added the TCs for CopyFromBufferHandle scenario.
  tensorflow/lite/interpreter_test.cc
Labels: cla: yes, ready to pull, size:M

#27493 Add tensorflow_framework to data of tf_cc_shared_object
  tensorflow/tensorflow.bzl
  tensorflow/tools/lib_package/BUILD
Labels: cla: yes, ready to pull, size:XS

#26993 remove sentence about usage of rmsprop for RNN
  tensorflow/python/keras/optimizers.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#27506 Lite: Compare Op bug fix
  tensorflow/lite/kernels/comparisons.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#26977 Added Testcase to cover shift scenario.
  tensorflow/lite/kernels/kernel_util_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#27564 Correct doc of Ftrl optimizer by remplacing $ to $$
  tensorflow/python/compat/compat.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#27595 Fix typo in python/keras
  tensorflow/python/keras/layers/core.py
  tensorflow/python/keras/layers/serialization.py
  tensorflow/python/keras/optimizer_v2/nadam.py
  tensorflow/python/keras/utils/tf_utils.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#26972 Lite: Fully_connected Op bug-fix
  tensorflow/lite/kernels/fully_connected.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#27555 Updated doc for py_function
  tensorflow/python/ops/script_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#27580 Updated doc with code formatting for SparseConditionalAccumulator
  tensorflow/python/ops/data_flow_ops.py
Labels: cla: yes, comp:ops, ready to pull, type:docs

#25840 Fixed invalid link in model_pruning readme
  tensorflow/contrib/model_pruning/README.md
Labels: cla: yes, ready to pull, size:XS

#27567 Update docs for create_local_cluster
  tensorflow/python/framework/test_util.py
Labels: cla: yes, ready to pull, size:S

#27587 Clickable link edit in documentation.
  tensorflow/python/keras/metrics.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#27578 Updated with code formatting for endpoints.
  tensorflow/python/ops/ctc_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#27590 Spelling fix for KL Divergence
  tensorflow/python/keras/metrics.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#27110 Lite: Range Op small refactor
  tensorflow/lite/kernels/range.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#27659 Fix Typo
  tensorflow/stream_executor/platform/default/dso_loader.cc
Labels: cla: yes, ready to pull, type:docs

#27554 Fixing a bug in tf.parallel_stack
  tensorflow/core/common_runtime/parallel_concat_optimizer.cc
  tensorflow/python/kernel_tests/stack_op_test.py
Labels: cla: yes, comp:grappler, ready to pull, size:S

#27645 Fix symlinks in lib_package
  tensorflow/tensorflow.bzl
  tensorflow/tools/lib_package/BUILD
Labels: cla: yes, prtype:bugfix, ready to pull, size:S, subtype:bazel

#27658 Removed redundant ticks to render properly (DOCS)
  tensorflow/python/keras/losses.py
Labels: cla: yes, ready to pull, size:XS, type:docs

#27569 Update docs for compute_gradient
  tensorflow/python/ops/gradient_checker_v2.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#27558 Added Oxford comma in README.md
  README.md
Labels: cla: yes, ready to pull, type:docs

#27636 Fix `cmake` build error in Android example
  tensorflow/examples/android/build.gradle
Labels: cla: yes, ready to pull, size:XS, type:build/install

#27333 Updated subgraph.cc
  tensorflow/lite/core/subgraph.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#27412 [XLA] Reduce the logging level for two utilities
  tensorflow/compiler/xla/service/call_graph.cc
  tensorflow/compiler/xla/service/hlo_parser.cc
Labels: cla: yes, comp:xla, ready to pull, size:S

#27299 TFTRT: Allow reshape from weights to constant scalar tensors
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#27702 fix typo
  tensorflow/compiler/jit/xla_device.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#26986 Replace deprecated usage of np.asscalar with np.ndarray.item()
  tensorflow/python/eager/tensor_test.py
Labels: cla: yes, comp:eager, ready to pull, size:XS

#27677 fix typo in comment
  tensorflow/python/ops/data_flow_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#27694 pip_package: Remove duplicated libtensorflow_framework.so
  tensorflow/python/platform/sysconfig.py
  tensorflow/tools/pip_package/MANIFEST.in
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: cla: yes, ready to pull, size:XS, type:build/install

#27369 TfLite floor_mod.cc compilation warning fix
  tensorflow/lite/kernels/internal/reference/reference_ops.h
Labels: cla: yes, comp:lite, ready to pull, size:XS

#27727 Disable 3 tests which fail on tf 1.12.1.
  tensorflow/contrib/constrained_optimization/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/distributions/BUILD
Labels: cla: yes

#27722 Edit source as clickable link
  tensorflow/python/ops/nn_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#27717 Fix link to TF-TRT docs
  tensorflow/compiler/tf2tensorrt/segment/segment.cc
Labels: cla: yes, comp:runtime, ready to pull, size:XS

#27721 Title of paper as clickable link
  tensorflow/python/ops/nn_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#27737 Disable one more macos test for python35
  tensorflow/python/keras/BUILD
Labels: cla: yes

#27678 Moved pooling reference ops into its own file
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/reference/pooling.h
  tensorflow/lite/kernels/internal/reference/reference_ops.h
Labels: cla: yes, comp:lite, ready to pull, size:L

#27755 Disable one more flaky test
  tensorflow/python/BUILD
Labels: cla: yes

#27588 Updated docs formatting
  tensorflow/python/feature_column/feature_column_v2.py
Labels: cla: yes, ready to pull, size:XS

#27740 Add trailing $$
  tensorflow/python/keras/optimizer_v2/rmsprop.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#27736 fix indent for python formatting
  tensorflow/python/keras/engine/input_layer.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#27751 Api doc updated
  tensorflow/core/api_def/base_api/api_def_BatchToSpace.pbtxt
  tensorflow/core/api_def/base_api/api_def_SpaceToBatch.pbtxt
  tensorflow/core/api_def/base_api/api_def_SpaceToBatchND.pbtxt
Labels: cla: yes, comp:apis, ready to pull, size:S

#27733 Remove numerics check from clip_by_global_norm
  tensorflow/python/kernel_tests/clip_ops_test.py
  tensorflow/python/ops/clip_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#27624 CleanUp & TC added for L2_pool Graph transformation.
  tensorflow/lite/toco/graph_transformations/identify_l2_pool.cc
  tensorflow/lite/toco/graph_transformations/tests/BUILD
  tensorflow/lite/toco/graph_transformations/tests/identify_l2_pool_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#27793 Temporarily add debug options on bazel build
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes

#27797 Display bazel log file on trapped cleanup.
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes

#27734 Update README.md
  tensorflow/contrib/slim/README.md
Labels: cla: yes, ready to pull, size:XS

#27779 [doc/keras] incorrect comment in `__init__` of `tf.keras.layers.AveragePooling1D`
  tensorflow/python/keras/layers/pooling.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#27798 lib_package: fix dylib symlinks on mac
  tensorflow/tools/lib_package/BUILD
Labels: cla: yes, ready to pull, size:S, subtype:bazel

#27775 add back-ticks for formatting
  tensorflow/python/ops/sparse_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#27818 Fixing small typo in comment
  tensorflow/python/distribute/estimator_training.py
Labels: cla: yes, comp:tpus, ready to pull, type:docs

#27801 Remove the debug changes
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes, size:XS

#27870 Add --incompatible_remove_native_http_archive=false to windows bazel calls
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes

#24010 Make var loading logging messages debug from info
  tensorflow/python/training/warm_starting_util.py
Labels: cla: yes, ready to pull, size:XS

#27865 sysconfig: fix library name on macos
  tensorflow/python/platform/sysconfig.py
Labels: cla: yes, ready to pull, size:XS

#27767 Make link clickable
  tensorflow/python/ops/signal/dct_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#27873 Add --incompatible_disable_cc_toolchain_label_from_crosstool_proto
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes

#27869 [Intel MKL] Disabling MatMul fusions in grappler for MKL backend
  tensorflow/core/grappler/optimizers/remapper.cc
Labels: cla: yes, core, ready to pull, size:S

#27812 Update links to correct example projects
  tensorflow/lite/g3doc/models/object_detection/overview.md
Labels: cla: yes, ready to pull, size:XS, type:docs

#27878 Fix windows build for CPU too
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
Labels: cla: yes

#27774 reduce indent to display as regular text
  tensorflow/python/ops/init_ops_v2.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#27072 preserve collections after converting graph to a tensorrt-optimized one
  tensorflow/python/compiler/tensorrt/trt_convert.py
Labels: cla: yes, ready to pull, size:M

#27919 Fixed rendering errors in tf.GradientTape docs
  tensorflow/python/eager/backprop.py
Labels: cla: yes, comp:eager, ready to pull, size:XS

#27958 Update version to 1.12.2
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#27959 Update header on release notes
  RELEASE.md
Labels: cla: yes

#27901 Fix typo in tensorrt_include
  third_party/tensorrt/tensorrt_configure.bzl
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#27950 Update docstrings in `configure.py`
  configure.py
Labels: cla: yes, ready to pull, size:S

#27922 Use tf_logging instead of print in lazy_loader.py
  tensorflow/python/util/lazy_loader.py
Labels: cla: yes, ready to pull, size:XS

#27933 Dataset doc updated
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, ready to pull, size:M

#25035 Allow tf.contrib.tpu._prepare_validation_data to modify x,y
  tensorflow/contrib/tpu/python/tpu/keras_support.py
Labels: cla: yes, ready to pull, size:XS

#27963 Add release notes for 1.12.2 to the master branch
  RELEASE.md
Labels: cla: yes, ready to pull, size:XS

#27251 Update tf.math.logical_xor
  tensorflow/python/ops/math_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#25986 Update version script for support TF 2.0
  .github/ISSUE_TEMPLATE/00-bug-performance-issue.md
Labels: cla: yes, ready to pull

#27960 Adding exception handling code to tf.Dimension methods
  tensorflow/python/framework/tensor_shape.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#26775 [ROCm] Update interfaces within port.h
  tensorflow/core/util/port.cc
  tensorflow/core/util/port.h
  tensorflow/python/framework/test_util.py
  tensorflow/python/kernel_tests/conv_ops_3d_test.py
  tensorflow/python/kernel_tests/conv_ops_test.py
  tensorflow/python/kernel_tests/matmul_op_test.py
  tensorflow/python/kernel_tests/pooling_ops_test.py
  tensorflow/python/util/port.i
Labels: cla: yes, ready to pull, size:S

#27221 Fix build with bazel master when using explicit repository name
  tensorflow/cc/framework/cc_op_gen.cc
Labels: cla: yes, ready to pull, size:S

#28048 [Intel MKL] IsMklEnabled() check in CI now works with TF 2.0
  tensorflow/tools/ci_build/linux/mkl/build-dev-container.sh
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#27566 Improve description for tf.test.is_gpu_available
  tensorflow/python/framework/test_util.py
Labels: cla: yes, ready to pull, size:XS, type:docs

#27625 Update api_def_AudioSpectrogram.pbtxt
  tensorflow/core/api_def/base_api/api_def_AudioSpectrogram.pbtxt
Labels: cla: yes, comp:apis, ready to pull, size:XS

#28034 Missing test case added for Conv2D
  tensorflow/lite/toco/tflite/operator_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#27466 Doc fix: replace `batch` with `batch_size`, and clarify wording
  tensorflow/python/keras/layers/recurrent.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#27834 Add support for line breaks in jupyter
  tensorflow/tools/compatibility/ipynb.py
Labels: cla: yes, ready to pull, size:S

#27966 Update release notes for TensorFlow 1.14.0
  RELEASE.md
Labels: cla: yes, ready to pull

#27991 Fix BatchMatMulV2 case in TFLite/Toco in 1.14 branch
  tensorflow/lite/build_def.bzl
  tensorflow/lite/testing/generate_examples_lib.py
  tensorflow/lite/toco/import_tensorflow.cc
  tensorflow/lite/toco/tflite/whitelisted_flex_ops.cc
Labels: cla: yes, ready to pull, size:M

#28056 1.14.0-rc0 cherry-pick request: Remove SparseConditionalAccumulator in 2.0.
  tensorflow/python/ops/data_flow_ops.py
  tensorflow/tools/api/golden/v2/tensorflow.sparse.-sparse-conditional-accumulator.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.sparse.pbtxt
  tensorflow/tools/compatibility/renames_v2.py
Labels: cla: yes, size:M

#28089 Update version numbers for TensorFlow 1.14.0-rc0
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/docker/Dockerfile.devel
  tensorflow/tools/docker/Dockerfile.devel-gpu
  tensorflow/tools/docker/Dockerfile.devel-mkl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:S

#28062 Adding rhel community builds to readme
  README.md
Labels: cla: yes, ready to pull, size:XS

#26722 [ROCm] Adding rocmprim as a third_party library, minor update to eigen patch
  tensorflow/core/kernels/BUILD
  tensorflow/workspace.bzl
  third_party/rocprim.BUILD
Labels: cla: yes, ready to pull, size:M

#27162 [ROCm] Support HCC based on Clang9 from ROCm2.2
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, kokoro:force-run, ready to pull, size:XS

#28097 1.14.0-rc0 cherry-pick request: Set mixed precision in ConfigProto if mixed precision is enabled.
  tensorflow/core/BUILD
  tensorflow/python/BUILD
  tensorflow/python/client/session.py
  tensorflow/python/training/experimental/mixed_precision.py
  tensorflow/python/training/experimental/mixed_precision_global_state.py
  tensorflow/python/training/experimental/mixed_precision_test.py
Labels: cla: yes, kokoro:force-run, ready to pull, size:M

#25574 Update docstrings in upgrade_schema.py
  tensorflow/lite/schema/upgrade_schema.py
Labels: cla: yes, ready to pull, size:XS

#27616 Cleanup & TC added l2_norm graph transformation.
  tensorflow/lite/toco/graph_transformations/identify_l2_normalization.cc
  tensorflow/lite/toco/graph_transformations/tests/BUILD
  tensorflow/lite/toco/graph_transformations/tests/identify_l2_normalization_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#28055 Fix error message
  tensorflow/python/util/nest.py
Labels: cla: yes, ready to pull, size:XS

#27277 Added Test cases for missing scenarios.
  tensorflow/lite/mutable_op_resolver_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#27773 set indent to display as list
  tensorflow/python/ops/sparse_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#28021 Fix build error
  third_party/gpus/cuda_configure.bzl
Labels: cla: yes, comp:gpu, size:XS

#28085 Correct out-of-date reference to Python file
  tensorflow/c/c_api_function.cc
Labels: cla: yes, ready to pull, size:XS

#28120 Pin tf-estimator-nightly to 1.14.0.dev2019042301
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:XS

#28121 1.14.0-rc0 cherry-pick request: Merge pull request #27069 from yongtang:tf.math.floordiv-floormod
  tensorflow/core/api_def/python_api/api_def_FloorDiv.pbtxt
  tensorflow/core/api_def/python_api/api_def_FloorMod.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.math.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.math.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.pbtxt
  tensorflow/tools/compatibility/renames_v2.py
Labels: cla: yes, size:S

#28123 Fix missing dependencies in pip package
  tensorflow/examples/saved_model/integration_tests/BUILD
  tensorflow/examples/speech_commands/BUILD
  tensorflow/tools/pip_package/BUILD
Labels: cla: yes, ready to pull, size:S

#28124 Exclude device_tracer for CPU build
  tensorflow/core/platform/default/build_config.bzl
Labels: cla: yes, ready to pull, size:XS

#26583 [ROCm] Enable ROCm support for "softsign_op"
  tensorflow/core/kernels/softsign_op.cc
  tensorflow/core/kernels/softsign_op_gpu.cu.cc
Labels: cla: yes, ready to pull, size:M

#28127 Add a BUILD.system file for kissfft so that the license can be used as a dependency
  third_party/kissfft/BUILD.system
  third_party/kissfft/workspace.bzl
Labels: cla: yes, ready to pull, size:S

#27995 Fix #27994: compat.as_bytes should support bytearray
  tensorflow/python/util/compat.py
Labels: cla: yes, ready to pull, size:XS, stat:awaiting response

#27134 Synced the implementation of QuantizationParams.
  tensorflow/lite/kernels/test_util.h
Labels: cla: yes, comp:lite, ready to pull, size:M

#28128 Parse visible device list from ConfigProto
  tensorflow/python/eager/context.py
  tensorflow/python/framework/config_test.py
Labels: cla: yes, ready to pull, size:S

#28119 [ROCm] Correcting license filename for rocprim
  tensorflow/tools/lib_package/BUILD
  tensorflow/tools/pip_package/BUILD
  third_party/rocprim.BUILD
Labels: cla: yes, ready to pull, size:XS

#28162 Merge pull request #28021 from avasid:master
  third_party/gpus/cuda_configure.bzl
Labels: cla: yes, size:S

#28159 Disable tests in tensorflow/examples/speech_commands for pip builds as they have a transitive dependency on kissfft (which is broken for Windows).
  tensorflow/examples/speech_commands/BUILD
  tensorflow/tools/pip_package/BUILD
  tensorflow/tools/pip_package/setup.py
  third_party/kissfft/BUILD.bazel
  third_party/systemlibs/syslibs_configure.bzl
Labels: cla: yes, size:S

#27884 Lite: Unpack Op additional memory fix
  tensorflow/lite/kernels/unpack.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#28190 Three cherrypicks
  tensorflow/contrib/summary/summary.py
  tensorflow/python/eager/context.py
  tensorflow/python/framework/config_test.py
  tensorflow/python/kernel_tests/summary_ops_test.py
  tensorflow/python/ops/summary_ops_v2.py
  tensorflow/tools/api/golden/v1/tensorflow.summary.pbtxt
  tensorflow/tools/compatibility/all_renames_v2.py
  tensorflow/tools/compatibility/renames_v2.py
  tensorflow/tools/compatibility/tf_upgrade_v2.py
  tensorflow/tools/compatibility/tf_upgrade_v2_test.py
  tensorflow/tools/pip_package/setup.py
  third_party/kissfft/BUILD.bazel
  third_party/kissfft/BUILD.system
  third_party/kissfft/workspace.bzl
  third_party/systemlibs/syslibs_configure.bzl
Labels: cla: yes, size:M

#27988 [TF-TRT] Adds asymmetric padding for Conv2D and Pool
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
Labels: cla: yes, comp:runtime, ready to pull, size:M

#28193 Use "tf-estimator-nightly" instead of "tensorflow_estimator"
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#27123 [Java] Implements EagerSession for eager execution.
  tensorflow/java/BUILD
  tensorflow/java/src/main/java/org/tensorflow/EagerSession.java
  tensorflow/java/src/main/native/BUILD
  tensorflow/java/src/main/native/eager_session_jni.cc
  tensorflow/java/src/main/native/eager_session_jni.h
  tensorflow/java/src/test/java/org/tensorflow/EagerSessionTest.java
Labels: cla: yes, comp:eager, ready to pull, size:L

#28196 Fix memory leak in gcs file cache under certain STL versions.
  tensorflow/core/platform/cloud/ram_file_block_cache.cc
Labels: cla: yes, size:S

#25511 Added missing conditions in the TC's
  tensorflow/lite/python/interpreter_test.py
Labels: cla: yes, comp:lite, ready to pull, size:S

#28160 Fix multiline magic
  tensorflow/tools/compatibility/ipynb.py
Labels: cla: yes, ready to pull, size:XS

#27738 change format of references
  tensorflow/python/keras/optimizer_v2/adam.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#24097 Fix deprecated warning of sparse_merge
  tensorflow/python/ops/sparse_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS
