Repository tensorflow/tensorflow, pull requests merged in 2019-09, with the labels that each got.

#31934 Update API docs for ParallelInterleaveDataset
  tensorflow/core/api_def/base_api/api_def_ParallelInterleaveDataset.pbtxt
Labels: cla: yes, ready to pull, size:M

#30351 Remove deprecated .where in math_grad.py
  tensorflow/python/ops/math_grad.py
Labels: awaiting review, cla: yes, comp:ops, ready to pull, size:S

#32182 [r1.15 Cherrypick] Fix use-after-free of CancellationManager in LocalRendezvousImpl.
  tensorflow/core/framework/rendezvous.cc
Labels: cla: yes, size:S

#32123 Track trackables in graph networks
  tensorflow/python/feature_column/feature_column_v2.py
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/network_test.py
  tensorflow/python/keras/engine/training.py
Labels: cla: yes, size:S

#32191 fix OSS issue with cupti tracer
  tensorflow/core/profiler/internal/gpu/cupti_tracer.cc
Labels: cla: yes, size:S

#32190 [r1.15 Cherrypick] Make writing saved_model.pb atomic so there's a way to check that a SavedModel is complete
  tensorflow/python/saved_model/save.py
Labels: cla: yes, size:L

#32094 r2.0 cherry-pick request: [Intel MKL] Upgrade MKL-DNN to 0.20.3
  tensorflow/workspace.bzl
  third_party/mkl_dnn/mkldnn.BUILD
Labels: cla: yes, size:S

#31629 Go: allow larger C array backed slices on 64 bit machines
  tensorflow/go/graph.go
  tensorflow/go/tensor.go
Labels: cla: yes, ready to pull, size:S

#32217 Make curl available on all tensorflow docker images
  tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/tensorflow-ppc64le.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/cpu.partial.Dockerfile
Labels: cla: yes, kokoro:force-run, ready to pull, size:S

#31757 Bug fix for Tensorflow Lite quantized ops tests
  tensorflow/lite/kernels/conv_test.cc
  tensorflow/lite/kernels/depthwise_conv_test.cc
  tensorflow/lite/kernels/test_util.h
Labels: cla: yes, comp:lite, kokoro:force-run, ready to pull, size:S

#31937 r2.0-Cherrypick:Makes `nest` able to flatten dictionary views (produced by dict.items…
  tensorflow/python/util/nest.py
  tensorflow/python/util/nest_test.py
  tensorflow/python/util/util.cc
  tensorflow/python/util/util.h
  tensorflow/python/util/util.i
Labels: cla: yes, size:M

#31590 [ROCm] enable nextafter op on ROCm.
  tensorflow/core/kernels/nextafter_op.cc
  tensorflow/core/kernels/nextafter_op.h
  tensorflow/core/kernels/nextafter_op_gpu.cu.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#32140 [XLA] [MLIR] Don't include CUDA when it isn't configured
  tensorflow/compiler/xla/service/BUILD
Labels: cla: yes, comp:xla, ready to pull, size:XS

#32181 [r2.0 Cherrypick] Fix use-after-free of CancellationManager in LocalRendezvousImpl.
  tensorflow/core/framework/rendezvous.cc
Labels: cla: yes, size:S

#32220 [r2.0:Cherrypick]:Fix add_metric name ordering issue.
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/engine/training_test.py
Labels: cla: yes, size:M

#32080 [r2.0:Cherrypick] Remove tensor input shape from function signature.
  tensorflow/core/common_runtime/eager/execute.cc
  tensorflow/core/common_runtime/eager/kernel_and_device.cc
  tensorflow/core/common_runtime/eager/kernel_and_device.h
  tensorflow/core/common_runtime/process_function_library_runtime.cc
  tensorflow/core/framework/function.cc
  tensorflow/core/framework/function.h
Labels: cla: yes, size:M

#32165 Include atomic headers
  tensorflow/lite/kernels/acceleration_test_util_internal.h
Labels: cla: yes, comp:lite, ready to pull, size:XS

#32189 [r2.0:Cherrypick]Negating cosine similarity loss so that value gets minimized while training without needed a wrapper function.
  tensorflow/python/keras/losses.py
  tensorflow/python/keras/losses_test.py
  tensorflow/python/keras/metrics.py
Labels: cla: yes, size:S

#32226 Support for complex valued SVD gradient backprop
  tensorflow/python/kernel_tests/svd_op_test.py
  tensorflow/python/ops/linalg_grad.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#32256 [r2.0 Cherrypick]:Make calls to `tf.function(f)()`, `tf.function(f).get_concrete_function` and `tf.function(f).get_initialization_function` thread-safe.
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/function_test.py
Labels: cla: yes, size:M

#32126 Rewrite some code segment to be more elegant and Pythonic
  tensorflow/examples/tutorials/word2vec/word2vec_basic.py
Labels: cla: yes, ready to pull, size:S

#32258 [r2.0 CherryPick]: @tf.function: Show a warning message when tracing happens too frequently
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/function.py
Labels: cla: yes, size:M

#32275 Pin Tensorboard and estimator versions to a working nightly.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32280 Fix the estimator and tb names.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32252 [r2.0-Cherrypick]NNAPI TransposeConv op takes tensor inputs from TFLite node
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
Labels: cla: yes, size:S

#32295 [r1.15 cherrypick] Remove cuda from path for windows integration build.
  tensorflow/tools/ci_build/windows/integration/gpu_pip_on_cpu/build_tf_windows.sh
Labels: cla: yes, size:S

#32160 [tf.data] Increase default buffer size to 256 MB
  tensorflow/python/data/ops/readers.py
Labels: cla: yes, ready to pull, size:XS

#32282 Add incompatible_shape_error attribute to equal op
  tensorflow/core/api_def/python_api/api_def_Equal.pbtxt
  tensorflow/core/api_def/python_api/api_def_NotEqual.pbtxt
  tensorflow/core/framework/common_shape_fns.cc
  tensorflow/core/framework/common_shape_fns.h
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/cwise_ops_common.cc
  tensorflow/core/kernels/cwise_ops_common.h
  tensorflow/core/ops/math_ops.cc
  tensorflow/core/ops/math_ops_test.cc
  tensorflow/python/eager/core_test.py
  tensorflow/python/kernel_tests/cwise_ops_binary_test.py
  tensorflow/python/kernel_tests/cwise_ops_test.py
  tensorflow/python/ops/check_ops.py
  tensorflow/python/ops/math_ops.py
  tensorflow/python/ops/parallel_for/pfor.py
  tensorflow/python/ops/variables.py
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: cla: yes, size:L

#32177 Use `patch` utility for patching sources on all platforms
  third_party/repo.bzl
Labels: cla: yes, ready to pull, size:M

#32063 MKL DNN: Fixing deprecation test for MKL DNN when OpenMP threads are set
  tensorflow/tools/api/tests/deprecation_test.py
Labels: awaiting review, cla: yes, ready to pull, size:S

#32065 Add SaveOptions object with option to whitelist op namespaces.
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/saving/save.py
  tensorflow/python/keras/saving/saved_model/save.py
  tensorflow/python/saved_model/BUILD
  tensorflow/python/saved_model/save.py
  tensorflow/python/saved_model/save_options.py
  tensorflow/python/saved_model/save_test.py
  tensorflow/tools/api/golden/v1/tensorflow.keras.-model.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.-sequential.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.experimental.-linear-model.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.experimental.-wide-deep-model.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.models.-model.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.models.-sequential.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.models.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.saved_model.-save-options.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.saved_model.experimental.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.saved_model.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.-model.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.-sequential.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.experimental.-linear-model.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.experimental.-wide-deep-model.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.models.-model.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.models.-sequential.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.models.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.saved_model.-save-options.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.saved_model.pbtxt
  tensorflow/tools/api/lib/python_object_to_proto_visitor.py
Labels: cla: yes, comp:keras, size:M

#32292 [r2.0-CherryPick]:Fix loss computation when y_true and y_pred is not same shape.
  tensorflow/python/keras/engine/training_dataset_test.py
  tensorflow/python/keras/losses.py
  tensorflow/python/keras/utils/tf_utils_test.py
  tensorflow/python/kernel_tests/confusion_matrix_test.py
  tensorflow/python/kernel_tests/losses_test.py
  tensorflow/python/ops/confusion_matrix.py
Labels: cla: yes, size:M

#32267 [r2.0 CherryPick]: [INTEL MKL] Add support for Addv2
  tensorflow/core/graph/mkl_graph_util.h
  tensorflow/core/graph/mkl_layout_pass.cc
  tensorflow/core/graph/mkl_layout_pass_test.cc
  tensorflow/core/kernels/mkl_cwise_ops_common.cc
  tensorflow/core/ops/math_ops.cc
Labels: cla: yes, size:M

#32257 [r2.0-CherryPick] Deduplicate Keras weights
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/engine/training_eager.py
  tensorflow/python/keras/engine/training_test.py
  tensorflow/python/keras/premade/wide_deep.py
  tensorflow/python/keras/saving/hdf5_format.py
  tensorflow/python/keras/utils/layer_utils.py
Labels: cla: yes, comp:keras, size:M

#32269 [r2.0-rc1 CherryPick]: Several tf.keras mixed precision API changes
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/mixed_precision/experimental/keras_test.py
  tensorflow/python/keras/mixed_precision/experimental/policy.py
  tensorflow/python/keras/mixed_precision/experimental/policy_test.py
  tensorflow/python/training/experimental/loss_scale.py
  tensorflow/python/training/experimental/loss_scale_test.py
  tensorflow/tools/api/golden/v1/tensorflow.keras.mixed_precision.experimental.-policy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.mixed_precision.experimental.-policy.pbtxt
Labels: cla: yes, size:L

#32272 [r2.0-rc1 CherryPick]: Improve Layer docstrings in regards to autocasting.
  tensorflow/python/keras/engine/base_layer.py
Labels: cla: yes, comp:keras, size:M

#32297 [r2.0 CherryPick]: Upgrading giflib to fix CVE-2019-15133
  tensorflow/opensource_only.files
  tensorflow/workspace.bzl
  third_party/gif.BUILD
  third_party/gif_fix_strtok_r.patch
Labels: cla: yes, size:M

#32184 [2.0.0-rc0 CherryPick]: Only add ModuleWrapper when lazy loading is requested or when using TF 1.x (to print deprecation warnings).
  tensorflow/api_template.__init__.py
  tensorflow/python/tools/api/generator/create_python_api.py
  tensorflow/tools/api/tests/api_compatibility_test.py
  tensorflow/tools/common/public_api.py
  tensorflow/virtual_root_template_v2.__init__.py
Labels: cla: yes, size:S

#32259 [r2.0 Cherrypick]:Implementing RFC#126: Allow Op names of the form RepoName>OpName.
  tensorflow/core/framework/graph_def_util_test.cc
  tensorflow/core/framework/node_def.proto
  tensorflow/core/framework/node_def_util.cc
  tensorflow/core/framework/node_def_util_test.cc
  tensorflow/core/framework/op_def.proto
  tensorflow/core/lib/strings/scanner.h
  tensorflow/core/lib/strings/scanner_test.cc
Labels: cla: yes, size:M

#32300 [r2.0-CherryPick]:Implementing RFC#126: Allow Op names of the form RepoName>OpName
  tensorflow/python/framework/python_op_gen_internal.cc
Labels: cla: yes, size:XS

#32251 Some XLA utility functions
  tensorflow/compiler/xla/service/gpu/gpu_fusible.cc
  tensorflow/compiler/xla/service/gpu/gpu_fusible_test.cc
  tensorflow/compiler/xla/shape_util.cc
  tensorflow/compiler/xla/shape_util.h
  tensorflow/compiler/xla/shape_util_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:L

#32301 [r2.0-CherryPick]: Adds support for generator inputs w/ varying batch sizes & shapes n t…
  tensorflow/python/keras/engine/data_adapter.py
  tensorflow/python/keras/engine/data_adapter_test.py
  tensorflow/python/keras/engine/training_generator_test.py
  tensorflow/python/keras/engine/training_utils.py
  tensorflow/python/keras/engine/training_v2.py
Labels: cla: yes, size:M

#32306 [r2.0-CherryPick]:Keras SavedModel important bug fixes and refactor
  tensorflow/python/keras/BUILD
  tensorflow/python/keras/backend.py
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/base_layer_utils.py
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/engine/sequential.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/saving/saved_model/README.md
  tensorflow/python/keras/saving/saved_model/base_serialization.py
  tensorflow/python/keras/saving/saved_model/layer_serialization.py
  tensorflow/python/keras/saving/saved_model/model_serialization.py
  tensorflow/python/keras/saving/saved_model/network_serialization.py
  tensorflow/python/keras/saving/saved_model/save.py
  tensorflow/python/keras/saving/saved_model/save_impl.py
  tensorflow/python/keras/saving/saved_model/saved_model_test.py
  tensorflow/python/keras/saving/saving_utils.py
Labels: cla: yes, size:XL

#32303 [r2.0-CherryPick]:Add tf.saved_model.Asset public symbol.
  tensorflow/examples/saved_model/integration_tests/export_simple_text_embedding.py
  tensorflow/python/compiler/tensorrt/trt_convert.py
  tensorflow/python/ops/lookup_ops.py
  tensorflow/python/saved_model/load.py
  tensorflow/python/saved_model/load_test.py
  tensorflow/python/saved_model/load_v1_in_v2.py
  tensorflow/python/saved_model/save.py
  tensorflow/python/saved_model/save_test.py
  tensorflow/python/training/tracking/tracking.py
  tensorflow/tools/api/golden/v1/tensorflow.saved_model.-asset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.saved_model.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.saved_model.-asset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.saved_model.pbtxt
Labels: cla: yes, size:M

#32332 [r1.15 Cherryick]:Install gast at known version and not the latest.
  tensorflow/tools/ci_build/builds/pip_new.sh
Labels: cla: yes, size:XS

#32334 2.0.0-rc1 cherry-pick request: Don't exclude tensorboard symbols from goldens if tensorboard pip is installed.
  tensorflow/tools/api/tests/api_compatibility_test.py
Labels: cla: yes, size:S

#32324 [r2.0 CherryPick]:Update version to 2.0.0-rc1
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32305 2.0.0-rc1 cherry-pick request: Import submodules using relative imports.
  tensorflow/BUILD
  tensorflow/api_template.__init__.py
  tensorflow/api_template_v1.__init__.py
  tensorflow/python/tools/api/generator/create_python_api.py
  tensorflow/tools/api/tests/module_test.py
Labels: cla: yes, size:M

#32339 [r2.0Cherrypick]: Install gast at known version and not the latest.
  tensorflow/tools/ci_build/builds/pip_new.sh
Labels: cla: yes, size:XS

#32362 Adding full name
  RELEASE.md
Labels: cla: yes, size:XS

#32367 [r2.0-CherryPick]: Fix segfault error in trt_convert_test
  tensorflow/python/compiler/tensorrt/trt_convert_test.py
Labels: cla: yes, size:XS

#32317 [INTEL MKL] Fixed missing copts in BUILD file.
  tensorflow/core/common_runtime/eager/BUILD
Labels: cla: yes, ready to pull, size:XS

#32325 Fix Tensorflow Lite model accuracy page link
  tensorflow/lite/g3doc/performance/post_training_quantization.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#32391 Freeze gast==0.2.2 (#32319) in setup.py requirements.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32390 Freeze gast==0.2.2 (#32319) in setup.py requirements.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32179 Corrected typo in `ones_like`
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, size:XS

#32338 [r1.15:CherryPick]:Add incompatible_shape_error attribute to equal op
  tensorflow/core/api_def/python_api/api_def_Equal.pbtxt
  tensorflow/core/api_def/python_api/api_def_NotEqual.pbtxt
  tensorflow/core/framework/common_shape_fns.cc
  tensorflow/core/framework/common_shape_fns.h
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/cwise_ops_common.cc
  tensorflow/core/kernels/cwise_ops_common.h
  tensorflow/core/ops/math_ops.cc
  tensorflow/core/ops/math_ops_test.cc
  tensorflow/python/eager/core_test.py
  tensorflow/python/kernel_tests/cwise_ops_binary_test.py
  tensorflow/python/kernel_tests/cwise_ops_test.py
  tensorflow/python/ops/check_ops.py
  tensorflow/python/ops/math_ops.py
  tensorflow/python/ops/parallel_for/pfor.py
  tensorflow/python/ops/variables.py
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: cla: yes, size:L

#32304 Update installation guide for pip consolidation.
  README.md
Labels: cla: yes, size:S

#32253 [r1.15:CherryPick]NNAPI TransposeConv op takes tensor inputs from TFLite node
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
Labels: cla: yes, size:S

#32308 Fix shape inference for default gradients of resources
  tensorflow/core/common_runtime/shape_refiner.cc
  tensorflow/python/kernel_tests/control_flow_ops_py_test.py
Labels: cla: yes, kokoro:force-run, size:S

#32342 [Intel Mkl] Move IsMklEnabled() test to new module
  tensorflow/tools/ci_build/linux/mkl/build-dev-container.sh
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#32155 Use where_v2 to silence deprecation warning
  tensorflow/python/data/util/random_seed.py
Labels: cla: yes, ready to pull, size:XS

#32431 [r2.0-CherrPick]:Add Ftrl cuda kernels.
  tensorflow/core/kernels/training_ops.cc
  tensorflow/core/kernels/training_ops_gpu.cu.cc
  tensorflow/python/keras/optimizer_v2/ftrl_test.py
Labels: cla: yes, size:M

#32433 Fix major Adamax gpu bug.
  tensorflow/core/kernels/training_ops_gpu.cu.cc
  tensorflow/python/keras/optimizer_v2/BUILD
  tensorflow/python/keras/optimizer_v2/adamax_test.py
  tensorflow/python/keras/optimizer_v2/optimizer_v2_test.py
Labels: cla: yes, size:M

#32445 [r1.15 CherryPick]: [INTEL-MKL] Use tf_opts when compiling MKL related eager files.
  tensorflow/core/common_runtime/eager/BUILD
Labels: cla: yes, size:XS

#32411 Fix simple typo: activiations -> activations
  tensorflow/compiler/mlir/lite/ir/tfl_ops.td
Labels: cla: yes, ready to pull, size:XS

#32440 [r2.0 Cherrypick]: Cherrypick `cast_to_floatx` new behavior
  tensorflow/python/keras/backend.py
  tensorflow/python/keras/backend_test.py
Labels: cla: yes, size:S

#32504 Fix performance regression issue by reusing metrics property.
  tensorflow/python/keras/callbacks.py
Labels: cla: yes, size:S

#32482 [r2.0-CherryPick]: Have LossScaleOptimizer better emulate the OptimizerV2 interface.
  tensorflow/python/keras/mixed_precision/experimental/BUILD
  tensorflow/python/keras/mixed_precision/experimental/keras_test.py
  tensorflow/python/keras/mixed_precision/experimental/loss_scale.py
  tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py
  tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer_test.py
  tensorflow/python/keras/optimizers.py
  tensorflow/tools/api/golden/v1/tensorflow.keras.mixed_precision.experimental.-loss-scale-optimizer.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.mixed_precision.experimental.-loss-scale-optimizer.pbtxt
Labels: cla: yes, size:L

#32507 2.0.0-rc2 cherry-pick request: Use relative imports only in TensorFlow.
  tensorflow/python/tools/api/generator/api_gen.bzl
  tensorflow/python/tools/api/generator/create_python_api.py
Labels: cla: yes, size:S

#32503 Pin tensorflow_estimator to 1.15.1
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32499 fix variable reference in docs
  tensorflow/core/api_def/base_api/api_def_TensorScatterAdd.pbtxt
Labels: cla: yes, ready to pull, size:XS

#32527 [r2.0-CherryPick]:Disallow comparing ObjectIdentityWrapper to others
  tensorflow/python/util/object_identity.py
  tensorflow/python/util/object_identity_test.py
Labels: cla: yes, size:S

#32513 Update release notes for tensorrt and mixed precision
  RELEASE.md
Labels: cla: yes, size:S

#32530 [r2.0:CherryPick]:Update the version to 2.0.0-rc2
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32531 Update the version to 1.15.0-rc1.
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32538 Systemlibs cherry-picks for r2.0
  tensorflow/BUILD
  tensorflow/c/generate-pc.sh
  tensorflow/workspace.bzl
  third_party/systemlibs/enum34.BUILD
  third_party/systemlibs/functools32.BUILD
  third_party/systemlibs/jsoncpp.BUILD
  third_party/systemlibs/syslibs_configure.bzl
Labels: cla: yes, size:M

#32511 [r2.0-CherryPick]:Fix bug when cloning functional models that use Tensor keyword argume…
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/models.py
  tensorflow/python/keras/models_test.py
Labels: cla: yes, size:L

#32399 [r2.0 CherryPick]: Use experimental_ref() in moving_averages
  tensorflow/python/training/moving_averages.py
Labels: cla: yes, size:S

#32526 [r1.15-CherryPick]:Disallow comparing ObjectIdentityWrapper to others
  tensorflow/python/training/moving_averages.py
  tensorflow/python/util/object_identity.py
  tensorflow/python/util/object_identity_test.py
Labels: cla: yes, size:S

#32456 Add BuiltinOperatorName message in debug log
  tensorflow/lite/optional_debug_tools.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#32559 [r2.0-CherryPick]:Split segment_reduction_ops.cc to reduce compile time.
  tensorflow/contrib/makefile/tf_op_files.txt
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/segment_reduction_ops_impl.h
  tensorflow/core/kernels/segment_reduction_ops_impl_1.cc
  tensorflow/core/kernels/segment_reduction_ops_impl_2.cc
  tensorflow/core/kernels/segment_reduction_ops_impl_3.cc
  tensorflow/core/kernels/segment_reduction_ops_impl_4.cc
  tensorflow/core/kernels/segment_reduction_ops_impl_5.cc
Labels: cla: yes, size:L

#32498 Implement test for avg. pool into TFLu - Int8
  tensorflow/lite/experimental/micro/kernels/pooling.cc
  tensorflow/lite/experimental/micro/kernels/pooling_test.cc
  tensorflow/lite/experimental/micro/tools/make/Makefile
Labels: cla: yes, comp:lite, ready to pull, size:L

#32560 Stop caching inf/nan floats
  tensorflow/python/eager/pywrap_tensor.cc
Labels: cla: yes, size:XS

#31713 Add API docs for LMDBDataset
  tensorflow/core/api_def/base_api/api_def_LMDBDataset.pbtxt
Labels: cla: yes, comp:data, ready to pull, size:S

#31993 Register flops for BatchMatMulV2
  tensorflow/python/ops/math_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:XS

#32566 [r1.15-CherryPick]: Autograph: Remove tf.autograph.experimental.set_loop_options doc
  tensorflow/python/autograph/lang/directives.py
Labels: cla: yes, size:XL

#32591 fix typo in pywrap_tfe_src.cc
  tensorflow/python/eager/pywrap_tfe_src.cc
Labels: cla: yes, comp:eager, ready to pull, size:XS

#32596 Fix support for custom op namespacing in Python
  tensorflow/cc/framework/cc_op_gen.cc
  tensorflow/core/framework/node_def_util.cc
  tensorflow/core/framework/op_def_util.cc
  tensorflow/core/framework/op_def_util_test.cc
  tensorflow/core/graph/graph_constructor.cc
  tensorflow/examples/adding_an_op/zero_out_1_test.py
  tensorflow/examples/adding_an_op/zero_out_op_1.py
  tensorflow/examples/adding_an_op/zero_out_op_kernel_1.cc
  tensorflow/python/framework/ops.py
  tensorflow/python/framework/python_op_gen.cc
  tensorflow/python/framework/python_op_gen_internal.cc
  tensorflow/python/framework/python_op_gen_internal.h
  tensorflow/python/framework/test_ops.cc
  tensorflow/python/ops/gradients_test.py
Labels: cla: yes, size:M

#32565 [r2.0-CherryPick]: Autograph: Remove tf.autograph.experimental.set_loop_options doc
  tensorflow/python/autograph/lang/directives.py
Labels: cla: yes, size:XS

#32441 [r2.0-CherryPick]:Cherrypick batch_dot behavior change
  tensorflow/python/keras/backend.py
  tensorflow/python/keras/backend_test.py
Labels: cla: yes, size:L

#32572 Use arg 'axis' when calling 'tensorflow.python.ops.nn_impl.l2_normalize'
  tensorflow/python/ops/clustering_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#32626 Cherrypicks for estimator 2.0 release
  tensorflow/python/keras/layers/serialization.py
  tensorflow/python/keras/premade/linear.py
  tensorflow/python/keras/premade/linear_test.py
  tensorflow/python/keras/premade/wide_deep.py
  tensorflow/python/keras/premade/wide_deep_test.py
Labels: cla: yes, size:M

#32537 systemlibs: unbundle functools32
  tensorflow/workspace.bzl
  third_party/systemlibs/functools32.BUILD
  third_party/systemlibs/syslibs_configure.bzl
Labels: cla: yes, ready to pull, size:S

#32634 [ROCm] Fix for the broken ROCm Nightly Community Supported Build
  tensorflow/c/eager/c_api_experimental_test.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#32631 [r2.0-CherryPick]:forward_compatible env variable caching perf optimization.
  tensorflow/python/compat/compat.py
  tensorflow/python/compat/compat_test.py
Labels: cla: yes, size:S

#32644 TF 2.0 Cherrypick for TensorBoard 2.0 dependency
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32669 [r2.0-CherryPick]:[tf.data] Avoid double conversion to a tensor during input normalizat…
  tensorflow/python/data/util/structure.py
  tensorflow/python/framework/type_spec.py
Labels: cla: yes, size:M

#32652 fix typo
  tensorflow/compiler/xla/service/gpu/kernel_mapping_scheme.h
Labels: cla: yes, comp:xla, ready to pull, size:XS

#32610 fix typo
  tensorflow/compiler/xla/service/gpu/ir_emission_utils.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#32635 [Intel Mkl] Updating README.md for 1.14.0 release
  README.md
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#32568 Nms stability
  tensorflow/core/kernels/non_max_suppression_op.cc
  tensorflow/core/kernels/non_max_suppression_op.cu.cc
Labels: cla: yes, ready to pull, size:XS

#32599 Switch IteratorTest to use TF combinations
  tensorflow/python/data/kernel_tests/iterator_test.py
Labels: cla: yes, ready to pull, size:M

#31890 [tflite] Fix Unpack operator UINT8 quantisation
  tensorflow/lite/toco/graph_transformations/quantize.cc
  tensorflow/lite/toco/graph_transformations/tests/BUILD
  tensorflow/lite/toco/graph_transformations/tests/unpack_quantize_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#32277 Fix build on Windows
  tensorflow/lite/tools/make/Makefile
Labels: cla: yes, comp:lite, ready to pull, size:XS

#30157 [TF 2.0 Docs] Doc update for math functions
  tensorflow/core/api_def/base_api/api_def_Greater.pbtxt
  tensorflow/core/api_def/base_api/api_def_GreaterEqual.pbtxt
  tensorflow/core/api_def/base_api/api_def_IsFinite.pbtxt
  tensorflow/core/api_def/base_api/api_def_IsInf.pbtxt
  tensorflow/core/api_def/base_api/api_def_IsNan.pbtxt
  tensorflow/core/api_def/base_api/api_def_Less.pbtxt
  tensorflow/core/api_def/base_api/api_def_LessEqual.pbtxt
  tensorflow/core/api_def/base_api/api_def_Lgamma.pbtxt
  tensorflow/core/api_def/base_api/api_def_Log.pbtxt
  tensorflow/core/api_def/base_api/api_def_Log1p.pbtxt
Labels: cla: yes, ready to pull, size:M

#32699 [ROCm] Droppping "contrib" references from the ROCm CSB script
  tensorflow/tools/ci_build/linux/rocm/run_csb_tests.sh
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#32738 [XLA:GPU][ROCm] Adding no_rocm tag to ROCm XLA CI failed test cases
  tensorflow/compiler/mlir/glob_lit_test.bzl
  tensorflow/compiler/mlir/tensorflow/BUILD
  tensorflow/compiler/tests/BUILD
  tensorflow/compiler/xla/service/gpu/BUILD
Labels: cla: yes, comp:xla, ready to pull, size:XS

#32670 [r1.15-CherryPick] [tf.data] Avoid double conversion to a tensor during input normalizat…
  tensorflow/python/data/util/structure.py
  tensorflow/python/framework/type_spec.py
Labels: cla: yes, size:M

#32632 [r1.15-CherryPick]:forward_compatible env variable caching perf optimization.
  tensorflow/python/compat/compat.py
  tensorflow/python/compat/compat_test.py
Labels: cla: yes, size:S

#32744 [Grappler] Fix bug in layout optimizer introduced by cl/247704284. Re…
  tensorflow/core/grappler/optimizers/layout_optimizer.cc
Labels: cla: yes, size:XS

#32700 [r1.15-CherryPick] Making compute engine metadata client protected And not register GCS file system when TPU GCS file system option is ON
  tensorflow/core/platform/cloud/gcs_file_system.cc
  tensorflow/core/platform/cloud/gcs_file_system.h
Labels: cla: yes, size:S

#32733 Pin Estimator version to newly released 2.0.0
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32649 Add load error
  tensorflow/core/platform/hadoop/hadoop_file_system.cc
Labels: cla: yes, ready to pull, size:XS

#32688 [r1.15-CherryPick]:Cast `inputs` array to float64 in case of big endian architecture for normalization
  tensorflow/contrib/layers/python/layers/normalization.py
Labels: cla: yes, size:S

#32789 Update version numbers for TensorFlow 1.15.0-rc2
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32423 Fix few typos in the annotations and docs
  tensorflow/core/common_runtime/function.h
  tensorflow/core/grappler/utils/frame.h
  tensorflow/core/platform/cloud/curl_http_request.h
  tensorflow/lite/c/c_api_internal.h
  tensorflow/lite/delegates/gpu/gl/compiler/compiled_node.cc
  tensorflow/lite/experimental/c/c_api_types.h
  tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/Camera2BasicFragment.java
  third_party/gpus/crosstool/windows/msvc_wrapper_for_nvcc.py.tpl
  third_party/hadoop/hdfs.h
Labels: cla: yes, ready to pull, size:S, type:docs

#32794 [r1.15-CherryPick]: Cherrypicks svoii
  tensorflow/core/grappler/BUILD
  tensorflow/core/grappler/costs/graph_properties.cc
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
  tensorflow/core/grappler/optimizers/constant_folding.cc
  tensorflow/core/grappler/optimizers/dependency_optimizer.cc
  tensorflow/core/grappler/optimizers/memory_optimizer.cc
  tensorflow/core/grappler/optimizers/shape_optimizer.cc
  tensorflow/core/grappler/utils.cc
  tensorflow/core/grappler/utils.h
  tensorflow/core/grappler/utils/graph_view.cc
  tensorflow/core/grappler/utils_test.cc
  tensorflow/core/kernels/cwise_op_abs.cc
  tensorflow/core/ops/math_ops.cc
  tensorflow/python/kernel_tests/cwise_ops_unary_test.py
  tensorflow/workspace.bzl
Labels: cla: yes, size:L

#32151 [INTEL MKL] Add primitive cache for mkl softmax
  tensorflow/core/kernels/mkl_softmax_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#32753 Fix TensorListResize being incorrectly marked as stateful
  tensorflow/core/ops/list_ops.cc
Labels: cla: yes, ready to pull, size:XS

#32820 [r2.0-CherryPick]:remove array_ops.where deprecation message.
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, size:XS

#32758 Use static python_version dependency configuration in setup.py
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:S

#32826 [r2.0-CherryPick]: Fix deprecation warnings in feature_column_v2.
  tensorflow/python/feature_column/feature_column_v2.py
Labels: cla: yes, size:S

#32824 [r2.0-CherryPick]: Update TF version to 2.0.0.
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#32823 [r2.0-CherryPick]:Update TRT6 headerfiles
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  third_party/tensorrt/tensorrt_configure.bzl
Labels: cla: yes, size:XS

#32828 [r1.15-CherryPick]:Update TRT6 headerfiles
  third_party/tensorrt/tensorrt_configure.bzl
Labels: cla: yes, size:XS

#32788 Fix exported_symbols.lds
  tensorflow/lite/experimental/c/exported_symbols.lds
Labels: cla: yes, comp:lite, ready to pull, size:XS

#32739 typo fix
  tensorflow/python/keras/engine/training.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#32846 Un-blacklist Softmax & Log in auto_mixed_precision
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
  tensorflow/core/grappler/optimizers/auto_mixed_precision_test.cc
Labels: cla: yes, comp:grappler, ready to pull, size:M

#32852 [r2.0-CherryPick]: Fix licenses in C, java and python packages.
  tensorflow/tools/ci_build/ci_sanity.sh
  tensorflow/tools/lib_package/BUILD
  tensorflow/tools/pip_package/BUILD
  tensorflow/tools/pip_package/MANIFEST.in
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: cla: yes, size:S

#32742 [r2.0-CherryPick]: [Grappler] Fix bug in layout optimizer introduced by cl/247704284. Re…
  tensorflow/core/grappler/optimizers/layout_optimizer.cc
Labels: cla: yes, size:XS

#32853 [r1.15-CherryPick]: Fix licenses in C, java and python packages.
  tensorflow/tools/ci_build/ci_sanity.sh
  tensorflow/tools/lib_package/BUILD
  tensorflow/tools/pip_package/BUILD
  tensorflow/tools/pip_package/MANIFEST.in
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: cla: yes, size:S

#32861 Mark tf.keras.utils.multi_gpu_model as deprecated.
  tensorflow/python/keras/utils/multi_gpu_utils.py
Labels: cla: yes, size:XS

#32639 slightly optimize tflite Concatenate operation
  tensorflow/lite/kernels/internal/reference/reference_ops.h
Labels: cla: yes, comp:lite, ready to pull, size:S

#32668 Updated doc for all symbols in tf.keras.activations
  tensorflow/python/keras/activations.py
Labels: awaiting review, cla: yes, comp:keras, prtype:bugfix, ready to pull, size:M

#32247 Release Notes for TensorFlow 2.0.0
  RELEASE.md
Labels: cla: yes, size:L

#32848 [r1.15-CherryPick]: Allow MLIR external repository to be created from non-tensorflow repository.
  tensorflow/opensource_only.files
  tensorflow/workspace.bzl
  third_party/mlir/WORKSPACE
  third_party/mlir/mlir_configure.bzl
Labels: cla: yes, size:S

#32827 [Intel Mkl] Upgrading MKL public CI to py3
  tensorflow/tools/ci_build/linux/cpu/run_mkl.sh
Labels: cla: yes, ready to pull, size:XS

#32838 only copy binaries required by cuda
  third_party/gpus/cuda_configure.bzl
Labels: cla: yes, comp:gpu, ready to pull, size:S

#32929 [r1.15-CherryPick]:Fix the license copy code after the latest changes in windows libtensorflow build scripts.
  tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh
  tensorflow/tools/ci_build/windows/libtensorflow_gpu.sh
Labels: cla: yes, size:S

#32936 Fix typo in libtensorflow cpu build.
  tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh
Labels: cla: yes, size:XS
