Repository tensorflow/tensorflow, pull requests merged in 2020-07, with the labels that each got.

#39630 Solved issue with Single Writer Multiple Reader mode
  tensorflow/python/keras/saving/hdf5_format.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#40843 [DLPack] Fix memory leak in from_dlpack
  tensorflow/c/eager/dlpack.cc
  tensorflow/python/tfe_wrapper.cc
Labels: cla: yes, ready to pull, size:S

#39859 TF-TRT Pack op conversion in dynamic shape mode
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L

#40828 TF Chat Room
  README.md
Labels: cla: yes, ready to pull, size:XS

#40769 [INTEL MKL] Update build name with new branding
  README.md
Labels: cla: yes, ready to pull, size:XS

#37930 TFLu: Update MBED version to mbed-os-6.0.0-alpha-3
  tensorflow/lite/micro/tools/make/templates/mbed-os.lib.tpl
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XS

#40968 Add test and fix one error for writable file
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.cc
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.h
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem_test.cc
Labels: cla: yes, ready to pull, size:M

#40861 Change GetMatchingPaths to avoid traversing unnecesscary paths
  tensorflow/core/platform/file_system_helper.cc
Labels: cla: yes, ready to pull, size:M

#41015 Add file block cache interface
  tensorflow/c/experimental/filesystem/plugins/gcs/BUILD
  tensorflow/c/experimental/filesystem/plugins/gcs/file_block_cache.h
Labels: cla: yes, ready to pull, size:M

#41011 micro fix in limitations.md
  tensorflow/python/autograph/g3doc/reference/limitations.md
Labels: cla: yes, comp:autograph, ready to pull, size:XS

#40554 Add benchmark for Bidirectional LSTM on IMDB
  tensorflow/python/keras/benchmarks/BUILD
  tensorflow/python/keras/benchmarks/benchmark_util.py
  tensorflow/python/keras/benchmarks/keras_examples_benchmark_test.py
Labels: cla: yes, comp:keras, ready to pull, size:M

#37004 Add checking of kwonlyargs in keras has_arg
  tensorflow/python/keras/utils/generic_utils.py
  tensorflow/python/keras/utils/generic_utils_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#41044 Update array_ops.py
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#41068 Remove static string member
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem_test.cc
Labels: cla: yes, ready to pull, size:M

#41056 Replaced deprecated functions in exmaples
  tensorflow/python/keras/preprocessing/image.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#40763 Avoid memory 'leak' in Go with multiple inputs
  tensorflow/go/session.go
  tensorflow/go/session_test.go
Labels: cla: yes, ready to pull, size:M

#40223 [grappler] Convert identity ConjugateTranspose to Conj instead of removing it
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
  tensorflow/core/grappler/optimizers/arithmetic_optimizer_test.cc
Labels: cla: yes, comp:grappler, ready to pull, size:S

#36839 Add step argument to SummaryWriter.(set_)as_default.
  tensorflow/python/kernel_tests/summary_ops_test.py
  tensorflow/python/ops/summary_ops_v2.py
  tensorflow/tools/api/golden/v2/tensorflow.summary.-summary-writer.pbtxt
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:M

#41002 [CherryPick:r2.3] Support dynamic outputs for XLA on demand ops.
  tensorflow/compiler/jit/xla_launch_util.cc
  tensorflow/compiler/xla/service/BUILD
  tensorflow/compiler/xla/service/transfer_manager.cc
  tensorflow/compiler/xla/service/transfer_manager.h
  tensorflow/compiler/xrt/kernels/xrt_execute_op.cc
  tensorflow/python/distribute/tpu_strategy_test.py
Labels: cla: yes

#41017 Cherry-pick dlpack fix #40843 into r2.3
  tensorflow/c/eager/dlpack.cc
  tensorflow/python/tfe_wrapper.cc
Labels: cla: yes, size:XS

#41006 Add SaveableObjects to SavedModel.
  RELEASE.md
  tensorflow/core/protobuf/saved_object_graph.proto
  tensorflow/python/ops/lookup_ops.py
  tensorflow/python/saved_model/load.py
  tensorflow/python/saved_model/load_test.py
  tensorflow/python/saved_model/save.py
  tensorflow/python/training/saving/saveable_object_util.py
  tensorflow/python/training/tracking/base.py
  tensorflow/python/training/tracking/graph_view.py
Labels: cla: yes, size:L

#41082 Add create dir, delete dir/file
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.cc
Labels: cla: yes, kokoro:force-run, ready to pull, size:M

#40581 Make the XLA_FLAGS=--xla_gpu_asm_extra_flags works with replay_computation
  tensorflow/compiler/xla/tools/replay_computation.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#41163 Update version numbers for TensorFlow 2.3.0-rc1
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#41121 cmsis-nn: Revert dynamic allocation for quant params
  tensorflow/lite/micro/kernels/cmsis-nn/depthwise_conv.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#38752 Add return statement to the micro-test framework.
  tensorflow/lite/micro/testing/micro_test.h
Labels: cla: yes, comp:lite, comp:micro, size:XS

#39698 [tflite] nnapi delegate max_delegated_partitions=0
  tensorflow/lite/tools/delegates/nnapi_delegate_provider.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#41145 Sign compare warning fixes batch 9
  tensorflow/compiler/tf2xla/const_analysis.cc
  tensorflow/compiler/tf2xla/graph_compiler.cc
  tensorflow/compiler/tf2xla/graph_compiler_util.cc
  tensorflow/compiler/tf2xla/kernels/conv_op_helpers.cc
  tensorflow/compiler/tf2xla/lib/data_format.cc
  tensorflow/compiler/tf2xla/literal_util.cc
  tensorflow/compiler/tf2xla/mlir_tf2xla.cc
  tensorflow/compiler/tf2xla/shape_util.cc
  tensorflow/compiler/tf2xla/tf2xla.cc
  tensorflow/compiler/tf2xla/xla_compiler.cc
  tensorflow/compiler/tf2xla/xla_context.cc
Labels: cla: yes, ready to pull, size:M

#39902 [TFLite] 16x8 reference kernel for PAD operator
  tensorflow/lite/delegates/nnapi/acceleration_test_list.cc
  tensorflow/lite/kernels/internal/reference/pad.h
  tensorflow/lite/kernels/pad.cc
  tensorflow/lite/kernels/pad_test.cc
  tensorflow/lite/kernels/register.cc
  tensorflow/lite/toco/tflite/op_version.cc
  tensorflow/lite/tools/versioning/op_version.cc
  tensorflow/lite/tools/versioning/runtime_version.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#40685 supporting x dtype instead of only float 32 in K.relu
  tensorflow/python/keras/backend.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#40585 Add complex64 and complex128 gpu support for tensor_scatter_nd_add
  tensorflow/core/kernels/inplace_ops_functor_gpu.cu.cc
Labels: cla: yes, comp:core, prtype:bugfix, ready to pull, size:XS

#40158 [compiler] Fix segmentation fault in segment graph
  tensorflow/compiler/tf2tensorrt/segment/segment.cc
Labels: awaiting review, cla: yes, comp:gpu:tensorrt, ready to pull, size:XS

#41158 Add ram file block cache
  tensorflow/c/experimental/filesystem/plugins/gcs/BUILD
  tensorflow/c/experimental/filesystem/plugins/gcs/cleanup.h
  tensorflow/c/experimental/filesystem/plugins/gcs/file_block_cache.h
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache.cc
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache.h
Labels: cla: yes, ready to pull, size:L

#41144 Simplify code for keras_cpu_benchmark_test
  tensorflow/python/keras/benchmarks/BUILD
  tensorflow/python/keras/benchmarks/keras_cpu_benchmark_test.py
Labels: cla: yes, comp:keras, ready to pull, size:M

#41140 r2.3 cherry-pick request: Shift padded NMS compat window forward to fix TFLite conversion
  tensorflow/compiler/tests/image_ops_test.py
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes

#41203 Add expiring_lru_cache
  tensorflow/c/experimental/filesystem/plugins/gcs/BUILD
  tensorflow/c/experimental/filesystem/plugins/gcs/expiring_lru_cache.h
  tensorflow/c/experimental/filesystem/plugins/gcs/expiring_lru_cache_test.cc
Labels: cla: yes, ready to pull, size:L

#41173 Support path-like objects in FileIO and GFile
  tensorflow/python/lib/io/file_io.py
  tensorflow/python/lib/io/file_io_test.py
  tensorflow/python/util/compat.py
Labels: cla: yes, ready to pull, size:S

#41192 Add Rename, Copy, Delete recursively
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#41223 Add a new badge for nightly build on arm
  README.md
Labels: cla: yes, ready to pull, size:XS

#41199 Fix categorical_crossentropy docstring
  tensorflow/python/keras/backend.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#41030 [TFLite] Documentation: fix typo in doc for the post-training quantization, 16x8
  tensorflow/lite/g3doc/performance/post_training_quantization.md
Labels: awaiting review, cla: yes, comp:lite, ready to pull, size:XS

#26936 Lite: Slice Op refactored
  tensorflow/lite/delegates/nnapi/acceleration_test_list.cc
  tensorflow/lite/kernels/slice.cc
  tensorflow/lite/kernels/slice_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#40621 add script for updating keras application's efficientnet weights from ckpt
  tensorflow/python/keras/applications/efficientnet_weight_update_util.py
Labels: cla: yes, comp:keras, ready to pull, size:L

#41273 Fix FileIO tests for Python < 3.6
  tensorflow/python/lib/io/file_io_test.py
Labels: cla: yes, ready to pull, size:S

#40925 [MLIR] Update lhlo.const to linalg lowering to use affine.store inste…
  tensorflow/compiler/mlir/hlo/BUILD
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc
  tensorflow/compiler/mlir/hlo/tests/lhlo-legalize-to-linalg.mlir
Labels: cla: yes, ready to pull, size:S

#40619 TF2.x API Docs module.py example fix.
  tensorflow/python/module/module.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#40966 refact huber loss
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#41235 Add ram test and remove unused header
  tensorflow/c/experimental/filesystem/plugins/gcs/BUILD
  tensorflow/c/experimental/filesystem/plugins/gcs/cleanup.h
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache.h
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache_test.cc
Labels: cla: yes, ready to pull, size:L

#41217 [ROCm] Fix for ROCm Breakage - 200708
  tensorflow/compiler/xla/service/sharding_propagation.cc
Labels: cla: yes, ready to pull, size:XS

#40962 [INTEL MKL] Replace tensorflow::bfloat16 with Eigen::bfloat16
  tensorflow/compiler/mlir/xla/transforms/legalize_tf.cc
  tensorflow/compiler/xla/client/lib/constants.cc
  tensorflow/compiler/xla/service/hlo_parser.cc
  tensorflow/compiler/xla/tests/prng_test.cc
  tensorflow/core/framework/bfloat16_test.cc
  tensorflow/core/framework/numeric_types.h
  tensorflow/core/kernels/cast_op.h
  tensorflow/core/kernels/sparse_matmul_op.cc
  tensorflow/core/lib/bfloat16/bfloat16.cc
  tensorflow/core/lib/bfloat16/bfloat16.h
Labels: cla: yes, ready to pull, size:L

#41215 Added str_util fuzzers
  tensorflow/security/fuzzing/BUILD
  tensorflow/security/fuzzing/arg_def_case_fuzz.cc
  tensorflow/security/fuzzing/consume_leading_digits_fuzz.cc
  tensorflow/security/fuzzing/consume_non_whitespace_fuzz.cc
  tensorflow/security/fuzzing/string_replace_fuzz.cc
Labels: cla: yes, ready to pull, size:M

#41210 added priority function
  tensorflow/c/kernels.cc
  tensorflow/c/kernels.h
Labels: cla: yes, ready to pull, size:S

#41282 Add path exist, is directory, stat
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#41219 Add nearest fill mode for image projective transform
  tensorflow/core/kernels/image_ops.cc
  tensorflow/core/kernels/image_ops.h
  tensorflow/python/keras/layers/preprocessing/image_preprocessing.py
  tensorflow/python/keras/layers/preprocessing/image_preprocessing_test.py
Labels: cla: yes, ready to pull, size:M

#41275 [TFLite] Error reporting message does not include name of the operator.
  tensorflow/lite/tools/optimize/quantize_model.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#40190 Add INT16 support in modify_model_interface
  tensorflow/lite/tools/optimize/modify_model_interface.cc
  tensorflow/lite/tools/optimize/modify_model_interface.h
  tensorflow/lite/tools/optimize/modify_model_interface_main.cc
  tensorflow/lite/tools/optimize/modify_model_interface_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:L

#41265 Enable half for scatter ops on GPU
  tensorflow/core/kernels/resource_variable_ops.cc
  tensorflow/core/kernels/scatter_functor.cc
  tensorflow/core/kernels/scatter_functor_gpu.cu.cc
  tensorflow/core/kernels/scatter_op.cc
  tensorflow/python/kernel_tests/resource_variable_ops_test.py
  tensorflow/python/kernel_tests/scatter_ops_test.py
Labels: cla: yes, ready to pull, size:S

#41295 Prefer Python 3 methods over compatibility aliases
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/python/data/ops/iterator_ops.py
  tensorflow/python/data/ops/multi_device_iterator_ops.py
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/utils/data_utils.py
  tensorflow/python/lib/io/file_io.py
  tensorflow/python/ops/numpy_ops/np_arrays.py
  tensorflow/python/training/server_lib.py
Labels: cla: yes, ready to pull, size:S

#40184 TF-TRT Improve test coverage of pool op converters
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L

#41007 [INTEL MKL] Adding oneDNN partials for Ubuntu versions 16.04. 18.04, 20.04
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel-onednn-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel-onednn.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-onednn-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-onednn.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-devel-onednn-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-devel-onednn.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-onednn-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-onednn.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-devel-onednn-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-devel-onednn.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-onednn-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-onednn.Dockerfile
  tensorflow/tools/dockerfiles/partials/onednn/ubuntu/bazel.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/onednn/ubuntu/cpu.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/onednn/ubuntu/devel.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/onednn/ubuntu/jupyter.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/onednn/ubuntu/python.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/onednn/ubuntu/python3.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/onednn/ubuntu/test-devel.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/onednn/ubuntu/version.partial.Dockerfile
  tensorflow/tools/dockerfiles/spec.yml
  tensorflow/tools/dockerfiles/tests/import-onednn.sh
Labels: cla: yes, ready to pull, size:XL

#40957 Fix tf32.
  tensorflow/core/platform/BUILD
  tensorflow/python/BUILD
  tensorflow/python/framework/config_test.py
  tensorflow/tools/def_file_filter/symbols_pybind.txt
Labels: cla: yes, ready to pull, size:S

#40902 Small update to tf.vectorized_map() and code syntax in docs in control_flow_ops.py
  tensorflow/python/ops/parallel_for/control_flow_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#41337 S3 registration
  tensorflow/c/experimental/filesystem/plugins/s3/BUILD
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.h
Labels: cla: yes, ready to pull, size:M

#41379 Add aws crypto and init for s3
  tensorflow/c/experimental/filesystem/plugins/s3/BUILD
  tensorflow/c/experimental/filesystem/plugins/s3/aws_crypto.cc
  tensorflow/c/experimental/filesystem/plugins/s3/aws_crypto.h
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.h
Labels: cla: yes, ready to pull, size:M

#40700 Add arm source file into aws-checksums
  third_party/aws/aws-checksums.bazel
Labels: cla: yes, ready to pull, size:XS

#41384 Increase complexity of arg_def_fuzz
  tensorflow/security/fuzzing/consume_leading_digits_fuzz.cc
Labels: cla: yes, ready to pull, size:S

#41390 Fix FileIO tests for Python < 3.6
  tensorflow/python/lib/io/file_io_test.py
Labels: cla: yes, ready to pull, size:S

#40109 Fix the docs and parameters warning of Hessians with tf 2.0 upgrader
  tensorflow/python/ops/gradients_impl.py
  tensorflow/tools/compatibility/tf_upgrade_v2.py
  tensorflow/tools/compatibility/tf_upgrade_v2_test.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#41348 Doc error for `tf.linalg.trace`
  tensorflow/python/ops/math_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#41010 [INTEL MKL] Pad+Conv fusion for bf16
  tensorflow/core/common_runtime/mkl_layout_pass.cc
  tensorflow/core/common_runtime/mkl_layout_pass_test.cc
  tensorflow/core/kernels/mkl_fused_ops_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#41293 Fix deprecated usage of collections ABC
  tensorflow/python/compiler/xla/xla.py
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/python/data/ops/iterator_ops.py
  tensorflow/python/data/util/structure.py
  tensorflow/python/debug/wrappers/framework.py
  tensorflow/python/distribute/input_lib.py
  tensorflow/python/framework/indexed_slices.py
  tensorflow/python/keras/engine/training_utils.py
  tensorflow/python/keras/layers/preprocessing/preprocessing_test_utils.py
  tensorflow/python/keras/layers/recurrent.py
  tensorflow/python/ops/math_ops.py
  tensorflow/python/ops/nn_ops.py
  tensorflow/python/ops/variable_scope.py
  tensorflow/python/tools/saved_model_cli.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:M

#39690 Add explicit block_size to TriangularSolveExpander constructor
  tensorflow/compiler/xla/service/BUILD
  tensorflow/compiler/xla/service/triangular_solve_expander.cc
  tensorflow/compiler/xla/service/triangular_solve_expander.h
  tensorflow/compiler/xla/service/triangular_solve_expander_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:M

#40040 Fix package name
  tensorflow/python/training/checkpoint_management.py
Labels: cla: yes, ready to pull, size:XS

#41253 Fix invalid test in zero_padding_2d test
  tensorflow/python/keras/layers/convolutional_test.py
Labels: cla: yes, comp:keras, ready to pull, size:M

#39747 [Intel MKL] Vectorize FP32/BF16 RandomUniform process
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/random_binomial_op.cc
  tensorflow/core/kernels/random_op.cc
  tensorflow/core/kernels/random_op_cpu.h
  tensorflow/core/kernels/random_op_test.cc
  tensorflow/core/lib/random/BUILD
  tensorflow/core/lib/random/random_distributions.h
  tensorflow/python/kernel_tests/random/random_ops_test.py
Labels: cla: yes, comp:mkl, ready to pull, size:M

#41381 remove file block cache
  tensorflow/c/experimental/filesystem/plugins/gcs/BUILD
  tensorflow/c/experimental/filesystem/plugins/gcs/file_block_cache.h
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache.cc
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache.h
Labels: cla: yes, ready to pull, size:M

#40903 [-Wsign-compare] warning fixes batch 6
  tensorflow/compiler/tf2xla/ops/xla_ops.cc
  tensorflow/core/framework/shape_inference.cc
  tensorflow/core/grappler/optimizers/common_subgraph_elimination.cc
  tensorflow/core/grappler/optimizers/debug_stripper.cc
  tensorflow/core/grappler/optimizers/model_pruner.cc
  tensorflow/core/grappler/utils.cc
  tensorflow/core/grappler/utils/topological_sort.cc
  tensorflow/core/profiler/utils/derived_timeline.cc
  tensorflow/core/profiler/utils/xplane_utils.cc
  tensorflow/core/util/bcast.h
  tensorflow/python/framework/python_op_gen.cc
  tensorflow/python/framework/python_op_gen_internal.cc
Labels: cla: yes, comp:core, ready to pull, size:M

#41249 Create keras_io_examples folder and upload text with transformer benchmark.
  tensorflow/python/keras/benchmarks/BUILD
  tensorflow/python/keras/benchmarks/benchmark_util.py
  tensorflow/python/keras/benchmarks/keras_cpu_benchmark_test.py
  tensorflow/python/keras/benchmarks/keras_examples_benchmark_test.py
  tensorflow/python/keras/benchmarks/keras_examples_benchmarks/bidirectional_lstm_benchmark_test.py
  tensorflow/python/keras/benchmarks/keras_examples_benchmarks/text_classification_transformer_benchmark_test.py
Labels: cla: yes, comp:keras, ready to pull, size:L

#41423 Lazy loading for s3_client and executor
  tensorflow/c/experimental/filesystem/plugins/s3/BUILD
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#36118 Riscv 32 mcu
  tensorflow/lite/micro/arduino/abi.cc
  tensorflow/lite/micro/examples/hello_world/riscv32_mcu/Makefile.inc
  tensorflow/lite/micro/examples/magic_wand/riscv32_mcu/Makefile.inc
  tensorflow/lite/micro/examples/micro_speech/riscv32_mcu/Makefile.inc
  tensorflow/lite/micro/examples/person_detection/riscv32_mcu/Makefile.inc
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/helper_functions.inc
  tensorflow/lite/micro/tools/make/targets/mcu_riscv_makefile.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:M

#41435 Fix typo in estimator min bound
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#41431 Adding filesystem_interface methods for transactions
  tensorflow/c/experimental/filesystem/filesystem_interface.h
Labels: cla: yes, ready to pull, size:M

#40851 initial test for matmul with abstract tensors
  tensorflow/c/eager/c_api_test_util.cc
  tensorflow/c/eager/c_api_test_util.h
  tensorflow/c/eager/c_api_unified_experimental_test.cc
Labels: cla: yes, kokoro:force-run, ready to pull, size:M

#41436 Refactor read and blockfetcher in RamFileBlockCache
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache.cc
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache.h
  tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache_test.cc
Labels: cla: yes, ready to pull, size:M

#41359 Add error message fix in qr grad and test coverage
  tensorflow/python/kernel_tests/qr_op_test.py
  tensorflow/python/ops/linalg_grad.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#40034 Update Keras application docs
  tensorflow/python/keras/applications/densenet.py
  tensorflow/python/keras/applications/efficientnet.py
  tensorflow/python/keras/applications/inception_resnet_v2.py
  tensorflow/python/keras/applications/inception_v3.py
  tensorflow/python/keras/applications/mobilenet.py
  tensorflow/python/keras/applications/mobilenet_v2.py
  tensorflow/python/keras/applications/nasnet.py
  tensorflow/python/keras/applications/resnet.py
  tensorflow/python/keras/applications/resnet_v2.py
  tensorflow/python/keras/applications/vgg16.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#41454 S3 transfer manager and random_access_file
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.h
Labels: cla: yes, ready to pull, size:M

#41296 Let Attention layer accept a layer mask of list of length 3, namely [query_mask, value_mask, key_mask] #41294
  tensorflow/python/keras/layers/dense_attention.py
Labels: cla: yes, comp:keras, ready to pull, size:XL

#41433 Introducing WrappedFileSystem for transactions
  tensorflow/core/platform/file_system.h
Labels: cla: yes, comp:core, ready to pull, size:M

#41393 Use Bazel's builtin patch support.
  third_party/com_google_absl_fix_mac_and_nvcc_build.patch
  third_party/eigen3/gpu_packet_math.patch
  third_party/icu/udata.patch
  third_party/png_fix_rpi.patch
  third_party/repo.bzl
Labels: cla: yes, ready to pull, size:S

#40602 add test case to keras model save with pathlike dir
  tensorflow/python/keras/saving/save_test.py
  tensorflow/python/saved_model/loader_impl.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#41426 [Cherrypick r2.3] Fix critical bug with `add_loss` TFOpLayer graph construction that caused incorrect loss values and backprop issues
  tensorflow/python/keras/backend.py
  tensorflow/python/keras/engine/functional_test.py
Labels: cla: yes

#41385 [Cherrypick:r2.3] Explicitly raise a (clearer) error message when models end up in inva…
  tensorflow/python/keras/engine/base_layer_v1.py
  tensorflow/python/keras/engine/training_v1.py
Labels: cla: yes

#41464 Update "master" to "dispatch"/"dispatcher" in tf.data service terminology
  tensorflow/core/data/service/BUILD
  tensorflow/core/data/service/data_service.cc
  tensorflow/core/data/service/data_service.h
  tensorflow/core/data/service/data_service_test.cc
  tensorflow/core/data/service/dispatcher.proto
  tensorflow/core/data/service/dispatcher_impl.cc
  tensorflow/core/data/service/dispatcher_impl.h
  tensorflow/core/data/service/grpc_dispatcher_impl.cc
  tensorflow/core/data/service/grpc_dispatcher_impl.h
  tensorflow/core/data/service/grpc_worker_impl.cc
  tensorflow/core/data/service/grpc_worker_impl.h
  tensorflow/core/data/service/server_lib.cc
  tensorflow/core/data/service/server_lib.h
  tensorflow/core/data/service/test_cluster.cc
  tensorflow/core/data/service/test_cluster.h
  tensorflow/core/data/service/worker_impl.cc
  tensorflow/core/data/service/worker_impl.h
  tensorflow/core/kernels/data/experimental/data_service_dataset_op.cc
  tensorflow/core/kernels/data/experimental/data_service_ops.cc
  tensorflow/core/kernels/data/experimental/data_service_ops.h
  tensorflow/python/data/experimental/ops/data_service_ops.py
  tensorflow/python/data/experimental/service/__init__.py
  tensorflow/python/data/experimental/service/server_lib.py
  tensorflow/python/data/experimental/service/server_lib_test.py
  tensorflow/python/data/experimental/service/server_lib_wrapper.cc
  tensorflow/python/data/kernel_tests/data_service_ops_test.py
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.service.-dispatch-server.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.service.-worker-server.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.service.pbtxt
  tensorflow/tools/def_file_filter/symbols_pybind.txt
Labels: cla: yes

#41357 2.3-rc2 cherry-pick request: Correctly set the experimental_io_device when restoring variable from a checkpoint.
  tensorflow/python/training/tracking/base.py
Labels: cla: yes

#41477 S3 writable and appendable
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#41483 Raise an error when some but not all values passed to the first layer…
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/functional_test.py
Labels: cla: yes, size:M

#41463 Moving last set of FileSystem derivatives to new API
  tensorflow/core/platform/s3/s3_file_system.cc
  tensorflow/core/platform/s3/s3_file_system.h
  tensorflow/core/platform/windows/windows_file_system.cc
  tensorflow/core/platform/windows/windows_file_system.h
  tensorflow/core/util/memmapped_file_system.cc
  tensorflow/core/util/memmapped_file_system.h
  tensorflow/tools/android/inference_interface/asset_manager_filesystem.cc
  tensorflow/tools/android/inference_interface/asset_manager_filesystem.h
Labels: cla: yes, comp:core, ready to pull, size:M

#41498 Update version numbers for TensorFlow 2.3.0-rc2
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#39678 Fix a bug that the output of `tf.sparse.fill_empty_rows` may not be ordered
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
  tensorflow/python/kernel_tests/sparse_ops_test.py
Labels: cla: yes, comp:core, ready to pull, size:XS

#41462 Moving more filesystems to transactions
  tensorflow/core/platform/cloud/gcs_file_system.cc
  tensorflow/core/platform/cloud/gcs_file_system.h
  tensorflow/core/platform/default/posix_file_system.cc
  tensorflow/core/platform/default/posix_file_system.h
  tensorflow/core/platform/hadoop/hadoop_file_system.cc
  tensorflow/core/platform/hadoop/hadoop_file_system.h
Labels: cla: yes, comp:core, ready to pull, size:M

#40998 [XLA/GPU] rsqrt is cheap and should be fused.
  tensorflow/compiler/xla/service/gpu/instruction_fusion.cc
Labels: cla: yes, comp:xla, size:S, stat:awaiting response

#41469 [Intel MKL] Fixing bfloat16 build failure in MklRelu
  tensorflow/core/kernels/mkl_relu_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#40749 [EXT-SYSLIB] Add absl_py logging submodule to build flow.
  tensorflow/opensource_only.files
  tensorflow/workspace.bzl
  third_party/systemlibs/absl_py.absl.logging.BUILD
Labels: cla: yes, ready to pull, size:S

#41261 Remove repeated call in FindKernelDef
  tensorflow/core/framework/op_kernel.cc
Labels: cla: yes, ready to pull, size:XS

#41511 S3 read only memory region and stat
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#41502 Modify smart_resize in keras.preprocessing.image
  tensorflow/python/keras/preprocessing/image.py
  tensorflow/python/keras/preprocessing/image_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:M

#41383 added INT16 support in corresponding python wrappers
  tensorflow/lite/tools/optimize/python/modify_model_interface.cc
  tensorflow/lite/tools/optimize/python/modify_model_interface_constants.py
  tensorflow/lite/tools/optimize/python/modify_model_interface_lib_test.py
Labels: cla: yes, comp:lite, ready to pull, size:S

#40626 Fix error caused by incorrect rank assumption in tf.image.flip_left_right
  tensorflow/python/ops/image_ops_impl.py
  tensorflow/python/ops/image_ops_test.py
Labels: cla: yes, comp:ops, ready to pull, size:M

#41472 Add palette-based png support for tf.image.decode_png
  tensorflow/core/lib/png/BUILD
  tensorflow/core/lib/png/png_io.cc
  tensorflow/core/lib/png/testdata/palette_only.png
  tensorflow/python/ops/image_ops_test.py
Labels: cla: yes, comp:core, prtype:bugfix, ready to pull, size:S

#41264 [INTEL MKL] BF16 exp
  tensorflow/core/kernels/cwise_op_exp.cc
  tensorflow/python/kernel_tests/cwise_ops_unary_test.py
Labels: cla: yes, comp:mkl, ready to pull, size:S

#40971 [Intel MKL] Factor out the macros for handling test registeration
  tensorflow/core/common_runtime/mkl_layout_pass_test.cc
  tensorflow/core/grappler/optimizers/mkl_remapper_test.cc
  tensorflow/core/util/mkl_util.h
Labels: cla: yes, comp:mkl, ready to pull, size:M

#41481 Fix tf32 for real.
  tensorflow/core/common_runtime/gpu/BUILD
  tensorflow/python/BUILD
Labels: cla: yes, ready to pull, size:XS

#39988 [TFLite, 16x8] 16x8 Reference kernel for the MEAN operator.
  tensorflow/lite/delegates/nnapi/acceleration_test_list.cc
  tensorflow/lite/kernels/internal/reference/integer_ops/mean.h
  tensorflow/lite/kernels/internal/reference/reduce.h
  tensorflow/lite/kernels/reduce.cc
  tensorflow/lite/kernels/reduce_test.cc
  tensorflow/lite/kernels/register.cc
  tensorflow/lite/toco/tflite/op_version.cc
  tensorflow/lite/tools/optimize/operator_property.cc
  tensorflow/lite/tools/versioning/op_version.cc
  tensorflow/lite/tools/versioning/op_version_test.cc
  tensorflow/lite/tools/versioning/runtime_version.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#40179 TF-TRT test FusedBatchNorm op converter
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L, stat:awaiting response

#41471 Add distribution_util to benchmarks.
  tensorflow/python/keras/benchmarks/BUILD
  tensorflow/python/keras/benchmarks/benchmark_util.py
  tensorflow/python/keras/benchmarks/distribution_util.py
Labels: cla: yes, comp:keras, ready to pull, size:M

#41517 Add minor TODO comment - test PR
  tensorflow/python/eager/function.py
Labels: cla: yes, comp:eager, ready to pull, size:XS

#41497 Refactor gcs part 1 random access file
  tensorflow/c/experimental/filesystem/plugins/gcs/BUILD
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.cc
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.h
Labels: cla: yes, ready to pull, size:M

#41529 Account for possibility of pyc extension in TFLite check.
  tensorflow/lite/python/interpreter.py
Labels: cla: yes, comp:lite, prtype:bugfix, ready to pull, size:XS

#40881 Make ProgBarLogger, ModelCheckpoint and TensorBoard callbacks not use batch hooks when possible
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/callbacks_test.py
Labels: cla: yes, comp:keras, ready to pull, size:M

#41551 S3 simple copy
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#41514 Improve error message in shape check
  tensorflow/core/framework/tensor_shape.cc
  tensorflow/python/kernel_tests/broadcast_to_ops_test.py
Labels: cla: yes, comp:core, prtype:bugfix, ready to pull, size:S

#41516 Add commented arguments and new methods to FileSystem for Transactions
  tensorflow/core/platform/file_system.cc
  tensorflow/core/platform/file_system.h
Labels: cla: yes, comp:core, ready to pull, size:M

#41592 Refactor gcs part 2 random access file
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#41603 Fix issue in tf.ones where tf.quint8/quint16 does not work in graph mode
  tensorflow/python/kernel_tests/constant_op_test.py
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, ready to pull, size:S

#41601 S3 multi part copy
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#40116 Fix [SplitV CPU Kernel] condition error for parallelism output judgement.
  tensorflow/core/kernels/split_v_op.cc
Labels: cla: yes, comp:core, ready to pull, size:XS

#40943 Cadence HiFi4 NN Library v2.2.0 update
  tensorflow/lite/micro/kernels/xtensa_hifi/activations.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/add.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/conv.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/depthwise_conv.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/floor.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/fully_connected.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/logistic.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/mul.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/pooling.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/softmax.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/svdf.cc
  tensorflow/lite/micro/tools/make/ext_libs/xtensa_hifi_nn_library.inc
  tensorflow/lite/micro/tools/make/targets/xtensa_hifi_makefile.inc
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XL

#41633 2.3.0 cherry-pick request: Update tensorboard dependency to 2.3
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#41636 [CherryPick 2.3] Going back to forcing embedding layer variables on the CPU even within a tf.function as this is breaking some user code.
  tensorflow/python/keras/layers/embeddings.py
Labels: cla: yes

#40901 Type annotations to improve the tracing process of tf.function
  RELEASE.md
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/function.py
  tensorflow/python/eager/function_test.py
  tensorflow/tools/api/golden/v1/tensorflow.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.pbtxt
Labels: cla: yes, ready to pull, size:M

#41429 Scalar shape
  tensorflow/c/ops.cc
  tensorflow/c/ops.h
  tensorflow/c/ops_test.cc
Labels: API review, cla: yes, ready to pull, size:S

#41644 Updating estimator version after estimator final release
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#41638 Adding TF_UNUSED_VARIABLE
  tensorflow/core/platform/macros.h
Labels: cla: yes, comp:core, ready to pull, size:XS

#41622 S3 delete file delete/create dir
  tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc
Labels: cla: yes, ready to pull, size:M

#40134 Fix missing tick in BatchNorm doc
  tensorflow/python/keras/layers/normalization_v2.py
  tensorflow/python/keras/layers/recurrent.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#41399 [Grappler] Fix bug in UpdateSqueezeDims
  tensorflow/core/grappler/optimizers/generic_layout_optimizer_transposer.cc
  tensorflow/core/grappler/optimizers/generic_layout_optimizer_transposer_test.cc
Labels: cla: yes, comp:grappler, ready to pull, size:M

#41672 Clone rel/ directory structure
  tensorflow/tools/ci_build/rel/macos/cpu_py35_nonpip.sh
  tensorflow/tools/ci_build/rel/macos/cpu_py35_pip.sh
  tensorflow/tools/ci_build/rel/macos/cpu_py36_nonpip.sh
  tensorflow/tools/ci_build/rel/macos/cpu_py36_pip.sh
  tensorflow/tools/ci_build/rel/macos/cpu_py37_nonpip.sh
  tensorflow/tools/ci_build/rel/macos/cpu_py37_pip.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_py35_nonpip.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_py35_pip.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_py36_nonpip.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_py36_pip.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_py37_nonpip.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_py37_pip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_pip_on_cpu.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py35_nonpip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py35_pip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py36_nonpip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py36_pip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py37_nonpip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py37_pip.sh
  tensorflow/tools/ci_build/rel/windows/cpu_py35.bat
  tensorflow/tools/ci_build/rel/windows/cpu_py36.bat
  tensorflow/tools/ci_build/rel/windows/cpu_py37.bat
  tensorflow/tools/ci_build/rel/windows/gpu_pip_on_cpu.bat
  tensorflow/tools/ci_build/rel/windows/gpu_py35.bat
  tensorflow/tools/ci_build/rel/windows/gpu_py36.bat
  tensorflow/tools/ci_build/rel/windows/gpu_py37.bat
  tensorflow/tools/ci_build/rel/windows/libtensorflow_cpu.sh
  tensorflow/tools/ci_build/rel/windows/libtensorflow_gpu.sh
Labels: cla: yes

#41509 Add string_print_f fuzzer
  tensorflow/security/fuzzing/BUILD
  tensorflow/security/fuzzing/stringprintf_fuzz.cc
Labels: cla: yes, ready to pull, size:M, stat:awaiting response

#39562 [ROCm] NonMaxSuppression
  tensorflow/core/kernels/non_max_suppression_op.cu.cc
  tensorflow/core/kernels/non_max_suppression_op.h
  tensorflow/core/kernels/non_max_suppression_op_gpu_test.cc
  tensorflow/core/kernels/ops_testutil.cc
Labels: awaiting review, cla: yes, comp:gpu, ready to pull, size:M

#41618 Gcs filesystem test part 1
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.cc
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.h
  tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem_test.cc
Labels: cla: yes, ready to pull, size:M

#40701 Update release notes for TensorFlow 2.3.0
  RELEASE.md
Labels: cla: yes, size:XS

#41670 Update version numbers for TensorFlow 2.3.0
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#41412 Reuse HumanString in HumanStringWithLayout
  tensorflow/compiler/xla/shape_util.cc
Labels: awaiting review, cla: yes, comp:xla, ready to pull, size:XS

#41687 Also copy ubuntu sanity build to new layout
  tensorflow/tools/ci_build/rel/ubuntu/sanity.sh
Labels: cla: yes

#41640 Raise error when calling .fit() w/ batch_size and a tf dataset
  tensorflow/python/keras/engine/data_adapter.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#41631 [XLA] Extend the Algebraic Simplifier to convert Pow(x, 3) -> x*x*x.
  tensorflow/compiler/xla/service/algebraic_simplifier.cc
  tensorflow/compiler/xla/service/algebraic_simplifier_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:S

#38960 go: Add input mapping option when importing Graph
  tensorflow/go/graph.go
  tensorflow/go/graph_test.go
Labels: cla: yes, ready to pull, size:M

#41662 NFC - minor spelling tweaks
  RELEASE.md
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/infer_fusibility_op_interface.td
  tensorflow/core/framework/BUILD
  tensorflow/lite/delegates/utils/dummy_delegate/README.md
  tensorflow/lite/g3doc/convert/metadata.md
  tensorflow/lite/g3doc/performance/gpu.md
  tensorflow/lite/micro/tools/make/targets/xtensa_hifi/README.md
  tensorflow/lite/tools/benchmark/README.md
  tensorflow/lite/tools/delegates/README.md
Labels: cla: yes, comp:lite, ready to pull, size:S

#41665 Fix messy formating in tf.linalg.inv's docstring
  tensorflow/core/api_def/base_api/api_def_MatrixInverse.pbtxt
Labels: cla: yes, comp:core, prtype:bugfix, ready to pull, size:XS
