Repository tensorflow/tensorflow, pull requests merged in 2020-05, with the labels that each got.

#38957 Update iOS related rules
  tensorflow/lite/special_rules.bzl
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull, size:S

#39011 NFC - minor spelling tweaks in pbtxt
  tensorflow/core/api_def/base_api/api_def_AdjustHue.pbtxt
  tensorflow/core/api_def/base_api/api_def_AdjustSaturation.pbtxt
  tensorflow/core/api_def/base_api/api_def_BoostedTreesCalculateBestFeatureSplitV2.pbtxt
  tensorflow/core/api_def/base_api/api_def_CudnnRNN.pbtxt
  tensorflow/core/api_def/base_api/api_def_CudnnRNNV2.pbtxt
  tensorflow/core/api_def/base_api/api_def_CudnnRNNV3.pbtxt
  tensorflow/core/api_def/base_api/api_def_GenerateBoundingBoxProposals.pbtxt
  tensorflow/core/api_def/base_api/api_def_ParseSequenceExampleV2.pbtxt
  tensorflow/core/api_def/base_api/api_def_QuantizedMatMulWithBias.pbtxt
  tensorflow/core/api_def/base_api/api_def_QuantizedMatMulWithBiasAndRelu.pbtxt
  tensorflow/core/api_def/base_api/api_def_QuantizedMatMulWithBiasAndReluAndRequantize.pbtxt
  tensorflow/core/api_def/base_api/api_def_SparseSegmentMeanWithNumSegments.pbtxt
  tensorflow/core/api_def/base_api/api_def_SparseSegmentSqrtNWithNumSegments.pbtxt
  tensorflow/core/api_def/base_api/api_def_SparseSegmentSumWithNumSegments.pbtxt
  tensorflow/core/api_def/base_api/api_def_Substr.pbtxt
  tensorflow/go/op/wrappers.go
Labels: cla: yes, ready to pull, size:M

#38959 Add gcs_file_system to be part of the pip wheel build
  tensorflow/core/platform/default/build_config.bzl
Labels: cla: yes, ready to pull, size:XS

#39048 [INTEL_MKL] Threadpool changes with dnnl 1.4 release.
  tensorflow/core/util/mkl_threadpool.h
Labels: cla: yes, comp:mkl, ready to pull, size:S

#38895 Change code examples in tf.strings.format to use TF 2.x
  tensorflow/python/ops/string_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#38079 Use fixed width types consistently
  tensorflow/lite/micro/kernels/pad_test.cc
Labels: cla: yes, comp:micro, ready to pull, size:S

#38728 [ROCm] Disabling a subtest within //tensorflow/python/eager:function_test_gpu…
  tensorflow/python/eager/function_test.py
Labels: cla: yes, ready to pull, size:S

#38774 Fix test to run on all filesystem
  tensorflow/c/experimental/filesystem/modular_filesystem_test.cc
Labels: cla: yes, ready to pull, size:S

#38848 Use TF_CALL_GPU_ALL_TYPES for variable ops
  tensorflow/core/kernels/variable_ops.cc
  tensorflow/python/kernel_tests/variable_ops_test.py
Labels: cla: yes, ready to pull, size:XS

#39172 Resubmit of PR 38848 but only support complex64 and complex128
  tensorflow/core/kernels/variable_ops.cc
  tensorflow/python/kernel_tests/variable_ops_test.py
Labels: cla: yes, ready to pull, size:XS

#39188 Add Python 3.8 to classifiers and remove old ones
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#39119 Spellcheck of filenames a-e in tensorflow/python/keras/layers/.
  tensorflow/python/keras/layers/convolutional.py
  tensorflow/python/keras/layers/core.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#39123 Fix Huber Loss crashes due to data type mismatch
  tensorflow/python/keras/losses.py
  tensorflow/python/keras/losses_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#39151 TF-TRT ConvertTranspose in dynamic shape mode
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L

#39159 Fix issue in boolean_mask when axis is passed as a tensor
  tensorflow/python/kernel_tests/array_ops_test.py
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#39131 Fix BatchNormalization issue with virtual_batch_size when shape has None
  tensorflow/python/keras/layers/normalization.py
  tensorflow/python/keras/layers/normalization_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#39193 Increase Apache Spark version to 2.4.5 to handle GitHub Security Alert
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
Labels: cla: yes

#38965 [ROCm] Adding no_rocm tag to tests currently failing on ROCm platform
  tensorflow/python/keras/layers/BUILD
  tensorflow/python/keras/layers/preprocessing/BUILD
  tensorflow/python/keras/mixed_precision/experimental/BUILD
  tensorflow/python/kernel_tests/BUILD
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#39194 Disable OwnedMultiDeviceIterator on TPU Pod.
  tensorflow/python/distribute/tpu_strategy.py
Labels: cla: yes

#39202 Update RELEASE.md
  RELEASE.md
Labels: cla: yes

#39201 Update version numbers for TensorFlow 2.2.0
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#38899 Fix exception handling of tf.histogram_fixed_width_bins
  tensorflow/python/ops/histogram_ops.py
  tensorflow/python/ops/histogram_ops_test.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#38869 [TFLite 16x8] Versioning of 16x8 reference kernels
  tensorflow/lite/kernels/register.cc
  tensorflow/lite/toco/tflite/op_version.cc
  tensorflow/lite/tools/versioning/op_version.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#39124 Add S3 filesystem support on Windows
  tensorflow/core/platform/default/build_config.bzl
  tensorflow/core/platform/s3/BUILD
  tensorflow/core/platform/s3/s3_file_system.cc
  tensorflow/core/platform/s3/s3_file_system_test.cc
  third_party/aws/BUILD.bazel
  third_party/aws/aws-c-common.bazel
  third_party/aws/aws-checksums.bazel
Labels: cla: yes, ready to pull, size:M

#38579 update dataset_ops.py
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, ready to pull, size:XS

#38802 Remove calls to deprecated cusparse APIs
  tensorflow/core/kernels/cuda_sparse.cc
  tensorflow/core/kernels/cuda_sparse.h
  tensorflow/core/kernels/sparse/add_op.cc
  tensorflow/core/kernels/sparse/kernels.h
  tensorflow/core/kernels/sparse/mat_mul_op.cc
  tensorflow/core/kernels/sparse/sparse_mat_mul_op.cc
Labels: cla: yes, size:XL

#39181 Added TANH op and test to micro
  tensorflow/lite/micro/kernels/all_ops_resolver.cc
  tensorflow/lite/micro/kernels/elementwise.cc
  tensorflow/lite/micro/kernels/elementwise_test.cc
  tensorflow/lite/micro/kernels/micro_ops.h
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:M

#39225 make `bazel build` work on aarch64/arm linux
  third_party/remote_config/remote_platform_configure.bzl
Labels: cla: yes, ready to pull, size:XS

#39023 Fix misspelling in tensorflow/lite/tools
  tensorflow/lite/tools/benchmark/benchmark_performance_options.cc
  tensorflow/lite/tools/delegates/external_delegate_provider.cc
  tensorflow/lite/tools/evaluation/evaluation_delegate_provider.h
  tensorflow/lite/tools/evaluation/evaluation_delegate_provider_test.cc
  tensorflow/lite/tools/make/Makefile
  tensorflow/lite/tools/optimize/operator_property.h
  tensorflow/lite/tools/optimize/python/modify_model_interface_lib.py
  tensorflow/lite/tools/versioning/op_version.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#39183 TF-TRT squeeze op conversion with empty squeeze_dims attribute
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, ready to pull, size:L

#38705 Support options(environment variable) to enable grpc reuse port.
  tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc
Labels: cla: yes, ready to pull, size:S

#39137 Add cardinality calculation for Dataset.unbatch() when possible
  tensorflow/core/kernels/data/experimental/unbatch_dataset_op.cc
  tensorflow/python/data/experimental/kernel_tests/cardinality_test.py
Labels: cla: yes, comp:data, prtype:bugfix, ready to pull, size:S

#38020 Fix document error for ApplyFtrl, ApplyFtrlV2 and SparseApplyFtrlV2
  tensorflow/core/api_def/base_api/api_def_ApplyFtrl.pbtxt
  tensorflow/core/api_def/base_api/api_def_ApplyFtrlV2.pbtxt
  tensorflow/core/api_def/base_api/api_def_SparseApplyFtrlV2.pbtxt
Labels: cla: yes, ready to pull, size:S

#39153 TF-TRT test ConvertUnary in dynamic shape mode.
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L

#39231 Add mlir graph optimization to the build
  tensorflow/compiler/mlir/python/BUILD
Labels: cla: yes, ready to pull, size:XL

#39283 [ROCm] Fix for ROCm CSB breakage on 200507
  tensorflow/core/kernels/cuda_sparse.h
  tensorflow/core/kernels/sparse/mat_mul_op.cc
  tensorflow/core/kernels/sparse/sparse_mat_mul_op.cc
Labels: cla: yes, ready to pull, size:S

#39242 Static link GPU OpenGL tests
  tensorflow/lite/delegates/gpu/gl/kernels/BUILD
Labels: cla: yes, comp:lite, ready to pull, size:S

#35904 Pydoc fixes for StructuredTensor
  tensorflow/python/ops/structured/structured_tensor.py
  tensorflow/python/ops/structured/structured_tensor_test.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#38354 [TFLite 16x8] Tanh/Sigmoid implementation is extended to the general parameter scale
  tensorflow/lite/kernels/activations.cc
  tensorflow/lite/kernels/activations_test.cc
  tensorflow/lite/kernels/internal/reference/integer_ops/logistic.h
  tensorflow/lite/kernels/internal/reference/integer_ops/tanh.h
  tensorflow/lite/kernels/register.cc
  tensorflow/lite/toco/tflite/op_version.cc
  tensorflow/lite/tools/versioning/op_version.cc
Labels: cla: yes, comp:lite, ready to pull, size:L

#39150 [TFLite 16x8] Leaky Relu reference kernel for activations in int16
  tensorflow/lite/kernels/activations.cc
  tensorflow/lite/kernels/activations_test.cc
  tensorflow/lite/toco/tflite/op_version.cc
  tensorflow/lite/tools/optimize/operator_property.cc
  tensorflow/lite/tools/versioning/op_version.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#39352 Update version numbers for TensorFlow 1.15.3
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#39354 Update version numbers for TensorFlow 2.1.1
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#39356 Update version numbers for TensorFlow 2.0.2
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#37064 [Intel Mkl] Upgrade Sqlite3 to fix CVE-2019-19880 CVE-2019-19244 and …
  tensorflow/workspace.bzl
Labels: cla: yes, size:XS, waiting for patch release

#37658 get is_training from bn_op so moving_mean and moving_var tensor is se…
  tensorflow/contrib/quantize/python/fold_batch_norms.py
Labels: cla: yes, size:XS, waiting for patch release

#37663 r1.15 cherry-pick request: Fix linking issue on TFLite r1.15 branch.
  tensorflow/lite/tools/make/Makefile
Labels: cla: yes, comp:lite, type:build/install, waiting for patch release

#38276 Cherry-pick curl CVE fix
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes, waiting for patch release

#39087 Fix dynamic display for PyCharm (r1.15)
  tensorflow/python/keras/utils/generic_utils.py
Labels: cla: yes, kokoro:force-run, size:XS, waiting for patch release

#39034 [r1.15-CherryPick] Add __reduce__ method in virtual pip root due to lazy loading
  tensorflow/virtual_root_template_v1.__init__.py
  tensorflow/virtual_root_template_v2.__init__.py
Labels: cla: yes, waiting for patch release

#38408 Cherrypick libjpeg-turbo version update
  third_party/jpeg/BUILD.bazel
  third_party/jpeg/workspace.bzl
Labels: cla: yes, waiting for patch release

#39295 API to provide custom table level optimizers in TPUEmbedding.
  tensorflow/python/tpu/tpu_embedding.py
Labels: cla: yes, waiting for patch release

#39192 Increase Apache Spark version to 2.4.5 to handle GitHub Security Alert
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
Labels: cla: yes, waiting for patch release

#39191 Increase Apache Spark version to 2.4.5 to handle GitHub Security Alert
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
Labels: cla: yes, waiting for patch release

#39086 Fix dynamic display for PyCharm (r2.0)
  tensorflow/python/keras/utils/generic_utils.py
Labels: cla: yes, size:XS, waiting for patch release

#38275 Cherry-pick curl CVE fix
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes, waiting for patch release

#38407 Cherrypick libjpeg-turbo version update
  third_party/jpeg/BUILD.bazel
  third_party/jpeg/workspace.bzl
Labels: cla: yes, waiting for patch release

#37063 [Intel Mkl] Upgrade Sqlite3 to fix CVE-2019-19880 CVE-2019-19244 and …
  tensorflow/workspace.bzl
Labels: cla: yes, size:XS, waiting for patch release

#39383 Manual cherrypick of #38292
  tensorflow/compiler/jit/kernels/BUILD
  tensorflow/compiler/jit/kernels/xla_ops.cc
  tensorflow/compiler/xla/executable_run_options.h
  tensorflow/compiler/xla/service/generic_transfer_manager.cc
  tensorflow/compiler/xla/service/gpu/convolution_thunk.cc
  tensorflow/compiler/xla/service/gpu/cudnn_batchnorm_thunk.cc
  tensorflow/compiler/xla/service/gpu/custom_call_thunk.cc
  tensorflow/compiler/xla/service/gpu/gpu_executable.cc
  tensorflow/compiler/xla/service/gpu/thunk.h
  tensorflow/compiler/xla/service/gpu/tuple_thunk.cc
Labels: cla: yes

#39311 Fix bogomips extraction on s390x arch
  tensorflow/core/platform/profile_utils/cpu_utils.cc
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#39239 add -DDEBUG_BUILD to dbg profile
  .bazelrc
Labels: cla: yes, ready to pull, size:XS

#39062 [INTEL MKL] Fix for build error.
  tensorflow/core/common_runtime/BUILD
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
Labels: cla: yes, ready to pull, size:XS

#36773 Support Keras grouped convolutions
  tensorflow/python/keras/layers/convolutional.py
  tensorflow/python/keras/layers/convolutional_test.py
  tensorflow/python/ops/nn_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.-conv1-d.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.-conv2-d.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.-conv3-d.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.-convolution1-d.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.-convolution2-d.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.-convolution3-d.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.-conv1-d.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.-conv2-d.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.-conv3-d.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.-convolution1-d.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.-convolution2-d.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.-convolution3-d.pbtxt
Labels: cla: yes, comp:keras, ready to pull, size:M

#39190 Increase Apache Spark version to 2.4.5 to handle GitHub Security Alert
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
Labels: cla: yes, waiting for patch release

#39085 Fix dynamic display for PyCharm (r2.1)
  tensorflow/python/keras/utils/generic_utils.py
Labels: cla: yes, size:XS, waiting for patch release

#38441 [ROCm] Update tensorflow 2.1 release branch ROCm path to build with hipclang
  tensorflow/core/kernels/conv_2d_gpu.h
  tensorflow/core/lib/bfloat16/bfloat16.h
  tensorflow/tools/ci_build/Dockerfile.rocm
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_rocm.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, waiting for patch release

#38406 Cherrypick libjpeg-turbo version update
  third_party/jpeg/BUILD.bazel
  third_party/jpeg/workspace.bzl
Labels: cla: yes, waiting for patch release

#38274 Cherry-pick curl CVE fix
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes, waiting for patch release

#39043 Remove unnecessary objc_library target
  tensorflow/lite/experimental/ios/BUILD.apple
  tensorflow/lite/experimental/swift/BUILD.apple
Labels: cla: yes, comp:lite, ready to pull, size:S

#37062 [Intel Mkl] Upgrade Sqlite3 to fix CVE-2019-19880 CVE-2019-19244 and …
  tensorflow/workspace.bzl
Labels: cla: yes, size:XS, waiting for patch release

#37775 fix a compile error of r2.1 caused by skylib address invalid.
  WORKSPACE
Labels: cla: yes, size:XS, waiting for patch release

#39200 [INTEL MKL] Fix for UT failure in graph_runner_test
  tensorflow/core/common_runtime/BUILD
Labels: cla: yes, ready to pull, size:XS

#39254 [XLA] Adapting HLO-to-LHLO-legalization to use Buffer Assignment
  tensorflow/compiler/mlir/xla/tests/hlo-legalize-to-lhlo.mlir
  tensorflow/compiler/mlir/xla/transforms/hlo_legalize_to_lhlo.cc
  tensorflow/compiler/mlir/xla/transforms/rewriters.h
  tensorflow/compiler/xla/service/mlir_gpu/kernel_lowering.cc
Labels: cla: yes, ready to pull, size:L

#39443 Cherrypick keras fix
  tensorflow/BUILD
  tensorflow/api_template.__init__.py
  tensorflow/api_template_v1.__init__.py
  tensorflow/python/compat/BUILD
  tensorflow/python/compat/v2_compat.py
  tensorflow/python/tf2.py
  tensorflow/python/tools/api/generator/api_gen.bzl
  tensorflow/tools/api/tests/api_compatibility_test.py
  tensorflow/tools/api/tests/module_test.py
Labels: cla: yes

#39285 [INTEL MKL] Fix dequantize op regression issue
  tensorflow/core/kernels/dequantize_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#39349 Update release notes for TensorFlow 1.15.3
  RELEASE.md
Labels: cla: yes

#39355 Update release notes for TensorFlow 2.0.2
  RELEASE.md
Labels: cla: yes

#39353 Update release notes for TensorFlow 2.1.1
  RELEASE.md
Labels: cla: yes

#39399 Refactoring: Format String -> Format Method
  configure.py
Labels: cla: yes, ready to pull, size:S

#39477 Pin keras_preprocessing to 1.1.0 instead of accidentally installing 1…
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#39330 Added POC for tf_program
  tensorflow/compiler/mlir/python/mlir_wrapper/BUILD
  tensorflow/compiler/mlir/python/mlir_wrapper/attrs.cc
  tensorflow/compiler/mlir/python/mlir_wrapper/basic_classes.cc
  tensorflow/compiler/mlir/python/mlir_wrapper/builders.cc
  tensorflow/compiler/mlir/python/mlir_wrapper/filecheck_wrapper.cc
  tensorflow/compiler/mlir/python/mlir_wrapper/mlir_wrapper.cc
  tensorflow/compiler/mlir/python/mlir_wrapper/mlir_wrapper.h
  tensorflow/compiler/mlir/python/mlir_wrapper/ops.cc
  tensorflow/compiler/mlir/python/mlir_wrapper/types.cc
  tensorflow/python/tf_program/BUILD
  tensorflow/python/tf_program/mlir_gen.py
  tensorflow/python/tf_program/pywrap_tfd.py
  tensorflow/python/tf_program/tests/BUILD
  tensorflow/python/tf_program/tests/mlir_gen_test.py
Labels: cla: yes, ready to pull, size:XL

#39104 [Lite] data: Fix memory leak
  tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#39171 Respect inference type in DefaultQuantParamsPass
  tensorflow/compiler/mlir/lite/quantization/quantization_config.h
  tensorflow/compiler/mlir/lite/tf_tfl_passes.cc
  tensorflow/compiler/mlir/lite/transforms/default_quant_params.cc
  tensorflow/compiler/mlir/lite/transforms/passes.h
Labels: cla: yes, ready to pull, size:S

#39327 [XLA] Fix a bug in the copy operations
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc
  tensorflow/compiler/xla/service/gpu/kernel_mapping_scheme.h
  tensorflow/compiler/xla/service/gpu/tests/BUILD
  tensorflow/compiler/xla/service/gpu/tests/gpu_copy_alone_test.cc
Labels: cla: yes, ready to pull, size:M

#39461 Update docstring of tf.split to clarify num_or_size_splits
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#39281 add __cudaInitModule to cudart_stub.cc
  tensorflow/stream_executor/cuda/cudart_stub.cc
Labels: cla: yes, ready to pull, size:XS

#39481 Fix the issue of tf.divide's return value is not a tensor
  tensorflow/python/ops/math_ops.py
  tensorflow/python/ops/math_ops_test.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#39444 [tflite] add fp32->fp16 relaxation option to NNAPI delegate
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
  tensorflow/lite/delegates/nnapi/nnapi_delegate.h
  tensorflow/lite/delegates/nnapi/nnapi_delegate_kernel.h
  tensorflow/lite/tools/benchmark/benchmark_performance_options.cc
  tensorflow/lite/tools/delegates/nnapi_delegate_provider.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#39525 Fix tests when `tf._major_api_version` does not exist
  tensorflow/tools/api/tests/module_test.py
Labels: cla: yes

#39368 Remove Python2 badge about raspberryPi in README.md
  README.md
Labels: cla: yes, ready to pull, size:XS

#39127 Removing unreachable return
  tensorflow/lite/python/op_hint.py
Labels: cla: yes, comp:lite, ready to pull, size:XS

#39511 Removes duplicate space from retracing warning message
  tensorflow/python/eager/def_function.py
Labels: cla: yes, ready to pull, size:XS

#39441 Switch Raspberry Pi building to unofficial GCC 6.5 toolchain
  arm_compiler.BUILD
  tensorflow/lite/tools/pip_package/setup.py
  tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
  tensorflow/workspace.bzl
  third_party/toolchains/cpus/arm/cc_config.bzl.tpl
Labels: TF 1.15, cla: yes, type:build/install

#39288 better error msg for incorrect WAV format chunk
  tensorflow/core/lib/wav/wav_io.cc
Labels: cla: yes, ready to pull, size:XS

#39426 Add mlir_graph_optimization_pass.h header to pip wheel
  tensorflow/tools/pip_package/BUILD
Labels: cla: yes, ready to pull, size:XS

#39318 Adds support for xcore.ai platform in Micro
  tensorflow/lite/micro/testing/test_xcore_binary.sh
  tensorflow/lite/micro/tools/make/download_and_extract.sh
  tensorflow/lite/micro/tools/make/targets/xcore_makefile.inc
  tensorflow/lite/micro/xcore/README.md
  tensorflow/lite/micro/xcore/debug_log.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:M

#39384 Update protobuf-java to 3.9.2
  tensorflow/java/maven/proto/pom.xml
Labels: cla: yes, ready to pull, size:XS

#39412 add bias to transpose_conv.py TESTs.
  tensorflow/lite/testing/op_tests/transpose_conv.py
Labels: cla: yes, comp:lite, ready to pull, size:S

#39420 [INTEL MKL] enabling mkldnn threadpool build options
  .bazelrc
  tensorflow/tensorflow.bzl
  third_party/mkl/build_defs.bzl
  third_party/mkl_dnn/BUILD
  third_party/mkl_dnn/build_defs.bzl
  third_party/mkl_dnn/mkldnn_v1.BUILD
Labels: cla: yes, comp:mkl, ready to pull, size:M

#38016 [INTEL MKL] Fusing BN and Relu in mkl path
  tensorflow/core/common_runtime/mkl_layout_pass.cc
  tensorflow/core/common_runtime/mkl_layout_pass_test.cc
  tensorflow/core/grappler/optimizers/mkl_remapper_test.cc
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
  tensorflow/core/ops/mkl_nn_ops.cc
  tensorflow/core/ops/nn_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:L

#38600 Grpc server uses provided host name/ip instead of localhost if possible
  tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc
  tensorflow/core/distributed_runtime/rpc/grpc_server_lib.h
Labels: cla: yes, prtype:bugfix, ready to pull, size:S

#39541 Autograph decorated functions with tf.map_fn
  tensorflow/python/kernel_tests/map_fn_test.py
  tensorflow/python/ops/map_fn.py
Labels: cla: yes, ready to pull, size:S

#39548 [INTEL MKL] Fix conv_ops_test and remapper_test
  tensorflow/core/grappler/optimizers/remapper_test.cc
  tensorflow/core/kernels/conv_ops_test.cc
Labels: cla: yes, ready to pull, size:S

#39573 Update SECURITY.md
  SECURITY.md
Labels: cla: yes, ready to pull, size:XS

#39427 [ROCm] hip-clang / ROCm 3.5 build fixes
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
  tensorflow/stream_executor/rocm/rocm_gpu_executor.cc
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_rocm.tpl
  third_party/gpus/cuda_configure.bzl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, ready to pull, size:S

#39155 TF-TRT test activation converter
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L, stat:awaiting response

#38666 Fix a bug related to build TF Lite on RPI Zero.
  tensorflow/lite/g3doc/guide/build_rpi.md
  tensorflow/lite/tools/make/targets/rpi_makefile.inc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#39500 Fix typo preventing compilation
  tensorflow/lite/micro/examples/person_detection/esp/app_camera_esp.h
Labels: cla: yes, comp:micro, ready to pull, size:XS

#39725 Fix sha256sum issue of mkl_dnn/oneDNN
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull, size:XS

#37087 docs: add tip to prefer tf.shape(x) over x.shape in custom layers/models
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:XS

#39042 Fixed recompute grad issue - no memory savings
  tensorflow/python/eager/forwardprop_test.py
  tensorflow/python/keras/integration_test/BUILD
  tensorflow/python/keras/integration_test/gradient_checkpoint_test.py
  tensorflow/python/ops/custom_gradient.py
  tensorflow/python/ops/gradients_test.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#38549 Fix issue in tf.image.extract_glimpse
  RELEASE.md
  tensorflow/core/api_def/base_api/api_def_ExtractGlimpseV2.pbtxt
  tensorflow/core/kernels/attention_ops.cc
  tensorflow/core/kernels/eigen_attention.h
  tensorflow/core/ops/image_ops.cc
  tensorflow/python/kernel_tests/attention_ops_test.py
  tensorflow/python/ops/image_ops_impl.py
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: API review, cla: yes, prtype:bugfix, ready to pull, size:M

#38630 [Intel MKL] Enable BF16 Softmax/SoftmaxGrad
  tensorflow/core/kernels/mkl_tmp_bf16_ops.cc
  tensorflow/core/kernels/reduction_ops.h
  tensorflow/core/ops/nn_grad.cc
  tensorflow/python/ops/math_ops_test.py
  tensorflow/python/ops/nn_grad_test.py
  tensorflow/python/ops/nn_test.py
Labels: cla: yes, comp:mkl, ready to pull, size:S

#39404 [tflite] reformat/cleanup label_image readme.md
  tensorflow/lite/examples/label_image/README.md
  tensorflow/lite/examples/label_image/label_image.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#38940 Update check_cuda_libs.py
  third_party/gpus/check_cuda_libs.py
Labels: cla: yes, ready to pull, size:XS

#39325 [INTEL MKL] Enabling DNNL SGEMM and removing all code related to MKL matmuls.
  tensorflow/core/common_runtime/mkl_layout_pass.cc
  tensorflow/core/kernels/mkl_matmul_op.cc
  tensorflow/core/ops/math_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#37936 TFLu: remove -fno-builtin compiler flag
  tensorflow/lite/micro/tools/make/targets/apollo3evb_makefile.inc
  tensorflow/lite/micro/tools/make/targets/bluepill_makefile.inc
  tensorflow/lite/micro/tools/make/targets/ecm3531_makefile.inc
  tensorflow/lite/micro/tools/make/targets/hexagon_makefile.inc
  tensorflow/lite/micro/tools/make/targets/mcu_riscv_makefile.inc
  tensorflow/lite/micro/tools/make/targets/stm32f4_makefile.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XS

#39717 Update tpu_strategy.py; replacing np.rank with np.ndim
  tensorflow/python/distribute/tpu_strategy.py
Labels: cla: yes, ready to pull, size:XS

#39840 Fix typo in Core ML Delegate docs
  tensorflow/lite/g3doc/performance/coreml_delegate.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#39821 [Lite]: Fix memory leak from model
  tensorflow/lite/experimental/delegates/coreml/builders/op_builder.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#39762 include tf_types.def as part of the tf-nightly pip install
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:XS

#39204 TF-TRT Conv2d op conversion dynamic shape mode
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L, stat:awaiting response

#39826 Fix incorrect reference of np.assert_allclose (should be np.testing.assert_allclose)
  tensorflow/python/ops/check_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#39095 Addition in resources section
  README.md
Labels: cla: yes, ready to pull, size:XS

#38958 Update examples in docstring to use TF 2.x code
  tensorflow/python/ops/histogram_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#39723 TFLu: Update CMSIS-NN glue interface in conv.cc
  tensorflow/lite/micro/kernels/cmsis-nn/conv.cc
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, comp:micro, ready to pull, size:M

#39424 Add uint32/uint64 support for tf.tile
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/tile_functor_cpu_uint32.cc
  tensorflow/core/kernels/tile_functor_cpu_uint64.cc
  tensorflow/core/kernels/tile_ops.cc
  tensorflow/python/kernel_tests/shape_ops_test.py
Labels: cla: yes, ready to pull, size:M

#39166 Improve GPU BW throughput of transpose by vectorization
  tensorflow/core/kernels/conv_2d_gpu.h
Labels: cla: yes, ready to pull, size:M

#38956 Add ios_static_framework bazel target for Swift
  tensorflow/lite/experimental/swift/BUILD.apple
Labels: cla: yes, comp:lite, ready to pull, size:S

#39825 Add complex tensor support for tf.debugging.assert_near
  tensorflow/python/kernel_tests/check_ops_test.py
  tensorflow/python/ops/check_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#39156 TF-TRT enable BiasAdd op in dynamic shape mode
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L

#39849 Move -no-as-needed to the top of the linking command line in the cuda toolchain
  third_party/gpus/crosstool/cc_toolchain_config.bzl.tpl
  third_party/nccl/archive.BUILD
Labels: cla: yes, ready to pull, size:S

#37213 Fix plot_model for .pdf files
  tensorflow/python/keras/utils/vis_utils.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#39791 Improving the performance of reads from S3 by parallelizing downloads
  tensorflow/core/kernels/data/tf_record_dataset_op.cc
  tensorflow/core/platform/s3/s3_file_system.cc
  tensorflow/core/platform/s3/s3_file_system.h
  tensorflow/core/platform/s3/s3_file_system_test.cc
  third_party/aws/workspace.bzl
Labels: cla: yes, ready to pull, size:L

#39519 [INTEL MKL] Threadpool changes for pooling ops.
  tensorflow/core/kernels/mkl_avgpooling_op.cc
  tensorflow/core/kernels/mkl_maxpooling_op.cc
  tensorflow/core/kernels/mkl_pooling_ops_common.cc
  tensorflow/core/kernels/mkl_pooling_ops_common.h
Labels: cla: yes, comp:mkl, ready to pull, size:M

#39472 [INTEL MKL] Threadpool support for quantize, dequantize and transpose op.
  tensorflow/core/kernels/mkl_dequantize_op.cc
  tensorflow/core/kernels/mkl_quantize_op.cc
  tensorflow/core/kernels/mkl_transpose_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#39473 [INTEL MKL] Threadpool api support for misc ops.
  tensorflow/core/kernels/mkl_lrn_op.cc
  tensorflow/core/kernels/mkl_requantize_per_channel_op.cc
  tensorflow/core/kernels/mkl_slice_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#39518 [INTEL MKL] threadpool support for mkl_conv_bwd ops.
  tensorflow/core/kernels/mkl_conv_grad_filter_ops.cc
  tensorflow/core/kernels/mkl_conv_grad_input_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#39471 [INTEL MKL] Threadpool api implementation for concat and fused batchnorm op.
  tensorflow/core/kernels/mkl_concat_op.cc
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#38835 [Intel MKL] Implement new DNNL1.x MatMul primitive cache
  tensorflow/core/kernels/mkl_matmul_op.cc
  tensorflow/core/kernels/mkl_matmul_ops_common.h
Labels: cla: yes, comp:mkl, ready to pull, size:L, stat:awaiting response

#39914 [ROCm] Fix for ROCm CSB breakage - 200527
  tensorflow/python/keras/integration_test/gradient_checkpoint_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#39911 in resolution of [Wsign-compare] warning id 1
  tensorflow/core/platform/protobuf.cc
Labels: cla: yes, ready to pull, size:XS

#39887 Prefer generator expressions over list comprehensions
  tensorflow/lite/python/lite.py
  tensorflow/python/eager/function.py
  tensorflow/python/framework/subscribe.py
  tensorflow/python/framework/test_util.py
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/layers/preprocessing/category_crossing.py
  tensorflow/python/keras/layers/preprocessing/hashing.py
  tensorflow/python/keras/saving/hdf5_format.py
  tensorflow/tools/dockerfiles/assembler.py
  third_party/gpus/check_cuda_libs.py
Labels: cla: yes, ready to pull, size:S

#39529 Add complex64/complex128 support for tf.math.l2_normalize
  tensorflow/python/ops/nn_impl.py
  tensorflow/python/ops/nn_test.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#39134 Fix ValueError with tf.keras.metrics.Recall and float64 keras backend
  tensorflow/python/keras/metrics_test.py
  tensorflow/python/keras/utils/metrics_utils.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#39517 [INTEL MKL] threadpool support for relu, eltwise and softmax.
  tensorflow/core/kernels/mkl_aggregate_ops.cc
  tensorflow/core/kernels/mkl_relu_op.cc
  tensorflow/core/kernels/mkl_softmax_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#36316 Pad keras.backend.ctc_decode output to consistent shape
  tensorflow/python/keras/backend.py
  tensorflow/python/keras/backend_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#39650 Allow single element padding_values to be broadcasted to a structure for tf.data.Dataset.padded_batch
  tensorflow/python/data/kernel_tests/padded_batch_test.py
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, ready to pull, size:S

#38092 Remove expired forward compatibility horizons
  tensorflow/compiler/tests/fused_batchnorm_test.py
  tensorflow/python/keras/layers/normalization.py
  tensorflow/python/ops/nn_fused_batchnorm_test.py
  tensorflow/python/ops/nn_impl.py
Labels: cla: yes, ready to pull, size:L

#36990 Fix label_smoothing in multidimensional CategoricalCrossentropy.
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#37438 Minor refactoring and robust mode check for imagenet_utils.py
  tensorflow/python/keras/applications/densenet.py
  tensorflow/python/keras/applications/imagenet_utils.py
  tensorflow/python/keras/applications/imagenet_utils_test.py
  tensorflow/python/keras/applications/inception_resnet_v2.py
  tensorflow/python/keras/applications/inception_v3.py
  tensorflow/python/keras/applications/mobilenet.py
  tensorflow/python/keras/applications/mobilenet_v2.py
  tensorflow/python/keras/applications/nasnet.py
  tensorflow/python/keras/applications/resnet.py
  tensorflow/python/keras/applications/resnet_v2.py
  tensorflow/python/keras/applications/vgg16.py
  tensorflow/python/keras/applications/vgg19.py
  tensorflow/python/keras/applications/xception.py
Labels: cla: yes, comp:keras, ready to pull, size:S
