Repository tensorflow/tensorflow, pull requests merged in 2020-04, with the labels that each got.

#37260 [XLA] vectorize row reduction for even row size
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc
  tensorflow/compiler/xla/service/gpu/kernel_mapping_scheme.h
  tensorflow/compiler/xla/service/gpu/tests/BUILD
  tensorflow/compiler/xla/service/gpu/tests/reduction_vectorization_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:L

#35666 [ROCm] Support for complex type BLAS operations
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/batch_matmul_op_test.py
  tensorflow/python/kernel_tests/eig_op_test.py
  tensorflow/python/kernel_tests/init_ops_test.py
  tensorflow/python/kernel_tests/linalg/linear_operator_adjoint_test.py
  tensorflow/python/kernel_tests/linalg/linear_operator_circulant_test.py
  tensorflow/python/kernel_tests/lu_op_test.py
  tensorflow/python/kernel_tests/matmul_op_test.py
  tensorflow/python/kernel_tests/matrix_exponential_op_test.py
  tensorflow/python/kernel_tests/matrix_inverse_op_test.py
  tensorflow/python/kernel_tests/matrix_logarithm_op_test.py
  tensorflow/python/kernel_tests/matrix_square_root_op_test.py
  tensorflow/python/kernel_tests/self_adjoint_eig_op_test.py
  tensorflow/python/kernel_tests/signal/BUILD
  tensorflow/python/kernel_tests/svd_op_test.py
  tensorflow/python/kernel_tests/tensordot_op_test.py
  tensorflow/python/ops/special_math_ops_test.py
  tensorflow/stream_executor/rocm/rocm_blas.cc
  tensorflow/stream_executor/rocm/rocm_blas.h
Labels: cla: yes, ready to pull, size:L

#36641 [ROCm] CUDA/ROCm shared interface
  tensorflow/core/util/gpu_device_functions.h
Labels: cla: yes, comp:gpu, ready to pull, size:M

#37813 [Autograph] Fix loop else support and add loop integration test
  tensorflow/python/autograph/converters/break_statements.py
  tensorflow/python/autograph/converters/loop_integration_test.py
Labels: cla: yes, comp:autograph, ready to pull, size:M

#37890 [tflite] add xnnpack delegate to label_image
  tensorflow/lite/examples/label_image/BUILD
  tensorflow/lite/examples/label_image/README.md
  tensorflow/lite/examples/label_image/label_image.cc
  tensorflow/lite/examples/label_image/label_image.h
  third_party/cpuinfo/BUILD.bazel
Labels: cla: yes, comp:lite, ready to pull, size:M

#37901 [INTEL MKL] Fix a bug within MklFusedBatchNormOp
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#37992 2.2-rc2 cherry-pick request: Delegate _aggregate_gradients in LossScaleOptimizer.
  tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py
Labels: cla: yes

#38085 Fix TFE_OpReset doesn't clear inputs completely
  tensorflow/c/eager/c_api_experimental.cc
Labels: cla: yes

#38093 Allow unused keys when a dict is passed to a single-input Functional …
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/engine/network_test.py
Labels: cla: yes

#38139 Fix the typo when calling to model quantizer
  tensorflow/lite/python/lite.py
Labels: cla: yes

#37853 Added example and description about numpy_function() in Dataset.map()
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, ready to pull, size:S

#37856 tf.SparseTensor to tf.sparse.SparseTensor
  tensorflow/core/api_def/base_api/api_def_SparseMatrixOrderingAMD.pbtxt
  tensorflow/core/api_def/base_api/api_def_SparseMatrixSparseCholesky.pbtxt
  tensorflow/core/api_def/base_api/api_def_SparseMatrixSparseMatMul.pbtxt
  tensorflow/examples/saved_model/integration_tests/export_simple_text_embedding.py
  tensorflow/go/op/wrappers.go
  tensorflow/python/client/session.py
  tensorflow/python/data/experimental/ops/batching.py
  tensorflow/python/data/experimental/ops/grouping.py
  tensorflow/python/data/kernel_tests/from_sparse_tensor_slices_test.py
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/python/data/ops/iterator_ops.py
  tensorflow/python/data/util/sparse.py
  tensorflow/python/feature_column/feature_column.py
  tensorflow/python/feature_column/feature_column_v2.py
  tensorflow/python/framework/indexed_slices.py
  tensorflow/python/framework/ops.py
  tensorflow/python/framework/sparse_tensor.py
  tensorflow/python/keras/layers/local.py
  tensorflow/python/ops/array_ops.py
  tensorflow/python/ops/ctc_ops.py
  tensorflow/python/ops/map_fn.py
  tensorflow/python/ops/math_ops.py
  tensorflow/python/ops/parallel_for/pfor.py
  tensorflow/python/ops/ragged/ragged_tensor.py
  tensorflow/python/ops/sets_impl.py
  tensorflow/python/ops/sparse_ops.py
  tensorflow/python/util/nest.py
  tensorflow/python/util/util.h
  tensorflow/python/util/util_wrapper.cc
Labels: cla: yes, ready to pull, size:M

#38137 [Intel MKL] Fix incorrect DNNL1.2 integration in pooling backprop
  tensorflow/core/kernels/mkl_avgpooling_op.cc
  tensorflow/core/kernels/mkl_maxpooling_op.cc
  tensorflow/core/kernels/mkl_pooling_ops_common.cc
  tensorflow/core/kernels/mkl_pooling_ops_common.h
Labels: cla: yes, comp:mkl, ready to pull, size:S

#38048 Add usage examples and improve documentation on tf.keras.applications models
  tensorflow/python/keras/applications/densenet.py
  tensorflow/python/keras/applications/efficientnet.py
  tensorflow/python/keras/applications/inception_resnet_v2.py
  tensorflow/python/keras/applications/inception_v3.py
  tensorflow/python/keras/applications/mobilenet.py
  tensorflow/python/keras/applications/mobilenet_v2.py
  tensorflow/python/keras/applications/nasnet.py
  tensorflow/python/keras/applications/resnet.py
  tensorflow/python/keras/applications/resnet_v2.py
  tensorflow/python/keras/applications/vgg16.py
  tensorflow/python/keras/applications/vgg19.py
  tensorflow/python/keras/applications/xception.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:L

#37954 [Intel MKL] Fixing bfloat16 integration in MatMul and BatchMatMul for…
  tensorflow/core/kernels/mkl_batch_matmul_op.cc
  tensorflow/core/kernels/mkl_matmul_op.cc
  tensorflow/core/kernels/mkl_matmul_op_fused.cc
  tensorflow/core/kernels/mkl_matmul_ops_common.h
  tensorflow/core/kernels/mkl_tmp_bf16_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:M

#37212 [MLIR][XLA] Buffer Assignment
  tensorflow/compiler/mlir/BUILD
  tensorflow/compiler/mlir/xla/BUILD
  tensorflow/compiler/mlir/xla/tests/buffer-assignment.mlir
  tensorflow/compiler/mlir/xla/transforms/buffer_assignment.cc
  tensorflow/compiler/mlir/xla/transforms/buffer_assignment.h
  tensorflow/compiler/mlir/xla/transforms/passes.h
Labels: cla: yes, ready to pull, size:L

#38142 Fix <unknown> shape issue for sparse.transpose
  tensorflow/python/framework/sparse_tensor_test.py
  tensorflow/python/ops/sparse_ops.py
Labels: cla: yes, ready to pull, size:XS

#37905 Updated "tf.keras.losses.cosine_similarity()" docs
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#37837 Make @tf.function-wrapped functions pickleable
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/def_function_test.py
Labels: cla: yes, comp:eager, ready to pull, size:M

#37603 Replace fit_generator by fit
  tensorflow/python/keras/preprocessing/image.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#26885 Lite: ResizeTensor Dim size check added to avoid reallocation if no c…
  tensorflow/lite/core/subgraph.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#38208 Fix TPU `saved_model.save` with SyncOnReadVariable.
  tensorflow/python/distribute/tpu_strategy.py
Labels: cla: yes

#38115 TFLu: Fix compilation errors for cmsis-nn/softmax.cc
  tensorflow/lite/micro/kernels/cmsis-nn/softmax.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#38125 [INTEL MKL] Enabling conv2D (NCHW format) fusion in grappler remapper
  tensorflow/core/grappler/optimizers/BUILD
  tensorflow/core/grappler/optimizers/mkl_remapper_test.cc
  tensorflow/core/grappler/optimizers/remapper.cc
Labels: cla: yes, comp:grappler, ready to pull, size:L

#35359 Add Edge Board Support in Arduino Library Build for TFLu (micro)
  tensorflow/lite/micro/examples/magic_wand/arduino/Makefile.inc
  tensorflow/lite/micro/examples/magic_wand/arduino/accelerometer_handler.cc
  tensorflow/lite/micro/examples/magic_wand/arduino/output_handler.cc
  tensorflow/lite/micro/examples/magic_wand/sparkfun_edge/accelerometer_handler.cc
  tensorflow/lite/micro/examples/magic_wand/sparkfun_edge/output_handler.cc
  tensorflow/lite/micro/examples/micro_speech/arduino/Makefile.inc
  tensorflow/lite/micro/examples/micro_speech/arduino/audio_provider.cc
  tensorflow/lite/micro/examples/micro_speech/arduino/command_responder.cc
  tensorflow/lite/micro/examples/micro_speech/sparkfun_edge/audio_provider.cc
  tensorflow/lite/micro/examples/micro_speech/sparkfun_edge/command_responder.cc
  tensorflow/lite/micro/examples/person_detection/arduino/HM01B0_platform.h
  tensorflow/lite/micro/examples/person_detection/arduino/Makefile.inc
  tensorflow/lite/micro/examples/person_detection/arduino/detection_responder.cc
  tensorflow/lite/micro/examples/person_detection/arduino/image_provider.cc
  tensorflow/lite/micro/examples/person_detection/himax_driver/HM01B0.c
  tensorflow/lite/micro/examples/person_detection/himax_driver/HM01B0.h
  tensorflow/lite/micro/examples/person_detection/himax_driver/HM01B0_debug.c
  tensorflow/lite/micro/examples/person_detection/himax_driver/HM01B0_optimized.c
  tensorflow/lite/micro/examples/person_detection/sparkfun_edge/detection_responder.cc
  tensorflow/lite/micro/examples/person_detection/sparkfun_edge/image_provider.cc
  tensorflow/lite/micro/tools/make/fix_arduino_subfolders.py
  tensorflow/lite/micro/tools/make/helper_functions.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XL

#37518 [ROCm] Fix for broken ROCm CSB - 200311
  tensorflow/core/BUILD
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#38176 Update jsoncpp from 1.8.4 to 1.9.2
  tensorflow/workspace.bzl
  third_party/jsoncpp.BUILD
Labels: cla: yes, ready to pull, size:S

#38200 [INTEL MKL] upgrade curl version to 7.69.1 to fix CVE-2019-15601
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes, comp:mkl, ready to pull, size:S

#38179 [r2.2:CherryPick] Check for None spec in module_util.py.
  tensorflow/python/tools/module_util.py
Labels: cla: yes

#38131 [r2.2 Cherrypick] Support building XNNPACK delegate for Linux/AArch64
  third_party/cpuinfo/BUILD.bazel
Labels: cla: yes

#38277 [r2.2:CherryPick] Updated model `metrics_names` doc with note on when `metrics_names` will be populated. Also added some examples.
  tensorflow/python/keras/engine/training.py
Labels: cla: yes

#38278 [r2.2:CherryPick] Ensure saved_model_cli and deps are included in pip package.
  tensorflow/python/tools/BUILD
Labels: cla: yes

#37965 Fix Bug in MixedPrecisionLossScaleOptimizer
  tensorflow/python/keras/optimizers_test.py
  tensorflow/python/training/experimental/loss_scale_optimizer.py
Labels: cla: yes, ready to pull, size:XS

#38282 [r2.2:CherryPick] Adding a missing dependency to version.cc, fixing an undefined_symbol_error in tensorflow_serving.
  tensorflow/python/BUILD
Labels: cla: yes

#38273 Cherry-pick curl CVE fix
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes

#38201 [DOCS] Updated documentation for the versioning of the TensorFlow Lite operators.
  tensorflow/lite/g3doc/guide/ops_version.md
Labels: cla: yes, comp:lite, kokoro:force-run, ready to pull, size:S

#38040 Fix for issue #35318: zero offset for weights should be zero for int8…
  tensorflow/lite/micro/kernels/fully_connected_test.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#36519 Use deserialize-helper for deserializing dict activations
  tensorflow/python/keras/activations.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#37148 Simplify keras conv compute_output_shape
  tensorflow/python/keras/layers/convolutional.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37994 Fixed make_*_function method name in *_step docstrings
  tensorflow/python/keras/engine/training.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37893 [tflite] make label_image build
  tensorflow/lite/examples/label_image/BUILD
  tensorflow/lite/examples/label_image/label_image.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#35965 [ROCm] Enabling the kernel Relu for float16
  tensorflow/core/kernels/relu_op.cc
  tensorflow/core/kernels/relu_op_gpu.cu.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#37927 [MLIR][XLA] Add ConcatenateOp to LHLO/HLO emitters
  tensorflow/compiler/xla/service/mlir_gpu/hlo_dialect_emitter.cc
  tensorflow/compiler/xla/service/mlir_gpu/hlo_dialect_emitter.h
  tensorflow/compiler/xla/service/mlir_gpu/lhlo_dialect_emitter.cc
  tensorflow/compiler/xla/service/mlir_gpu/lhlo_dialect_emitter.h
  tensorflow/compiler/xla/service/mlir_gpu/tests/BUILD
  tensorflow/compiler/xla/service/mlir_gpu/tests/concatenate.hlo
  tensorflow/compiler/xla/service/mlir_gpu/tests/mlir_gpu_lhlo_gen_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:S

#38268 Pickleable tf.function, attempt #2
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/def_function_test.py
Labels: cla: yes, ready to pull, size:M

#38209 Support negative axis for tf.signal.fftshift
  tensorflow/python/kernel_tests/signal/fft_ops_test.py
  tensorflow/python/ops/signal/fft_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#37955 pathlib.Path support for keras
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/saving/save.py
  tensorflow/python/keras/saving/save_test.py
  tensorflow/python/keras/utils/data_utils.py
  tensorflow/python/keras/utils/io_utils.py
  tensorflow/python/keras/utils/io_utils_test.py
  tensorflow/python/keras/utils/vis_utils.py
Labels: API review, cla: yes, comp:keras, ready to pull, size:M

#38323 [r2.2:CherryPick] Create optimizer weights when loading model from HDF5
  tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py
  tensorflow/python/keras/optimizer_v2/optimizer_v2.py
  tensorflow/python/keras/optimizers.py
  tensorflow/python/keras/saving/hdf5_format.py
  tensorflow/python/keras/saving/hdf5_format_test.py
Labels: cla: yes

#38286 Update version numbers for TensorFlow 2.2.0-rc3
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#38304 revert the gitignore due to build failure
  .gitignore
Labels: cla: yes, size:XS

#38330 [r2.2:CherryPick] increase the macos 3.8 pip build timeout, disable a failing test.
  tensorflow/python/BUILD
Labels: cla: yes

#38331 Model.fit doc fixes
  tensorflow/python/keras/engine/training.py
Labels: cla: yes

#38334 Add `socketpair.c` to curl buildable files to fix Windows builds.
  third_party/curl.BUILD
Labels: cla: yes

#37616 Added several 'see also' references in Python API documentation
  tensorflow/python/ops/array_ops.py
  tensorflow/python/ops/functional_ops.py
  tensorflow/python/ops/linalg_ops.py
  tensorflow/python/ops/map_fn.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#38326 systemlibs: unbundle astunparse and small syslibs updates
  tensorflow/workspace.bzl
  third_party/systemlibs/astunparse.BUILD
  third_party/systemlibs/grpc.bazel.grpc_deps.bzl
  third_party/systemlibs/protobuf.bzl
  third_party/systemlibs/syslibs_configure.bzl
Labels: cla: yes, ready to pull, size:S

#38364 Only enable `use_fused_avg_updates` in non-XLA context.
  tensorflow/python/distribute/custom_training_loop_models_test.py
  tensorflow/python/keras/layers/normalization.py
Labels: cla: yes

#38267 [XLA][LHLO] Added support for SideEffects interfaces to LHLO operations.
  tensorflow/compiler/mlir/xla/ir/lhlo_ops.td
Labels: cla: yes, ready to pull, size:M

#38118 Refactor ExecuteTrtEngine.
  tensorflow/compiler/tf2tensorrt/BUILD
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
  tensorflow/compiler/tf2tensorrt/convert/utils.cc
  tensorflow/compiler/tf2tensorrt/convert/utils.h
  tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
  tensorflow/compiler/tf2tensorrt/utils/trt_engine_utils.cc
  tensorflow/compiler/tf2tensorrt/utils/trt_engine_utils.h
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:L

#38333 r2.2 systemlibs cherry-picks
  tensorflow/compiler/xla/python/bfloat16.h
  tensorflow/compiler/xla/python/dlpack.h
  tensorflow/compiler/xla/python/python_ref_manager.h
  tensorflow/compiler/xla/python/tpu_driver/client/tpu_client_extension.cc
  tensorflow/compiler/xla/python/types.h
  tensorflow/compiler/xla/python/xla.cc
  tensorflow/lite/testing/string_util_wrapper.cc
  tensorflow/lite/tools/optimize/sparsity/python/format_converter_extension.cc
  tensorflow/python/autograph/impl/testing/pybind_for_testing.cc
  tensorflow/python/client/debug_events_writer_wrapper.cc
  tensorflow/python/client/device_lib_wrapper.cc
  tensorflow/python/client/events_writer_wrapper.cc
  tensorflow/python/client/tf_session_wrapper.cc
  tensorflow/python/framework/dtypes.cc
  tensorflow/python/framework/memory_checker_test_helper.cc
  tensorflow/python/framework/op_def_registry.cc
  tensorflow/python/framework/python_memory_checker_helper.cc
  tensorflow/python/framework/python_op_gen_wrapper.cc
  tensorflow/python/grappler/cluster_wrapper.cc
  tensorflow/python/grappler/cost_analyzer_wrapper.cc
  tensorflow/python/grappler/graph_analyzer_tool_wrapper.cc
  tensorflow/python/grappler/item_wrapper.cc
  tensorflow/python/grappler/model_analyzer_wrapper.cc
  tensorflow/python/grappler/tf_optimizer_wrapper.cc
  tensorflow/python/lib/core/bfloat16_wrapper.cc
  tensorflow/python/lib/core/py_exception_registry_wrapper.cc
  tensorflow/python/lib/core/py_func_wrapper.cc
  tensorflow/python/lib/core/pybind11_absl.h
  tensorflow/python/lib/core/pybind11_lib.h
  tensorflow/python/lib/core/pybind11_proto.h
  tensorflow/python/lib/core/pybind11_status.h
  tensorflow/python/lib/io/file_io_wrapper.cc
  tensorflow/python/lib/io/record_io_wrapper.cc
  tensorflow/python/lite/toco_python_api_wrapper.cc
  tensorflow/python/mlir_wrapper.cc
  tensorflow/python/platform/stacktrace_handler_wrapper.cc
  tensorflow/python/profiler/internal/profiler_wrapper.cc
  tensorflow/python/profiler/internal/scoped_annotation_wrapper.cc
  tensorflow/python/profiler/internal/traceme_wrapper.cc
  tensorflow/python/tfcompile_wrapper.cc
  tensorflow/python/tfe_wrapper.cc
  tensorflow/python/training/quantize_training_wrapper.cc
  tensorflow/python/util/kernel_registry_wrapper.cc
  tensorflow/python/util/port_wrapper.cc
  tensorflow/python/util/py_checkpoint_reader_wrapper.cc
  tensorflow/python/util/stat_summarizer_wrapper.cc
  tensorflow/python/util/tf_stack.cc
  tensorflow/python/util/tfprof_wrapper.cc
  tensorflow/python/util/transform_graph_wrapper.cc
  tensorflow/python/util/util_wrapper.cc
  tensorflow/workspace.bzl
  third_party/pybind11.BUILD
  third_party/systemlibs/astunparse.BUILD
  third_party/systemlibs/grpc.bazel.grpc_deps.bzl
  third_party/systemlibs/protobuf.bzl
  third_party/systemlibs/pybind11.BUILD
  third_party/systemlibs/syslibs_configure.bzl
Labels: cla: yes

#38401 Update libjpeg-turbo 2.0.0 => 2.0.4
  third_party/jpeg/BUILD.bazel
  third_party/jpeg/workspace.bzl
Labels: cla: yes, ready to pull, size:S

#38405 Cherrypick libjpeg-turbo version update
  third_party/jpeg/BUILD.bazel
  third_party/jpeg/workspace.bzl
Labels: cla: yes

#38301 refactoring: early return 'if else' -> 'if'
  tensorflow/python/distribute/combinations.py
Labels: cla: yes, ready to pull, size:S

#38355 Update SlurmClusterResolver documentation
  tensorflow/python/distribute/cluster_resolver/README.slurm
  tensorflow/python/distribute/cluster_resolver/README_Slurm.md
  tensorflow/python/distribute/cluster_resolver/slurm_cluster_resolver.py
Labels: cla: yes, ready to pull, size:M

#38417 r2.2-rc3 cherry-pick request: Fix a bug that profile XLA gpu crashes OOM.
  tensorflow/compiler/xla/service/gpu/gpu_executable.cc
  tensorflow/core/profiler/internal/gpu/cupti_tracer.cc
Labels: cla: yes

#38283 Fix issue 36146
  tensorflow/python/util/nest.py
Labels: cla: yes, ready to pull, size:XS

#35890 [ROCm] Fix for //tensorflow/python/kernel_tests/signal:mel_ops_test
  tensorflow/python/ops/signal/mel_ops.py
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#38368 Cadence NNLib:Fixed various unit test failures
  tensorflow/lite/micro/kernels/xtensa_hifi/conv.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/depthwise_conv.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/svdf.cc
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, comp:lite, ready to pull, size:M

#38290 Use GemmStridedBatched in batch matmul kernels
  tensorflow/core/kernels/batch_matmul_op_impl.h
Labels: cla: yes, ready to pull, size:M

#38128 [Intel MKL] Support MatMul fusion for bfloat16 type.
  tensorflow/core/graph/mkl_layout_pass_test.cc
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/ops/math_ops.cc
  tensorflow/core/ops/mkl_nn_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#38436 [2.2 cherrypick-request] Upgrade XNNPack to fix build issues on AArch64
  tensorflow/workspace.bzl
  third_party/cpuinfo/BUILD.bazel
  third_party/cpuinfo/workspace.bzl
  third_party/pthreadpool/BUILD.bazel
  third_party/pthreadpool/workspace.bzl
Labels: cla: yes

#38440 [r2.2:CherryPick] Fix input size used for batch normalization.
  tensorflow/python/distribute/zero_batch_test.py
  tensorflow/python/keras/layers/normalization.py
Labels: cla: yes

#37312 Update release notes for TensorFlow 2.2.0
  RELEASE.md
Labels: cla: yes

#38399 Add aarch64 cross compile toolchain for TFLite
  arm_compiler.BUILD
  tensorflow/workspace.bzl
  third_party/toolchains/cpus/arm/BUILD
  third_party/toolchains/cpus/arm/arm_compiler_configure.bzl
  third_party/toolchains/cpus/arm/cc_config.bzl.tpl
Labels: cla: yes, ready to pull, size:L

#38374 [Intel MKL] add attr to fix ut
  tensorflow/core/ops/mkl_nn_ops.cc
  tensorflow/core/ops/nn_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#38258 Add float16 to _TENSOR_CONTENT_TYPES in tf.make_tensor_proto
  tensorflow/python/framework/tensor_util.py
  tensorflow/python/framework/tensor_util_test.py
Labels: cla: yes, ready to pull, size:S

#38398 [compiler] Correct dims_rhs constraint
  tensorflow/compiler/mlir/tensorflow/tests/einsum.mlir
  tensorflow/compiler/mlir/tensorflow/transforms/einsum.cc
Labels: cla: yes, ready to pull, size:XS

#37381 xla_lhlo.neg and xla_lhlo.abs support integer arguments
  tensorflow/compiler/mlir/xla/tests/lhlo-legalize-to-linalg.mlir
  tensorflow/compiler/mlir/xla/transforms/map_xla_to_scalar_op.h
Labels: cla: yes, ready to pull, size:S

#38094 Use vector load/store in the normalization CUDA kernel
  tensorflow/core/kernels/softmax_op_gpu.cu.cc
Labels: cla: yes, ready to pull, size:M

#38371 Reduce code duplication tpu_embedding
  tensorflow/python/tpu/tpu_embedding.py
Labels: cla: yes, ready to pull, size:S

#38479 [lite] fix nnapi:nnapi_delegate_verbose_validation
  tensorflow/lite/delegates/nnapi/BUILD
Labels: cla: yes, comp:lite, ready to pull, size:XS

#38493 Update backend.py -> unique_object_name method's docstring section
  tensorflow/python/keras/backend.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#35924 [ROCm] Optimized training apply ops
  tensorflow/core/kernels/training_ops.cc
  tensorflow/core/kernels/training_ops_gpu.cu.cc
  tensorflow/python/keras/optimizer_v2/adadelta_test.py
  tensorflow/python/keras/optimizer_v2/adagrad_test.py
  tensorflow/python/keras/optimizer_v2/rmsprop_test.py
Labels: cla: yes, ready to pull, size:L

#38472 perfer python3 to compile
  configure
Labels: cla: yes, ready to pull, size:XS

#33808 An implementation of eigendecomposition gradients
  tensorflow/python/kernel_tests/eig_op_test.py
  tensorflow/python/ops/linalg_grad.py
Labels: cla: yes, ready to pull, size:M

#38544 Add XLA kernel for tf.ensure_shape
  tensorflow/compiler/jit/mark_for_compilation_pass.cc
  tensorflow/compiler/tests/BUILD
  tensorflow/compiler/tests/ensure_shape_op_test.py
  tensorflow/compiler/tf2xla/kernels/BUILD
  tensorflow/compiler/tf2xla/kernels/ensure_shape_op.cc
Labels: cla: yes, comp:xla, ready to pull, size:M

#36640 [ROCm] Create a wrapper header for rocprim and cub
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/bincount_op_gpu.cu.cc
  tensorflow/core/kernels/dynamic_partition_op_gpu.cu.cc
  tensorflow/core/kernels/generate_box_proposals_op.cu.cc
  tensorflow/core/kernels/gpu_prim.h
  tensorflow/core/kernels/histogram_op_gpu.cu.cc
  tensorflow/core/kernels/l2loss_op_gpu.cu.cc
  tensorflow/core/kernels/multinomial_op_gpu.cu.cc
  tensorflow/core/kernels/non_max_suppression_op.cu.cc
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
  tensorflow/core/kernels/scan_ops_gpu.h
  tensorflow/core/kernels/softmax_op_gpu.cu.cc
  tensorflow/core/kernels/sparse/BUILD
  tensorflow/core/kernels/sparse/kernels_gpu.cu.cc
  tensorflow/core/kernels/sparse_xent_op_gpu.cu.cc
  tensorflow/core/kernels/topk_op_gpu.h
  tensorflow/core/kernels/where_op_gpu.cu.h
Labels: cla: yes, ready to pull, size:L

#37304 Implement manip gradient in cc.
  tensorflow/cc/BUILD
  tensorflow/cc/gradients/manip_grad.cc
  tensorflow/cc/gradients/manip_grad_test.cc
Labels: cla: yes, ready to pull, size:M

#38289 [ROCm] Adding no_rocm tag to CSB tests currently failing on the ROCm platform
  tensorflow/python/distribute/BUILD
  tensorflow/python/eager/BUILD
  tensorflow/python/keras/distribute/BUILD
  tensorflow/python/keras/layers/BUILD
  tensorflow/python/keras/optimizer_v2/BUILD
  tensorflow/python/profiler/BUILD
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#38527 pass name to GraphExecutionFunction
  tensorflow/python/keras/backend.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#38123 TFLu: fix compilation issue in cmsis-nn/conv.cc
  tensorflow/lite/micro/kernels/cmsis-nn/conv.cc
  tensorflow/lite/micro/kernels/cmsis-nn/depthwise_conv.cc
  tensorflow/lite/micro/kernels/cmsis-nn/fully_connected.cc
  tensorflow/lite/micro/kernels/cmsis-nn/pooling.cc
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#37753 Micro: Enable M-Profile Vector Extension if Supported.
  tensorflow/lite/micro/tools/make/ext_libs/cmsis.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XS

#38509 List deterministic op functionality bug fixes in version 2.2 release notes
  RELEASE.md
Labels: cla: yes

#38444 Add Python 2 EOL notice
  RELEASE.md
Labels: cla: yes, size:XS

#35996 Add 16 bit support to kernel operator SOFTMAX
  tensorflow/lite/kernels/activations.cc
  tensorflow/lite/kernels/activations_test.cc
  tensorflow/lite/kernels/internal/common.h
  tensorflow/lite/kernels/internal/reference/softmax.h
  tensorflow/lite/kernels/internal/types.h
Labels: cla: yes, comp:lite, ready to pull, size:L

#38124 Use Unified Memory in TRT opconverter tests
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: awaiting review, cla: yes, comp:gpu:tensorrt, ready to pull, size:L

#38322 [INTEL MKL] Fixing build issue in two unit tests
  tensorflow/core/common_runtime/eager/BUILD
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite_test.cc
Labels: cla: yes, ready to pull, size:S

#36560 [ROCm] Fix for a test regression on the ROCm platform - 200207 - 2
  tensorflow/python/eager/profiler_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#38387 [MLIR][XLA] Adding new tests for buffer assignment, and fixing its addDynamicallyLegalFuncOp.
  tensorflow/compiler/mlir/xla/BUILD
  tensorflow/compiler/mlir/xla/tests/buffer-assignment.mlir
  tensorflow/compiler/mlir/xla/transforms/buffer_assignment.cc
  tensorflow/compiler/mlir/xla/transforms/buffer_assignment_test.cc
Labels: cla: yes, ready to pull, size:L

#38586 Backport 'Do not call Unprotect on remote inputs'
  tensorflow/core/common_runtime/eager/tensor_handle.cc
Labels: cla: yes, size:XS

#38543 fix readability (newlines) on github issue templates
  .github/ISSUE_TEMPLATE/00-bug-issue.md
  .github/ISSUE_TEMPLATE/80-performance-issue.md
Labels: cla: yes, ready to pull, size:M

#38095 Add int16 support for tf.math.minimum and tf.math.maximum
  tensorflow/core/kernels/cwise_op_gpu_maximum.cu.cc
  tensorflow/core/kernels/cwise_op_gpu_minimum.cu.cc
  tensorflow/core/kernels/cwise_op_maximum.cc
  tensorflow/core/kernels/cwise_op_minimum.cc
  tensorflow/core/ops/math_ops.cc
  tensorflow/core/ops/ops.pbtxt
  tensorflow/python/kernel_tests/cwise_ops_test.py
Labels: cla: yes, ready to pull, size:S

#38614 [Intel MKL] Fixing mkl_eager_op_rewrite compile error
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
Labels: cla: yes, ready to pull, size:XS

#38587 refactoring: early return 'if else' syntax -> 'if' syntax
  tensorflow/python/autograph/impl/api.py
  tensorflow/python/autograph/pyct/anno.py
Labels: cla: yes, ready to pull, size:XS

#38484 Fix reduce op ut failure: root rank=-1
  tensorflow/core/nccl/nccl_manager.cc
Labels: cla: yes, ready to pull, size:XS

#38584 [INTEL MKL] remove the py3 flag in mkl contianer build
  tensorflow/tools/ci_build/linux/mkl/build-dev-container.sh
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#38439 Allow passing custom image preprocessing config to the TFL eval tool.
  tensorflow/lite/tools/evaluation/stages/image_classification_stage.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#38580 [INTEL MKL] Fix a bug which is related to backward MKL Conv Input
  tensorflow/core/kernels/mkl_conv_grad_input_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#38577 Create stale.yml
  .github/stale.yml
Labels: cla: yes, ready to pull, size:S

#38499 Added code to pass appropriate logs to on_test|train_end() methods
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/engine/training.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#38649 Update RELEASE.md
  RELEASE.md
Labels: cla: yes

#38647 [2.2 cherrypick] Img preproc layers fix
  tensorflow/python/keras/layers/preprocessing/image_preprocessing.py
  tensorflow/python/keras/layers/preprocessing/image_preprocessing_test.py
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-rotation.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-translation.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-zoom.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-rotation.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-translation.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-zoom.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.pbtxt
Labels: cla: yes

#38653 Update version numbers for TensorFlow 2.2.0
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#38575 [Intel MKL] Enabling BFloat16 convolution fusions
  tensorflow/core/grappler/optimizers/mkl_remapper_test.cc
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/kernels/mkl_tmp_bf16_ops.cc
Labels: cla: yes, ready to pull, size:L

#38656 [Intel MKL] Fix yet another mkl_eager_op build failure
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
Labels: cla: yes, ready to pull, size:XS

#38136 [XLA] vectorize row reduction for even row size (new version of PR #37260)
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc
  tensorflow/compiler/xla/service/gpu/kernel_mapping_scheme.h
  tensorflow/compiler/xla/service/gpu/tests/BUILD
  tensorflow/compiler/xla/service/gpu/tests/reduction_vectorization_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:L

#38582 [ROCm] Adding complex datatype support for StridedBatchGemm API calls
  tensorflow/stream_executor/rocm/rocm_blas.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#38284 [TFMicro] Add versions to logistic and max pool
  tensorflow/lite/micro/kernels/all_ops_resolver.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XS

#38715 Update stale.yml
  .github/stale.yml
Labels: cla: yes, ready to pull, size:XS

#38288 Add uint16, uint32, uint64 support for tf.math.equal
  tensorflow/core/kernels/cwise_op_equal_to_1.cc
  tensorflow/core/kernels/cwise_op_not_equal_to_1.cc
  tensorflow/core/ops/math_ops.cc
  tensorflow/python/kernel_tests/cwise_ops_binary_test.py
Labels: cla: yes, ready to pull, size:S

#37624 [Intel MKL] Enable DepthwiseConv2D + BiasAdd (+ Relu/Relu6/Elu) fusion
  tensorflow/core/graph/mkl_layout_pass.cc
  tensorflow/core/graph/mkl_layout_pass_test.cc
  tensorflow/core/grappler/optimizers/mkl_remapper_test.cc
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/kernels/mkl_conv_ops.cc
  tensorflow/core/kernels/mkl_fused_ops_test.cc
  tensorflow/core/ops/mkl_nn_ops.cc
  tensorflow/core/ops/nn_ops.cc
Labels: cla: yes, comp:mkl, ready to pull, size:L

#38639 TFLu: add stm32f4 binary building to CI script
  tensorflow/lite/micro/kernels/cmsis-nn/add.cc
  tensorflow/lite/micro/kernels/cmsis-nn/conv.cc
  tensorflow/lite/micro/kernels/cmsis-nn/fully_connected.cc
  tensorflow/lite/micro/kernels/cmsis-nn/softmax.cc
  tensorflow/lite/micro/tools/ci_build/test_all.sh
  tensorflow/lite/micro/tools/ci_build/test_stm32f4.sh
  tensorflow/lite/micro/tools/make/targets/stm32f4_makefile.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#38663 Fix TypeError while importing tensorflow caused by site.USER_SITE is set to None
  tensorflow/api_template.__init__.py
  tensorflow/api_template_v1.__init__.py
Labels: cla: yes, ready to pull, size:XS

#38010 Update activations.py
  tensorflow/python/keras/activations.py
Labels: cla: yes, comp:keras, ready to pull, size:XS, stat:awaiting tensorflower

#38717 [Intel MKL] Fixes an issue with tensorflow bfloat16 scope that create…
  tensorflow/python/tpu/bfloat16.py
  tensorflow/python/tpu/bfloat16_test.py
Labels: cla: yes, ready to pull, size:XS

#35946 [TFLite int16] Symmetric 16-bit activations and 8-bit weights: reference kernel CONV_2D
  tensorflow/lite/kernels/conv.cc
  tensorflow/lite/kernels/conv_test.cc
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/common.h
  tensorflow/lite/kernels/internal/conv_per_channel_quantized_16x8_test.cc
  tensorflow/lite/kernels/internal/reference/integer_ops/conv.h
  tensorflow/lite/kernels/kernel_util.cc
  tensorflow/lite/kernels/test_util.h
Labels: cla: yes, comp:lite, ready to pull, size:L

#38671 [INTEL MKL] Upgrading DNNL to v1.4
  tensorflow/workspace.bzl
  third_party/mkl_dnn/mkldnn_v1.BUILD
Labels: cla: yes, ready to pull, size:S

#38744 TFLu compile option in msys under Win64
  tensorflow/lite/micro/tools/make/download_and_extract.sh
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#38706 [TFLite] Introduce ruy_profiler to Makefile
  tensorflow/lite/tools/make/Makefile
Labels: cla: yes, comp:lite, ready to pull, size:XS

#38259 [INTEL_MKL] Boiler plate code for dnnl threadpool and mkl_conv_ops.cc
  tensorflow/core/common_runtime/process_util.cc
  tensorflow/core/common_runtime/threadpool_device.cc
  tensorflow/core/kernels/mkl_conv_ops.cc
  tensorflow/core/kernels/mkl_input_conversion_op.cc
  tensorflow/core/kernels/mkl_reshape_op.cc
  tensorflow/core/kernels/mkl_tfconv_op.h
  tensorflow/core/util/BUILD
  tensorflow/core/util/mkl_threadpool.h
  tensorflow/core/util/mkl_util.h
Labels: cla: yes, ready to pull, size:L

#38716 Add builtin len() support of tf.data.Dataset for autograph
  tensorflow/python/autograph/operators/py_builtins.py
  tensorflow/python/autograph/operators/py_builtins_test.py
Labels: cla: yes, ready to pull, size:S

#38769 Update CI build scripts for TF Lite micro
  tensorflow/lite/micro/tools/ci_build/ci_build_micro_projects.sh
  tensorflow/lite/micro/tools/ci_build/test_all.sh
  tensorflow/lite/micro/tools/ci_build/test_arc.sh
  tensorflow/lite/micro/tools/ci_build/test_arduino.sh
  tensorflow/lite/micro/tools/ci_build/test_arduino_library.sh
  tensorflow/lite/micro/tools/ci_build/test_bluepill.sh
  tensorflow/lite/micro/tools/ci_build/test_mbed.sh
  tensorflow/lite/micro/tools/ci_build/test_mbed_library.sh
  tensorflow/lite/micro/tools/ci_build/test_sparkfun.sh
  tensorflow/lite/micro/tools/ci_build/test_stm32f4.sh
  tensorflow/lite/micro/tools/ci_build/test_x86.sh
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#37074 Add different pattern to show op in timeline
  tensorflow/python/client/timeline.py
Labels: cla: yes, ready to pull, size:M

#38807 [r2.2:Cherrypick][tf.data] This CL changes how the in-memory cache resource is managed, making it possible for the cache dataset to support both a) sharing of the cache across iterators and b) serialization. As a consequence, this CL enables sharing of the cache across iterators for tf.distribute and tf.data service use cases (which require serialization support).
  tensorflow/core/api_def/base_api/api_def_DummyMemoryCache.pbtxt
  tensorflow/core/grappler/optimizers/data/make_stateless.cc
  tensorflow/core/grappler/optimizers/data/make_stateless_test.cc
  tensorflow/core/kernels/data/cache_dataset_ops.cc
  tensorflow/core/kernels/data/cache_dataset_ops.h
  tensorflow/core/kernels/data/cache_ops.cc
  tensorflow/core/kernels/data/dataset_utils.h
  tensorflow/core/ops/dataset_ops.cc
  tensorflow/python/data/kernel_tests/cache_test.py
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: cla: yes

#38759 [ROCm] Fix for a build failure on the ROCm platform - 200420
  tensorflow/core/grappler/optimizers/constant_folding_test.cc
  tensorflow/lite/kernels/pack_test.cc
  tensorflow/lite/kernels/unpack_test.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#38808 [r2.2:Cherrypick] Fix last partial batch loss regression in 2.2
  tensorflow/python/keras/engine/compile_utils.py
  tensorflow/python/keras/metrics_correctness_test.py
Labels: cla: yes

#38844 [tf.data] Memory-safe implementation of sharing access to the memory …
  tensorflow/core/kernels/data/cache_dataset_ops.cc
  tensorflow/core/kernels/data/cache_ops.cc
  tensorflow/core/kernels/data/cache_ops.h
Labels: cla: yes

#38654 [ROCm] Updating Dockerfile.rocm / CI scripts to use ROCm 3.3
  configure.py
  tensorflow/tools/ci_build/Dockerfile.rocm
  tensorflow/tools/ci_build/linux/rocm/run_cc_core.sh
  tensorflow/tools/ci_build/linux/rocm/run_csb_tests.sh
  tensorflow/tools/ci_build/linux/rocm/run_py3_core.sh
  tensorflow/tools/ci_build/xla/linux/rocm/run_py3.sh
Labels: cla: yes, comp:gpu, ready to pull, size:S

#38641 Consistent capitalization of "Python" in array_ops.py
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#37798 Fix: Misleading convert error when no concrete functions are given
  tensorflow/lite/python/lite.py
  tensorflow/lite/python/lite_v2_test.py
Labels: awaiting review, cla: yes, comp:lite, ready to pull, size:XS

#38846 [INTEL MKL] fix a missing build dependency.
  tensorflow/core/common_runtime/BUILD
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#38819 Update documentation to switch from deprecated tf.extract_image_patches to tf.image.extract_patches
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#38553 [INTEL MKL] Enabling tf_cuda_cc_test to execute in CPU only builds also.
  tensorflow/c/BUILD
  tensorflow/tensorflow.bzl
Labels: cla: yes, ready to pull, size:XS

#37277 [BugFix] - Prefetching on GPU is actually executed on CPU
  tensorflow/python/data/experimental/kernel_tests/prefetch_to_device_test.py
  tensorflow/python/data/kernel_tests/BUILD
  tensorflow/python/data/kernel_tests/iterator_test.py
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/python/data/ops/iterator_ops.py
Labels: cla: yes, comp:data, ready to pull, size:S

#38864 Fix timeline fail to parse long kernel names when op_time is set
  tensorflow/python/client/timeline.py
Labels: cla: yes, ready to pull, size:XS

#38604 replace std::round() with TfLiteRound().
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/common.h
Labels: cla: yes, ready to pull, size:S

#38616 [Intel MKL] Enabling Conv2D bfloat16 fusions
  tensorflow/core/graph/mkl_layout_pass.cc
  tensorflow/core/graph/mkl_layout_pass_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#38667 xla_hlo.compare support dynamic shape in materialize broadcast
  tensorflow/compiler/mlir/xla/tests/materialize-broadcasts.mlir
  tensorflow/compiler/mlir/xla/transforms/materialize_broadcasts.cc
Labels: cla: yes, ready to pull, size:S

#38955 Fix incorrect usage of os.system().
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl
Labels: cla: yes, ready to pull, size:S

#38006 _ConstantValue can now see through tf.identity ops
  tensorflow/python/framework/tensor_util.py
  tensorflow/python/framework/tensor_util_test.py
  tensorflow/python/kernel_tests/confusion_matrix_test.py
Labels: cla: yes, ready to pull, size:XS

#38917 Add missing mlir_passthrough_op in pip wheel install
  tensorflow/tools/pip_package/BUILD
Labels: cla: yes, ready to pull, size:XS

#38880 Update snappy library to 1.1.8
  tensorflow/workspace.bzl
Labels: cla: yes, ready to pull, size:XS
