Repository tensorflow/tensorflow, pull requests merged in 2020-12, with the labels that each got.

#45286 Push and pop gcc diagnostic pragma's in the flexbuffer patching script.
  tensorflow/lite/micro/tools/make/flatbuffers_download.sh
Labels: cla: yes, comp:micro, ready to pull, size:XS

#45220 Addition for resources
  README.md
Labels: cla: yes, ready to pull, size:XS

#44958 [INTEL MKL] Added cpu docker file with python36.
  tensorflow/tools/ci_build/Dockerfile.cpu-py36
Labels: awaiting review, cla: yes, comp:mkl, ready to pull, size:S

#45242 Fix linking failure of Flex delegate in Archive mode
  tensorflow/lite/experimental/ios/allowlist_TensorFlowLiteC.txt
Labels: cla: yes, comp:lite

#45131 r2.4: Update CMake build rules of TFLite
  tensorflow/lite/CMakeLists.txt
  tensorflow/lite/examples/minimal/CMakeLists.txt
  tensorflow/lite/examples/minimal/README.md
  tensorflow/lite/tools/cmake/README.md
Labels: cla: yes, size:M

#45309 [Cherrypick:r2.4] Save Keras metadata in a separate proto and raise deprecation warnings when loading a SavedModel with tf.saved_model.save().
  tensorflow/python/keras/saving/BUILD
  tensorflow/python/keras/saving/saved_model/constants.py
  tensorflow/python/keras/saving/saved_model/load.py
  tensorflow/python/keras/saving/saved_model/save.py
  tensorflow/python/saved_model/save.py
  tensorflow/python/training/tracking/graph_view.py
Labels: cla: yes

#45264 [CherryPick:r2.4] Revert renaming of tools to exec_tools
  tensorflow/tensorflow.bzl
Labels: cla: yes

#44584 Add several fixes for s390x architecture and other Big-Endian systems
  tensorflow/compiler/xla/literal.cc
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/data/experimental/lmdb_dataset_op_test.cc
  third_party/cpuinfo/BUILD.bazel
Labels: awaiting review, cla: yes, ready to pull, size:S

#45345 [Cherrypick:r2.4] Change protobuf version back to 3.9.2
  tensorflow/tools/ci_build/release/common.sh
  tensorflow/tools/ci_build/release/common_win.bat
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#45318 Update version numbers for TensorFlow 2.4.0-rc4
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#45316 Fix the release build for xtensa.
  tensorflow/lite/micro/tools/make/targets/xtensa_makefile.inc
Labels: cla: yes, comp:micro, ready to pull, size:XS

#45314 ifdef out known failing test cases for Quantize for hifimini.
  tensorflow/lite/micro/kernels/quantize_test.cc
Labels: cla: yes, comp:micro, ready to pull, size:S

#45048 ifdef out known failing test cases for Conv2D for hifimini.
  tensorflow/lite/micro/kernels/conv_test.cc
Labels: awaiting review, cla: yes, comp:micro, ready to pull, size:M

#45353 [Cherypick:r2.4] pin to old version(3.9.2)has broken docs Fixes #45300
  tensorflow/tools/ci_build/release/common.sh
  tensorflow/tools/ci_build/release/common_win.bat
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#43566 TFLu: Port TFL detection postprocess operator
  tensorflow/lite/micro/all_ops_resolver.cc
  tensorflow/lite/micro/examples/hello_world/hello_world_test.cc
  tensorflow/lite/micro/examples/hello_world/main_functions.cc
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/detection_postprocess.cc
  tensorflow/lite/micro/kernels/detection_postprocess_test.cc
  tensorflow/lite/micro/kernels/flexbuffers_generated_data.cc
  tensorflow/lite/micro/kernels/flexbuffers_generated_data.h
  tensorflow/lite/micro/kernels/kernel_runner.cc
  tensorflow/lite/micro/kernels/kernel_runner.h
  tensorflow/lite/micro/kernels/test_data_generation/BUILD
  tensorflow/lite/micro/kernels/test_data_generation/README.md
  tensorflow/lite/micro/kernels/test_data_generation/generate_flexbuffers_data.cc
  tensorflow/lite/micro/micro_allocator.cc
  tensorflow/lite/micro/micro_interpreter_test.cc
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:micro, prtype:bugfix, ready to pull, size:XL

#45334 Fix esp32 ci build
  tensorflow/lite/micro/tools/ci_build/test_esp32.sh
Labels: cla: yes, comp:micro, comp:micro:espressif, ready to pull, size:XS

#45277 Fixed wrong cast which caused problems with build for ARC targets.
  tensorflow/lite/micro/kernels/arc_mli/mli_tf_utils.h
Labels: cla: yes, comp:micro, ready to pull, size:XS

#45355 Have `make test` pass for Xtensa hifimini.
  tensorflow/lite/micro/kernels/softmax_test.cc
  tensorflow/lite/micro/tools/make/targets/bluepill_makefile.inc
  tensorflow/lite/micro/tools/make/targets/xtensa_makefile.inc
Labels: cla: yes, comp:micro, ready to pull, size:S

#45344 Allow for gpu platforms other than CUDA in jax
  tensorflow/compiler/xla/pjrt/BUILD
  tensorflow/compiler/xla/pjrt/gpu_device.cc
  tensorflow/compiler/xla/pjrt/gpu_device.h
  tensorflow/compiler/xla/pjrt/gpu_multistream_test.cc
  tensorflow/compiler/xla/python/BUILD
  tensorflow/compiler/xla/python/xla.cc
  tensorflow/compiler/xla/python/xla_client.py
Labels: cla: yes, comp:xla, ready to pull, size:S

#45307 Extract a function for parsing operator FILL
  tensorflow/lite/core/api/flatbuffer_conversions.cc
  tensorflow/lite/core/api/flatbuffer_conversions.h
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:S

#45311 Extract reference for operator FILL to standalone header
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/reference/fill.h
  tensorflow/lite/kernels/internal/reference/reference_ops.h
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:M

#45349 Exclude targets that are known to not build with bazel.
  tensorflow/lite/micro/benchmarks/BUILD
  tensorflow/lite/micro/examples/image_recognition_experimental/BUILD
  tensorflow/lite/micro/examples/person_detection/BUILD
  tensorflow/lite/micro/examples/person_detection/utils/BUILD
  tensorflow/lite/micro/testing/BUILD
Labels: cla: yes, comp:micro, ready to pull, size:S

#45390 Revert recent SavedModel changes
  tensorflow/core/protobuf/saved_object_graph.proto
  tensorflow/python/keras/saving/BUILD
  tensorflow/python/keras/saving/saved_model/constants.py
  tensorflow/python/keras/saving/saved_model/load.py
  tensorflow/python/keras/saving/saved_model/save.py
  tensorflow/python/keras/saving/saved_model/saved_model_test.py
  tensorflow/python/saved_model/BUILD
  tensorflow/python/saved_model/save.py
  tensorflow/python/training/tracking/graph_view.py
Labels: cla: yes

#44894 Added bf16 support for Sparse_Xent_op.
  tensorflow/core/kernels/sparse_xent_op.cc
  tensorflow/core/kernels/sparse_xent_op_test.cc
  tensorflow/python/kernel_tests/sparse_xent_op_test.py
Labels: cla: yes, comp:core, ready to pull, size:M

#45389 micro: list test and kernel files explicitly in Makefile
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:micro, ready to pull, size:M

#45075 Fix wrong image_data_format() usage
  tensorflow/python/keras/applications/mobilenet_v2.py
  tensorflow/python/keras/applications/mobilenet_v3.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#45283 Improve recurrent layers Call API mask documentation
  tensorflow/python/keras/layers/recurrent.py
  tensorflow/python/keras/layers/recurrent_v2.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#45369 Align PPD op between TFL and TFLM
  tensorflow/lite/kernels/detection_postprocess.cc
  tensorflow/lite/micro/kernels/detection_postprocess.cc
Labels: cla: yes, comp:lite, comp:micro, comp:micro:arm, ready to pull, size:M

#37520 Documented tf.keras.preprocessing purpose
  tensorflow/python/keras/preprocessing/__init__.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#45000 Softnms
  tensorflow/core/kernels/image/non_max_suppression_op.cc
  tensorflow/core/kernels/image/non_max_suppression_op_test.cc
  tensorflow/python/ops/image_ops_test.py
Labels: cla: yes, comp:core, ready to pull, size:S

#45380 Try to switch to h5py 3.1.0
  tensorflow/tools/ci_build/install/install_centos_pip_packages.sh
  tensorflow/tools/ci_build/install/install_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
  tensorflow/tools/ci_build/release/common.sh
  tensorflow/tools/ci_build/release/common_win.bat
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#45419 Refactor for case BuiltinOperator_EXP in flatbuffer_conversions.cc/h;…
  tensorflow/lite/core/api/flatbuffer_conversions.cc
  tensorflow/lite/core/api/flatbuffer_conversions.h
Labels: cla: yes, comp:micro, ready to pull, size:S

#45461 Fixed error in the example of image_gradients documentation
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#45189 Always build libtensorflow in a manylinux2010 compatible way
  tensorflow/tools/ci_build/builds/libtensorflow.sh
  tensorflow/tools/ci_build/linux/libtensorflow_docker.sh
Labels: cla: yes, ready to pull, size:XS

#45490 Add option in the TFLM makefile to disable downloads.
  tensorflow/lite/micro/tools/ci_build/test_all.sh
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/ext_libs/cmsis_nn.inc
Labels: cla: yes, comp:micro, ready to pull, size:M

#45391 tflite: Prevent from reallocation of persistent tensors
  tensorflow/lite/arena_planner.cc
  tensorflow/lite/arena_planner_test.cc
Labels: cla: yes, prtype:bugfix, size:S

#45408 [ROCm][r2.4]Porting changes from master to switch to ROCm 3.9
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
  tensorflow/core/kernels/conv_2d_gpu.h
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
  tensorflow/core/kernels/scan_ops_gpu.h
  tensorflow/core/platform/default/rocm_rocdl_path.cc
  tensorflow/core/platform/rocm_rocdl_path_test.cc
  tensorflow/core/util/gpu_launch_config.h
  tensorflow/stream_executor/rocm/rocm_gpu_executor.cc
  tensorflow/tools/ci_build/Dockerfile.rocm
  tensorflow/tools/ci_build/linux/rocm/run_cc_core.sh
  tensorflow/tools/ci_build/linux/rocm/run_csb_tests.sh
  tensorflow/tools/ci_build/linux/rocm/run_py3_core.sh
  tensorflow/tools/ci_build/xla/linux/rocm/run_py3.sh
  third_party/gpus/compress_find_rocm_config.py
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_rocm.tpl
  third_party/gpus/find_rocm_config.py
  third_party/gpus/find_rocm_config.py.gz.base64
  third_party/gpus/rocm/BUILD.tpl
  third_party/gpus/rocm/rocm_config.h.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, size:L

#44017 [PluggableDevice] Kernel C API enhancement for retrieving attributes
  tensorflow/c/kernels.cc
  tensorflow/c/kernels.h
  tensorflow/c/kernels_test.cc
Labels: API review, cla: yes, ready to pull, size:L

#45493 Delete unnecessary BUILD files as part of flatbuffer patching for TFLM.
  tensorflow/lite/micro/tools/make/flatbuffers_download.sh
Labels: cla: yes, comp:micro, ready to pull, size:S

#45260 [Language Fix] Change BlackBox to ClosedBox
  tensorflow/lite/kernels/bidirectional_sequence_rnn_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#45010 Fix for TF Lite verifier, arg_min_max op and lsh_projection_test on Big Endian machine
  tensorflow/lite/delegates/nnapi/nnapi_delegate_test.cc
  tensorflow/lite/kernels/arg_min_max.cc
  tensorflow/lite/kernels/lsh_projection_test.cc
  tensorflow/lite/tools/verifier.cc
Labels: cla: yes, comp:lite, prtype:bugfix, ready to pull, size:S

#45474 TFLu: Fix bug in PPD op
  tensorflow/lite/micro/kernels/detection_postprocess.cc
Labels: cla: yes, comp:micro, prtype:bugfix, ready to pull, size:XS

#45386 [ROCm] Re-enabling unit-tests that are now passing on ROCm platform
  tensorflow/core/common_runtime/constant_folding_test.cc
  tensorflow/core/kernels/depthwise_conv_ops_test.cc
  tensorflow/core/kernels/image/resize_bilinear_op_test.cc
  tensorflow/python/compiler/xla/jit_compile_test.py
  tensorflow/python/eager/forwardprop_test.py
  tensorflow/python/keras/backend_test.py
  tensorflow/python/keras/integration_test/forwardprop_test.py
  tensorflow/python/keras/layers/pooling_test.py
  tensorflow/python/keras/layers/preprocessing/image_preprocessing_test.py
  tensorflow/python/kernel_tests/linalg_grad_test.py
  tensorflow/python/kernel_tests/pool_test.py
  tensorflow/python/ops/control_flow_ops_test.py
  tensorflow/python/ops/init_ops_v2_test.py
Labels: cla: yes, comp:gpu, ready to pull, size:M

#45498 Default initialize fixed point Eigen types.
  third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/FixedPointTypes.h
Labels: cla: yes

#45499 Validate that `DataFormat*` attributes form a permutation.
  tensorflow/core/kernels/data_format_ops.cc
  tensorflow/python/ops/nn_test.py
Labels: cla: yes

#45500 Mark `MemmappedTensorAllocator` as returning opaque handle.
  tensorflow/core/kernels/immutable_constant_op.cc
Labels: cla: yes

#45501 Completely rewrite `GetMatchingPaths`.
  tensorflow/core/platform/file_system_helper.cc
Labels: cla: yes

#45502 Prevent CHECK-fail in LSTM/GRU with zero-length input.
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes

#45503 Prevent unitialized memory access in `GraphConstructor::MakeEdge`
  tensorflow/core/common_runtime/graph_constructor.cc
Labels: cla: yes

#45464 Build for TARGET_ARCH=fusion_f1 via reference implementation fallback.
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/svdf.cc
  tensorflow/lite/micro/kernels/svdf.h
  tensorflow/lite/micro/kernels/svdf_common.cc
  tensorflow/lite/micro/kernels/xtensa/conv.cc
  tensorflow/lite/micro/kernels/xtensa/depthwise_conv.cc
  tensorflow/lite/micro/kernels/xtensa/fully_connected.cc
  tensorflow/lite/micro/kernels/xtensa/svdf.cc
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/targets/xtensa_makefile.inc
Labels: cla: yes, comp:micro, ready to pull, size:L

#45553 Update PCRE library from 8.42 to 8.44
  tensorflow/workspace.bzl
Labels: cla: yes

#45486 tflite: Add casts to std::min/std::max when comparing mis-matched types
  tensorflow/lite/kernels/internal/common.h
  tensorflow/lite/kernels/internal/quantization_util.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#45560 Dockerfiles: Pin pip version and fix apt-get
  tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/devel-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/devel-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/jupyter.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/python.partial.Dockerfile
Labels: cla: yes

#45561 Dockerfiles: Pin pip version and fix apt-get
  tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/devel-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/devel-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/mkl_horovod/horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/jupyter.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/python.partial.Dockerfile
Labels: cla: yes

#44540 Add GPU kernel for SparseApplyFtrl
  tensorflow/core/kernels/training_ops.cc
  tensorflow/core/kernels/training_ops_gpu.cu.cc
Labels: cla: yes, comp:core, ready to pull, size:M

#45562 Dockerfiles: Pin pip version and fix apt-get
  tensorflow/tools/dockerfiles/dockerfiles/arm64v8/devel-cpu-arm64v8-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/arm64v8/devel-cpu-arm64v8.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel-mpi-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel-mpi-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel-mpich-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel-mpich-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-mpi-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-mpi-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-mpich-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-mpich-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-devel-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-devel-mpi-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-devel-mpi-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-devel-mpich-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-devel-mpich-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-devel.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-mpi-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-mpi-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-mpich-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04-mpich-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-18.04.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-devel-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-devel-mpi-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-devel-mpi-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-devel-mpich-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-devel-mpich-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-devel.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-mpi-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-mpi-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-mpich-horovod-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04-mpich-horovod.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-20.04.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le.Dockerfile
  tensorflow/tools/dockerfiles/partials/jupyter.partial.Dockerfile
  tensorflow/tools/dockerfiles/partials/ubuntu/python.partial.Dockerfile
Labels: cla: yes

#45559 Update version numbers for TensorFlow 2.4.0
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#45555 Run apt-get update before installing jupyter dependencies
  tensorflow/tools/dockerfiles/dockerfiles/arm64v8/devel-cpu-arm64v8-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-cpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/dockerfiles/ppc64le/gpu-ppc64le-jupyter.Dockerfile
  tensorflow/tools/dockerfiles/partials/jupyter.partial.Dockerfile
Labels: cla: yes, ready to pull, size:S

#45534 Dispatch reverse_sequence
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#45495 ellaborated docs on determinism in dataset ops
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, ready to pull, size:S

#42134 [TFLite] Fix potential overflow in 64-bit MultiplyByQuantizedMultiplier function
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/common.h
  tensorflow/lite/kernels/internal/quantization_util_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#45440 Extract a function for parsing operator DIV
  tensorflow/lite/core/api/flatbuffer_conversions.cc
  tensorflow/lite/core/api/flatbuffer_conversions.h
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:S

#45496 Changed TOSA common legalizations to use llvm::Optional<>
  tensorflow/compiler/mlir/tosa/transforms/fuse_bias_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: cla: yes, ready to pull, size:XL

#45280 Fix unique shape inference
  tensorflow/core/ops/array_ops.cc
  tensorflow/python/kernel_tests/unique_op_test.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:M

#45296 [tflite] map leaky relu to prelu to use NNAPI
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
  tensorflow/lite/delegates/nnapi/nnapi_delegate_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#44923 [Intel MKL] Improve CNMS performance by removing unnecessary allocation
  tensorflow/core/kernels/image/non_max_suppression_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#45399 Only use site.USER_SITE if ENABLE_USER_SITE is set
  tensorflow/api_template.__init__.py
Labels: cla: yes, ready to pull, size:XS

#45487 Try to switch to h5py 3.1.0
  tensorflow/compiler/mlir/tensorflow/tests/tf_saved_model/common.py
  tensorflow/python/keras/saving/hdf5_format.py
  tensorflow/python/keras/saving/save_test.py
  tensorflow/tools/ci_build/install/install_centos_pip_packages.sh
  tensorflow/tools/ci_build/install/install_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.5_pip_packages.sh
  tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
  tensorflow/tools/ci_build/release/common.sh
  tensorflow/tools/ci_build/release/common_win.bat
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, comp:lite, prtype:bugfix, ready to pull, size:S

#45278 Keras SavedModel: Ignore custom metrics failure when compile=False
  tensorflow/python/keras/saving/saved_model/load.py
  tensorflow/python/keras/saving/saved_model/saved_model_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#45547 Cleanup `tensorflow/c/experimental/gradients` Part 1
  tensorflow/c/eager/BUILD
  tensorflow/c/eager/gradient_checker.cc
  tensorflow/c/eager/gradient_checker.h
  tensorflow/c/eager/gradient_checker_test.cc
  tensorflow/c/eager/mnist_gradients_test.cc
  tensorflow/c/eager/mnist_gradients_testutil.cc
  tensorflow/c/eager/mnist_gradients_testutil.h
  tensorflow/c/eager/unified_api_test.cc
  tensorflow/c/eager/unified_api_testutil.cc
  tensorflow/c/eager/unified_api_testutil.h
  tensorflow/c/experimental/gradients/BUILD
  tensorflow/c/experimental/gradients/custom_gradient_test.cc
  tensorflow/c/experimental/gradients/grad_test_helper.cc
  tensorflow/c/experimental/gradients/grad_test_helper.h
  tensorflow/c/experimental/gradients/nn_grad_test.cc
Labels: cla: yes, kokoro:force-run, ready to pull, size:L

#45587 [TFTRT] Rename ParameterizedOpConverterTest classes with more descriptive names
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:M

#44220 Update release notes for TensorFlow 2.4.0
  RELEASE.md
Labels: cla: yes, size:S

#45358 [Intel MKL] Add MatMul+BiasAdd+Add fusion
  tensorflow/core/grappler/optimizers/mkl_remapper_test.cc
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/kernels/mkl/mkl_fused_ops_test.cc
  tensorflow/core/kernels/mkl/mkl_matmul_op_fused.cc
  tensorflow/core/kernels/mkl/mkl_matmul_ops_common.h
Labels: cla: yes, comp:grappler, ready to pull, size:L

#45400 Update local.py
  tensorflow/python/keras/layers/local.py
Labels: cla: yes, comp:keras, ready to pull, size:XS, type:docs-bug

#45215 Making label smoothing documentation more helpful
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#45618 Refactor quantize (reference and xtensa) for a complete fallback.
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/quantize.cc
  tensorflow/lite/micro/kernels/quantize.h
  tensorflow/lite/micro/kernels/quantize_common.cc
  tensorflow/lite/micro/kernels/quantize_test.cc
  tensorflow/lite/micro/kernels/xtensa/quantize.cc
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:micro, ready to pull, size:L

#45673 Manually fix licenses for the files to ensure consistent formatting.
  tensorflow/lite/micro/all_ops_resolver.cc
  tensorflow/lite/micro/all_ops_resolver.h
  tensorflow/lite/micro/examples/micro_speech/ceva/main_functions.cc
  tensorflow/lite/micro/examples/micro_speech/nxp_k66f/audio_provider.cc
  tensorflow/lite/micro/kernels/arc_mli/conv.cc
  tensorflow/lite/micro/kernels/arc_mli/depthwise_conv.cc
  tensorflow/lite/micro/kernels/arc_mli/fully_connected.cc
  tensorflow/lite/micro/kernels/arc_mli/pooling.cc
  tensorflow/lite/micro/kernels/detection_postprocess.cc
  tensorflow/lite/micro/kernels/flexbuffers_generated_data.cc
  tensorflow/lite/micro/kernels/flexbuffers_generated_data.h
  tensorflow/lite/micro/kernels/micro_utils.h
  tensorflow/lite/micro/kernels/split_v_test.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/activations.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/conv.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/depthwise_conv.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/floor.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/fully_connected.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/logistic.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/pooling.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/softmax.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/svdf.cc
  tensorflow/lite/micro/kernels/xtensa_hifi/xtensa_tf_micro_common.h
  tensorflow/lite/micro/riscv32_mcu/debug_log.cc
  tensorflow/lite/micro/testing/download_renode.sh
  tensorflow/lite/micro/testing/test_xtensa_hifi_binary.sh
  tensorflow/lite/micro/xcore/debug_log.cc
Labels: cla: yes, comp:micro, ready to pull, size:L

#44022 [MLIR] Fix verifier for TF::Conv2DOp and TF::Conv3DOp.
  tensorflow/compiler/mlir/lite/quantization/tensorflow/tests/tf_to_quant.mlir
  tensorflow/compiler/mlir/lite/tests/dilated-conv.mlir
  tensorflow/compiler/mlir/lite/tests/prepare-tf-with-allowing-bf16-type-legalization.mlir
  tensorflow/compiler/mlir/lite/tests/prepare-tf.mlir
  tensorflow/compiler/mlir/tensorflow/ir/tf_generated_ops.td
  tensorflow/compiler/mlir/tensorflow/ir/tf_ops_a_m.cc
  tensorflow/compiler/mlir/tensorflow/tests/layout_optimization_layout_assignment_gpu_cc_60.mlir
  tensorflow/compiler/mlir/tensorflow/tests/layout_optimization_layout_assignment_gpu_cc_70.mlir
  tensorflow/compiler/mlir/tensorflow/tests/layout_optimization_layout_assignment_to_nchw.mlir
  tensorflow/compiler/mlir/tensorflow/tests/layout_optimization_layout_assignment_to_nhwc.mlir
  tensorflow/compiler/mlir/tensorflow/tests/layout_optimization_to_nchw.mlir
  tensorflow/compiler/mlir/tensorflow/tests/legalize_hlo.mlir
  tensorflow/compiler/mlir/tensorflow/tests/optimize.mlir
  tensorflow/compiler/mlir/tensorflow/tests/tf-ops.mlir
  tensorflow/compiler/mlir/tensorflow/tests/tf_optimize.mlir
  tensorflow/compiler/mlir/xla/tests/legalize-tf.mlir
Labels: cla: yes, ready to pull, size:M

#45672 Download pigweed as part of the TensorflowLite Micro makefile.
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/pigweed.patch
  tensorflow/lite/micro/tools/make/pigweed_download.sh
Labels: cla: yes, comp:micro, ready to pull, size:M

#45265 Add missing arch-specific dependencies to tf_to_kernel
  tensorflow/compiler/mlir/tools/kernel_gen/BUILD
Labels: cla: yes, ready to pull, size:XS

#45677 update estimator version after estimator final release
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#45595 README: update Linaro CI links
  README.md
Labels: cla: yes, ready to pull, size:XS

#44486 Fixed incorrect ptxas usage affecting performance when using CUDA
  tensorflow/stream_executor/gpu/asm_compiler.cc
Labels: cla: yes, ready to pull, size:S

#45679 Fix bazel build with -DTF_LITE_STATIC_MEMORY.
  tensorflow/lite/micro/micro_mutable_op_resolver.h
Labels: cla: yes, comp:micro, ready to pull, size:XS

#45654 fix asan check in c++ gradients
  tensorflow/c/eager/gradient_checker.cc
  tensorflow/c/eager/gradient_checker_test.cc
  tensorflow/c/experimental/gradients/grad_test_helper.cc
Labels: cla: yes, comp:eager, ready to pull, size:M

#44919 Refactor SparseApply[Proximal]Adagrad into classes
  tensorflow/core/kernels/training_ops.cc
  tensorflow/core/kernels/training_ops.h
Labels: cla: yes, comp:core, ready to pull, size:L

#45666 micro: fix build warning due to example person_detection
  tensorflow/lite/micro/examples/person_detection/Makefile.inc
Labels: cla: yes, comp:micro, ready to pull, size:XS

#45721 Disable a few tests.
  tensorflow/python/feature_column/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/boosted_trees/BUILD
  tensorflow/tools/pip_package/setup.py.orig
Labels: cla: yes, waiting for patch release

#45722 Disable a few tests.
  tensorflow/python/feature_column/BUILD
  tensorflow/python/kernel_tests/boosted_trees/BUILD
  tensorflow/tools/pip_package/setup.py.orig
Labels: cla: yes, waiting for patch release

#45723 Disable a few tests.
  tensorflow/python/feature_column/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/boosted_trees/BUILD
  tensorflow/tools/pip_package/setup.py.orig
Labels: cla: yes, waiting for patch release

#45725 Disable a few tests.
  tensorflow/python/feature_column/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/boosted_trees/BUILD
  tensorflow/tools/pip_package/setup.py.orig
Labels: cla: yes, waiting for patch release

#45726 Disable a few tests.
  tensorflow/python/feature_column/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/boosted_trees/BUILD
  tensorflow/tools/pip_package/setup.py.orig
Labels: cla: yes, waiting for patch release

#45724 Fix sanity build, reorder tags to satisfy buildifier.
  tensorflow/python/kernel_tests/linalg/BUILD
Labels: cla: yes, waiting for patch release

#45710 Add upper bound to `h5py`.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, waiting for patch release

#45711 Add upper bound to `h5py`.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, waiting for patch release

#45712 Add upper bound to `h5py`.
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, waiting for patch release

#45674 Add check to ensure that files in tensorflow/lite/micro have proper license and formatting
  tensorflow/lite/micro/tools/ci_build/test_all.sh
  tensorflow/lite/micro/tools/ci_build/test_code_style.sh
  tensorflow/tools/ci_build/Dockerfile.micro
Labels: cla: yes, comp:micro, ready to pull, size:S

#45589 [TFTRT - Dynamic Shape Phase 3] Add Dynamic Shape Testing for ConvertClipByValue
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:M

#45728 Fix sanity build
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/boosted_trees/BUILD
Labels: cla: yes, waiting for patch release

#45729 Fix sanity build
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/boosted_trees/BUILD
Labels: cla: yes, waiting for patch release

#45583 [ROCm] Updates required to add ROCm support for JAX
  tensorflow/compiler/xla/python/xla_client.py
  tensorflow/compiler/xla/service/gpu/BUILD
  tensorflow/compiler/xla/service/gpu/thunk_emitter.cc
  third_party/gpus/find_rocm_config.py
  third_party/gpus/find_rocm_config.py.gz.base64
  third_party/gpus/rocm/BUILD.tpl
  third_party/gpus/rocm/build_defs.bzl.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, comp:gpu, ready to pull, size:M

#45747 Disable test which now fails as code is too old.
  tensorflow/python/eager/BUILD
Labels: cla: yes, waiting for patch release

#44846 Bump libjpeg-turbo from 2.0.4 to 2.0.5
  third_party/jpeg/workspace.bzl
Labels: cla: no, waiting for patch release

#44847 Bump libjpeg-turbo from 2.0.4 to 2.0.5
  third_party/jpeg/workspace.bzl
Labels: cla: no, waiting for patch release

#44848 Bump libjpeg-turbo from 2.0.4 to 2.0.5
  third_party/jpeg/workspace.bzl
Labels: cla: no, waiting for patch release

#44849 Bump libjpeg-turbo from 2.0.4 to 2.0.5
  third_party/jpeg/workspace.bzl
Labels: cla: no, waiting for patch release

#44850 Bump libjpeg-turbo from 2.0.4 to 2.0.5
  third_party/jpeg/workspace.bzl
Labels: cla: no, waiting for patch release

#43987 Bump junit from 4.11 to 4.13.1.
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
  tensorflow/java/maven/tensorflow-hadoop/pom.xml
Labels: cla: yes, waiting for patch release

#43988 Bump junit from 4.11 to 4.13.1.
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
  tensorflow/java/maven/tensorflow-hadoop/pom.xml
Labels: cla: yes, waiting for patch release

#43989 Bump junit from 4.11 to 4.13.1.
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
  tensorflow/java/maven/tensorflow-hadoop/pom.xml
Labels: cla: yes, waiting for patch release

#43990 Bump junit from 4.11 to 4.13.1.
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
  tensorflow/java/maven/tensorflow-hadoop/pom.xml
Labels: cla: yes, waiting for patch release

#43991 Bump junit from 4.11 to 4.13.1.
  tensorflow/java/maven/spark-tensorflow-connector/pom.xml
  tensorflow/java/maven/tensorflow-hadoop/pom.xml
Labels: cla: yes, waiting for patch release

#45619 Build Xtensa kernels for Vision P6
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/xtensa/conv.cc
  tensorflow/lite/micro/kernels/xtensa/depthwise_conv.cc
  tensorflow/lite/micro/kernels/xtensa/fixedpoint_utils.h
  tensorflow/lite/micro/kernels/xtensa/fully_connected.cc
  tensorflow/lite/micro/kernels/xtensa/quantize.cc
  tensorflow/lite/micro/kernels/xtensa/svdf.cc
  tensorflow/lite/micro/kernels/xtensa/xtensa.h
Labels: cla: yes, comp:micro, ready to pull, size:L

#45548 Update PCRE library from 8.42 to 8.44
  tensorflow/workspace.bzl
Labels: cla: no, waiting for patch release

#45549 Update PCRE library from 8.42 to 8.44
  tensorflow/workspace.bzl
Labels: cla: no, waiting for patch release

#45550 Update PCRE library from 8.42 to 8.44
  tensorflow/workspace.bzl
Labels: cla: no, waiting for patch release

#45551 Update PCRE library from 8.42 to 8.44
  tensorflow/workspace.bzl
Labels: cla: no, waiting for patch release

#45552 Update PCRE library from 8.42 to 8.44
  tensorflow/workspace.bzl
Labels: cla: no, waiting for patch release

#45750 Fix sanity
  tensorflow/python/eager/BUILD
Labels: cla: yes

#45720 Some initial documentation for the TfLite Micro CI system.
  tensorflow/lite/micro/CONTRIBUTING.md
  tensorflow/lite/micro/docs/images/tflm_continuous_integration_1.png
Labels: cla: yes, comp:micro, ready to pull, size:S

#45442 Extract reference for operator DIV to standalone header
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/reference/div.h
  tensorflow/lite/kernels/internal/reference/reference_ops.h
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:L

#45761 Add exception for .resource and .md files from the style check.
  tensorflow/lite/micro/tools/ci_build/test_code_style.sh
Labels: cla: yes, comp:micro, ready to pull, size:XS

#43930 Add additional example to timeseries_dataset_from_array
  tensorflow/python/keras/preprocessing/timeseries.py
Labels: awaiting review, cla: yes, comp:keras, ready to pull, size:M

#44726 Expand the TFLu Renode docs
  tensorflow/lite/micro/docs/renode.md
  tensorflow/lite/micro/testing/bluepill_nontest.resc
Labels: awaiting review, cla: yes, comp:lite, comp:micro, ready to pull, size:S

#45697 [ROCm] Updating Stream Executor Blas interface (for ROCm) to call rocblas APIs…
  tensorflow/stream_executor/rocm/rocm_blas.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XL

#45776 Update version numbers for TensorFlow 1.15.5
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#45772 Update version numbers for TensorFlow 2.0.4
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#45775 Update version numbers for TensorFlow 2.1.3
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#45773 Update version numbers for TensorFlow 2.2.2
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#45774 Update version numbers for TensorFlow 2.3.2
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#43499 eigen download link points to google storage instead of bitbucket
  tensorflow/lite/tools/make/download_dependencies.sh
Labels: cla: yes, size:XS, waiting for patch release

#43633 [ROCm] Porting changes to support newer ROCm versions to r2.1
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
  tensorflow/core/platform/default/rocm_rocdl_path.cc
  tensorflow/core/platform/rocm_rocdl_path_test.cc
  tensorflow/tools/ci_build/Dockerfile.rocm
  tensorflow/tools/ci_build/linux/rocm/run_cc_core.sh
  tensorflow/tools/ci_build/linux/rocm/run_csb_tests.sh
  tensorflow/tools/ci_build/linux/rocm/run_py3_core.sh
  tensorflow/tools/ci_build/xla/linux/rocm/run_py3.sh
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_rocm.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, size:XS, waiting for patch release

#45718 [Cherrypick:r2.3] Don't do fused average updates inside XLA context as it may create extra tf.cond which causes OOM on TPUs.
  tensorflow/python/keras/layers/normalization.py
Labels: cla: yes, waiting for patch release

#45719 [Cherrypick:r2.2] SavedModel loading: Create temporary graphs for importing functions to avoid leaking memory
  tensorflow/python/saved_model/function_deserialization.py
  tensorflow/python/saved_model/load_test.py
Labels: cla: yes, waiting for patch release

#45526 Default initialize fixed point Eigen types.
  third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/FixedPointTypes.h
Labels: cla: yes, waiting for patch release

#45527 Validate that `DataFormat*` attributes form a permutation.
  tensorflow/core/kernels/data_format_ops.cc
  tensorflow/python/ops/nn_test.py
Labels: cla: yes, waiting for patch release

#45528 Mark `MemmappedTensorAllocator` as returning opaque handle.
  tensorflow/core/kernels/immutable_constant_op.cc
Labels: cla: yes, waiting for patch release

#45529 Prevent CHECK-fail in LSTM/GRU with zero-length input.
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes, waiting for patch release

#45530 Prevent unitialized memory access in `GraphConstructor::MakeEdge`
  tensorflow/core/graph/graph_constructor.cc
Labels: cla: yes, waiting for patch release

#45521 Default initialize fixed point Eigen types.
  third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/FixedPointTypes.h
Labels: cla: yes, waiting for patch release

#45522 Validate that `DataFormat*` attributes form a permutation.
  tensorflow/core/kernels/data_format_ops.cc
  tensorflow/python/ops/nn_test.py
Labels: cla: yes, waiting for patch release

#45523 Mark `MemmappedTensorAllocator` as returning opaque handle.
  tensorflow/core/kernels/immutable_constant_op.cc
Labels: cla: yes, waiting for patch release

#45524 Prevent CHECK-fail in LSTM/GRU with zero-length input.
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes, waiting for patch release

#45525 Prevent unitialized memory access in `GraphConstructor::MakeEdge`
  tensorflow/core/graph/graph_constructor.cc
Labels: cla: yes, waiting for patch release

#45516 Default initialize fixed point Eigen types.
  third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/FixedPointTypes.h
Labels: cla: yes, waiting for patch release

#45517 Validate that `DataFormat*` attributes form a permutation.
  tensorflow/core/kernels/data_format_ops.cc
  tensorflow/python/ops/nn_test.py
Labels: cla: yes, waiting for patch release

#45518 Mark `MemmappedTensorAllocator` as returning opaque handle.
  tensorflow/core/kernels/immutable_constant_op.cc
Labels: cla: yes, waiting for patch release

#45519 Prevent CHECK-fail in LSTM/GRU with zero-length input.
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes, waiting for patch release

#45520 Prevent unitialized memory access in `GraphConstructor::MakeEdge`
  tensorflow/core/graph/graph_constructor.cc
Labels: cla: yes, waiting for patch release

#45511 Default initialize fixed point Eigen types.
  third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/FixedPointTypes.h
Labels: cla: yes, waiting for patch release
