Repository tensorflow/tensorflow, pull requests merged in 2020-03, with the labels that each got.

#37040 Typofix: in docstring of Keras Model:fit
  tensorflow/python/keras/engine/training.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#37155 TFLu: Update CMSIS URL and remove ARM_MATH_LOOPUNROLL
  tensorflow/lite/micro/tools/make/ext_libs/cmsis.inc
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XS

#37175 [Intel MKL] Making BFloat16 MatMul & BatchMatMul in DNNL 1.2 conditio…
  tensorflow/core/kernels/mkl_batch_matmul_op.cc
  tensorflow/core/kernels/mkl_matmul_op.cc
  tensorflow/core/kernels/mkl_matmul_ops_common.h
Labels: cla: yes, comp:mkl, ready to pull, size:M

#37136 [ROCm][XLA:GPU] Fixing xla executable buffer creation
  tensorflow/compiler/xla/service/interpreter/executable.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#37150 Change quotes in TFLite tablegen to fix syntax highlighting
  tensorflow/compiler/mlir/lite/ir/tfl_ops.td
Labels: cla: yes, ready to pull, size:S

#37176 [Intel MKL] Supporting exponential_avg_factor attr for _MklFusedBatch…
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/mkl_fused_batch_norm_op.cc
  tensorflow/core/kernels/mkl_fused_batch_norm_op_test.cc
Labels: cla: yes, comp:mkl, ready to pull, size:L

#36995 Added doc for all application models for decode_prediction() and preprocess_input()
  tensorflow/python/keras/applications/efficientnet.py
  tensorflow/python/keras/applications/inception_v3.py
  tensorflow/python/keras/applications/nasnet.py
  tensorflow/python/keras/applications/resnet.py
  tensorflow/python/keras/applications/resnet_v2.py
  tensorflow/python/keras/applications/vgg16.py
  tensorflow/python/keras/applications/vgg19.py
  tensorflow/python/keras/applications/xception.py
Labels: cla: yes, comp:keras, ready to pull, size:M

#37018 Bugfix: keras custom train config serialize
  tensorflow/python/util/serialization.py
  tensorflow/python/util/serialization_test.py
Labels: cla: yes, ready to pull, size:M

#37163 Fix test that should only be running in v1
  tensorflow/python/ops/nn_fused_batchnorm_test.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#36977 improve API doc page: tf.data.Dataset
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, ready to pull, size:S

#37171 Update tf.image documentation
  tensorflow/python/ops/image_grad.py
  tensorflow/python/ops/image_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:M

#36930 TFLu: Update filtered tests for stm32f4
  tensorflow/lite/micro/tools/make/targets/stm32f4_makefile.inc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#36795 docfix: fix docstring error in KerasHistory
  tensorflow/python/keras/engine/base_layer.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#36941 [XLA] Fix mode for some files
  tensorflow/compiler/xla/service/BUILD
  tensorflow/compiler/xla/service/gpu/BUILD
  tensorflow/compiler/xla/service/hlo_instruction.cc
  tensorflow/compiler/xla/service/hlo_instructions.h
Labels: cla: yes, comp:xla, ready to pull, size:XS

#27422 TfLite one_hot int8 and unit8 feature support
  tensorflow/lite/kernels/one_hot.cc
  tensorflow/lite/kernels/one_hot_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#34492 TFLite TOCO: Verify trivial operator has no activation function
  tensorflow/lite/toco/graph_transformations/remove_trivial_binary.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#36834 Remove ppc64le manyinux2014 docker files.
  tensorflow/tools/ci_build/Dockerfile.rbe.cuda10.0-cudnn7-ubuntu18.04-manylinux2014.ppc64le
  tensorflow/tools/ci_build/Dockerfile.rbe.ubuntu16.04-manylinux2014.ppc64le
  tensorflow/tools/ci_build/devtoolset/build_devtoolset_ppc64le.sh
Labels: cla: yes, ready to pull, size:L

#37244 Added reference papers in docstring
  tensorflow/python/keras/applications/densenet.py
  tensorflow/python/keras/applications/efficientnet.py
  tensorflow/python/keras/applications/inception_resnet_v2.py
  tensorflow/python/keras/applications/mobilenet_v2.py
  tensorflow/python/keras/applications/nasnet.py
  tensorflow/python/keras/applications/resnet.py
  tensorflow/python/keras/applications/resnet_v2.py
  tensorflow/python/keras/applications/vgg16.py
  tensorflow/python/keras/applications/vgg19.py
Labels: cla: yes, comp:keras, ready to pull, size:M

#36699 Fix typos in the base_layer input casting warning
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/base_layer_test.py
  tensorflow/python/keras/engine/base_layer_v1.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#37305 [r2.2:Cherrypick] Fix windows GPU build - revert absl update
  tensorflow/compiler/tf2xla/BUILD
  tensorflow/tools/pip_package/build_pip_package.sh
  tensorflow/workspace.bzl
  third_party/com_google_absl_fix_mac_and_nvcc_build.patch
Labels: cla: yes

#37326 [Intel MKL] Fixing build error
  tensorflow/core/kernels/mkl_conv_ops.h
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#37115 fix resize image bug
  tensorflow/python/ops/image_ops_impl.py
  tensorflow/python/ops/image_ops_test.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#37197 Correct phrasing on CuDNN conditions
  tensorflow/python/keras/layers/recurrent_v2.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#37046 Fixed typo and improved vebosity in opcode registration error
  tensorflow/lite/micro/micro_allocator.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:XS

#37248 Fixed remote handles to be ready when they are poisoned
  tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc
Labels: cla: yes

#37322 [r2.2:Cherrypick] Export symbols with the characteristic `tf_` like `tf_git_version`.
  tensorflow/tf_version_script.lds
Labels: cla: yes

#37321 Update version numbers for TensorFlow 2.2.0-rc0
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#37271 [r2.2:Cherrypick] Reject code containing the for/else pattern, which is not being faithfully converted at the moment. This replaces silently incorrect behavior with a warning. Also whitelist known urllib module.
  tensorflow/python/autograph/core/config.py
  tensorflow/python/autograph/core/unsupported_features_checker.py
Labels: cla: yes

#37270 [r2.2:Cherrypick] Change Keras batch normalization layer to use the running mean and average computation in fused_batch_norm.
  tensorflow/python/keras/layers/normalization.py
Labels: cla: yes

#37267 [r2.2:Cherrypick] Add experimental_make_distributed_values_from_function method to distribution strategy.
  tensorflow/python/distribute/distribute_lib.py
  tensorflow/python/distribute/mirrored_strategy.py
  tensorflow/python/distribute/one_device_strategy.py
  tensorflow/python/distribute/parameter_server_strategy.py
  tensorflow/python/distribute/strategy_combinations.py
  tensorflow/python/distribute/tpu_strategy.py
  tensorflow/python/distribute/values.py
  tensorflow/python/distribute/values_test.py
  tensorflow/tools/api/golden/v2/tensorflow.distribute.-mirrored-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.-one-device-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-central-storage-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-multi-worker-mirrored-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-parameter-server-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-t-p-u-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-value-context.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.pbtxt
Labels: cla: yes

#37225 Update XNNPACK for support Windows
  tensorflow/workspace.bzl
  third_party/pthreadpool/workspace.bzl
Labels: cla: yes, ready to pull, size:S

#37343 Documentation fix: Cosine Similarity
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37373 [r2.2:Cherrypick] Eliminate tf.where call in updating running mean and average for batch norm in Keras. This unlocks the improvements promised by fusing updates into the CPU and GPU kernels.
  tensorflow/python/keras/layers/normalization.py
Labels: cla: yes

#37371 [Intel MKL] Fixing //tensorflow/core:__tensorflow_core_graph_mkl_related_tests
  tensorflow/core/graph/mkl_tfconversion_pass_test.cc
Labels: cla: yes, ready to pull, size:M

#37356 Split unroll_batch_matmul pass into own bazel build target
  tensorflow/compiler/mlir/lite/BUILD
  tensorflow/compiler/mlir/tensorflow/BUILD
  tensorflow/compiler/mlir/tensorflow/transforms/batchmatmul_to_einsum.cc
  tensorflow/compiler/mlir/tensorflow/transforms/unroll_batch_matmul.cc
Labels: cla: yes, ready to pull, size:S

#37388 NFC - minor spelling tweaks under lite/lib_package directory
  tensorflow/lite/lib_package/create_ios_frameworks.sh
Labels: cla: yes, comp:lite, ready to pull, size:XS

#37387 NFC - minor spelling tweaks under lite/g3doc directory
  tensorflow/lite/g3doc/microcontrollers/get_started.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#37368 Remove dependency on TF constant folding pass in mlir/lite
  tensorflow/compiler/mlir/lite/BUILD
  tensorflow/compiler/mlir/tensorflow/BUILD
Labels: cla: yes, size:S

#37408 r2.2: cherry-pick request: fix profile traces too large and windows builds.
  tensorflow/core/profiler/convert/BUILD
  tensorflow/core/profiler/convert/xplane_to_profile_response.cc
  tensorflow/core/profiler/convert/xplane_to_profile_response.h
  tensorflow/core/profiler/convert/xplane_to_profile_response_test.cc
  tensorflow/core/profiler/rpc/client/BUILD
  tensorflow/core/profiler/rpc/client/capture_profile.cc
  tensorflow/core/profiler/rpc/client/save_profile.cc
  tensorflow/core/profiler/rpc/client/save_profile.h
  tensorflow/core/profiler/rpc/profiler_service_impl.cc
  tensorflow/python/keras/callbacks_test.py
  tensorflow/python/profiler/BUILD
  tensorflow/python/profiler/internal/BUILD
  tensorflow/python/profiler/internal/profiler_wrapper.cc
  tensorflow/python/profiler/profiler_v2.py
  tensorflow/python/profiler/profiler_v2_test.py
Labels: cla: yes

#37367 Fix MultiWorkerMirroredStrategy validation in Model.fit
  tensorflow/python/keras/distribute/multi_worker_callback_tf2_test.py
  tensorflow/python/keras/engine/training.py
Labels: cla: yes

#37403 Ignore training=None when passed during Functional API construction.
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/engine/network_test.py
Labels: cla: yes

#37375 r2.2 cherry-pick request: Remove --config=mkl_open_source_only
  .bazelrc
Labels: cla: yes

#37402 [r2.2:Cherrypick] Diable a test that fails on open source build to unblock the release.
  tensorflow/compiler/mlir/tensorflow/tests/graphdef2mlir/BUILD
Labels: cla: yes

#37389 NFC - minor spelling tweaks under lite/testing directory
  tensorflow/lite/testing/op_tests/hardswish.py
  tensorflow/lite/testing/parse_testdata.cc
  tensorflow/lite/testing/tf_driver_test.cc
  tensorflow/lite/testing/zip_test_utils.py
Labels: cla: yes, comp:lite, ready to pull, size:S

#37279 [bugfix] Fix Quantized Leaky ReLU TFLite inference Ops.
  tensorflow/lite/kernels/activations.cc
  tensorflow/lite/kernels/activations_test.cc
  tensorflow/lite/kernels/internal/reference/reference_ops.h
  tensorflow/lite/kernels/internal/types.h
  tensorflow/lite/kernels/register.cc
Labels: cla: yes, comp:lite, prtype:bugfix, ready to pull, size:M

#37308 [XLA] Compare only the filename, not the full path.
  tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc
Labels: cla: yes, comp:xla, ready to pull, size:XS

#37249 Fix typo: delete redundant quote in tf_executor dialect
  tensorflow/compiler/mlir/tensorflow/ir/tf_executor_ops.td
Labels: cla: yes, ready to pull, size:XS

#37006 Resolves symbolic links for CUDA paths
  third_party/gpus/cuda_configure.bzl
  third_party/gpus/find_cuda_config.py
  third_party/gpus/find_cuda_config.py.gz.base64
  third_party/remote_config/common.bzl
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#37420 NFC - minor spelling tweaks under lite/micro directory
  tensorflow/lite/micro/examples/magic_wand/train/data_load.py
  tensorflow/lite/micro/examples/micro_speech/nxp_k66f/audio_provider.cc
  tensorflow/lite/micro/examples/person_detection/himax_driver/HM01B0.c
  tensorflow/lite/micro/examples/person_detection/himax_driver/HM01B0.h
  tensorflow/lite/micro/kernels/cmsis-nn/pooling.cc
  tensorflow/lite/micro/kernels/split.cc
  tensorflow/lite/micro/memory_planner/memory_planner.h
  tensorflow/lite/micro/micro_utils.h
  tensorflow/lite/micro/riscv32_mcu/debug_log.cc
  tensorflow/lite/micro/simple_memory_allocator.h
  tensorflow/lite/micro/tools/ci_build/test_all.sh
  tensorflow/lite/micro/tools/make/targets/ecm3531/_main.c
  tensorflow/lite/micro/tools/make/transform_arduino_source.py
  tensorflow/lite/micro/tools/make/transform_source.py
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#37391 NFC - minor spelling tweaks under lite/python directory
  tensorflow/lite/python/interpreter.py
  tensorflow/lite/python/lite_test.py
  tensorflow/lite/python/op_hint.py
  tensorflow/lite/python/tflite_convert.py
  tensorflow/lite/python/util.py
  tensorflow/lite/python/util_test.py
  tensorflow/lite/python/wrap_toco.py
Labels: cla: yes, comp:lite, ready to pull, size:S

#37419 Add close check
  tensorflow/core/platform/default/net.cc
Labels: cla: yes, ready to pull, size:S

#37377 [XLA] follow-up on GPU-deterministic reductions
  tensorflow/compiler/xla/service/gpu/gpu_compiler.cc
  tensorflow/python/kernel_tests/BUILD
Labels: cla: yes, comp:xla, ready to pull, size:S

#37374 Undo changes to the input spec when RNN.unroll is True.
  tensorflow/python/keras/layers/recurrent.py
  tensorflow/python/keras/saving/saved_model/saved_model_test.py
Labels: cla: yes

#37276 Allow missing labels when there is no loss / metric associated with t…
  tensorflow/python/keras/engine/compile_utils.py
  tensorflow/python/keras/engine/compile_utils_test.py
  tensorflow/python/keras/engine/training_test.py
Labels: cla: yes

#37314 Frees up Model.fit to take advantage of async eager when no batch-lev…
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/callbacks_test.py
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/base_layer_utils.py
  tensorflow/python/keras/engine/base_layer_v1.py
  tensorflow/python/keras/engine/data_adapter.py
  tensorflow/python/keras/engine/data_adapter_test.py
  tensorflow/python/keras/engine/network.py
  tensorflow/python/keras/engine/sequential.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/utils/generic_utils.py
Labels: cla: yes

#37459 Export Keras image preprocessing layers into the experimental namespace.
  tensorflow/python/keras/api/BUILD
  tensorflow/python/keras/layers/__init__.py
  tensorflow/python/keras/layers/preprocessing/image_preprocessing.py
  tensorflow/python/keras/layers/preprocessing/image_preprocessing_test.py
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-center-crop.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-contrast.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-crop.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-flip.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-height.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-rotation.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-translation.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-width.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-zoom.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-rescaling.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-resizing.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-center-crop.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-contrast.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-crop.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-flip.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-height.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-rotation.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-translation.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-width.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-zoom.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-rescaling.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-resizing.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.pbtxt
Labels: cla: yes

#37362 [r2.2:Cherryppick] Split unroll_batch_matmul pass into own build target
  tensorflow/compiler/mlir/lite/BUILD
  tensorflow/compiler/mlir/tensorflow/BUILD
  tensorflow/compiler/mlir/tensorflow/transforms/unroll_batch_matmul.cc
Labels: cla: yes

#37464 [TF XLA AOT] Make sure required sources are included in pip package.
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/BUILD
  tensorflow/tools/pip_package/MANIFEST.in
Labels: cla: yes

#37486 Debug windows builds, add `-s` bazel flag
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
Labels: cla: yes

#37174 Export encode_png to tf.io
  tensorflow/python/ops/image_ops.py
  tensorflow/python/ops/image_ops_impl.py
  tensorflow/tools/api/golden/v1/tensorflow.io.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.io.pbtxt
Labels: API review, cla: yes, comp:ops, ready to pull, size:XS

#37384 Add Python 3.8 to classifiers
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:XS

#37469 Correct getting dataset.element_spec
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, ready to pull, size:XS

#37069 tensor_bundle: Supply size hint to input buffer
  tensorflow/core/lib/io/inputbuffer.cc
  tensorflow/core/lib/io/inputbuffer.h
  tensorflow/core/lib/io/inputbuffer_test.cc
  tensorflow/core/util/tensor_bundle/tensor_bundle.cc
Labels: cla: yes, ready to pull, size:S

#37378 Add "AddV2" to tensorflow v1 flops calculation
  tensorflow/python/profiler/internal/flops_registry.py
Labels: cla: yes, ready to pull, size:XS

#37396 Update api_def_Acos.pbtxt
  tensorflow/core/api_def/base_api/api_def_Acos.pbtxt
Labels: cla: yes, ready to pull, size:XS

#37329 Categorical Hinge Loss Doc Updated
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#37190 Re-instate PR #36578: Go: NewTensor & Value performance improvement
  tensorflow/go/tensor.go
  tensorflow/go/tensor_test.go
Labels: cla: yes, ready to pull, size:L

#37499 [Intel MKL] Fix performance regression in DNNL 1 due to lack of primitive cache on reorder
  tensorflow/core/kernels/mkl_transpose_op.cc
  tensorflow/core/util/mkl_util.h
Labels: cla: yes, comp:mkl, ready to pull, size:M

#36639 [ROCm] Grappler unit tests and _FusedConv2D
  tensorflow/core/grappler/clusters/single_machine_test.cc
  tensorflow/core/grappler/devices.cc
  tensorflow/core/grappler/optimizers/auto_mixed_precision.cc
  tensorflow/core/grappler/optimizers/auto_mixed_precision_test.cc
  tensorflow/core/grappler/optimizers/generic_layout_optimizer_test.cc
  tensorflow/core/grappler/optimizers/generic_layout_optimizer_transposer_test.cc
  tensorflow/core/grappler/optimizers/memory_optimizer_test.cc
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/grappler/optimizers/remapper_test.cc
  tensorflow/core/grappler/utils_test.cc
Labels: cla: yes, comp:grappler, ready to pull, size:L

#37502 [tflite] add int8 input/output to label_image
  tensorflow/lite/examples/label_image/BUILD
  tensorflow/lite/examples/label_image/bitmap_helpers.h
  tensorflow/lite/examples/label_image/bitmap_helpers_impl.h
  tensorflow/lite/examples/label_image/get_top_n.h
  tensorflow/lite/examples/label_image/get_top_n_impl.h
  tensorflow/lite/examples/label_image/label_image.cc
  tensorflow/lite/examples/label_image/label_image.h
  tensorflow/lite/examples/label_image/label_image_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#37487 NFC - minor spelling tweaks under lite/experimental directory
  tensorflow/lite/experimental/examples/lstm/g3doc/README.md
  tensorflow/lite/experimental/examples/lstm/rnn_cell.py
  tensorflow/lite/experimental/kernels/hashtable_ops_test.cc
  tensorflow/lite/experimental/objc/apis/TFLInterpreter.h
  tensorflow/lite/experimental/resource/lookup_util.h
  tensorflow/lite/experimental/ruy/pack_avx2.cc
  tensorflow/lite/experimental/ruy/platform.h
  tensorflow/lite/experimental/ruy/test.h
  tensorflow/lite/experimental/ruy/tune.h
  tensorflow/lite/experimental/support/java/src/java/org/tensorflow/lite/support/tensorbuffer/TensorBuffer.java
  tensorflow/lite/experimental/swift/Sources/Interpreter.swift
  tensorflow/lite/experimental/swift/Sources/InterpreterError.swift
Labels: cla: yes, comp:lite, ready to pull, size:S

#36558 [ROCm] Fix for a test regression on the ROCm platform - 200207 - 1
  tensorflow/lite/kernels/concatenation_test.cc
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#36659 Debug log implementation to use the STM32 HAL UART implementation. Re…
  tensorflow/lite/micro/stm32f4HAL/debug_log.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#37550 Add `--define=no_tensorflow_py_deps=true` to all `bazel build ...:bui…
  tensorflow/tools/ci_build/builds/pip_new.sh
  tensorflow/tools/ci_build/release/macos/cpu_py35_full/release.sh
  tensorflow/tools/ci_build/release/macos/cpu_py37_full/release.sh
  tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
  tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh
Labels: cla: yes

#37551 Drop experimental and v2 qualifiers from Strategy experimental_run_v2 method. - experimental_run_v2 -> run
  tensorflow/python/debug/lib/distributed_callbacks_test.py
  tensorflow/python/distribute/README.md
  tensorflow/python/distribute/central_storage_strategy.py
  tensorflow/python/distribute/checkpointing_test.py
  tensorflow/python/distribute/ctl_correctness_test.py
  tensorflow/python/distribute/custom_training_loop_gradient_test.py
  tensorflow/python/distribute/custom_training_loop_input_test.py
  tensorflow/python/distribute/custom_training_loop_metrics_test.py
  tensorflow/python/distribute/custom_training_loop_models_test.py
  tensorflow/python/distribute/custom_training_loop_optimizer_test.py
  tensorflow/python/distribute/distribute_lib.py
  tensorflow/python/distribute/distribute_lib_test.py
  tensorflow/python/distribute/distribution_strategy_context.py
  tensorflow/python/distribute/input_lib_test.py
  tensorflow/python/distribute/keras_metrics_test.py
  tensorflow/python/distribute/minimize_loss_test.py
  tensorflow/python/distribute/mirrored_function_strategy_test.py
  tensorflow/python/distribute/mirrored_strategy.py
  tensorflow/python/distribute/mirrored_strategy_test.py
  tensorflow/python/distribute/moving_averages_test.py
  tensorflow/python/distribute/one_device_strategy.py
  tensorflow/python/distribute/saved_model_save_load_test.py
  tensorflow/python/distribute/saved_model_test_base.py
  tensorflow/python/distribute/strategy_combinations_test.py
  tensorflow/python/distribute/strategy_test_lib.py
  tensorflow/python/distribute/tpu_strategy.py
  tensorflow/python/distribute/values.py
  tensorflow/python/distribute/values_test.py
  tensorflow/python/distribute/zero_batch_test.py
  tensorflow/python/eager/forwardprop_test.py
  tensorflow/python/keras/distribute/distribute_strategy_test.py
  tensorflow/python/keras/distribute/distributed_training_utils.py
  tensorflow/python/keras/engine/data_adapter.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/engine/training_distributed.py
  tensorflow/python/kernel_tests/template_mirrored_strategy_test.py
  tensorflow/python/ops/nn_loss_scaling_utilities_test.py
  tensorflow/python/tpu/tpu.py
  tensorflow/python/training/experimental/loss_scaling_gradient_tape.py
  tensorflow/python/training/experimental/loss_scaling_gradient_tape_test.py
  tensorflow/tools/api/golden/v1/tensorflow.distribute.-mirrored-strategy.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.distribute.-one-device-strategy.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.distribute.-strategy.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.distribute.experimental.-central-storage-strategy.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.distribute.experimental.-multi-worker-mirrored-strategy.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.distribute.experimental.-parameter-server-strategy.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.distribute.experimental.-t-p-u-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.-mirrored-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.-one-device-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-central-storage-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-multi-worker-mirrored-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-parameter-server-strategy.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.distribute.experimental.-t-p-u-strategy.pbtxt
  tensorflow/tools/compatibility/tf_upgrade_v2.py
Labels: cla: yes

#37539 Corrected order of parameters in keras WideDeepModel
  tensorflow/python/keras/premade/wide_deep.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37514 [MLIR/XLA] fix wrong tilingSize dimension in lhlo-fuse-linalg pass
  tensorflow/compiler/mlir/xla/tests/lhlo-fuse-linalg.mlir
  tensorflow/compiler/mlir/xla/transforms/lhlo_fuse_linalg.cc
Labels: cla: yes, ready to pull, size:M

#31023 patch-callbacks_test
  tensorflow/python/keras/activations_test.py
  tensorflow/python/keras/callbacks_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37527 docs: update doc for tf.python.tools.saved_model_utils
  tensorflow/python/tools/saved_model_utils.py
Labels: cla: yes, ready to pull, size:XS

#37437 Update bucketized_column documentation comment to fix markdown
  tensorflow/python/feature_column/feature_column.py
  tensorflow/python/feature_column/feature_column_v2.py
Labels: cla: yes, ready to pull, size:XS

#37528 Added example related to top_k parameter in tf.keras.metrics.Precision
  tensorflow/python/keras/metrics.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#37255 Fixed inline code markdown for in docstring
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#37385 Fix for check_pydot when Graphviz is not installed
  tensorflow/python/keras/utils/vis_utils.py
  tensorflow/python/keras/utils/vis_utils_test.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#37566 Do not densify sparse gradients in LossScaleOptimizer
  tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer.py
  tensorflow/python/keras/mixed_precision/experimental/loss_scale_optimizer_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#36466 Go: fix handling empty tags-set for loading saved model
  tensorflow/go/saved_model.go
  tensorflow/go/saved_model_test.go
Labels: cla: yes, ready to pull, size:XS

#36765 [ROCm] Workaround for a known CPU/GPU kernel interface args passing bug
  tensorflow/core/kernels/relu_op.cc
  tensorflow/core/kernels/relu_op.h
  tensorflow/core/kernels/relu_op_functor.h
Labels: cla: yes, comp:gpu, ready to pull, size:S

#37549 Update setup.py estimator version
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#37524 r2.2-rc1 cherry-pick request: [Intel MKL] Fix performance regression in DNNL 1
  tensorflow/core/kernels/mkl_transpose_op.cc
  tensorflow/core/util/mkl_util.h
Labels: cla: yes, size:M

#35302 lite/kernels/concatenation: use tflite::TfLiteRound instead of std::round
  tensorflow/lite/kernels/internal/reference/concatenation.h
Labels: cla: yes, comp:lite, ready to pull, size:XS

#37016 [TfLite] SPLIT_V quantization support for int8
  tensorflow/lite/kernels/register.cc
  tensorflow/lite/kernels/split_v.cc
  tensorflow/lite/kernels/split_v_test.cc
  tensorflow/lite/toco/tflite/op_version.cc
  tensorflow/lite/tools/optimize/operator_property.cc
  tensorflow/lite/tools/versioning/op_version.cc
Labels: cla: yes, comp:lite, prtype:bugfix, ready to pull, size:M

#36273 Add custom_objects in the function layer_test
  tensorflow/python/keras/testing_utils.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37538 Added doc and examples for tf.keras.losses.get
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37582 Update version numbers for TensorFlow 2.2.0-rc1
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#37554 [r2.2:Cherrypick][TF XLA AOT PIP] Fix windows build by properly including the env_time from platform/windows/.
  tensorflow/compiler/tf2xla/BUILD
  tensorflow/core/platform/BUILD
  tensorflow/core/platform/default/BUILD
  tensorflow/core/platform/windows/BUILD
Labels: cla: yes

#37451 Make while_v2_indexed_slices_writers compatible with tensor equality.
  tensorflow/python/kernel_tests/control_flow_ops_py_test.py
  tensorflow/python/ops/while_v2_indexed_slices_rewriter.py
Labels: cla: yes

#37491 Resolve GPU delegate issues for OpenGL/OpenCL backends
  tensorflow/lite/delegates/gpu/BUILD
  tensorflow/lite/delegates/gpu/cl/inference_context.cc
  tensorflow/lite/delegates/gpu/cl/kernels/fully_connected.cc
  tensorflow/lite/delegates/gpu/gl/kernels/mean.cc
  tensorflow/lite/delegates/gpu/metal_delegate.mm
Labels: cla: yes

#37454 <release 2.2>-<rc0> cherry-pick request: Export minimum runtime string in MLIR tflite converter
  tensorflow/compiler/mlir/lite/BUILD
  tensorflow/compiler/mlir/lite/flatbuffer_translate.cc
  tensorflow/compiler/mlir/lite/tests/end2end/add.pbtxt
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/basic_lstm.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/convolution_2d_transpose_bias.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/custom_op_with_tflite_op.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/depthwise_conv2d.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/depthwise_conv2d_v2.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/disable_flex_enable_builtin.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/fake_quant.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/flex_exclusively.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/flex_op_with_tflite_op.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/fully_connected.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/fully_connected_v2.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/if_op.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/logical.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/lstm.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/math.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/max_pooling_with_arg_max_2d.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/max_unpool_2d.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/metadata.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/mul_v2.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/mul_v3.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/nn.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/numeric_verify.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/quantization.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/reshape.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/simple.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/svdf.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/svdf_v2.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/tfl_while_op.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/unidirectional_sequence_lstm.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/unidirectional_sequence_rnn.mlir
  tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer/while_op.mlir
  tensorflow/lite/g3doc/guide/ops_version.md
  tensorflow/lite/kernels/BUILD
  tensorflow/lite/model.cc
  tensorflow/lite/model_test.cc
  tensorflow/lite/testdata/test_min_runtime.bin
  tensorflow/lite/toco/tflite/BUILD
  tensorflow/lite/toco/tflite/op_version.cc
  tensorflow/lite/toco/tflite/op_version.h
  tensorflow/lite/toco/tflite/op_version_test.cc
  tensorflow/lite/tools/versioning/BUILD
  tensorflow/lite/tools/versioning/runtime_version.cc
  tensorflow/lite/tools/versioning/runtime_version.h
  tensorflow/lite/tools/versioning/runtime_version_test.cc
Labels: cla: yes

#37579 [r2.2:Cherrypick]Export fill mode for image_projective_transform
  tensorflow/core/api_def/base_api/api_def_ImageProjectiveTransformV2.pbtxt
  tensorflow/core/kernels/image_ops.cc
  tensorflow/core/kernels/image_ops.h
  tensorflow/core/ops/image_ops.cc
  tensorflow/python/keras/layers/preprocessing/image_preprocessing.py
  tensorflow/python/keras/layers/preprocessing/image_preprocessing_test.py
  tensorflow/python/ops/image_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-rotation.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-translation.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.keras.layers.experimental.preprocessing.-random-zoom.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-rotation.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-translation.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.keras.layers.experimental.preprocessing.-random-zoom.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: cla: yes

#37599 [r2.2:Cherrypick] Fix profiler error when calling model.fit twice in graph mode.
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/callbacks_test.py
Labels: cla: yes

#37465 Trigger sync only if exiting async_scope without exception.
  tensorflow/python/eager/context.py
Labels: cla: yes

#37589 exit bashrc if not running interactively
  tensorflow/tools/dockerfiles/bashrc
Labels: cla: yes, ready to pull, size:XS

#37592 Added preprocessing and corrected example of RGB images before feeding rgb_to_yub
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:S

#37574 Added description for call() in tf.keras.layers.Layer
  tensorflow/python/keras/engine/base_layer.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#37609 typo of TF_STRING in TF_Tensor comments.
  tensorflow/c/tf_tensor.h
Labels: cla: yes, ready to pull, size:XS

#37560 [tensorrt] add missing dependency to make it build
  tensorflow/compiler/tf2tensorrt/BUILD
Labels: cla: yes, comp:gpu:tensorrt, prtype:bugfix, ready to pull, size:XS

#36749 [tflite] add xnnpack delegate to label_image
  tensorflow/lite/examples/label_image/BUILD
  tensorflow/lite/examples/label_image/README.md
  tensorflow/lite/examples/label_image/label_image.cc
  tensorflow/lite/examples/label_image/label_image.h
  tensorflow/lite/tools/evaluation/BUILD
  tensorflow/lite/tools/evaluation/utils.cc
  tensorflow/lite/tools/evaluation/utils.h
  third_party/cpuinfo/BUILD.bazel
Labels: cla: yes, comp:lite, ready to pull, size:S

#26216 Keras: Simplify recurrent state updates
  tensorflow/python/keras/layers/convolutional_recurrent.py
  tensorflow/python/keras/layers/cudnn_recurrent.py
  tensorflow/python/keras/layers/recurrent.py
  tensorflow/python/keras/layers/recurrent_v2.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37120 Edited docstring, y_pred for SparseCategoricalAcc
  tensorflow/python/keras/metrics.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#37646 [r2.2:Cherrypick]Disable failing tests in py38 version.
  tensorflow/python/debug/BUILD
  tensorflow/python/keras/engine/BUILD
  tensorflow/python/kernel_tests/signal/BUILD
Labels: cla: yes

#37586 [Intel MKL] Fixing a bug in MKL Concat op
  tensorflow/core/kernels/mkl_concat_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#37648 [r2.2:Cherrypick] Disable new batchnorm codepath if momentum is not a Python float or int.
  tensorflow/python/keras/layers/normalization.py
Labels: cla: yes

#37651 r2.2-rc1 cherry-pick request: [Intel MKL] Fixing a bug in concat
  tensorflow/core/kernels/mkl_concat_op.cc
Labels: cla: yes

#36593 Fix Invalid description FileWriter
  tensorflow/python/summary/writer/writer.py
Labels: cla: yes, size:S, stat:awaiting response

#36060 [TFLite int16] 16-bit support for reference kernels: MAX/MIN and PACK/UNPACK
  tensorflow/lite/kernels/maximum_minimum.cc
  tensorflow/lite/kernels/maximum_minimum_test.cc
  tensorflow/lite/kernels/pack.cc
  tensorflow/lite/kernels/pack_test.cc
  tensorflow/lite/kernels/register.cc
  tensorflow/lite/kernels/unpack.cc
  tensorflow/lite/kernels/unpack_test.cc
  tensorflow/lite/toco/tflite/op_version.cc
  tensorflow/lite/tools/versioning/op_version.cc
Labels: cla: yes, comp:lite, ready to pull, size:L

#37672 [r2.2:Cherrypick]Update PIP_BIN_PATH to work with all py versions.
  tensorflow/tools/ci_build/builds/pip_new.sh
Labels: cla: yes

#37383 [tflite] NNAPI Pow op allows scalar input
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#37192 Specifying about representative_datasets in TfLiteConverter
  tensorflow/lite/python/lite.py
  tensorflow/python/keras/optimizer_v2/nadam.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#34446 TFLite: Missing activation in built-in Mul operation
  tensorflow/lite/delegates/gpu/common/model_builder.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#37294 Fix TF-TRT control edges between TRTEngineOp nodes
  tensorflow/compiler/tf2tensorrt/convert/convert_graph.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:XS

#35237 Fix typo in TFLiteConverter.from_concrete_function error message
  tensorflow/lite/python/lite.py
  tensorflow/lite/python/lite_v2_test.py
Labels: cla: yes, comp:lite, ready to pull, size:XS

#33292 Add TensorFlow MicroLite Support for the OpenMV Cam
  tensorflow/lite/micro/openmvcam/debug_log.cc
Labels: cla: yes, comp:lite, ready to pull, size:S

#37503 [tflite] allow passing quantized ReLU to NNAPI
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
Labels: awaiting review, cla: yes, comp:lite, ready to pull, size:XS

#37655 concat to tf.concat for consistency
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#37519 Update func_graph.py
  tensorflow/python/framework/func_graph.py
Labels: cla: yes, ready to pull, size:XS

#37223 Use `tf.compat.v1.summary.FileWriter` under TF v1
  tensorflow/tools/api/tests/module_test.py
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#37344 documentation improvement for `tf.debugging.assert_shapes`
  tensorflow/python/ops/check_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#37406 Fix a bug which may cause segmentation fault
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
Labels: cla: yes, comp:grappler, ready to pull, size:XS

#37704 [r2.2:Cherrypick] Remove the trailing 'm' , since the tag for py38 is not cp38m but cp38.
  tensorflow/tools/ci_build/release/windows/gpu_py38_full/release_pip_rename.sh
Labels: cla: yes

#37475 Introduce external delegate provider to benchmark model.
  tensorflow/lite/tools/benchmark/BUILD
  tensorflow/lite/tools/benchmark/README.md
  tensorflow/lite/tools/benchmark/external_delegate_provider.cc
  tensorflow/lite/tools/make/Makefile
Labels: cla: yes, comp:lite, ready to pull, size:M

#37585 Improve preprocessing text docs
  tensorflow/python/keras/preprocessing/text.py
Labels: cla: yes, ready to pull, size:M

#37636 Expose ability to enable NNApi in C api
  tensorflow/lite/c/c_api.cc
  tensorflow/lite/c/c_api_experimental.cc
  tensorflow/lite/c/c_api_experimental.h
  tensorflow/lite/c/c_api_experimental_test.cc
  tensorflow/lite/c/c_api_internal.h
Labels: cla: yes, comp:lite, ready to pull, size:S

#37719 Add -lrt to linkflags
  tensorflow/tensorflow.bzl
Labels: cla: yes, ready to pull, size:S

#36747 Micro: Return error if tensor allocation fails.
  tensorflow/lite/micro/examples/network_tester/network_tester_test.cc
  tensorflow/lite/micro/micro_interpreter.cc
Labels: cla: yes, comp:lite, comp:micro, ready to pull, size:S

#36673 Fix gpu test filters when running the ./configure script
  configure.py
Labels: cla: yes, ready to pull, size:XS

#37734 Static filesystem registration (modular filesystems)
  tensorflow/c/experimental/filesystem/BUILD
  tensorflow/c/experimental/filesystem/modular_filesystem.cc
  tensorflow/c/experimental/filesystem/modular_filesystem_registration.cc
  tensorflow/c/experimental/filesystem/plugins/posix/BUILD
  tensorflow/c/experimental/filesystem/plugins/posix/posix_filesystem.cc
  tensorflow/c/experimental/filesystem/plugins/posix/posix_filesystem.h
  tensorflow/c/experimental/filesystem/plugins/posix/posix_filesystem_static.cc
Labels: cla: yes, ready to pull, size:M

#37754 Add -lrt to linkflags
  tensorflow/tensorflow.bzl
Labels: cla: yes, ready to pull, size:S

#37699 NFC - minor spelling tweaks under lite and lite/examples directories
  tensorflow/lite/examples/label_image/label_image.cc
  tensorflow/lite/external_cpu_backend_context.h
  tensorflow/lite/graph_info.h
  tensorflow/lite/interpreter.cc
  tensorflow/lite/model_test.cc
  tensorflow/lite/util.h
Labels: cla: yes, ready to pull, size:S

#37565 Added code for preprocessing of YUV images before feeding yuv_to_rgb
  tensorflow/python/ops/image_ops_impl.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#37507 Fix typo
  tensorflow/core/api_def/base_api/api_def_DebugNumericSummary.pbtxt
  tensorflow/core/framework/tensor.cc
  tensorflow/core/kernels/cwise_ops_common.h
  tensorflow/core/kernels/spacetobatch_functor.h
Labels: cla: yes, ready to pull, size:S

#37631 NFC - minor spelling tweaks under lite/delegates directory
  tensorflow/lite/delegates/flex/kernel_test.cc
  tensorflow/lite/delegates/gpu/README.md
  tensorflow/lite/delegates/gpu/cl/cl_command_queue.h
  tensorflow/lite/delegates/gpu/cl/cl_program.h
  tensorflow/lite/delegates/gpu/cl/gl_interop.h
  tensorflow/lite/delegates/gpu/cl/inference_context.h
  tensorflow/lite/delegates/gpu/cl/kernels/fully_connected.cc
  tensorflow/lite/delegates/gpu/cl/kernels/max_unpooling.cc
  tensorflow/lite/delegates/gpu/cl/kernels/strided_slice.cc
  tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h
  tensorflow/lite/delegates/gpu/cl/precision.h
  tensorflow/lite/delegates/gpu/cl/tensor.cc
  tensorflow/lite/delegates/gpu/common/memory_management.h
  tensorflow/lite/delegates/gpu/common/memory_management/greedy_by_size_assignment.cc
  tensorflow/lite/delegates/gpu/common/memory_management/greedy_by_size_assignment.h
  tensorflow/lite/delegates/gpu/common/memory_management/internal.h
  tensorflow/lite/delegates/gpu/common/testing/interpreter_utils.h
  tensorflow/lite/delegates/gpu/common/workgroup_selection.cc
  tensorflow/lite/delegates/gpu/delegate.h
  tensorflow/lite/delegates/gpu/gl/compiler/variable_accessor.h
  tensorflow/lite/delegates/gpu/gl/gl_errors.cc
  tensorflow/lite/delegates/gpu/gl/gl_sync.h
  tensorflow/lite/delegates/gpu/gl/kernels/add_test.cc
  tensorflow/lite/delegates/gpu/gl/workgroups/ideal_workgroup_picker.cc
  tensorflow/lite/delegates/gpu/metal/compiled_model.cc
  tensorflow/lite/delegates/gpu/metal/inference_context.h
  tensorflow/lite/delegates/gpu/metal/kernels/add_test.mm
  tensorflow/lite/delegates/nnapi/acceleration_test_list.cc
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
  tensorflow/lite/delegates/nnapi/nnapi_delegate.h
  tensorflow/lite/delegates/nnapi/nnapi_delegate_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#37684 fix a bug in AddSymbolicGradients
  tensorflow/cc/framework/gradients.cc
  tensorflow/cc/framework/gradients_test.cc
Labels: cla: yes, prtype:bugfix, ready to pull, size:XS

#37707 Fix `'for' loop initial declarations are only allowed in C99 mode`
  tensorflow/lite/c/common.c
Labels: cla: yes, comp:lite, ready to pull, size:XS

#37697 NFC - minor spelling tweaks under lite/tools directory
  tensorflow/lite/tools/accuracy/ilsvrc/generate_validation_labels.py
  tensorflow/lite/tools/benchmark/benchmark_test.cc
  tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc
  tensorflow/lite/tools/evaluation/evaluation_stage.h
  tensorflow/lite/tools/evaluation/stages/topk_accuracy_eval_stage.h
  tensorflow/lite/tools/evaluation/stages/utils/image_metrics_test.cc
  tensorflow/lite/tools/gen_op_registration_test.cc
  tensorflow/lite/tools/optimize/calibration/builtin_logging_ops/lstm.cc
  tensorflow/lite/tools/optimize/calibration/calibrator_test.cc
  tensorflow/lite/tools/optimize/calibration/logging_op_resolver.cc
  tensorflow/lite/tools/optimize/operator_property.cc
  tensorflow/lite/tools/optimize/quantize_model.cc
Labels: cla: yes, ready to pull, size:M

#37694 NFC - minor spelling tweaks under lite/kernels directory
  tensorflow/lite/kernels/acceleration_test_util_internal_test.cc
  tensorflow/lite/kernels/activations.cc
  tensorflow/lite/kernels/bidirectional_sequence_lstm_test.cc
  tensorflow/lite/kernels/bidirectional_sequence_rnn_test.cc
  tensorflow/lite/kernels/cpu_backend_context.h
  tensorflow/lite/kernels/cpu_backend_gemm_custom_gemv.h
  tensorflow/lite/kernels/cpu_backend_gemm_eigen.cc
  tensorflow/lite/kernels/detection_postprocess_test.cc
  tensorflow/lite/kernels/fully_connected.cc
  tensorflow/lite/kernels/fully_connected_test.cc
  tensorflow/lite/kernels/internal/depthwiseconv_per_channel_quantized_test.cc
  tensorflow/lite/kernels/internal/optimized/depthwiseconv_float.h
  tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h
  tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8_3x3_filter.h
  tensorflow/lite/kernels/internal/optimized/integer_ops/depthwise_conv.h
  tensorflow/lite/kernels/internal/optimized/integer_ops/depthwise_conv_3x3_filter.h
  tensorflow/lite/kernels/internal/optimized/integer_ops/mean.h
  tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.cc
  tensorflow/lite/kernels/internal/optimized/optimized_ops.h
  tensorflow/lite/kernels/internal/quantization_util.cc
  tensorflow/lite/kernels/internal/reference/binary_function.h
  tensorflow/lite/kernels/internal/spectrogram.cc
  tensorflow/lite/kernels/internal/tensor_utils.h
  tensorflow/lite/kernels/internal/tensor_utils_test.cc
  tensorflow/lite/kernels/kernel_util.cc
  tensorflow/lite/kernels/lstm.cc
  tensorflow/lite/kernels/lstm_eval.cc
  tensorflow/lite/kernels/matrix_diag_test.cc
  tensorflow/lite/kernels/pad_test.cc
  tensorflow/lite/kernels/rfft2d.cc
  tensorflow/lite/kernels/strided_slice_test.cc
  tensorflow/lite/kernels/subgraph_test_util.h
  tensorflow/lite/kernels/subgraph_test_util_test.cc
  tensorflow/lite/kernels/svdf_test.cc
  tensorflow/lite/kernels/variable_ops_test.cc
  tensorflow/lite/kernels/while_test.cc
Labels: cla: yes, kokoro:force-run, ready to pull, size:M

#37696 NFC - minor spelling tweaks under lite/toco directory
  tensorflow/lite/toco/dump_graphviz.cc
  tensorflow/lite/toco/graph_transformations/convert_trivial_transpose_to_reshape.cc
  tensorflow/lite/toco/graph_transformations/graph_transformations.h
  tensorflow/lite/toco/graph_transformations/identify_dilated_conv.cc
  tensorflow/lite/toco/graph_transformations/propagate_fake_quant_num_bits.cc
  tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc
  tensorflow/lite/toco/graph_transformations/quantization_util.cc
  tensorflow/lite/toco/graph_transformations/remove_successive_transpose.cc
  tensorflow/lite/toco/graph_transformations/tests/remove_successive_transpose_test.cc
  tensorflow/lite/toco/graph_transformations/unroll_batch_matmul.cc
  tensorflow/lite/toco/logging/gen_html.py
  tensorflow/lite/toco/model.h
  tensorflow/lite/toco/python/toco_from_protos.py
  tensorflow/lite/toco/python/toco_from_protos_test.py
  tensorflow/lite/toco/tflite/export.cc
  tensorflow/lite/toco/tflite/operator_test.cc
  tensorflow/lite/toco/toco_cmdline_flags.cc
  tensorflow/lite/toco/toco_convert_test.cc
  tensorflow/lite/toco/toco_tooling.cc
  tensorflow/lite/toco/tooling_util.cc
Labels: cla: yes, ready to pull, size:M

#37677 Add missing dependencies download command
  tensorflow/lite/tools/pip_package/README.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#36655 Update wav_to_features.py
  tensorflow/examples/speech_commands/wav_to_features.py
Labels: cla: yes, ready to pull, size:XS

#37281 docs: add examples for random_uniform, random_normal and random_binomial in tf.keras.backend
  tensorflow/python/keras/backend.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#37647 Refactor DirectedInterleaveDatasetOp
  tensorflow/core/kernels/data/dataset_test_base.cc
  tensorflow/core/kernels/data/experimental/BUILD
  tensorflow/core/kernels/data/experimental/directed_interleave_dataset_op.cc
  tensorflow/core/kernels/data/experimental/directed_interleave_dataset_op.h
  tensorflow/core/kernels/data/experimental/directed_interleave_dataset_op_test.cc
Labels: cla: yes, comp:ops, ready to pull, size:L

#37781 Expose eager c_api_experimental to other language binding.
  tensorflow/BUILD
Labels: cla: yes, ready to pull, size:XS
