Repository tensorflow/tensorflow, pull requests merged in 2021-06, with the labels that each got.

#49144 TFLM: Enable FVP target in benchmarks
  tensorflow/lite/micro/benchmarks/Makefile.inc
  tensorflow/lite/micro/benchmarks/README.md
  tensorflow/lite/micro/benchmarks/person_detection_benchmark.cc
  tensorflow/lite/micro/cortex_m_corstone_300/micro_time.cc
  tensorflow/lite/micro/cortex_m_corstone_300/system_setup.cc
  tensorflow/lite/micro/kernels/ethos_u/README.md
  tensorflow/lite/micro/testing/test_with_arm_corstone_300.sh
  tensorflow/lite/micro/tools/make/ethos_u_core_platform_download.sh
  tensorflow/lite/micro/tools/make/ext_libs/ethos_u.inc
  tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc
Labels: cla: yes, comp:micro, comp:micro:arm, prtype:bugfix, ready to pull, size:M

#49857 Fix error when compile asm files
  tensorflow/lite/micro/tools/make/helper_functions.inc
Labels: cla: yes, comp:micro, ready to pull, size:XS

#49932 Remove IMAGE_RECOGNITION variables from third_party_downloads
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, comp:micro, ready to pull, size:XS

#49839 Update the TFLM readme to reflect the new repo location.
  tensorflow/lite/micro/README.md
Labels: cla: yes, comp:micro, ready to pull, size:M

#49881 Fix heap OOB / undefined behavior in `RaggedTensorToTensor`
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes

#49882 Fix heap OOB / undefined behavior in `RaggedTensorToTensor`
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes

#49883 Fix heap OOB / undefined behavior in `RaggedTensorToTensor`
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes

#49884 Fix heap OOB / undefined behavior in `RaggedTensorToTensor`
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes

#49598 [MLIR][DISC] legalize tensor_load inserted during hlo-to-lhlo conversion
  tensorflow/compiler/mlir/hlo/BUILD
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/transforms/lmhlo_passes.td
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/transforms/passes.h
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/CMakeLists.txt
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_tensor_load_op.cc
  tensorflow/compiler/mlir/hlo/tests/lhlo-legalize-tensor-load-op.mlir
Labels: cla: yes, ready to pull, size:L

#49885 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_add_op.cc
Labels: cla: yes

#49886 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_add_op.cc
Labels: cla: yes

#49887 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_add_op.cc
Labels: cla: yes

#49888 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_add_op.cc
Labels: cla: yes

#49952 Prevent yet another division by zero
  tensorflow/core/kernels/conv_grad_input_ops.cc
Labels: cla: yes

#49953 Prevent yet another division by zero
  tensorflow/core/kernels/conv_grad_input_ops.cc
Labels: cla: yes

#49954 Prevent yet another division by zero
  tensorflow/core/kernels/conv_grad_input_ops.cc
Labels: cla: yes

#49955 Prevent yet another division by zero
  tensorflow/core/kernels/conv_grad_input_ops.cc
Labels: cla: yes

#49957 Fix one more FPE.
  tensorflow/core/kernels/conv_ops.cc
Labels: cla: no

#49958 Fix one more FPE.
  tensorflow/core/kernels/conv_ops.cc
Labels: cla: no

#49959 Fix one more FPE.
  tensorflow/core/kernels/conv_ops.cc
Labels: cla: no

#49960 Fix one more FPE.
  tensorflow/core/kernels/conv_ops.cc
Labels: cla: no

#49963 Fix heap-buffer-overflow issue with .
  tensorflow/core/kernels/sparse_reshape_op.cc
Labels: cla: yes

#49964 Fix heap-buffer-overflow issue with .
  tensorflow/core/kernels/sparse_reshape_op.cc
Labels: cla: yes

#49965 Fix heap-buffer-overflow issue with .
  tensorflow/core/kernels/sparse_reshape_op.cc
Labels: cla: yes

#49966 Fix heap-buffer-overflow issue with .
  tensorflow/core/kernels/sparse_reshape_op.cc
Labels: cla: yes

#49967 Fix tf.raw_ops.SparseCross failing CHECK.
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#49990 Cherry pick 2.1 Add missing valuidation to FusedBatchNorm
  tensorflow/core/kernels/fused_batch_norm_op.cc
Labels: cla: no

#49991 Cherry pick 2.2 Add missing valuidation to FusedBatchNorm
  tensorflow/core/kernels/fused_batch_norm_op.cc
Labels: cla: no

#49992 Cherry pick 2.3 Add missing valuidation to FusedBatchNorm
  tensorflow/core/kernels/fused_batch_norm_op.cc
Labels: cla: no

#49986 Fix the 2.1 branch after cherrypicks
  tensorflow/core/kernels/fft_ops.cc
  tensorflow/core/kernels/quantize_and_dequantize_op.cc
  tensorflow/core/kernels/quantized_conv_ops.cc
  tensorflow/core/kernels/sparse/kernels.cc
  tensorflow/core/kernels/sparse/sparse_cholesky_op.cc
  tensorflow/core/kernels/sparse_add_op.cc
  tensorflow/core/kernels/sparse_reshape_op.cc
  tensorflow/core/kernels/sparse_split_op.cc
Labels: cla: yes

#49987 Fix r2.2 branch after cherrypicks
  tensorflow/core/kernels/sparse_split_op.cc
Labels: cla: yes

#49988 Fix r2.3 branch after cherrypicks
  tensorflow/core/kernels/sparse_split_op.cc
Labels: cla: yes

#49989 Fix r2.4 branch after cherrypicks
  tensorflow/core/kernels/sparse_split_op.cc
Labels: cla: yes

#49873 Fix crash with tf.transpose when a is complex and conjugate is True
  tensorflow/core/kernels/transpose_functor.h
  tensorflow/python/kernel_tests/transpose_op_test.py
  tensorflow/workspace.bzl
  third_party/jsoncpp.BUILD
Labels: cla: yes

#49874 Fix crash with tf.transpose when a is complex and conjugate is True
  tensorflow/core/kernels/transpose_functor.h
  tensorflow/python/kernel_tests/transpose_op_test.py
  tensorflow/workspace.bzl
  third_party/jsoncpp.BUILD
Labels: cla: yes

#49875 Fix crash with tf.transpose when a is complex and conjugate is True
  tensorflow/core/kernels/transpose_functor.h
  tensorflow/python/kernel_tests/transpose_op_test.py
  tensorflow/workspace.bzl
  third_party/jsoncpp.BUILD
Labels: cla: yes

#49876 Fix crash with tf.transpose when a is complex and conjugate is True
  tensorflow/core/kernels/transpose_functor.h
  tensorflow/python/kernel_tests/transpose_op_test.py
  tensorflow/workspace.bzl
  third_party/jsoncpp.BUILD
Labels: cla: yes

#49994 Cherry pick 2.1 TFLite: Error out when the graph has a recurion.
  tensorflow/lite/BUILD
  tensorflow/lite/core/subgraph.cc
  tensorflow/lite/core/subgraph.h
  tensorflow/lite/kernels/while.cc
  tensorflow/lite/model_test.cc
  tensorflow/lite/testdata/unsupported_recursion.bin
Labels: cla: yes

#49995 Cherry pick 2.2 TFLite: Error out when the graph has a recurion.
  tensorflow/lite/BUILD
  tensorflow/lite/core/subgraph.cc
  tensorflow/lite/core/subgraph.h
  tensorflow/lite/kernels/while.cc
  tensorflow/lite/model_test.cc
  tensorflow/lite/testdata/unsupported_recursion.bin
Labels: cla: yes

#49996 Cherrypick2.3 TFLite: Error out when the graph has a recurion.
  tensorflow/lite/BUILD
  tensorflow/lite/core/subgraph.cc
  tensorflow/lite/core/subgraph.h
  tensorflow/lite/kernels/while.cc
  tensorflow/lite/model_test.cc
  tensorflow/lite/testdata/unsupported_recursion.bin
Labels: cla: yes

#49997 Cherry pick 2.4 TFLite: Error out when the graph has a recurion.
  tensorflow/lite/BUILD
  tensorflow/lite/core/subgraph.cc
  tensorflow/lite/core/subgraph.h
  tensorflow/lite/kernels/while.cc
  tensorflow/lite/model_test.cc
  tensorflow/lite/testdata/unsupported_recursion.bin
Labels: cla: yes

#49999 CherryPick2.1:Add depth_to_space TFLite op
  tensorflow/lite/kernels/depth_to_space.cc
  tensorflow/lite/kernels/depth_to_space_test.cc
Labels: cla: no

#49998 CherryPick2.2:Add depth_to_space TFLite op
  tensorflow/lite/kernels/depth_to_space.cc
  tensorflow/lite/kernels/depth_to_space_test.cc
Labels: cla: no

#50000 CherryPick2.3:Add depth_to_space TFLite op
  tensorflow/lite/kernels/depth_to_space.cc
  tensorflow/lite/kernels/depth_to_space_test.cc
Labels: cla: no

#50001 CherryPick2.4:Add depth_to_space TFLite op
  tensorflow/lite/kernels/depth_to_space.cc
  tensorflow/lite/kernels/depth_to_space_test.cc
Labels: cla: no

#50003 CherryPick2.1:Define TfLiteFloatArrayGetSizeInBytes even when TF_LITE_STATIC_MEMORY…
  tensorflow/lite/c/c_api_internal.c
Labels: cla: no

#50006 CherryPick2.1: Fix heap-buffer-overflow issue with tf.raw_ops.SparseFillEmptyRows
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#50007 CherryPick2.2:Fix heap-buffer-overflow issue with tf.raw_ops.SparseFillEmptyRows.
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#50008 CherryPick2.3:Fix heap-buffer-overflow issue with tf.raw_ops.SparseFillEmptyRows.
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#50009 CherryPick2.4:Fix heap-buffer-overflow issue with tf.raw_ops.SparseFillEmptyRows.
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#50010 CherryPick:2.1 Fix bugs
  tensorflow/core/kernels/decode_padded_raw_op.cc
Labels: cla: no

#50011 CherryPick:2.2 Fix tf.io.decode_raw bugs
  tensorflow/core/kernels/decode_padded_raw_op.cc
Labels: cla: no

#50013 CherryPick:2.3 Fix tf.io.decode_raw bugs
  tensorflow/core/kernels/decode_padded_raw_op.cc
Labels: cla: no

#50012 CherryPick:2.4 Fix tf.io.decode_raw bugs
  tensorflow/core/kernels/decode_padded_raw_op.cc
Labels: cla: no

#50030 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_sparse_binary_op_shared.cc
Labels: cla: yes

#50031 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_sparse_binary_op_shared.cc
Labels: cla: yes

#50032 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_sparse_binary_op_shared.cc
Labels: cla: yes

#50033 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_sparse_binary_op_shared.cc
Labels: cla: yes

#50034 Ensure validation sticks in banded_triangular_solve_op
  tensorflow/core/kernels/linalg/banded_triangular_solve_op.cc
Labels: cla: yes

#50035 Ensure validation sticks in banded_triangular_solve_op
  tensorflow/core/kernels/banded_triangular_solve_op.cc
Labels: cla: yes

#50036 Bump curl
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes

#50037 Bump curl
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes

#50038 Bump curl
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes

#50039 Bump curl
  tensorflow/workspace.bzl
  third_party/curl.BUILD
Labels: cla: yes

#49009 [tf.data] graduate experimental `scan` API to tf.data.Dataset
  RELEASE.md
  tensorflow/python/autograph/operators/control_flow.py
  tensorflow/python/autograph/operators/control_flow_deprecated_py2.py
  tensorflow/python/data/experimental/kernel_tests/BUILD
  tensorflow/python/data/experimental/ops/BUILD
  tensorflow/python/data/experimental/ops/scan_ops.py
  tensorflow/python/data/kernel_tests/BUILD
  tensorflow/python/data/kernel_tests/scan_test.py
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.data.-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-fixed-length-record-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-t-f-record-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-text-line-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-csv-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-random-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-sql-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-fixed-length-record-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-t-f-record-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-text-line-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-csv-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-random-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-sql-dataset.pbtxt
Labels: cla: yes, comp:data, ready to pull, size:L

#50049 Update version numbers for TensorFlow 2.4.2
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#50050 Update version numbers for TensorFlow 2.1.4
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#50051 Update version numbers for TensorFlow 2.2.3
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#50052 Update version numbers for TensorFlow 2.3.3
  tensorflow/core/public/version.h
  tensorflow/tensorflow.bzl
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#50043 Update release notes for TensorFlow 2.1.4
  RELEASE.md
Labels: cla: yes

#50044 Update release notes for TensorFlow 2.2.3
  RELEASE.md
Labels: cla: yes

#50047 Update release notes for TensorFlow 2.3.3
  RELEASE.md
Labels: cla: yes

#50046 Update release notes for TensorFlow 2.4.2
  RELEASE.md
Labels: cla: yes

#50053 Fix broken cherrypick
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#50055 Fix broekn branch after cherrypick
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#50057 Fix broken code after cherrypick
  tensorflow/lite/core/subgraph.h
Labels: cla: yes

#50058 Fix cherrypick breakage
  tensorflow/lite/core/subgraph.cc
Labels: cla: yes

#49199 Add missing "metrics_*.py" modules to tflite_runtime bazel build script
  tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh
Labels: cla: yes, comp:lite, ready to pull, size:XS

#50060 Fix cherrypick breakage
  tensorflow/lite/core/subgraph.cc
Labels: cla: yes

#49825 Fix typo on line 3918, "tf.data.experimental.enable_debug_mode()"
  tensorflow/python/data/ops/dataset_ops.py
Labels: cla: yes, comp:data, prtype:bugfix, ready to pull, size:XS

#50061 Fix CherryPick issue
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#50062 Fix Cherrypick issue
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#50063 FIx Cherrypick issue
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#50064 Fix Cherrypick issue
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#50065 Fix json after cherrypicks
  third_party/jsoncpp.BUILD
Labels: cla: yes

#50066 Fix Cherrypick breakage
  third_party/jsoncpp.BUILD
Labels: cla: yes

#48951 Use static variable for checking TF_CUDNN_USE_FRONTEND
  tensorflow/core/util/use_cudnn.cc
Labels: cla: yes, comp:core, ready to pull, size:S

#49486 Suppress TF-32 warning print when disabled by TF's own API
  tensorflow/stream_executor/cuda/cuda_blas.cc
Labels: cla: yes, ready to pull, size:XS

#49178 [determinism] Add non-sparse softmax/xent GPU-determinism
  tensorflow/core/kernels/xent_op.cc
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/xent_op_deterministic_test.py
  tensorflow/python/kernel_tests/xent_op_test.py
  tensorflow/python/kernel_tests/xent_op_test_base.py
  tensorflow/python/ops/nn_ops.py
  tensorflow/tools/pip_package/BUILD
Labels: cla: yes, ready to pull, size:L

#50072 Revert "Stubbed out memory allocation calls in audio library"
  tensorflow/lite/experimental/microfrontend/lib/BUILD
  tensorflow/lite/experimental/microfrontend/lib/fft_io.c
  tensorflow/lite/experimental/microfrontend/lib/fft_util.cc
  tensorflow/lite/experimental/microfrontend/lib/filterbank_io.c
  tensorflow/lite/experimental/microfrontend/lib/filterbank_util.c
  tensorflow/lite/experimental/microfrontend/lib/fprintf_shim.h
  tensorflow/lite/experimental/microfrontend/lib/frontend_io.c
  tensorflow/lite/experimental/microfrontend/lib/frontend_main.c
  tensorflow/lite/experimental/microfrontend/lib/frontend_memmap_generator.c
  tensorflow/lite/experimental/microfrontend/lib/frontend_memmap_main.c
  tensorflow/lite/experimental/microfrontend/lib/frontend_util.c
  tensorflow/lite/experimental/microfrontend/lib/log_scale_io.c
  tensorflow/lite/experimental/microfrontend/lib/memory_util.h
  tensorflow/lite/experimental/microfrontend/lib/memory_util_fixed_pool.c
  tensorflow/lite/experimental/microfrontend/lib/memory_util_stdlib.c
  tensorflow/lite/experimental/microfrontend/lib/memory_util_test.cc
  tensorflow/lite/experimental/microfrontend/lib/noise_reduction_io.c
  tensorflow/lite/experimental/microfrontend/lib/noise_reduction_util.c
  tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control.c
  tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control_util.c
  tensorflow/lite/experimental/microfrontend/lib/window_io.c
  tensorflow/lite/experimental/microfrontend/lib/window_util.c
  tensorflow/lite/micro/examples/micro_speech/Makefile.inc
  tensorflow/lite/micro/examples/micro_speech/simple_features/bluepill/simple_features_generator_test.cc
  tensorflow/lite/micro/tools/make/targets/bluepill_makefile.inc
Labels: cla: yes, ready to pull, size:L

#49856 Enable method delegation test in eager distributed `AutoCastVariable`
  tensorflow/python/keras/mixed_precision/autocast_variable_test.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#50085 Update conv.cc
  tensorflow/lite/kernels/conv.cc
Labels: cla: yes

#50087 Update conv.cc
  tensorflow/lite/kernels/conv.cc
Labels: cla: yes

#50089 Update conv.cc
  tensorflow/lite/kernels/conv.cc
Labels: cla: yes

#48580 Symmetric Fake Quantization
  tensorflow/core/kernels/fake_quant_ops_functor.h
  tensorflow/core/kernels/fake_quant_ops_test.cc
Labels: cla: yes, comp:core, prtype:bugfix, ready to pull, size:S

#50090 Fix usage of TF_LITE_ENSURE_MSG in constructor
  tensorflow/lite/core/subgraph.cc
Labels: cla: yes

#50091 Fix usage of TF_LITE_ENSURE_MSG in constructor
  tensorflow/lite/core/subgraph.cc
Labels: cla: yes

#50092 Update ragged_tensor_to_variant_op.cc
  tensorflow/core/kernels/ragged_tensor_to_variant_op.cc
Labels: cla: yes

#49970 [MLIR][DISC] bufferize DynamicReshape and DynamicBroadcastInDim
  tensorflow/compiler/mlir/hlo/BUILD
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/hlo_ops.td
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/lhlo_ops.td
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/transforms/map_hlo_to_lhlo_op.h
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/transforms/mhlo_passes.td
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/transforms/passes.h
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/transforms/rewriters.h
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/IR/hlo_ops.cc
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/hlo_legalize_to_lhlo.cc
  tensorflow/compiler/mlir/hlo/tests/hlo-legalize-to-lhlo-only-dynamic.mlir
  tensorflow/compiler/mlir/tools/kernel_gen/transforms/bufferize_pass.cc
Labels: cla: yes, ready to pull, size:M

#50095 Fix branch after cherrypick
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#50097 Another attempt at fixing branch
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#49244 Upgrade Cudnn Frontend repo to v0.3 and use fallback list for ConvBiasAct ops
  tensorflow/stream_executor/cuda/cuda_dnn.cc
  tensorflow/workspace2.bzl
  third_party/cudnn_frontend_header_fix.patch
Labels: awaiting review, cla: yes, ready to pull, size:M

#50128 Update sparse_cross_op.cc
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#50129 Update sparse_cross_op.cc
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#49848 Fix an incorrect axis in the Dense layer documentation
  tensorflow/python/keras/layers/core.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#50151 Update sparse_fill_empty_rows_op.cc
  tensorflow/core/kernels/sparse_fill_empty_rows_op.cc
Labels: cla: yes

#49984 Update Release.md with 2.5.0 notes.
  RELEASE.md
Labels: cla: yes, ready to pull, size:L

#50160 Disabling failing raw_ops_test
  tensorflow/python/ops/raw_ops_test.py
Labels: cla: yes

#50162 Update raw_ops_test.py
  tensorflow/python/ops/raw_ops_test.py
Labels: cla: yes

#50161 Revert "Update sparse_cross_op.cc"
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#50059 Revert "Use cudnn for grouped backward input convolution."
  tensorflow/compiler/xla/service/gpu/gpu_conv_rewriter.cc
Labels: cla: yes, ready to pull, size:S

#49985 [XLA] Change the optimized dump filename to specify the target
  tensorflow/compiler/xla/service/cpu/cpu_compiler.cc
  tensorflow/compiler/xla/service/gpu/gpu_compiler.cc
Labels: cla: yes, ready to pull, size:XS

#50015 [TF-TRT] Argument bugfix
  tensorflow/python/compiler/tensorrt/trt_convert.py
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:S

#48207 fix lambda dynamic shape inference
  tensorflow/python/keras/engine/base_layer.py
  tensorflow/python/keras/engine/base_layer_v1.py
  tensorflow/python/keras/layers/core_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#50119 Added protobuf systemlib stub needed by gRPC.
  tensorflow/workspace2.bzl
  third_party/systemlibs/protobuf_deps.bzl
Labels: cla: yes, ready to pull, size:XS

#49510 Fix ubsan in bazelrc
  .bazelrc
Labels: cla: yes, ready to pull, size:XS

#49827 Adding documentation for running doctests locally
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:S

#49903 Added test case for Accuracy alias
  tensorflow/python/keras/engine/compile_utils_test.py
Labels: cla: yes, ready to pull, size:XS

#49942 Added RaggedTensor support to reduce_std
  tensorflow/python/ops/math_ops.py
  tensorflow/python/ops/math_ops_test.py
  tensorflow/python/ops/ragged/ragged_dispatch.py
  tensorflow/python/ops/ragged/ragged_dispatch_test.py
  tensorflow/python/ops/ragged/ragged_math_ops.py
  tensorflow/python/ops/ragged/ragged_reduce_op_test.py
Labels: cla: yes, ready to pull, size:M

#49609 Fixing math_ops.reduce_variance for dispatch failure to ragged
  tensorflow/python/ops/math_ops.py
  tensorflow/python/ops/math_ops_test.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:XS

#49519 Added missing reshape folding for MEAN op to TFLite MLIR converter
  tensorflow/compiler/mlir/lite/tests/optimize.mlir
  tensorflow/compiler/mlir/lite/transforms/optimize_patterns.td
Labels: cla: yes, ready to pull, size:S

#50131 Update bot_config.yml
  .github/bot_config.yml
Labels: cla: yes, ready to pull, size:XS

#50133 Create pylint-presubmit.yml
  .github/workflows/pylint-presubmit.yml
Labels: cla: yes, ready to pull, size:S

#50183 Fix cherrypick issue
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#50184 Update common_win.bat
  tensorflow/tools/ci_build/release/common_win.bat
Labels: cla: yes

#49317 Remove duplicated entry of Env::Default
  tensorflow/compiler/tf2xla/ops/BUILD
Labels: cla: yes, ready to pull, size:XS

#49279 [INTEL MKL] Use static variables for checking env variable and platform
  tensorflow/core/util/mkl_util.h
Labels: cla: yes, comp:mkl, ready to pull, size:S

#50135 [determinism] Factor core/kernels RequireDeterminism() into library
  tensorflow/core/kernels/image/resize_bilinear_op_gpu.cu.cc
  tensorflow/core/kernels/segment_reduction_ops.h
  tensorflow/core/kernels/segment_reduction_ops_gpu.cu.cc
  tensorflow/core/kernels/segment_reduction_ops_impl.h
  tensorflow/core/kernels/sparse_xent_op.cc
  tensorflow/core/util/determinism.h
  tensorflow/python/kernel_tests/sparse_xent_op_deterministic_test.py
  tensorflow/python/kernel_tests/xent_op_deterministic_test.py
Labels: cla: yes, ready to pull, size:M

#49511 Fix JNI memleak problem for java Tensor<String> reference invoked by tensor_jni.cc
  tensorflow/java/src/main/native/tensor_jni.cc
Labels: cla: yes, ready to pull, size:XS

#50146 Remove meaningless log in KernelDefBuilder
  tensorflow/core/framework/kernel_def_builder.cc
Labels: cla: yes, comp:core, ready to pull, size:XS

#48244 [TF-TRT] Enable INT8 calibration for use_implicit_batch=false when there is no dynamic shape inputs
  tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:S

#49488 Doc for custom_gradient to compute gradients for trainable params and computing over batch
  tensorflow/python/ops/custom_gradient.py
Labels: cla: yes, comp:ops, ready to pull, size:M, type:docs-bug

#49739 Add docs about forcing zero output for mask with Bidirectional
  tensorflow/python/keras/layers/wrappers.py
Labels: cla: yes, comp:keras, ready to pull, size:XS, type:docs-bug

#50185 Fix the nonpip builds for MacOS.
  tensorflow/tools/ci_build/rel/macos/cpu_py36_nonpip.sh
  tensorflow/tools/ci_build/rel/macos/cpu_py37_nonpip.sh
  tensorflow/tools/ci_build/rel/macos/cpu_py38_nonpip.sh
Labels: cla: yes, size:XS

#50201 Update raw_ops_test.py
  tensorflow/python/ops/raw_ops_test.py
Labels: cla: yes

#50203 Don't force reinstall TB
  tensorflow/tools/ci_build/release/common.sh
Labels: cla: yes

#49981 Fix error message for using numpy-related methods
  tensorflow/python/framework/ops.py
Labels: cla: yes, ready to pull, size:XS

#50056 [tf.data] graduate unique API from experimental to tf.data.Dataset
  RELEASE.md
  tensorflow/python/data/experimental/kernel_tests/BUILD
  tensorflow/python/data/experimental/ops/BUILD
  tensorflow/python/data/experimental/ops/unique.py
  tensorflow/python/data/kernel_tests/BUILD
  tensorflow/python/data/kernel_tests/unique_test.py
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.data.-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-fixed-length-record-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-t-f-record-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-text-line-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-csv-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-random-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-sql-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-fixed-length-record-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-t-f-record-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-text-line-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-csv-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-random-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-sql-dataset.pbtxt
Labels: cla: yes, comp:data, ready to pull, size:M

#50100 [MLIR][DISC] Bufferize DynamicIotaOp and DynamicPadOp
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/hlo_ops.td
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/lhlo_ops.td
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/transforms/map_hlo_to_lhlo_op.h
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/IR/hlo_ops.cc
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/hlo_legalize_to_lhlo.cc
  tensorflow/compiler/mlir/hlo/tests/hlo-legalize-to-lhlo-only-dynamic.mlir
Labels: cla: yes, ready to pull, size:M

#42846 Add a warning when fitting models loaded from SavedModels
  tensorflow/python/keras/saving/saved_model/load.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#49971 Fix _Arg op diagnostic for _handle_dtypes attribute
  tensorflow/core/ops/function_ops.cc
Labels: cla: yes, ready to pull, size:XS

#49497 Remove the AMDGPU due to duplicated dependency
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/BUILD
Labels: cla: yes, ready to pull, size:XS

#50084 [tf.data] graduate snapshot API from experimental to tf.data.Dataset
  RELEASE.md
  tensorflow/python/data/experimental/kernel_tests/BUILD
  tensorflow/python/data/experimental/ops/snapshot.py
  tensorflow/python/data/kernel_tests/BUILD
  tensorflow/python/data/kernel_tests/snapshot_test.py
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.data.-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-fixed-length-record-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-t-f-record-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-text-line-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-csv-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-random-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-sql-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-fixed-length-record-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-t-f-record-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-text-line-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-csv-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-random-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-sql-dataset.pbtxt
Labels: cla: yes, comp:data, ready to pull, size:L

#49314 Skip hdfs if -config=nohdfs is passed to bazel
  tensorflow/core/platform/default/build_config.bzl
  tensorflow/tools/lib_package/BUILD
  tensorflow/tools/pip_package/BUILD
Labels: cla: yes, comp:core, ready to pull, size:XS

#45830 [INTEL MKL] Replace dead Switch nodes with Identity
  tensorflow/core/grappler/optimizers/loop_optimizer.cc
  tensorflow/core/grappler/optimizers/loop_optimizer.h
  tensorflow/core/grappler/optimizers/loop_optimizer_test.cc
  tensorflow/python/kernel_tests/cond_v2_test.py
  tensorflow/python/kernel_tests/control_flow_ops_py_test.py
Labels: cla: yes, comp:grappler, ready to pull, size:M

#49859 Update doc example for tf.Variable.scatter_nd_update()
  tensorflow/python/ops/variables.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#50210 Disable io_test
  tensorflow/python/data/experimental/kernel_tests/BUILD
Labels: cla: yes, size:XS

#50197 Refactor SparseSegmentGrad kernel into a functor (NFC)
  tensorflow/core/kernels/segment_reduction_ops.h
  tensorflow/core/kernels/segment_reduction_ops_impl.h
  tensorflow/core/kernels/segment_reduction_ops_impl_5.cc
Labels: cla: yes, comp:core, ready to pull, size:M

#47957 Fixed NotImplementedError: Cannot convert a symbolic Tensor to a numpy array
  tensorflow/python/ops/array_ops.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#49720 Multiple Eager Rewriters
  tensorflow/compiler/mlir/tfr/integration/node_expansion_pass.cc
  tensorflow/core/common_runtime/eager/eager_op_rewrite_registry.cc
  tensorflow/core/common_runtime/eager/eager_op_rewrite_registry.h
  tensorflow/core/common_runtime/eager/eager_op_rewrite_registry_test.cc
  tensorflow/core/common_runtime/eager/mkl_eager_op_rewrite.cc
Labels: cla: yes, ready to pull, size:M
