Repository tensorflow/tensorflow, pull requests merged in 2021-05, with the labels that each got.

#47897 Cleanup expired forward compatibility horizons
  tensorflow/python/data/experimental/ops/error_ops.py
  tensorflow/python/data/experimental/ops/readers.py
  tensorflow/python/debug/lib/debug_v2_ops_test.py
  tensorflow/python/debug/lib/dumping_callback.py
  tensorflow/python/distribute/input_lib_test.py
  tensorflow/python/keras/layers/preprocessing/image_preprocessing.py
  tensorflow/python/ops/embedding_ops.py
  tensorflow/python/ops/image_ops_impl.py
  tensorflow/python/ops/lookup_ops.py
  tensorflow/python/ops/sparse_ops.py
Labels: cla: yes, ready to pull, size:M

#48814 Build Failure fix on AVX2 machines replace si64 with epi64
  tensorflow/lite/kernels/internal/optimized/depthwiseconv_uint8.h
Labels: cla: yes, comp:lite, ready to pull, size:XS

#48812 Port micro op GATHER_ND and its test code from lite
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/gather_nd.cc
  tensorflow/lite/micro/kernels/gather_nd_test.cc
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:micro, ready to pull, size:L

#48063 Add _FusedBatchNormGrad to support side_input and activation
  tensorflow/compiler/xla/service/gpu/cudnn_batchnorm_runner.cc
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/grappler/optimizers/remapper_test.cc
  tensorflow/core/kernels/fused_batch_norm_ex_op_test.cc
  tensorflow/core/kernels/fused_batch_norm_op.cc
  tensorflow/core/ops/nn_ops.cc
  tensorflow/stream_executor/cuda/cuda_dnn.cc
  tensorflow/stream_executor/cuda/cuda_dnn.h
  tensorflow/stream_executor/dnn.h
  tensorflow/stream_executor/rocm/rocm_dnn.cc
  tensorflow/stream_executor/rocm/rocm_dnn.h
  tensorflow/stream_executor/stream.cc
  tensorflow/stream_executor/stream.h
Labels: cla: yes, ready to pull, size:L

#48842 removing inconsistencies in micro_speech_test.cc
  tensorflow/lite/micro/examples/micro_speech/micro_speech_test.cc
Labels: cla: yes, comp:micro, ready to pull, size:XS

#48859 [Intel MKL] Einsum threadpool fix
  tensorflow/core/kernels/mkl/mkl_einsum_op.cc
Labels: cla: yes, comp:mkl, ready to pull, size:XS

#48891 [Cherry-pick:r2.5]Add -lrt to tf_cc_test linkopts on Linux platforms
  tensorflow/tensorflow.bzl
Labels: cla: yes

#48776 [cherry-pick r2.5] Fix 'Illegal ambiguous match' on Windows with `--config=nogcp/noaws`.
  tensorflow/core/platform/default/build_config.bzl
Labels: cla: yes, size:XS

#48626 Change "Simple Audio Recognition" to right link
  tensorflow/lite/micro/examples/micro_speech/train/README.md
Labels: cla: yes, comp:micro, ready to pull, size:XS, type:docs-bug

#48522 Disable AWS and HDFS support by default
  .bazelrc
  configure.py
  tensorflow/core/platform/default/build_config.bzl
  tensorflow/tools/lib_package/BUILD
  tensorflow/tools/pip_package/BUILD
Labels: awaiting review, cla: yes, comp:cloud, ready to pull, size:XS

#48887 [cherry-pick r2.5] Fix the backward RNN layer with ragged inputs.
  tensorflow/python/keras/backend.py
  tensorflow/python/keras/layers/recurrent.py
  tensorflow/python/keras/layers/recurrent_test.py
  tensorflow/python/keras/layers/recurrent_v2.py
Labels: cla: yes, size:M

#48591 Add "contribution welcome" in Bug template
  .github/ISSUE_TEMPLATE/00-bug-issue.md
Labels: cla: yes, ready to pull, size:XS

#48900 [Cherry-Pick:2.5]Fix fetching of handle data in ResourceGather's gradient
  tensorflow/python/keras/integration_test/gradients_test.py
  tensorflow/python/ops/embedding_ops_test.py
  tensorflow/python/ops/resource_variable_ops.py
Labels: cla: yes

#48899 [Cherry-Pick:2.5]disable irrelevant logging info for external users
  tensorflow/python/compat/compat_test.py
  tensorflow/python/framework/ops.py
  tensorflow/python/framework/tensor_shape.py
  tensorflow/python/ops/control_flow_v2_toggles.py
  tensorflow/python/ops/variable_scope.py
Labels: cla: yes

#48750 _init_profile_batch docstring specifies wrong return
  tensorflow/python/keras/callbacks.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#48904 Update version numbers for TensorFlow 2.5.0-rc3
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#48798 Cadence HiFi 5 NN Library v1.5.0 integration
  tensorflow/lite/micro/kernels/xtensa/conv.cc
  tensorflow/lite/micro/kernels/xtensa/depthwise_conv.cc
  tensorflow/lite/micro/kernels/xtensa/softmax.cc
  tensorflow/lite/micro/tools/make/ext_libs/xtensa.inc
  tensorflow/lite/micro/tools/make/ext_libs/xtensa_depthwise_patch_hifi5.patch
  tensorflow/lite/micro/tools/make/ext_libs/xtensa_download.sh
Labels: cla: yes, comp:micro, ready to pull, size:M

#48667 [mlir-hlo] Added RegionBranchOpInterfaces to lmhlo operations.
  tensorflow/compiler/mlir/hlo/BUILD
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/lhlo_ops.h
  tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/lhlo_ops.td
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/IR/lhlo_ops.cc
Labels: cla: yes, ready to pull, size:M

#48854 add go_package to proto definition files
  tensorflow/core/framework/dataset_options.proto
  tensorflow/core/framework/model.proto
  tensorflow/core/protobuf/extension_type_variant.proto
  tensorflow/core/protobuf/service_config.proto
  tensorflow/core/protobuf/snapshot.proto
Labels: cla: yes, comp:core, ready to pull, size:S

#47974 Add GPU implem of sparse segment reduction ops
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/gpu_prim_helpers.h
  tensorflow/core/kernels/gpu_prim_helpers_test.cu.cc
  tensorflow/core/kernels/segment_reduction_ops.h
  tensorflow/core/kernels/segment_reduction_ops_gpu.cu.cc
  tensorflow/core/kernels/segment_reduction_ops_impl.h
  tensorflow/core/kernels/segment_reduction_ops_impl_1.cc
  tensorflow/core/kernels/segment_reduction_ops_impl_5.cc
  tensorflow/core/util/gpu_device_functions.h
  tensorflow/core/util/gpu_kernel_helper.h
  tensorflow/python/kernel_tests/segment_reduction_ops_test.py
Labels: cla: yes, comp:core, ready to pull, size:L

#48831 [tf.data] graduate RandomDataset from experimental to tf.data.Dataset.random
  RELEASE.md
  tensorflow/python/data/experimental/kernel_tests/BUILD
  tensorflow/python/data/experimental/ops/BUILD
  tensorflow/python/data/experimental/ops/random_ops.py
  tensorflow/python/data/kernel_tests/BUILD
  tensorflow/python/data/kernel_tests/random_dataset_test.py
  tensorflow/python/data/ops/dataset_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.data.-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-fixed-length-record-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-t-f-record-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.-text-line-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-csv-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-random-dataset.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.data.experimental.-sql-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-fixed-length-record-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-t-f-record-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.-text-line-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-csv-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-random-dataset.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.data.experimental.-sql-dataset.pbtxt
Labels: cla: yes, comp:data, ready to pull, size:M

#48517 Enable broadcast send from non-collective group leader
  tensorflow/core/distributed_runtime/collective_param_resolver_distributed.cc
  tensorflow/core/distributed_runtime/collective_param_resolver_distributed_test.cc
Labels: cla: yes, comp:core, ready to pull, size:XS

#48893 Fix an issue when fusing BatchNorm in backprop
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/grappler/optimizers/remapper_test.cc
Labels: cla: yes, ready to pull, size:S

#48911 Improve docstrings for strings.lower() and strings.upper()
  tensorflow/core/api_def/base_api/api_def_StringLower.pbtxt
  tensorflow/core/api_def/base_api/api_def_StringUpper.pbtxt
Labels: cla: yes, comp:core, ready to pull, size:S

#48920 [CherryPick:r2.5]Run TensorFlow configure script in gpu_pip_on_cpu.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_pip_on_cpu.sh
Labels: cla: yes

#48921 Temporarily delete TOSA concat legalizations for v0.22 spec update
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: cla: yes, ready to pull, size:L

#48969 [CherryPick:2.5]Fix an invalid address vulnerability in `tf.raw_ops.RaggedBincount`.
  tensorflow/core/kernels/bincount_op.cc
Labels: cla: yes

#48970 [Cherrypick:2.5]Fix `tf.raw_ops.ResourceCountUpTo` null pointer dereference.
  tensorflow/python/lib/core/ndarray_tensor.cc
Labels: cla: yes

#48974 [Cheerypick 2.5]Handle a special grappler case resulting in crash.
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
  tensorflow/core/grappler/optimizers/dependency_optimizer.cc
Labels: cla: yes

#48975 [cherrypick 2.5]Fix `tf.raw_ops.RaggedTensorToVariant` invalid resize.
  tensorflow/core/kernels/ragged_tensor_to_variant_op.cc
Labels: cla: yes

#48976 [CherryPick 2.5]Fix 2 issues with `Conv3D`.
  tensorflow/core/kernels/conv_ops_3d.cc
Labels: cla: yes

#48980 [CherryPick 2.5]Fix `tf.raw_ops.RaggedTensorToTensor` failing CHECK in `tensor.cc`.
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes

#48981 [Cherrypick 2.5]Fix `tf.raw_ops.SparseCross` failing CHECK.
  tensorflow/core/kernels/sparse_cross_op.cc
Labels: cla: yes

#48982 [CherryPick 2.5]Fix the segfault in `tf.raw_ops.SparseCountSparseOutput`.
  tensorflow/core/kernels/count_ops.cc
Labels: cla: yes

#48983 [CherryPick 2.5]Validate some shape requirements for `Conv3DBackpropFilter*` and `Conv3DBackpropInput*` ops.
  tensorflow/core/kernels/conv_grad_ops_3d.cc
Labels: cla: yes

#48986 [CherryPick2.5]Prevent another division by zero.
  tensorflow/core/kernels/conv_grad_shape_utils.cc
Labels: cla: yes

#48988 [CherryPick:2.5]Prevent yet another division by zero
  tensorflow/core/kernels/conv_grad_input_ops.h
Labels: cla: yes

#48991 [cherrypick:2.5]Fix one division by zero
  tensorflow/core/kernels/quantized_mul_op.cc
Labels: cla: yes

#48992 [CherryPick:2.5]Remove `OP_REQUIRES` call from helper function.
  tensorflow/core/kernels/sparse/sparse_cholesky_op.cc
Labels: cla: yes

#48994 [CHerryPick:2.5]Fix null CHECK issue with `tf.raw_ops.EncodePng`.
  tensorflow/core/kernels/image/encode_png_op.cc
Labels: cla: yes

#48993 [CherryPick:2.5]Fix heap buffer overflow caused by rounding.
  tensorflow/core/kernels/quantized_resize_bilinear_op.cc
Labels: cla: yes

#48998 Fix overflow CHECK issue with `tf.raw_ops.AddManySparseToTensorsMap`.
  tensorflow/core/kernels/sparse_concat_op.cc
Labels: cla: yes

#48996 Fix overflow CHECK issue with `tf.raw_ops.DrawBoundingBoxes`.
  tensorflow/core/kernels/image/draw_bounding_box_op.cc
Labels: cla: yes

#48995 [CherryPick 2.5]Fix out of bounds read in `ragged_cross_op.cc`.
  tensorflow/core/kernels/ragged_cross_op.cc
Labels: cla: yes

#48997 Validate inputs to `QuantizedMul`
  tensorflow/core/kernels/quantized_mul_op.cc
Labels: cla: yes

#48984 [CherryPick2.5] Eliminate a division by 0 in 3D convolutions
  tensorflow/core/kernels/conv_grad_ops_3d.cc
Labels: cla: yes

#49003 [CherryPick:2.5]Validate arguments to `QuantizedReshape`.
  tensorflow/core/kernels/quantized_reshape_op.cc
Labels: cla: yes

#49005 [CherryPick:2.5]Enhance validation of ngram op and handle case of 0 tokens.
  tensorflow/core/kernels/string_ngrams_op.cc
  tensorflow/core/kernels/string_ngrams_op_test.cc
Labels: cla: yes

#49006 [CherryPick:2.5]Fix `tf.raw_ops.QuantizeAndDequantizeV4Grad` CHECK failure.
  tensorflow/core/kernels/quantize_and_dequantize_op.cc
Labels: cla: yes

#49002 [CherryPick:2.5]Validate min and max arguments to `QuantizedResizeBilinear`.
  tensorflow/core/kernels/quantized_resize_bilinear_op.cc
Labels: cla: yes

#48948 Removing some nonsense in AddNodeWithParameters
  tensorflow/lite/core/subgraph.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#48978 [CherryPick 2.5]Fix `tf.raw_ops.RaggedTensorToTensor` failing CHECK.
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes, comp:core, size:S

#48990 [CherryPick:2.5]Fix one FPE and remove two CHECK-fails.
  tensorflow/core/kernels/quantized_conv_ops.cc
Labels: cla: yes, comp:core, size:S

#49004 [CherryPick:2.5]Fix issues in Conv2DBackpropFilter.
  tensorflow/core/kernels/conv_grad_filter_ops.cc
Labels: cla: yes, comp:core, size:S

#48909 [XLA/GPU] Improve h-loop-fusion by changing its traversal order.
  tensorflow/compiler/xla/service/gpu/horizontal_loop_fusion.cc
  tensorflow/compiler/xla/service/gpu/horizontal_loop_fusion_test.cc
Labels: cla: yes, comp:xla, ready to pull, size:M

#49031 Fix `tf.raw_ops.CTCGreedyDecoder` CHECK failure.
  tensorflow/core/kernels/ctc_decoder_ops.cc
Labels: cla: yes, comp:core, size:XS

#49032 Fix crash in `SparseTensorToCSRSparseMatrixCPUFunctor`
  tensorflow/core/kernels/sparse/kernels.cc
Labels: cla: yes, comp:core, size:XS

#49033 Prevent division by 0 in `QuantizedBiasAdd`.
  tensorflow/core/kernels/quantized_bias_add_op.cc
Labels: cla: yes, comp:core, size:XS

#49034 Add missing validation in `QuantizedBatchNormWithGlobalNormalization`
  tensorflow/core/kernels/quantized_batch_norm_op.cc
Labels: cla: yes, comp:core, size:M

#49036 Fix divide by zero error in `fractional_pool_common.cc`.
  tensorflow/core/kernels/fractional_avg_pool_op.cc
Labels: cla: yes, comp:core, size:XS

#49039 [CherryPick 2.5] TF Security
  tensorflow/core/kernels/edit_distance_op.cc
  tensorflow/core/kernels/fft_ops.cc
  tensorflow/core/kernels/linalg/banded_triangular_solve_op.cc
  tensorflow/core/kernels/load_and_remap_matrix_op.cc
Labels: cla: yes, comp:core, size:M

#49037 Validate (and ensure validation sticks) inputs for `MatrixTriangularSolve`.
  tensorflow/core/kernels/linalg/matrix_triangular_solve_op_impl.h
Labels: cla: yes, comp:core, size:S

#41595 Fix binary crossentropy double epsilon
  tensorflow/python/keras/backend.py
  tensorflow/python/keras/losses.py
  tensorflow/python/keras/losses_test.py
  tensorflow/python/keras/metrics_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#49054 Fix heap buffer overflow
  tensorflow/core/kernels/maxpooling_op.cc
Labels: cla: yes

#49056 Add several missing validations in SDCA
  tensorflow/core/kernels/sdca_internal.cc
Labels: cla: yes

#49058 Don't do any work if output tensor is null (prevent div by 0)
  tensorflow/core/kernels/maxpooling_op.cc
Labels: cla: yes

#49051 Fix breakage in parameterized_truncated_normal_op.cc
  tensorflow/core/kernels/parameterized_truncated_normal_op.cc
Labels: cla: yes

#49062 Fix OOB read issue with `tf.raw_ops.CTCLoss`.
  tensorflow/core/kernels/ctc_loss_op.cc
Labels: cla: yes

#49063 Fix assertion failure in pooling_ops_3d
  tensorflow/core/kernels/pooling_ops_3d.cc
Labels: cla: yes

#49066 Fix SEGV in CTC ops
  tensorflow/core/kernels/ctc_decoder_ops.cc
Labels: cla: yes

#49067 Prevent heap OOB error in `MaxPoolGrad`
  tensorflow/core/kernels/maxpooling_op.cc
Labels: cla: yes

#49069 Prevent overflow in sparse op
  tensorflow/core/kernels/sparse_split_op.cc
Labels: cla: yes

#49096 Fix FPE issue with `tf.raw_ops.DenseCountSparseOutput`.
  tensorflow/core/kernels/count_ops.cc
Labels: cla: yes

#49073 Prevent one more div by 0 in TFLite
  tensorflow/lite/kernels/space_to_depth.cc
Labels: cla: yes

#49071 Fix division by zero in TFLite padding.
  tensorflow/lite/kernels/padding.h
Labels: cla: yes

#49072 Prevent another div by 0 in optimized pooling implementations TFLite
  tensorflow/lite/kernels/pooling.cc
  tensorflow/lite/kernels/pooling_test.cc
Labels: cla: yes

#49074 Handle one more division by 0 in TFLite.
  tensorflow/lite/kernels/gather_nd.cc
Labels: cla: yes

#49078 [CherryPick2.5]TFLite infinite loop and segfault
  tensorflow/lite/BUILD
  tensorflow/lite/core/subgraph.cc
  tensorflow/lite/core/subgraph.h
  tensorflow/lite/model_test.cc
  tensorflow/lite/testdata/unsupported_recursion.bin
Labels: cla: yes

#49080 Prevent division by 0.
  tensorflow/lite/kernels/conv.cc
Labels: cla: yes

#49070 Add missing valuidation to FusedBatchNorm.
  tensorflow/core/kernels/fused_batch_norm_op.cc
Labels: cla: yes

#49081 Prevent division by 0
  tensorflow/lite/kernels/embedding_lookup.cc
Labels: cla: yes

#49082 Prevent division by 0
  tensorflow/lite/kernels/batch_to_space_nd.cc
Labels: cla: yes

#49083 Prevent division by 0
  tensorflow/lite/kernels/space_to_batch_nd.cc
Labels: cla: yes

#49084 Prevent division by 0
  tensorflow/lite/kernels/svdf.cc
Labels: cla: yes

#49085 Prevent division by 0
  tensorflow/lite/kernels/split.cc
Labels: cla: yes

#49087 Prevent divisions by 0
  tensorflow/lite/kernels/depthwise_conv.cc
Labels: cla: yes

#49089 Fix integer overflow in TFLite concat
  tensorflow/lite/kernels/concatenation.cc
Labels: cla: yes

#49090 Fix a dangerous integer overflow and a malloc of negative size.
  tensorflow/lite/c/common.c
  tensorflow/lite/kernels/embedding_lookup_sparse.cc
Labels: cla: yes

#49093 Prevent memory overflow in ParseAttrValue from nested tensors.
  tensorflow/core/framework/attr_value_util.cc
Labels: cla: yes

#49097 [CherryPick 2.5] Fix crash with tf.transpose when a is complex and conjugate is True
  tensorflow/core/kernels/transpose_functor.h
  tensorflow/python/kernel_tests/transpose_op_test.py
Labels: cla: yes

#49060 [CherryPick 2.5] Add missing validation to pooling_ops_3d and prevent heap OOB
  tensorflow/core/kernels/pooling_ops_3d.cc
Labels: cla: yes, comp:core, size:S

#49114 Remove unused MicroInterpreter::tensor() API.
  tensorflow/lite/micro/micro_interpreter.cc
  tensorflow/lite/micro/micro_interpreter.h
  tensorflow/lite/micro/micro_interpreter_test.cc
Labels: cla: yes, ready to pull, size:M

#48971 Update legalizations for TOSA v0.22 Part 2
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
  tensorflow/compiler/mlir/tosa/transforms/tfl_legalize_patterns.td
Labels: cla: yes, ready to pull, size:XL

#49118 Fix heap OOB / undefined behavior in `RaggedTensorToTensor`
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes

#49128 Validate that a and b are proper sparse tensors
  tensorflow/core/kernels/sparse_sparse_binary_op_shared.cc
Labels: cla: yes

#49126 Ensure validation sticks in banded_triangular_solve_op
  tensorflow/core/kernels/linalg/banded_triangular_solve_op.cc
Labels: cla: yes

#49116 Update version numbers for TensorFlow 2.5.0
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#49124 [tf.data][cherrypick] Fix snapshot segfault when using repeat and pre…
  tensorflow/core/kernels/data/experimental/snapshot_dataset_op.cc
  tensorflow/python/data/experimental/kernel_tests/snapshot_test.py
Labels: cla: yes

#42574 [Grappler] Improve HoistCWiseUnaryChainsStage to support Reshape
  tensorflow/core/grappler/optimizers/arithmetic_optimizer.cc
  tensorflow/core/grappler/optimizers/arithmetic_optimizer_test.cc
Labels: cla: yes, comp:grappler, ready to pull, size:L

#49094 Remove TOSA identityn operator usage in legalizations
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: cla: yes, ready to pull, size:M

#48414 TF-TRT implement Range and RangeOptimal optimization profile strategies
  tensorflow/compiler/tf2tensorrt/utils/trt_shape_optimization_profiles.cc
  tensorflow/compiler/tf2tensorrt/utils/trt_shape_optimization_profiles.h
  tensorflow/compiler/tf2tensorrt/utils/trt_shape_optimization_profiles_test.cc
Labels: cla: yes, comp:gpu:tensorrt, ready to pull, size:M

#49023 Remove pcre library from Bazel file as it is not used anymore
  tensorflow/opensource_only.files
  tensorflow/workspace2.bzl
  third_party/pcre.BUILD
  third_party/systemlibs/pcre.BUILD
  third_party/systemlibs/syslibs_configure.bzl
Labels: cla: yes, ready to pull, size:M

#36364 embedding_lookup_sparse divide by zero fixed
  tensorflow/python/kernel_tests/embedding_ops_test.py
  tensorflow/python/ops/embedding_ops.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:XS

#48610 Check if all dimensions in output are non-zero
  tensorflow/python/keras/layers/convolutional.py
  tensorflow/python/keras/layers/convolutional_test.py
  tensorflow/python/keras/layers/local.py
  tensorflow/python/keras/layers/local_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#49008 fix numpy 1.20
  tensorflow/lite/micro/examples/magic_wand/train/requirements.txt
  tensorflow/lite/tools/pip_package/setup_with_binary.py
  tensorflow/python/ops/array_ops.py
  tensorflow/tools/ci_build/install/install_centos_pip_packages.sh
  tensorflow/tools/ci_build/install/install_pip_packages.sh
  tensorflow/tools/ci_build/install/install_pip_packages_by_version.sh
  tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh
  tensorflow/tools/ci_build/release/common.sh
  tensorflow/tools/ci_build/release/common_win.bat
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:XS

#48546 Fix GPU delegate flatbuffer target when built from external projects.
  tensorflow/lite/delegates/gpu/cl/BUILD
  tensorflow/tensorflow.bzl
Labels: cla: yes, comp:lite, ready to pull, size:S

#49024 Update LMDB to 0.9.29
  tensorflow/workspace2.bzl
Labels: cla: yes, ready to pull, size:XS

#49143 Facilitate building on Windows
  tensorflow/lite/micro/tools/make/arm_gcc_download.sh
  tensorflow/lite/micro/tools/make/flatbuffers_download.sh
  tensorflow/lite/micro/tools/make/targets/cortex_m_corstone_300_makefile.inc
  tensorflow/lite/micro/tools/make/targets/cortex_m_generic_makefile.inc
Labels: cla: yes, comp:micro, comp:micro:arm, kokoro:force-run, ready to pull, size:M

#48962 Mixed precision Mask in GlobalAveragePooling1D
  tensorflow/python/keras/layers/pooling.py
  tensorflow/python/keras/layers/pooling_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#49049 Made error message in keras.backend.bias_add match the check
  tensorflow/python/keras/backend.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#39324 Add blank_index parameter for ctc_greedy_decoder
  tensorflow/core/kernels/ctc_decoder_ops.cc
  tensorflow/core/ops/ctc_ops.cc
  tensorflow/python/kernel_tests/ctc_decoder_ops_test.py
  tensorflow/python/kernel_tests/ctc_loss_op_test.py
  tensorflow/python/ops/ctc_ops.py
  tensorflow/tools/api/golden/v1/tensorflow.nn.pbtxt
  tensorflow/tools/api/golden/v1/tensorflow.raw_ops.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.nn.pbtxt
  tensorflow/tools/api/golden/v2/tensorflow.raw_ops.pbtxt
Labels: cla: yes, ready to pull, size:M

#49025 Update libjpeg-turbo from 2.0.5 to 2.1.0
  third_party/jpeg/BUILD.bazel
  third_party/jpeg/workspace.bzl
Labels: cla: yes, ready to pull, size:XS

#49152 [Intel MKL] Parallelize UnsortedSegmentSum on CPU deivce
  tensorflow/core/kernels/segment_reduction_ops_impl.h
  tensorflow/core/kernels/segment_reduction_ops_test.cc
  tensorflow/python/kernel_tests/segment_reduction_ops_test.py
Labels: cla: yes, comp:core, ready to pull, size:M

#48905 [determinism] Add GPU excepts, CPU d9m, and tests to crop_and_resize
  tensorflow/core/kernels/image/crop_and_resize_op.cc
  tensorflow/core/util/BUILD
  tensorflow/core/util/determinism.cc
  tensorflow/core/util/determinism.h
  tensorflow/python/BUILD
  tensorflow/python/kernel_tests/sparse_xent_op_deterministic_test.py
  tensorflow/python/kernel_tests/xent_op_deterministic_test.py
  tensorflow/python/ops/image_grad_deterministic_test.py
  tensorflow/python/ops/image_grad_test_base.py
Labels: cla: yes, comp:core, ready to pull, size:L

#48654 Fix keras.layers.ReLU docs #48646
  tensorflow/python/keras/layers/advanced_activations.py
  tensorflow/python/keras/layers/advanced_activations_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:XS

#48956 Fix dtype of "global_batch_size"
  tensorflow/python/ops/nn_impl.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#48090 Update release notes for TensorFlow 2.5.0
  RELEASE.md
Labels: cla: yes, size:XS

#49174 Update Estimator version after estimator final release
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, size:XS

#49170 Include limits to prevent CI failure for tflite-micro.
  tensorflow/lite/micro/micro_utils.h
Labels: cla: yes, comp:micro, ready to pull, size:XS

#49197 Update python package description to include python 3.9
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#49218 Fixed Accuracy to be able to transform dynamically
  tensorflow/python/keras/engine/compile_utils.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#49166 Resolves coredump caused by `tf.data.experimental.save` with prefetch
  tensorflow/core/kernels/data/experimental/io_ops.cc
  tensorflow/python/data/experimental/kernel_tests/io_test.py
Labels: cla: yes, comp:core, ready to pull, size:S

#49226 [nnapi delegate] fix a trivial redundant comment and a typo
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
Labels: cla: yes, comp:lite, ready to pull, size:XS

#48595 micro: Printed memory plan layout changes
  tensorflow/lite/micro/memory_planner/BUILD
  tensorflow/lite/micro/memory_planner/greedy_memory_planner.cc
  tensorflow/lite/micro/memory_planner/greedy_memory_planner.h
  tensorflow/lite/micro/memory_planner/greedy_memory_planner_test.cc
  tensorflow/lite/micro/micro_allocator.cc
  tensorflow/lite/micro/micro_string.cc
  tensorflow/lite/micro/micro_string_test.cc
Labels: cla: yes, comp:micro, ready to pull, size:S

#37014 Modified reduce_variance for extra optimization
  tensorflow/python/ops/ragged/ragged_dispatch.py
  tensorflow/python/ops/ragged/ragged_dispatch_test.py
  tensorflow/python/ops/ragged/ragged_math_ops.py
  tensorflow/python/ops/ragged/ragged_reduce_op_test.py
Labels: cla: yes, comp:ops, prtype:bugfix, ready to pull, size:S

#49018 Adding example for uniform_row_length in RaggedTensor
  tensorflow/python/ops/ragged/ragged_tensor.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#48782 [Pluggable Device] Fix the MacOS regression for registering Pluggable…
  tensorflow/core/common_runtime/pluggable_device/BUILD
Labels: cla: yes, ready to pull, size:S

#49270 Cherry-pick: Add .zenodo.json for clean automated DOI numbers.
  .zenodo.json
Labels: cla: yes

#49271 Cherry-pick: Add .zenodo.json for clean automated DOI numbers.
  .zenodo.json
Labels: cla: yes

#49272 Cherry-pick: Add .zenodo.json for clean automated DOI numbers.
  .zenodo.json
Labels: cla: yes

#49273 Cherry-pick: Add .zenodo.json for clean automated DOI numbers.
  .zenodo.json
Labels: cla: yes

#49274 Cherry-pick: Add .zenodo.json for clean automated DOI numbers.
  .zenodo.json
Labels: cla: yes

#49280 Fix an invalid address vulnerability in `tf.raw_ops.RaggedBincount`.
  tensorflow/core/kernels/bincount_op.cc
Labels: cla: yes, comp:core, size:XS

#49281 Fix an invalid address vulnerability in `tf.raw_ops.RaggedBincount`.
  tensorflow/core/kernels/bincount_op.cc
Labels: cla: yes, comp:core, size:XS

#49282 Allowlist certain data types to avoid a seg fault.
  tensorflow/core/kernels/immutable_constant_op.cc
Labels: cla: yes, comp:core, size:XS

#49283 Allowlist certain data types to avoid a seg fault.
  tensorflow/core/kernels/immutable_constant_op.cc
Labels: cla: yes, comp:core, size:XS

#49284 Allowlist certain data types to avoid a seg fault.
  tensorflow/core/kernels/immutable_constant_op.cc
Labels: cla: yes, comp:core, size:XS

#49285 Allowlist certain data types to avoid a seg fault.
  tensorflow/core/kernels/immutable_constant_op.cc
Labels: cla: yes, comp:core, size:XS

#49287 CherryPick:2.1:PR #46974: Fix crash of tf.strings.substr when pos and len have different shapes
  tensorflow/core/kernels/substr_op.cc
  tensorflow/python/kernel_tests/substr_op_test.py
Labels: cla: yes, comp:core, size:S

#49288 CherryPick:2.2:PR #46974: Fix crash of tf.strings.substr when pos and len have different shapes
  tensorflow/core/kernels/substr_op.cc
  tensorflow/python/kernel_tests/substr_op_test.py
Labels: cla: yes, comp:core, size:S

#49289 CherryPick:2.3:PR #46974: Fix crash of tf.strings.substr when pos and len have different shapes
  tensorflow/core/kernels/substr_op.cc
  tensorflow/python/kernel_tests/substr_op_test.py
Labels: cla: yes, comp:core, size:S

#49121 <release 2.4>-<rc2> cherry-pick request: [tf.data] Fix snapshot segfault when using repeat and prefetch.
  tensorflow/core/kernels/data/experimental/snapshot_dataset_op.cc
  tensorflow/python/data/experimental/kernel_tests/snapshot_test.py
Labels: cla: yes, prtype:bugfix

#48806 [XLA/GPU] Add CustomCallSchedule to give schedule hints to custom-calls.
  tensorflow/compiler/mlir/xla/ir/mlir_hlo_builder.cc
  tensorflow/compiler/mlir/xla/ir/mlir_hlo_builder.h
  tensorflow/compiler/xla/client/xla_builder.cc
  tensorflow/compiler/xla/client/xla_builder.h
  tensorflow/compiler/xla/service/gpu/gpu_hlo_schedule.cc
  tensorflow/compiler/xla/service/gpu/gpu_hlo_schedule_test.cc
  tensorflow/compiler/xla/service/hlo.proto
  tensorflow/compiler/xla/service/hlo_instruction.cc
  tensorflow/compiler/xla/service/hlo_instruction.h
  tensorflow/compiler/xla/service/hlo_instructions.cc
  tensorflow/compiler/xla/service/hlo_instructions.h
  tensorflow/compiler/xla/service/hlo_memory_scheduler.cc
  tensorflow/compiler/xla/service/hlo_memory_scheduler.h
  tensorflow/compiler/xla/service/hlo_parser.cc
  tensorflow/compiler/xla/service/hlo_parser_test.cc
Labels: cla: yes, ready to pull, size:L

#48716 Fix invalid string formatting in merge.py
  tensorflow/python/keras/layers/merge.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#49192 Update the reference of FTRL optimizer
  tensorflow/python/keras/optimizer_v2/ftrl.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#49200 VLOG() to Text File
  tensorflow/core/platform/default/logging.cc
Labels: cla: yes, comp:core, ready to pull, size:S

#48475 Fixed unlinking the shared memory region on non-Android platform
  tensorflow/lite/delegates/nnapi/nnapi_delegate.cc
  tensorflow/lite/delegates/nnapi/nnapi_delegate_kernel.h
  tensorflow/lite/nnapi/nnapi_implementation.cc
Labels: TFLiteNNAPIDelegate, cla: yes, comp:lite, ready to pull, size:S

#49340 Fix `tf.raw_ops.RaggedTensorToTensor` failing CHECK.
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes, comp:core, size:S

#49341 Fix `tf.raw_ops.RaggedTensorToTensor` failing CHECK in `tensor.cc`.
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes, comp:core, size:XS

#49342 Fix `tf.raw_ops.RaggedTensorToTensor` failing CHECK in `tensor.cc`.
  tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc
Labels: cla: yes, comp:core, size:XS
