Repository tensorflow/tensorflow, pull requests merged in 2021-04, with the labels that each got.

#48208 Fix kernel_l2_pool_2d_test for the Xtensa target
  tensorflow/lite/micro/kernels/l2_pool_2d_test.cc
Labels: cla: yes, comp:micro, ready to pull, size:XS

#47650 [ROCm] AMP selection process for AMD GPUs
  tensorflow/core/grappler/optimizers/auto_mixed_precision.cc
  tensorflow/core/grappler/optimizers/auto_mixed_precision_test.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#48222 Fix GCS filesystem
  tensorflow/core/platform/env.h
Labels: cla: yes

#48065 [ClusterSpec] Allow sparse representation of TF_CONFIG.
  tensorflow/python/distribute/cluster_resolver/tfconfig_cluster_resolver_test.py
  tensorflow/python/training/server_lib.py
  tensorflow/python/training/server_lib_test.py
Labels: cla: yes, ready to pull, size:S

#47754 Support tflite kernel unittest in cmake.
  tensorflow/lite/CMakeLists.txt
  tensorflow/lite/kernels/CMakeLists.txt
  tensorflow/lite/kernels/activations_test.cc
  tensorflow/lite/kernels/quantize_test.cc
  tensorflow/lite/tools/cmake/modules/Findgoogletest.cmake
  tensorflow/lite/tools/cmake/modules/Findnsync.cmake
  tensorflow/lite/tools/cmake/modules/Findre2.cmake
  tensorflow/lite/tools/cmake/modules/flatbuffers.cmake
Labels: cla: yes, comp:lite, ready to pull, size:L

#48161 Add a reference to the API review practices
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:XS

#48184 Minor improvement to documentation
  tensorflow/lite/micro/docs/memory_management.md
  tensorflow/lite/micro/docs/rfc/preallocated_tensors.md
  tensorflow/lite/micro/kernels/cmsis_nn/README.md
  tensorflow/lite/micro/kernels/ethos_u/README.md
  tensorflow/lite/micro/micro_allocator.cc
Labels: cla: yes, comp:micro, comp:micro:arm, ready to pull, size:M

#47491 [ROCm] Updates to account for the removal of $ROCM_PATH/include/hiprand,rocrand dirs
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, comp:gpu, ready to pull, size:S

#48241 Fix for #48155
  tensorflow/lite/micro/tools/make/bash_helpers.sh
  tensorflow/lite/micro/tools/make/flatbuffers_download.sh
Labels: cla: yes, comp:micro, ready to pull, size:S

#48253 fix the TFLM github CI.
  tensorflow/lite/micro/tools/ci_build/test_all.sh
Labels: cla: yes, comp:micro, ready to pull, size:XS

#48284 Update Estimator Version to 2.5.0-rc0
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#47092 RaggedTensor support for sparse_categorical_crossentropy.
  tensorflow/python/keras/losses.py
  tensorflow/python/keras/losses_test.py
Labels: cla: yes, comp:keras, ready to pull, size:M

#47922 Fix Keras Callbacks logs / numpy_logs sync
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/callbacks_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:M

#48250 Update convolutional.py
  tensorflow/python/keras/layers/convolutional.py
Labels: cla: yes, ready to pull, size:XS

#48248 [INTEL MKL] update oneDNN version in TensorFlow to v2.2 official release
  tensorflow/workspace2.bzl
Labels: cla: yes, kokoro:force-run, ready to pull, size:XS

#48303 Fixes a bug in example code
  tensorflow/lite/g3doc/performance/post_training_quantization.md
Labels: cla: yes, comp:lite, ready to pull, size:XS

#47499 [Grappler] Add dataset.shard(1, 0) to noop_elimination pass
  tensorflow/core/grappler/optimizers/data/noop_elimination.cc
  tensorflow/core/grappler/optimizers/data/noop_elimination_test.cc
  tensorflow/python/data/experimental/kernel_tests/optimization/noop_elimination_test.py
Labels: cla: yes, ready to pull, size:M

#48218 Remove unneeded `file_io.file_exists` checks
  tensorflow/core/platform/cloud/gcs_file_system.cc
  tensorflow/python/framework/graph_io.py
  tensorflow/python/keras/saving/saved_model_experimental.py
  tensorflow/python/profiler/profile_context.py
  tensorflow/python/saved_model/utils_impl.py
  tensorflow/python/summary/writer/event_file_writer.py
  tensorflow/python/summary/writer/event_file_writer_v2.py
Labels: cla: yes, ready to pull, size:S

#48286 [INTEL MKL] Enable back MKL auto_mixed_precision
  tensorflow/core/grappler/optimizers/auto_mixed_precision.cc
  tensorflow/core/grappler/optimizers/auto_mixed_precision_test.cc
  tensorflow/core/grappler/optimizers/meta_optimizer.cc
Labels: cla: yes, comp:grappler, ready to pull, size:S

#48249 [INTEL MKL] Setting default value for KMP_BLOCKTIME
  tensorflow/core/common_runtime/BUILD
  tensorflow/core/common_runtime/threadpool_device.cc
  third_party/llvm_openmp/BUILD
  third_party/mkl/BUILD
Labels: cla: yes, comp:mkl, ready to pull, size:M

#48115 Re-enable the 5d fused batch norm
  tensorflow/python/keras/layers/normalization.py
  tensorflow/python/keras/layers/normalization_test.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#48247 [Intel MKL] added threadpool config and changed dnnl run to use the blockformat.
  tensorflow/tools/ci_build/linux/cpu/run_mkl.sh
Labels: cla: yes, ready to pull, size:S

#48291 Enable do_pylint only and --incremental
  tensorflow/tools/ci_build/ci_sanity.sh
Labels: cla: yes, ready to pull, size:S

#47108 micro: port operator FLOOR_MOD kernel from lite with test
  tensorflow/lite/kernels/internal/reference/floor_mod.h
  tensorflow/lite/micro/all_ops_resolver.cc
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/floor_mod.cc
  tensorflow/lite/micro/kernels/floor_mod_test.cc
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:L

#46973 Fix crash with tf.transpose when a is complex and conjugate is True
  tensorflow/core/kernels/transpose_functor.h
  tensorflow/python/kernel_tests/transpose_op_test.py
Labels: cla: yes, kokoro:force-run, prtype:bugfix, ready to pull, size:S

#48330 Fix faulty link to numpy docs.
  tensorflow/python/ops/numpy_ops/__init__.py
Labels: cla: yes, comp:ops, ready to pull, size:XS

#48215 Update _index.yaml
  tensorflow/compiler/mlir/g3doc/_index.yaml
  tensorflow/compiler/mlir/lite/README.md
  tensorflow/compiler/mlir/tosa/BUILD
Labels: cla: yes, ready to pull, size:XS, type:docs-bug

#47980 [ROCm] Fix for ROCM CSB breakage - 210322
  tensorflow/python/keras/distribute/BUILD
  tensorflow/python/keras/optimizer_v2/BUILD
  tensorflow/python/training/BUILD
Labels: cla: yes, comp:gpu, ready to pull, size:XS

#47788 Remove redundant arguments of ImageResizerState's API
  tensorflow/core/kernels/conv_ops_fused_image_transform.cc
  tensorflow/core/kernels/image/resize_area_op.cc
  tensorflow/core/kernels/image/resize_bicubic_op.cc
  tensorflow/core/kernels/image/resize_bilinear_op.cc
  tensorflow/core/kernels/image/resize_nearest_neighbor_op.cc
  tensorflow/core/kernels/quantized_resize_bilinear_op.cc
  tensorflow/core/util/image_resizer_state.h
Labels: cla: yes, comp:core, prtype:bugfix, ready to pull, size:M

#47300 Remove unnecessary bool conversion in basic test.
  tensorflow/python/kernel_tests/argmax_op_test.py
  tensorflow/python/kernel_tests/in_topk_op_test.py
Labels: awaiting review, cla: yes, ready to pull, size:XS

#48028 Add GPU support for sparse reorder
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/sparse_reorder_op.cc
  tensorflow/core/kernels/sparse_reorder_op.h
  tensorflow/core/kernels/sparse_reorder_op_gpu.cu.cc
  tensorflow/python/kernel_tests/sparse_reorder_op_test.py
Labels: cla: yes, comp:core, ready to pull, size:L

#47225 [XLA] Support QuantizeAndDequantizeV4
  tensorflow/compiler/jit/mark_for_compilation_pass.cc
  tensorflow/compiler/mlir/tensorflow/ir/tf_generated_ops.td
  tensorflow/compiler/mlir/xla/transforms/legalize_tf_with_tf2xla.cc
  tensorflow/compiler/tests/unary_ops_test.py
  tensorflow/compiler/tf2xla/kernels/quantize_and_dequantize_op.cc
Labels: awaiting review, cla: yes, ready to pull, size:M

#48318 Change sample to example in TextVectorization
  tensorflow/python/keras/layers/preprocessing/text_vectorization.py
Labels: cla: yes, comp:keras, ready to pull, size:S, type:docs-bug

#48351 [INTEL MKL] Curl upgrade to 7.76.0
  tensorflow/workspace2.bzl
  third_party/curl.BUILD
Labels: cla: yes, ready to pull, size:M

#47621 Fix Windows shared library build for CMake
  tensorflow/lite/CMakeLists.txt
  tensorflow/lite/c/c_api_types.h
  tensorflow/lite/delegates/gpu/common/task/weights_conversion.h
  tensorflow/lite/delegates/gpu/common/workgroup_selection.cc
  tensorflow/lite/delegates/gpu/delegate.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#47796 my changes => your changes
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:XS

#48346 [ROCm] Adding ROCm support for SparseToDense Op
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/sparse_to_dense_op.cc
  tensorflow/core/kernels/sparse_to_dense_op_gpu.cu.cc
  tensorflow/core/kernels/sparse_to_dense_op_gpu.h
Labels: cla: yes, comp:gpu, ready to pull, size:S

#46448 Add SkipLine to BufferedInputStream
  tensorflow/core/lib/io/buffered_inputstream.cc
  tensorflow/core/lib/io/buffered_inputstream.h
  tensorflow/core/lib/io/buffered_inputstream_test.cc
Labels: cla: yes, comp:core, ready to pull, size:M

#47521 Fixes Github #47520 Step number of batch_steps_per_second
  tensorflow/python/keras/callbacks.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#48385 [Graph C API] Remove GrapplerItemMap
  tensorflow/c/experimental/grappler/grappler.cc
  tensorflow/c/experimental/grappler/grappler.h
  tensorflow/c/experimental/grappler/grappler_test.cc
Labels: cla: yes, ready to pull, size:M

#48416 [r2.4] Adding missing Windows libtensorflow files.
  tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh
  tensorflow/tools/ci_build/windows/libtensorflow_gpu.sh
Labels: cla: yes

#48410 TFLiteConverter: Support QuantizeAndDequantizeV4
  tensorflow/compiler/mlir/lite/tests/legalize-tf.mlir
  tensorflow/compiler/mlir/lite/transforms/legalize_patterns.td
  tensorflow/compiler/mlir/tensorflow/ir/tf_generated_ops.td
  tensorflow/compiler/mlir/tensorflow/ir/tf_ops_n_z.cc
  tensorflow/compiler/mlir/tensorflow/tests/canonicalize.mlir
  tensorflow/compiler/mlir/tensorflow/transforms/canonicalize.td
Labels: ModelOptimizationToolkit, TFLiteConverter, cla: yes, ready to pull, size:S, type:feature

#48379 [CherryPick:r2.5] Update runtime version to 2.5.0
  tensorflow/lite/tools/versioning/runtime_version.cc
Labels: cla: yes

#48187 [ROCm] Update to use ROCm 4.1 (when building TF with --config=rocm)
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
  tensorflow/compiler/xla/tests/BUILD
  tensorflow/python/distribute/BUILD
  tensorflow/python/keras/distribute/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/distributions/BUILD
  tensorflow/python/kernel_tests/linalg/sparse/BUILD
  tensorflow/python/ops/math_ops_test.py
  tensorflow/python/ops/parallel_for/math_test.py
  tensorflow/python/ops/ragged/ragged_dispatch_test.py
  tensorflow/stream_executor/platform/default/BUILD
  tensorflow/stream_executor/platform/default/dlopen_checker.cc
  tensorflow/stream_executor/platform/default/dso_loader.cc
  tensorflow/stream_executor/platform/default/dso_loader.h
  tensorflow/stream_executor/rocm/BUILD
  tensorflow/stream_executor/rocm/rocm_fft.cc
  tensorflow/stream_executor/rocm/rocm_fft.h
  tensorflow/tools/ci_build/Dockerfile.rocm
  tensorflow/tools/ci_build/linux/rocm/run_gpu_multi.sh
  tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh
  third_party/gpus/find_rocm_config.py
  third_party/gpus/find_rocm_config.py.gz.base64
  third_party/gpus/rocm/BUILD.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, comp:gpu, ready to pull, size:L

#47896 Cleanup forward compatibility of random ops
  tensorflow/compiler/tests/stateful_random_ops_test.py
  tensorflow/python/ops/stateful_random_ops.py
  tensorflow/python/ops/stateless_random_ops.py
Labels: cla: yes, ready to pull, size:L

#48390 Update sequence.py
  tensorflow/python/keras/preprocessing/sequence.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#48398 Add extra point in ./tensorflow/examples README file
  tensorflow/examples/README.md
Labels: cla: yes, ready to pull, size:XS

#48337 Keras: Replace trivial control flow ops with tf.where
  tensorflow/python/keras/BUILD
  tensorflow/python/keras/metrics.py
  tensorflow/python/keras/optimizer_v2/BUILD
  tensorflow/python/keras/optimizer_v2/learning_rate_schedule.py
  tensorflow/python/keras/utils/metrics_utils.py
Labels: cla: yes, comp:keras, kokoro:force-run, ready to pull, size:S

#48437 Update version numbers for TensorFlow 2.5.0-rc1
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#48417 [r2.5] Adding missing Windows libtensorflow files.
  tensorflow/tools/ci_build/windows/libtensorflow_cpu.sh
  tensorflow/tools/ci_build/windows/libtensorflow_gpu.sh
Labels: cla: yes, size:M

#48387 r2.5-rc1 cherry-pick request: Upgrade curl to 7.76.0
  tensorflow/workspace2.bzl
  third_party/curl.BUILD
Labels: cla: yes

#48384 release 2.5-rc1 cherry-pick request: Fix MirroredStrategy eager performance regression
  tensorflow/python/distribute/distribute_lib.py
  tensorflow/python/distribute/mirrored_strategy.py
  tensorflow/python/keras/optimizer_v2/optimizer_v2.py
Labels: cla: yes

#48347 r2.5-rc1 cherry-pick request: [Intel MKL] Fix MKL auto-mixed precision grappler pass in --config=cuda
  tensorflow/core/grappler/optimizers/auto_mixed_precision.cc
  tensorflow/core/grappler/optimizers/auto_mixed_precision_test.cc
  tensorflow/core/grappler/optimizers/meta_optimizer.cc
Labels: cla: yes, size:S

#48345 r2.5-rc1 cherry-pick request: [Intel MKL] Update oneDNN to v2.2 official release
  tensorflow/workspace2.bzl
Labels: cla: yes, size:XS

#48341 [CherryPick:r2.5][tf.data] Apply options for a dataset before it is copied to another device in `tf.data.experimental.copy_to_device()`.
  tensorflow/python/data/experimental/kernel_tests/BUILD
  tensorflow/python/data/experimental/kernel_tests/copy_to_device_test.py
  tensorflow/python/data/experimental/ops/prefetching_ops.py
Labels: cla: yes, size:S

#48339 [CherryPick:r2.5] Rollback of rollback of [TF/XLA] Make sure that XLAControlFlowContext is injected on all paths of jit_compile=True
  tensorflow/python/eager/def_function.py
  tensorflow/python/eager/def_function_xla_jit_test.py
Labels: cla: yes

#48335 [CherryPick:r2.5] [TF/XLA] Fix the CollectiveReduceV2Op lowering by specifying the number of replicas needed at compile-time
  tensorflow/compiler/jit/xla_compilation_cache.cc
  tensorflow/python/keras/distribute/ctl_correctness_test.py
Labels: cla: yes

#48315 [r2.5 cherry-pick] Fix Keras Callbacks logs / numpy_logs sync
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/callbacks_test.py
Labels: cla: yes, comp:keras, size:M

#48283 2.5-rc1 cherry-pick request: Disable GPU SparseToDense
  tensorflow/core/kernels/sparse_to_dense_op.cc
  tensorflow/python/kernel_tests/BUILD
Labels: cla: yes, size:XS

#48182 Fix the spawning of subprocess on windows displaying a console window
  tensorflow/core/platform/windows/subprocess.cc
Labels: cla: yes, comp:core, ready to pull, size:XS

#48423 Update bot_config.yml
  .github/bot_config.yml
Labels: cla: yes, ready to pull, size:XS

#48419 [ROCm] Minor updates to the XLA / LLVM for AMDGPU backend
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#47986 Do not constant fold FloorDiv(x, 1)
  tensorflow/core/grappler/optimizers/constant_folding.cc
  tensorflow/core/grappler/optimizers/constant_folding_test.cc
Labels: cla: yes, comp:grappler, prtype:bugfix, ready to pull, size:S

#47482 micro: LOG_SOFTMAX PR2
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/reference/log_softmax.h
  tensorflow/lite/kernels/internal/reference/reference_ops.h
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:L

#48336 [ROCm] Enabling MLIR generated kernels by default on ROCm
  .bazelrc
  tensorflow/core/kernels/mlir_generated/build_defs.bzl
  tensorflow/core/kernels/mlir_generated/gpu_unary_ops_test.cc
Labels: cla: yes, comp:gpu, ready to pull, size:S

#48378 Added Reference Link to numpy.dtype
  tensorflow/python/framework/dtypes.py
Labels: cla: yes, ready to pull, size:XS

#48150 Add an example to test a single component
  CONTRIBUTING.md
Labels: cla: yes, ready to pull, size:XS

#48134 Update python package description to include python 3.9
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, ready to pull, size:XS

#48488 Fixing typo for estimator
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#48133 Update sqlite to latest sqlite-amalgamation-3350300
  tensorflow/workspace2.bzl
Labels: cla: yes, ready to pull, size:XS

#43426 Support RESIZE_BILINEAR in TFLu
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/reference/reference_ops.h
  tensorflow/lite/kernels/internal/reference/resize_bilinear.h
  tensorflow/lite/kernels/resize_bilinear.cc
  tensorflow/lite/micro/all_ops_resolver.cc
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/kernels/resize_bilinear.cc
  tensorflow/lite/micro/kernels/resize_bilinear_test.cc
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:lite, comp:micro, comp:micro:arm, kokoro:force-run, ready to pull, size:XL

#48201 Fix Roadmap description
  README.md
Labels: cla: yes, ready to pull, size:XS

#48381 [XLA] Enable vectorization of row broadcasting
  tensorflow/compiler/xla/service/gpu/ir_emission_utils.cc
  tensorflow/compiler/xla/service/gpu/ir_emission_utils.h
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.h
  tensorflow/compiler/xla/service/gpu/launch_dimensions.cc
  tensorflow/compiler/xla/service/gpu/launch_dimensions.h
  tensorflow/compiler/xla/service/gpu/parallel_loop_emitter.cc
  tensorflow/compiler/xla/service/gpu/tests/element_wise_row_vectorization.hlo
  tensorflow/compiler/xla/service/gpu/tests/elemental_ir_emitter.hlo
  tensorflow/compiler/xla/service/gpu/tests/fused_slice_different_operands.hlo
  tensorflow/compiler/xla/service/gpu/tests/fusion.hlo
  tensorflow/compiler/xla/service/llvm_ir/ir_array.cc
  tensorflow/compiler/xla/service/llvm_ir/ir_array.h
Labels: cla: yes, comp:xla, kokoro:force-run, ready to pull, size:L

#46767 RFC: Port 16x8 TensorFlow Lite operators to TensorFlow Lite for Microcontrollers
  tensorflow/lite/micro/README.md
  tensorflow/lite/micro/docs/rfc/001-rfc-16x8-quantization-port.md
Labels: cla: yes, comp:micro, kokoro:force-run, ready to pull, size:M, stat:awaiting response

#48433 Upgrade grpcio to 1.37.0
  tensorflow/tools/ci_build/release/common.sh
  tensorflow/tools/ci_build/release/common_win.bat
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, kokoro:force-run, ready to pull, size:S

#48404 Update tf.keras.callbacks.CSVLogger to work with cloud storage
  tensorflow/python/keras/callbacks.py
Labels: awaiting review, cla: yes, comp:keras, kokoro:force-run, ready to pull, size:XS

#48441 [ROCm] Added to AMP allow list to include BatchMatMul
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
Labels: cla: yes, comp:gpu, kokoro:force-run, ready to pull, size:XS

#47508 [ROCm] Enabling device tracing/profling support for AMD GPUs
  tensorflow/core/platform/default/build_config.bzl
  tensorflow/core/profiler/internal/gpu/BUILD
  tensorflow/core/profiler/internal/gpu/device_tracer_cuda.cc
  tensorflow/core/profiler/internal/gpu/device_tracer_rocm.cc
  tensorflow/core/profiler/internal/gpu/device_tracer_test.cc
  tensorflow/core/profiler/internal/gpu/rocm_tracer.cc
  tensorflow/core/profiler/internal/gpu/rocm_tracer.h
  tensorflow/core/profiler/utils/xplane_schema.cc
  tensorflow/core/profiler/utils/xplane_schema.h
  tensorflow/python/client/timeline.py
  tensorflow/python/client/timeline_test.py
  tensorflow/python/eager/profiler_test.py
  tensorflow/python/profiler/BUILD
  tensorflow/python/profiler/internal/run_metadata_test.py
  tensorflow/python/profiler/profile_context_test.py
  tensorflow/stream_executor/platform/default/dso_loader.cc
  tensorflow/stream_executor/platform/default/dso_loader.h
  tensorflow/stream_executor/rocm/BUILD
  tensorflow/stream_executor/rocm/roctracer_wrapper.h
  third_party/gpus/rocm/BUILD.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, comp:gpu, ready to pull, size:XL

#46115 Add ReadVariableOp gradient to C++
  tensorflow/cc/BUILD
  tensorflow/cc/gradients/resource_variable_grad.cc
  tensorflow/cc/gradients/resource_variable_grad_test.cc
Labels: cla: yes, kokoro:force-run, ready to pull, size:M

#48510 Small updates to the docs
  tensorflow/lite/micro/README.md
  tensorflow/lite/micro/docs/renode.md
  tensorflow/lite/micro/docs/rfc/001_preallocated_tensors.md
  tensorflow/lite/micro/docs/rfc/002_16x8_quantization_port.md
Labels: cla: yes, comp:micro, ready to pull, size:XS

#48515 Revert "Support RESIZE_BILINEAR in TFLu"
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/reference/reference_ops.h
  tensorflow/lite/kernels/internal/reference/resize_bilinear.h
  tensorflow/lite/kernels/resize_bilinear.cc
  tensorflow/lite/micro/all_ops_resolver.cc
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/kernels/resize_bilinear.cc
  tensorflow/lite/micro/kernels/resize_bilinear_test.cc
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:micro, ready to pull, size:XL

#48382 Update the use of setAlpha/setBeta for Cudnn frontend APIs
  tensorflow/stream_executor/cuda/cuda_dnn.cc
Labels: cla: yes, ready to pull, size:S

#48491 Remove deprecated function call in local.py
  tensorflow/python/keras/layers/local.py
Labels: cla: yes, comp:keras, kokoro:force-run, ready to pull, size:XS

#47315 [MLIR] Add concatenateOp lowering from lmhlo to Affine.
  tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/lhlo_legalize_to_affine.cc
  tensorflow/compiler/mlir/hlo/tests/lhlo-legalize-to-affine.mlir
Labels: cla: yes, ready to pull, size:M

#48193 TOSA legalization updates for spec v0.22, Part 1
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: awaiting review, cla: yes, ready to pull, size:XL

#47423 Add thread name in the error message when thread creation fails.
  tensorflow/core/platform/default/env.cc
Labels: cla: yes, comp:core, ready to pull, size:XS

#48529 Run bluepill tests with and without -Os
  tensorflow/lite/micro/tools/ci_build/test_bluepill.sh
Labels: cla: yes, comp:micro, ready to pull, size:XS

#48114 Integrate CUDNN v8 frontend API for fused convolution
  tensorflow/core/kernels/conv_ops_fused_impl.h
  tensorflow/core/util/BUILD
  tensorflow/stream_executor/cuda/cuda_dnn.cc
  tensorflow/stream_executor/cuda/cuda_dnn.h
  tensorflow/stream_executor/stream_executor_pimpl.cc
  tensorflow/stream_executor/stream_executor_pimpl.h
Labels: cla: yes, comp:core, ready to pull, size:L

#47948 Use Recording memory APIs in the benchmark.
  tensorflow/lite/micro/benchmarks/BUILD
  tensorflow/lite/micro/benchmarks/keyword_benchmark.cc
  tensorflow/lite/micro/benchmarks/micro_benchmark.h
  tensorflow/lite/micro/docs/memory_management.md
  tensorflow/lite/micro/recording_micro_interpreter.h
Labels: awaiting review, cla: yes, comp:micro, kokoro:force-run, ready to pull, size:S

#47477 micro: LOG_SOFTMAX PR3-5
  tensorflow/lite/kernels/internal/common.h
  tensorflow/lite/kernels/internal/reference/log_softmax.h
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/log_softmax.cc
  tensorflow/lite/micro/kernels/log_softmax_test.cc
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:L

#48457 Remove broken link in tf.keras.callbacks.TensorBoard at docs page
  tensorflow/python/keras/callbacks.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#47664 [tf.data] Add SkipInternal for flat_map and interleave
  tensorflow/core/kernels/data/dataset_test_base.h
  tensorflow/core/kernels/data/flat_map_dataset_op.cc
  tensorflow/core/kernels/data/flat_map_dataset_op_test.cc
  tensorflow/core/kernels/data/interleave_dataset_op.cc
  tensorflow/core/kernels/data/interleave_dataset_op_test.cc
Labels: cla: yes, comp:data, size:M, stat:awaiting tensorflower

#48163 Keras: Remove leftover Python 2 compatibility code
  tensorflow/python/keras/activations.py
  tensorflow/python/keras/saving/save_test.py
  tensorflow/python/keras/utils/data_utils.py
  tensorflow/python/keras/utils/io_utils.py
  tensorflow/python/keras/utils/io_utils_test.py
Labels: awaiting review, cla: yes, comp:keras, ready to pull, size:M

#48503 LearningRateScheduler does not necessarily reduce learning rate
  tensorflow/python/keras/callbacks.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#47987 Fix collections.abc import for Python 3.9
  tensorflow/python/keras/feature_column/base_feature_layer.py
  tensorflow/python/keras/keras_parameterized.py
  tensorflow/python/keras/layers/preprocessing/preprocessing_test_utils.py
  tensorflow/python/keras/saving/saved_model/json_utils.py
  tensorflow/python/keras/saving/saving_utils.py
  tensorflow/python/keras/saving/utils_v1/mode_keys.py
  tensorflow/python/keras/utils/object_identity.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#48508 micro: DEPTH_TO_SPACE PR3-5
  tensorflow/lite/kernels/internal/reference/depth_to_space.h
  tensorflow/lite/micro/all_ops_resolver.cc
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/depth_to_space.cc
  tensorflow/lite/micro/kernels/depth_to_space_test.cc
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:L

#48536 Update api_def_TensorScatterAdd.pbtxt
  tensorflow/core/api_def/base_api/api_def_TensorScatterAdd.pbtxt
Labels: cla: yes, comp:core, ready to pull, size:XS

#48574 Update of oneDNN version for mkl_aarch64 build target
  tensorflow/workspace2.bzl
  third_party/mkl_dnn/mkldnn_acl.BUILD
Labels: cla: yes, ready to pull, size:S

#48472 micro: add INT8 support to CUMSUM op
  tensorflow/lite/kernels/internal/reference/cumsum.h
  tensorflow/lite/micro/kernels/cumsum.cc
  tensorflow/lite/micro/kernels/cumsum_test.cc
Labels: cla: yes, comp:lite, comp:micro, prtype:bugfix, ready to pull, size:L

#48583 [Cherry-pick] Support the input/output data type inside the mlir quantizer
  tensorflow/compiler/mlir/lite/BUILD
  tensorflow/compiler/mlir/lite/quantization/lite/quantize_model.cc
  tensorflow/compiler/mlir/lite/quantization/quantization_utils.cc
  tensorflow/compiler/mlir/lite/quantization/quantization_utils.h
  tensorflow/compiler/mlir/lite/tests/modify_io_nodes.mlir
  tensorflow/compiler/mlir/lite/transforms/modify_io_nodes.cc
  tensorflow/compiler/mlir/lite/transforms/passes.h
  tensorflow/compiler/mlir/lite/transforms/post_quantize.cc
  tensorflow/lite/python/convert.py
  tensorflow/lite/python/lite.py
  tensorflow/lite/python/wrap_toco.py
  tensorflow/lite/toco/python/toco_python_api.cc
  tensorflow/lite/toco/python/toco_python_api.h
  tensorflow/python/lite/toco_python_api_wrapper.cc
Labels: cla: yes

#48594 micro: Update person detection readme
  tensorflow/lite/micro/examples/person_detection/README.md
Labels: cla: yes, comp:micro, ready to pull, size:XS

#48565 [tf.data] support all test combinations for `PrefetchWithSlackTest`
  tensorflow/python/data/experimental/kernel_tests/BUILD
  tensorflow/python/data/experimental/kernel_tests/prefetch_with_slack_test.py
Labels: cla: yes, comp:data, ready to pull, size:S

#48616 Refactor resize_bilinear reference op
  tensorflow/lite/kernels/internal/BUILD
  tensorflow/lite/kernels/internal/reference/reference_ops.h
  tensorflow/lite/kernels/internal/reference/resize_bilinear.h
Labels: cla: yes, ready to pull, size:L

#48619 Add -mlongcalls to the Xtensa compiler flags.
  tensorflow/lite/micro/tools/make/targets/xtensa_makefile.inc
Labels: cla: yes, comp:micro, ready to pull, size:XS

#48578 [INTEL MKL] [2.5 cherry pick] Log warning message for int8 in case of native format
  tensorflow/core/common_runtime/mkl_layout_pass.cc
Labels: cla: yes, comp:mkl, ready to pull, size:S

#47851 [ROCm] Switching to rocblas_gemm_ex for MFMA-enabled architectures
  tensorflow/stream_executor/gpu/gpu_driver.h
  tensorflow/stream_executor/rocm/rocm_blas.cc
  tensorflow/stream_executor/rocm/rocm_driver.cc
Labels: cla: yes, comp:gpu, ready to pull, size:M

#48399 [tflite] make build of tflite cmd line tools work again
  third_party/absl/com_google_absl_fix_mac_and_nvcc_build.patch
Labels: cla: yes, comp:lite, ready to pull, size:S, type:build/install

#48573 Update TF/TFL -> TOSA legalization tests with SSA values associated
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
Labels: cla: yes, ready to pull, size:XL

#48566 Fix all conv layers when filters is 0
  tensorflow/python/keras/layers/convolutional.py
  tensorflow/python/keras/layers/convolutional_test.py
Labels: cla: yes, comp:keras, kokoro:force-run, prtype:bugfix, ready to pull, size:S

#48648 Update bot_config.yml
  .github/bot_config.yml
Labels: cla: yes, kokoro:force-run, ready to pull, size:XS

#47920 Replacing cuda_py_tests with cuda_py_test where applicable
  tensorflow/python/BUILD
  tensorflow/python/kernel_tests/signal/BUILD
Labels: cla: yes, ready to pull, size:S

#48596 micro: Show memory plan if preprocessor define set
  tensorflow/lite/micro/micro_allocator.cc
Labels: cla: yes, comp:micro, ready to pull, size:XS

#48634 Fix handling of last dimension of RaggedTensor in SparseCategoricalLoss.
  tensorflow/python/keras/losses.py
  tensorflow/python/keras/losses_test.py
Labels: cla: yes, comp:keras, prtype:bugfix, ready to pull, size:S

#45690 MeanIoU: Support y_pred passed as a logits tensor or probability tensor
  tensorflow/python/keras/metrics.py
  tensorflow/python/keras/metrics_test.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#48642 Remove image_recognition_experimental example
  tensorflow/lite/micro/examples/image_recognition_experimental/.gitignore
  tensorflow/lite/micro/examples/image_recognition_experimental/BUILD
  tensorflow/lite/micro/examples/image_recognition_experimental/Makefile.inc
  tensorflow/lite/micro/examples/image_recognition_experimental/README.md
  tensorflow/lite/micro/examples/image_recognition_experimental/image_provider.h
  tensorflow/lite/micro/examples/image_recognition_experimental/image_recognition_model.h
  tensorflow/lite/micro/examples/image_recognition_experimental/image_recognition_test.cc
  tensorflow/lite/micro/examples/image_recognition_experimental/main.cc
  tensorflow/lite/micro/examples/image_recognition_experimental/stm32f746_discovery/display_util.cc
  tensorflow/lite/micro/examples/image_recognition_experimental/stm32f746_discovery/display_util.h
  tensorflow/lite/micro/examples/image_recognition_experimental/stm32f746_discovery/image_provider.cc
  tensorflow/lite/micro/examples/image_recognition_experimental/stm32f746_discovery/image_util.cc
  tensorflow/lite/micro/examples/image_recognition_experimental/stm32f746_discovery/image_util.h
  tensorflow/lite/micro/examples/image_recognition_experimental/util.h
  tensorflow/lite/micro/tools/make/Makefile
  tensorflow/lite/micro/tools/make/download_and_extract.sh
  tensorflow/lite/micro/tools/make/fix_arduino_subfolders.py
  tensorflow/lite/micro/tools/make/third_party_downloads.inc
Labels: cla: yes, comp:micro, ready to pull, size:L

#48682 Fix sparkfun edge build for https://github.com/tensorflow/tflite-micro
  tensorflow/lite/micro/tools/make/targets/apollo3evb_makefile.inc
Labels: cla: yes, comp:micro, ready to pull, size:S

#48519 [TFLite] Fix the (u)int8 reference LOG_SOFTMAX operator by properly precomputing the kernel parameters
  tensorflow/lite/kernels/activations.cc
  tensorflow/lite/kernels/activations_test.cc
Labels: cla: yes, comp:lite, ready to pull, size:M

#48687 Update bot_config.yml
  .github/bot_config.yml
Labels: cla: yes, ready to pull, size:XS

#48617 Port RESIZE_BILINEAR kernel and tests from lite to micro
  tensorflow/lite/micro/all_ops_resolver.cc
  tensorflow/lite/micro/kernels/BUILD
  tensorflow/lite/micro/kernels/micro_ops.h
  tensorflow/lite/micro/kernels/resize_bilinear.cc
  tensorflow/lite/micro/kernels/resize_bilinear_test.cc
  tensorflow/lite/micro/micro_mutable_op_resolver.h
  tensorflow/lite/micro/tools/make/Makefile
Labels: cla: yes, comp:micro, ready to pull, size:L

#48666 Cadence HiFi 5 NN Library v1.5.0 integration
  tensorflow/lite/micro/kernels/xtensa/fully_connected.cc
  tensorflow/lite/micro/kernels/xtensa/xtensa.h
  tensorflow/lite/micro/tools/make/ext_libs/xtensa.inc
  tensorflow/lite/micro/tools/make/ext_libs/xtensa_download.sh
Labels: cla: yes, comp:micro, ready to pull, size:M

#48542 Fixed MobilenetV3 from keras/application
  tensorflow/python/keras/applications/applications_test.py
  tensorflow/python/keras/applications/mobilenet_v3.py
Labels: cla: yes, comp:keras, ready to pull, size:S

#48709 Update version numbers for TensorFlow 2.5.0-rc2
  tensorflow/core/public/version.h
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes, kokoro:force-run

#48707 [CHerryPick:r2.5] Keras Training API: Make sure to update the stateful metrics in the Progbar once the MetricsContainer is built so the metrics are not averaged over an epoch.
  tensorflow/python/keras/callbacks.py
  tensorflow/python/keras/callbacks_test.py
  tensorflow/python/keras/utils/generic_utils.py
Labels: cla: yes

#48655 [CherryPick:r2.5]Allow ProfilerFactory to return a nullptr ProfilerInterface
  tensorflow/core/profiler/lib/profiler_factory.cc
  tensorflow/core/profiler/lib/profiler_factory.h
  tensorflow/core/profiler/lib/profiler_session.cc
Labels: cla: yes, size:XS

#48653 [CherryPick:r2.5] Use ast instead of astunparse for python 3.9+.
  tensorflow/python/autograph/pyct/ast_util_test.py
  tensorflow/python/autograph/pyct/cfg.py
  tensorflow/python/autograph/pyct/loader_test.py
  tensorflow/python/autograph/pyct/parser.py
  tensorflow/python/autograph/pyct/parser_test.py
  tensorflow/python/autograph/pyct/transformer_test.py
Labels: cla: yes, size:M

#48651 r2.5-rc2 cherry-pick request: [Intel MKL] Log a warning message when int8 is not supported
  tensorflow/core/common_runtime/mkl_layout_pass.cc
Labels: cla: yes, size:S

#48645 [r2.5 port][ROCm] Port PR 47508 to r2.5
  tensorflow/core/platform/default/build_config.bzl
  tensorflow/core/profiler/internal/gpu/BUILD
  tensorflow/core/profiler/internal/gpu/device_tracer_cuda.cc
  tensorflow/core/profiler/internal/gpu/device_tracer_rocm.cc
  tensorflow/core/profiler/internal/gpu/device_tracer_test.cc
  tensorflow/core/profiler/internal/gpu/rocm_tracer.cc
  tensorflow/core/profiler/internal/gpu/rocm_tracer.h
  tensorflow/core/profiler/utils/xplane_schema.cc
  tensorflow/core/profiler/utils/xplane_schema.h
  tensorflow/python/client/timeline.py
  tensorflow/python/client/timeline_test.py
  tensorflow/python/eager/profiler_test.py
  tensorflow/python/profiler/BUILD
  tensorflow/python/profiler/internal/run_metadata_test.py
  tensorflow/python/profiler/profile_context_test.py
  tensorflow/stream_executor/platform/default/dso_loader.cc
  tensorflow/stream_executor/platform/default/dso_loader.h
  tensorflow/stream_executor/rocm/BUILD
  tensorflow/stream_executor/rocm/roctracer_wrapper.h
  third_party/gpus/rocm/BUILD.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, size:XL

#48622 2.5.0-rc1 cherry-pick request: Update tensorboard dependency to 2.5.x
  tensorflow/tools/pip_package/setup.py
Labels: cla: yes

#48618 [Cherrypick:2.5]Switch absl to `lts_2021_03_24` LTS branch
  third_party/absl/com_google_absl_fix_mac_and_nvcc_build.patch
  third_party/absl/workspace.bzl
Labels: cla: yes, size:XS

#48628 [r2.5 port][ROCm] Port PR 47851 to r2.5
  tensorflow/stream_executor/gpu/gpu_driver.h
  tensorflow/stream_executor/rocm/rocm_blas.cc
  tensorflow/stream_executor/rocm/rocm_driver.cc
Labels: cla: yes, size:M

#48440 [r2.5 port][ROCm] Port PR 47937 to r2.5
  tensorflow/core/kernels/fft_ops.cc
  tensorflow/python/kernel_tests/signal/BUILD
  tensorflow/python/kernel_tests/signal/fft_ops_test.py
  tensorflow/stream_executor/rocm/rocm_fft.cc
  tensorflow/stream_executor/rocm/rocm_fft.h
Labels: cla: yes, size:M

#48507 [r2.5 port][ROCm] Port PR 48187 to r2.5
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
  tensorflow/compiler/xla/tests/BUILD
  tensorflow/python/distribute/BUILD
  tensorflow/python/keras/distribute/BUILD
  tensorflow/python/kernel_tests/BUILD
  tensorflow/python/kernel_tests/distributions/BUILD
  tensorflow/python/kernel_tests/linalg/sparse/BUILD
  tensorflow/python/ops/math_ops_test.py
  tensorflow/python/ops/parallel_for/math_test.py
  tensorflow/python/ops/ragged/ragged_dispatch_test.py
  tensorflow/stream_executor/platform/default/BUILD
  tensorflow/stream_executor/platform/default/dlopen_checker.cc
  tensorflow/stream_executor/platform/default/dso_loader.cc
  tensorflow/stream_executor/platform/default/dso_loader.h
  tensorflow/stream_executor/rocm/BUILD
  tensorflow/stream_executor/rocm/rocm_fft.cc
  tensorflow/stream_executor/rocm/rocm_fft.h
  tensorflow/tools/ci_build/Dockerfile.rocm
  tensorflow/tools/ci_build/linux/rocm/run_gpu_multi.sh
  tensorflow/tools/ci_build/linux/rocm/run_gpu_single.sh
  third_party/gpus/find_rocm_config.py
  third_party/gpus/find_rocm_config.py.gz.base64
  third_party/gpus/rocm/BUILD.tpl
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, size:L

#48442 [r2.5 port][ROCm] Port PR 47646 to r2.5
  tensorflow/python/kernel_tests/pad_op_test.py
Labels: cla: yes, size:S

#48495 [r2.5 port][ROCm] Port PR 48336 to r2.5
  .bazelrc
  tensorflow/core/kernels/mlir_generated/build_defs.bzl
  tensorflow/core/kernels/mlir_generated/gpu_unary_ops_test.cc
Labels: cla: yes, size:S

#48493 [r2.5 port][ROCm] Port PR 48419 to r2.5
  tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc
Labels: cla: yes, size:S

#48444 [r2.5 port][ROCm] Port PR 47980 to r2.5
  tensorflow/python/keras/distribute/BUILD
  tensorflow/python/keras/optimizer_v2/BUILD
  tensorflow/python/training/BUILD
Labels: cla: yes, size:XS

#48445 [r2.5 port][ROCm] Port PR 48346 to r2.5
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/sparse_to_dense_op.cc
  tensorflow/core/kernels/sparse_to_dense_op_gpu.cu.cc
  tensorflow/core/kernels/sparse_to_dense_op_gpu.h
Labels: cla: yes, size:S

#48447 [r2.5 port][ROCm] Port PR#47650 and PR#48441 to r2.5
  tensorflow/core/grappler/optimizers/auto_mixed_precision.cc
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
  tensorflow/core/grappler/optimizers/auto_mixed_precision_test.cc
Labels: cla: yes, size:M

#48569 [Cherrypick:2.5]Copy execution plan in graph partitioner. Also adds code to model_builder_test that fails without this fix.
  tensorflow/lite/delegates/gpu/common/model_builder_test.cc
  tensorflow/lite/delegates/utils.cc
  tensorflow/lite/delegates/utils.h
Labels: cla: yes, size:S

#48543 [r2.5] Update of oneDNN version for mkl_aarch64 build target
  tensorflow/workspace2.bzl
  third_party/mkl_dnn/mkldnn_acl.BUILD
Labels: cla: yes, size:S

#48443 [r2.5 port][ROCm] Port PR 47491 to r2.5
  third_party/gpus/rocm_configure.bzl
Labels: cla: yes, size:S

#48633 Edit CosineSimilarity documentation
  tensorflow/python/keras/losses.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#48659 Update micro_speech mbed generation for disco_f746ng
  tensorflow/lite/micro/examples/micro_speech/README.md
  tensorflow/lite/micro/examples/micro_speech/disco_f746ng/Makefile.inc
  tensorflow/lite/micro/tools/make/targets/disco_f746ng_makefile.inc
  tensorflow/lite/micro/tools/make/targets/mbed_makefile.inc
Labels: cla: yes, comp:micro, ready to pull, size:S

#48715 style(log) : pretty up a debug log string
  tensorflow/core/common_runtime/eager/execute.cc
Labels: cla: yes, comp:core, ready to pull, size:XS

#48706 Iterative horizontal fusion.
  tensorflow/compiler/xla/service/gpu/gpu_compiler.cc
  tensorflow/compiler/xla/service/gpu/gpu_fusible.cc
  tensorflow/compiler/xla/service/gpu/gpu_fusible.h
  tensorflow/compiler/xla/service/gpu/horizontal_input_fusion.cc
  tensorflow/compiler/xla/service/gpu/horizontal_input_fusion_test.cc
  tensorflow/compiler/xla/service/gpu/horizontal_loop_fusion.cc
  tensorflow/compiler/xla/service/gpu/horizontal_loop_fusion_test.cc
  tensorflow/compiler/xla/service/hlo_creation_utils.cc
  tensorflow/compiler/xla/service/hlo_creation_utils.h
Labels: cla: yes, comp:xla, ready to pull, size:L

#48728 [CherryPick 2.5] 3.9 compatibility fix for AST unparsing
  tensorflow/python/framework/test_util.py
Labels: cla: yes

#48729 [Cherrypicke:2.5]Disable pad_op_test for macos. Test times out during 2.5 release
  tensorflow/python/kernel_tests/BUILD
Labels: cla: yes

#48620 hard_sigmoid doc
  tensorflow/python/keras/activations.py
Labels: cla: yes, comp:keras, ready to pull, size:XS

#48737 Update sqlite to latest sqlite-amalgamation-3350500
  tensorflow/workspace2.bzl
Labels: cla: yes, ready to pull, size:XS

#48696 TFLM: Bump CMSIS version
  tensorflow/lite/micro/tools/make/ext_libs/cmsis_download.sh
Labels: cla: yes, comp:micro:arm, ready to pull, size:XS
