Repository tensorflow/tensorflow, pull requests merged in 2022-10, with the labels that each got.

#53576 [tensorflow/lite/schema/upgrade_schema.py] Move `(see :schema.fbs).` up to `operator_type` arg descriptor
  tensorflow/lite/schema/upgrade_schema.py
Labels: type:docs-bug, comp:lite, ready to pull, size:XS

#57776 [ROCm] Add stream_executor/stream.h header to pip package
  tensorflow/tools/pip_package/BUILD
Labels: awaiting review, ready to pull, comp:gpu, size:XS

#57686 [TF-TRT]: Propagate batch_dims in Gather converter
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
Labels: ready to pull, size:S, comp:gpu:tensorrt

#57782 [TFTRT] Avoid saving unused variables after conversion
  tensorflow/python/compiler/tensorrt/trt_convert.py
Labels: awaiting review, ready to pull, size:S, comp:gpu:tensorrt

#57842 Updates oneDNN and Compute Library bulds on AArch64
  tensorflow/workspace2.bzl
  third_party/compute_library/BUILD
  third_party/compute_library/compute_library.patch
Labels: ready to pull, size:S

#57518 [tosa] Add legalization for TFL gelu
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: awaiting review, ready to pull, size:M

#57955 [ROCm] Add fence to memory barrier in XLA for gfx90a.
  tensorflow/compiler/xla/service/gpu/ir_emitter.cc
  tensorflow/compiler/xla/service/gpu/ir_emitter.h
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc
Labels: awaiting review, ready to pull, comp:xla, size:S

#57957 Changes to add patch to openmp build, to fix build failure
  tensorflow/workspace2.bzl
  third_party/llvm_openmp/openmp_switch_default_patch.patch
Labels: awaiting review, ready to pull, size:S

#57987 Support for ACL fixed format kernels and depth wise convolution
  tensorflow/core/kernels/mkl/mkl_batch_matmul_op.cc
  tensorflow/core/kernels/mkl/mkl_conv_ops.cc
  tensorflow/core/kernels/mkl/mkl_matmul_op_fused.cc
  tensorflow/core/kernels/mkl/mkl_matmul_ops_common.h
  tensorflow/workspace2.bzl
  third_party/compute_library/BUILD
  third_party/compute_library/acl_depthwise_updateable_weights.patch
  third_party/compute_library/acl_fixed_format_kernels_striding.patch
  third_party/compute_library/acl_fixup_SVE_merges.patch
  third_party/compute_library/activation_func_correct_args.patch
  third_party/mkl_dnn/onednn_acl_depthwise_convolution.patch
  third_party/mkl_dnn/onednn_acl_fixed_format_kernels.patch
  third_party/mkl_dnn/onednn_acl_threadcap.patch
Labels: ready to pull, size:XL

#57878 [oneDNN] Upgrading oneDNN to 2.7
  tensorflow/workspace2.bzl
  third_party/mkl_dnn/mkldnn_v1.BUILD
Labels: ready to pull, comp:mkl, size:M

#57969 Fix fail to build of aot_compiled_test on aarch64
  tensorflow/compiler/tf2xla/BUILD
Labels: awaiting review, ready to pull, size:XS

#58008 Remove empty glob
  tensorflow/tools/docs/BUILD
Labels: awaiting review, ready to pull, size:XS

#57701 [TFTRT] Disable TF32 evaluation in BatchMatMulWeightBroadcast test cases.
  tensorflow/python/compiler/tensorrt/test/batch_matmul_test.py
Labels: awaiting review, ready to pull, size:XS, comp:gpu:tensorrt

#57670 [TF-TRT] Fix calibration with data dependent shapes
  tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
  tensorflow/python/compiler/tensorrt/test/BUILD
  tensorflow/python/compiler/tensorrt/test/data_dependent_shape_test.py
Labels: ready to pull, size:M, comp:gpu:tensorrt

#57908 Update AMP mkl lists
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
Labels: ready to pull, comp:grappler, size:XS

#58061 output test failure logs
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_pip.sh
Labels: ready to pull, size:XS

#57074 [oneDNN] Enable fp32 & bf16 Einsum for CPU by default
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
  tensorflow/core/kernels/mkl/mkl_einsum_op.cc
Labels: ready to pull, comp:grappler, size:XS

#58079 Replace reviewer for automatic cherrypicks
  .github/workflows/release-branch-cherrypick.yml
Labels: awaiting review, ready to pull, size:XS

#57927 Update SECURITY.md to use a form.
  SECURITY.md
Labels: awaiting review, ready to pull, size:XS

#57519 [tosa] Add legalization for TF/TFL conv3d
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/fuse_bias_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
Labels: ready to pull, size:L

#58066 Replace auto assignment list
  .github/bot_config.yml
Labels: awaiting review, ready to pull, size:XS

#57979 [ROCm] Fix 2 more unit tests for gpu_kernel_tiling_test on ROCm
  tensorflow/compiler/xla/service/gpu/tests/gpu_codegen_test.cc
  tensorflow/compiler/xla/service/gpu/tests/gpu_kernel_tiling_test.cc
Labels: awaiting review, ready to pull, comp:gpu, size:S

#55780 Remove ROCm specific casing in nextafter_op impl.
  tensorflow/core/kernels/nextafter_op.h
Labels: ready to pull, comp:gpu, size:S

#58029 Fixed some Grammar mistakes in array_ops.py
  tensorflow/python/ops/array_ops.py
Labels: awaiting review, ready to pull, comp:ops, size:S

#58069 [TF-TRT] Fix some compilation warnings in TF-TRT
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/ops/quantization_ops_test.cc
Labels: awaiting review, ready to pull, size:XS, comp:gpu:tensorrt

#57699 Update image.rot90 docstring.
  tensorflow/python/ops/image_ops_impl.py
Labels: ready to pull, comp:ops, size:XS

#57163 Link tensorflow.dll to kernels_experimental on Windows
  tensorflow/BUILD
Labels: ready to pull, size:XS

#55677 Return an error code for `TF_GetInputTensorFromVariable`
  tensorflow/c/BUILD
  tensorflow/c/kernels_experimental.cc
  tensorflow/core/lib/gtl/BUILD
Labels: ready to pull, size:S

#58099 Disable failing linalg tests on ARM_CI
  tensorflow/tools/ci_build/build_scripts/ARM_SKIP_TESTS.sh
Labels: ready to pull, size:S

#57998 [oneDNN] Fix AvgPool3d Floating point exception
  tensorflow/core/kernels/mkl/mkl_avgpooling_op.cc
  tensorflow/python/kernel_tests/nn_ops/pooling_ops_3d_test.py
Labels: cla: yes, ready to pull, size:S

#58065 Deprecate ImplicitBatchModeCompatible dynamic shape strategy
  tensorflow/python/compiler/tensorrt/trt_convert.py
Labels: awaiting review, ready to pull, size:XS, comp:gpu:tensorrt

#58157 Update the keras packages version in master.
  tensorflow/tools/pip_package/setup.py
Labels: awaiting review, ready to pull, size:XS

#57954 [TF-TRT] Additional TRT 8.5 Fixups
  tensorflow/compiler/tf2tensorrt/common/utils.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/utils.cc
  tensorflow/compiler/tf2tensorrt/convert/weights.cc
  tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
  tensorflow/compiler/tf2tensorrt/utils/trt_engine_utils.cc
Labels: ready to pull, size:XS, comp:gpu:tensorrt

#58005 [ROCm] fixed unit test for gpu_compiler_test on ROCm
  tensorflow/compiler/xla/service/gpu/gpu_compiler_test.cc
Labels: awaiting review, ready to pull, comp:xla, size:XS

#58170 Fix-rel-notes
  RELEASE.md
Labels: size:M

#58121 [ROCm] Absorb fix for the LLVM AMDGPU backend addition of fp16 support of ne…
  tensorflow/compiler/xla/service/elemental_ir_emitter.cc
Labels: awaiting review, ready to pull, comp:gpu, size:XS

#57778 Add mirrorpad legalization for TF and TFL
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: awaiting review, ready to pull, size:M

#56485 [TF-TRT] Disable TF32 for TF-TRT unittests that needs it
  tensorflow/python/compiler/tensorrt/test/biasadd_matmul_test.py
  tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py
Labels: ready to pull, size:M, comp:gpu:tensorrt

#58148 [TF-TRT] Adding additional TraceMe ranges
  tensorflow/compiler/tf2tensorrt/BUILD
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc
  tensorflow/compiler/tf2tensorrt/kernels/trt_engine_resource_ops.cc
  tensorflow/compiler/tf2tensorrt/segment/segment.cc
Labels: awaiting review, ready to pull, size:M, comp:gpu:tensorrt

#58078 [tosa] Add TFL.Relu0To1Op definition and Legalize to TOSA with Lit Test
  tensorflow/compiler/mlir/lite/ir/tfl_op_enums.td
  tensorflow/compiler/mlir/lite/ir/tfl_ops.td
  tensorflow/compiler/mlir/lite/tests/ops.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: awaiting review, ready to pull, size:M

#58172 Add missing link library for MhloDialect
  tensorflow/compiler/xla/mlir_hlo/lib/Dialect/mhlo/IR/CMakeLists.txt
Labels: awaiting review, ready to pull, size:XS

#58174 Fix duplicated dylibs in Mac pip wheel
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: ready to pull, size:XS

#57948 [ROCm] Fix for gpu_kernel_tiling_test on ROCm.
  tensorflow/compiler/xla/service/gpu/tests/gpu_kernel_tiling_test.cc
Labels: ready to pull, comp:gpu, size:XS

#58103 Fix typos and broken links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: awaiting review, ready to pull, size:M

#58173 Update rules_pkg
  tensorflow/workspace3.bzl
Labels: ready to pull, size:XS

#57783 Fix crash in tf.image.crop_and_resize caused by invalid box_indices
  tensorflow/core/kernels/image/crop_and_resize_op.cc
  tensorflow/python/ops/image_ops_test.py
Labels: awaiting review, ready to pull, size:S, prtype:bugfix

#58167 Fix valgrind error
  tensorflow/core/common_runtime/pending_counts.h
Labels: ready to pull, size:XS, comp:core

#58203 [NVIDIA TF] Enable bfloat16 on GPU for random ops
  tensorflow/core/kernels/random_op.cc
  tensorflow/core/kernels/random_op_gpu.cu.cc
  tensorflow/core/kernels/stateful_random_ops.cc
  tensorflow/core/kernels/stateful_random_ops_gpu.cu.cc
  tensorflow/core/kernels/stateless_random_ops.cc
  tensorflow/core/kernels/stateless_random_ops_v2.cc
Labels: ready to pull, size:S

#58154 Remove empty glob
  tensorflow/core/BUILD
Labels: ready to pull, size:S, comp:core

#58185 Remove outdated docs re: Arduino Library Manager installation
  tensorflow/lite/g3doc/microcontrollers/library.md
Labels: awaiting review, comp:lite, ready to pull, size:XS

#58149 [OneDNN] Bug fix: Fixing a primitive cache key
  tensorflow/core/kernels/mkl/mkl_conv_ops.cc
Labels: ready to pull, size:XS

#56943 Updated Task Library Text Tasks Documentation
  tensorflow/lite/g3doc/inference_with_metadata/task_library/bert_nl_classifier.md
  tensorflow/lite/g3doc/inference_with_metadata/task_library/bert_question_answerer.md
  tensorflow/lite/g3doc/inference_with_metadata/task_library/nl_classifier.md
Labels: awaiting review, comp:lite, ready to pull, size:M

#58269 Upgrading to the latest oneDNN 2.7.1
  tensorflow/workspace2.bzl
  third_party/mkl_dnn/mkldnn_v1.BUILD
Labels: ready to pull, size:S

#58216 Do not pass 4th argument to _MklNativeFusedConv2D
  tensorflow/core/kernels/conv_ops_benchmark_test.cc
Labels: awaiting review, ready to pull, size:S

#58266 Fix zlib download URL
  tensorflow/workspace2.bzl
Labels: ready to pull, size:XS

#58254 [NVIDIA TF] Unit tests for bf16 random ops on GPU
  tensorflow/python/kernel_tests/random/random_ops_test.py
  tensorflow/python/kernel_tests/random/stateful_random_ops_test.py
  tensorflow/python/kernel_tests/random/stateless_random_ops_test.py
Labels: ready to pull, size:M

#57938 Fixed Grammer mistakes of control_flow_op.py
  tensorflow/python/autograph/operators/control_flow.py
Labels: ready to pull, size:S, comp:autograph

#58320 Declare strides when ACL objects init and activation in ACL depthwise
  tensorflow/tools/ci_build/build_scripts/ARM_SKIP_TESTS.sh
  third_party/compute_library/acl_fixed_format_kernels_striding.patch
  third_party/mkl_dnn/onednn_acl_depthwise_convolution.patch
  third_party/mkl_dnn/onednn_acl_fixed_format_kernels.patch
Labels: ready to pull, comp:mkl, size:M

#58260 Update libjpeg_turbo
  third_party/jpeg/jpeg.BUILD
  third_party/jpeg/workspace.bzl
Labels: ready to pull, size:XS

#58089 Fix conjugate transpose for 0/1D complex tensor
  tensorflow/core/kernels/transpose_functor_gpu.cu.cc
Labels: awaiting review, ready to pull, size:S, comp:core

#58259 Range kenrel: align CPU and GPU impl
  tensorflow/core/kernels/sequence_ops.cc
Labels: ready to pull, size:XS, comp:core

#58282 Improving converters for Select/SelectV2 operations.
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.h
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes_test.cc
  tensorflow/compiler/tf2tensorrt/convert/ops/selectv2.cc
  tensorflow/compiler/tf2tensorrt/convert/weights.h
Labels: awaiting review, ready to pull, size:M, comp:gpu:tensorrt

#56488 [TF-TRT] Enable Sparse Compute Env Var: `TF_TRT_SPARSE_MODE`
  tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc
Labels: awaiting review, ready to pull, size:M, comp:gpu:tensorrt

#58215 [ROCm] Enable RCCL in XLA pjrt
  tensorflow/compiler/xla/pjrt/gpu/BUILD
  tensorflow/compiler/xla/pjrt/gpu/nccl_id_store.cc
  tensorflow/compiler/xla/pjrt/gpu/se_gpu_pjrt_client.cc
Labels: awaiting review, ready to pull, comp:gpu, size:S

#57769 Update libpng to libpng-1.6.38
  tensorflow/workspace2.bzl
Labels: awaiting review, ready to pull, size:XS

#57069 Fix endianness issue in Tensor::BitcastFrom() on s390x
  tensorflow/compiler/mlir/tensorflow/ir/tf_generated_ops.td
  tensorflow/compiler/xla/BUILD
  tensorflow/compiler/xla/literal.cc
  tensorflow/core/api_def/base_api/api_def_Bitcast.pbtxt
  tensorflow/core/framework/BUILD
  tensorflow/core/framework/tensor.cc
  tensorflow/core/util/BUILD
  tensorflow/core/util/tensor_bundle/BUILD
  tensorflow/core/util/tensor_bundle/byte_swap_array.h
  tensorflow/go/op/wrappers.go
  tensorflow/tsl/util/BUILD
  tensorflow/tsl/util/byte_swap_array.cc
  tensorflow/tsl/util/byte_swap_array.h
  tensorflow/tsl/util/tensor_bundle/BUILD
Labels: awaiting review, ready to pull, size:S

#58356 [Intel oneDNN] Show warning for Windows GPU build
  configure.py
Labels: ready to pull, size:S

#58345 Support python 3.11 changes.
  tensorflow/python/keras/utils/tf_inspect.py
  tensorflow/python/util/dispatch.py
  tensorflow/python/util/stack_trace.h
  tensorflow/python/util/tf_inspect.py
Labels: awaiting review, ready to pull, size:S

#57047 Update - Text Classification
  tensorflow/lite/g3doc/models/modify/model_maker/text_classification.ipynb
Labels: comp:lite, ready to pull, size:M
