Repository tensorflow/tensorflow, pull requests merged in 2023-08, with the labels that each got.

#61184 Relax DLPack stride requirements
  tensorflow/c/eager/BUILD
  tensorflow/c/eager/dlpack.cc
  tensorflow/c/eager/dlpack_test.cc
Labels: awaiting review, comp:eager, ready to pull, size:M

#61431 Slight differences with AARCH64 so need to relax test
  tensorflow/python/kernel_tests/nn_ops/rnn_cell_test.py
Labels: awaiting review, ready to pull, size:XS

#60258 Update example code to use TensorFlow 2.0 behaviour
  tensorflow/lite/g3doc/guide/inference.md
Labels: awaiting review, comp:lite, ready to pull, size:S

#60696 Use fp32 compute result as the reference for tf32 test in ROCm as MIO…
  tensorflow/compiler/tests/BUILD
  tensorflow/compiler/tests/tensor_float_32_test.py
Labels: awaiting review, ready to pull, size:S

#61450 Fix link failure in XLA unit tests
  tensorflow/compiler/xla/service/cpu/BUILD
Labels: ready to pull, size:XS

#61294 [NVIDIA TF] Optimize embedding_lookup_sparse using new grad op [PART 2/3]
  tensorflow/core/kernels/segment_reduction_ops_gpu.cu.h
  tensorflow/core/kernels/segment_reduction_ops_gpu_0.cu.cc
  tensorflow/core/kernels/segment_reduction_ops_gpu_1.cu.cc
  tensorflow/core/kernels/segment_reduction_ops_impl.h
  tensorflow/core/kernels/segment_reduction_ops_impl_5.cc
Labels: awaiting review, ready to pull, size:L, comp:core

#60700 [TOSA] Update tfl.mean legalization to match the new reference kernel behaviour
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
Labels: awaiting review, size:M

#61448 Minor typos were fixed
  CONTRIBUTING.md
Labels: awaiting review, ready to pull, size:S

#60786 [PluggableDevice] Always link kernels_experimental c api
  tensorflow/c/BUILD
Labels: awaiting review, ready to pull, size:XS

#61467 version bump and formatting
  tensorflow/tools/ci_build/osx/arm64/tensorflow_as_build_nightly.Jenkinsfile
  tensorflow/tools/ci_build/osx/arm64/tensorflow_as_build_release.Jenkinsfile
  tensorflow/tools/ci_build/osx/arm64/tensorflow_as_test_ci.Jenkinsfile
  tensorflow/tools/ci_build/osx/arm64/tensorflow_as_test_nightly.Jenkinsfile
  tensorflow/tools/ci_build/osx/arm64/tensorflow_as_test_release.Jenkinsfile
Labels: ready to pull, size:S

#60824 Update list_physical_devices and list_logical_devices Argument notes
  tensorflow/python/framework/config.py
Labels: awaiting review, ready to pull, size:S, prtype:bugfix

#61456 Fixed the broken link on faq.md
  tensorflow/lite/g3doc/guide/faq.md
Labels: awaiting review, comp:lite, ready to pull, size:XS

#61474 [Linaro:ARM_CI] Rename scripts to be clearer about function
  .github/workflows/arm-cd.yml
  .github/workflows/arm-ci-extended-cpp.yml
  .github/workflows/arm-ci-extended.yml
  .github/workflows/arm-ci.yml
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_test.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_test_build.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_test_cpp.sh
Labels: ready to pull, size:XS

#61397 ColumnReduceKernel: type casting fix and improvement
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
  third_party/flatbuffers/flatbuffers.BUILD
Labels: awaiting review, ready to pull, size:S, comp:core

#61383 [Linaro:ARM_CI] Switch to building with clang by default
  tensorflow/tools/ci_build/build_scripts/ARM_SKIP_TESTS.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_test.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_test_build.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_test_cpp.sh
Labels: ready to pull, size:S

#61207 [NextPluggabledevice] Enable XLA auto clustering mode for NextPluggableDevice
  tensorflow/compiler/jit/kernels/xla_ops.cc
  tensorflow/compiler/tf2xla/BUILD
  tensorflow/compiler/tf2xla/xla_op_registry.cc
  tensorflow/core/common_runtime/next_pluggable_device/BUILD
  tensorflow/core/common_runtime/next_pluggable_device/next_pluggable_device_factory.h
  tensorflow/core/tfrt/common/BUILD
Labels: awaiting review, ready to pull, size:M

#61498 [Linaro:ARM_CI] Run build tests
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_test_cpp.sh
Labels: ready to pull, size:S

#61079 Updating tf.experimental.numpy.vander for N=0
  tensorflow/python/ops/numpy_ops/np_array_ops.py
  tensorflow/python/ops/numpy_ops/np_array_ops_test.py
Labels: ready to pull, comp:ops, size:XS

#61503 Fixing build issue with Clang 16
  tensorflow/tsl/lib/io/cache.h
Labels: awaiting review, ready to pull, size:XS

#61502 [oneDNN]: Code cleanup
  tensorflow/core/common_runtime/mkl_layout_pass.cc
  tensorflow/core/kernels/mkl/mkl_batch_matmul_helper.h
  tensorflow/core/kernels/mkl/mkl_batch_matmul_op.cc
  tensorflow/core/kernels/mkl/mkl_concat_op.cc
  tensorflow/core/kernels/mkl/mkl_conv_ops.h
  tensorflow/core/kernels/mkl/mkl_einsum_op.cc
  tensorflow/core/kernels/mkl/mkl_fused_batch_norm_op.cc
  tensorflow/core/kernels/mkl/mkl_pooling_ops_common.h
Labels: awaiting review, ready to pull, comp:mkl, size:M

#61358 [NextPluggableDevice] Add TF_TemporaryVariable C API
  tensorflow/c/kernels_experimental.cc
  tensorflow/c/kernels_experimental.h
Labels: awaiting review, ready to pull, size:M

#61522 [Linaro:ARM_CI] Enable tests that now pass
  tensorflow/tools/ci_build/build_scripts/ARM_SKIP_TESTS.sh
  tensorflow/tools/ci_build/build_scripts/ARM_SKIP_TESTS_EXTENDED.sh
Labels: ready to pull, size:XS

#61595 [oneDNN] upgrade onednn version to 3.2.1
  tensorflow/workspace2.bzl
  third_party/mkl_dnn/mkldnn_v1.BUILD
Labels: ready to pull, comp:mkl, size:XS

#61278 [NextPluggableDevice] Variant datatype support in MakeTensorFromProto
  tensorflow/core/common_runtime/next_pluggable_device/next_pluggable_device.cc
Labels: awaiting review, ready to pull, size:M, comp:core

#61638 [ROCm] Fixed error: call to 'min' is ambiguous
  tensorflow/core/kernels/reduction_gpu_kernels.cu.h
Labels: awaiting review, ready to pull, comp:gpu, size:XS

#61663 Enable rsync working on windows
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: awaiting review, ready to pull, size:XS

#61670 Ensure that pywrap_quantize_model.so has correct RPATH
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: ready to pull, size:XS

#61672 Update args description of crop_to_bounding_box & pad_to_bounding_box
  tensorflow/python/ops/image_ops_impl.py
Labels: awaiting review, ready to pull, comp:ops, size:S

#61332 [oneDNN] Add 2 new patterns for layernorm fusion
  tensorflow/core/grappler/optimizers/remapper.cc
  tensorflow/core/grappler/optimizers/remapper_test.cc
Labels: awaiting review, ready to pull, comp:grappler, size:L

#61690 Add missing elem-wize functions to xla operation semantics doc
  tensorflow/compiler/xla/g3doc/operation_semantics.md
Labels: awaiting review, ready to pull, comp:xla, size:S

#61404 Update requirements.in
  ci/official/requirements_updater/requirements.in
Labels: awaiting review, ready to pull, size:XS

#61637 Register DEVICE_DEFAULT for Assign(Add/Sub)VariableOp
  tensorflow/core/kernels/resource_variable_ops.cc
Labels: awaiting review, ready to pull, size:S, comp:core

#61727 Fix TF-TPU build flags
  ci/official/envs/nightly_linux_x86_tpu_py310
  ci/official/envs/nightly_linux_x86_tpu_py311
  ci/official/envs/nightly_linux_x86_tpu_py39
Labels: awaiting review, ready to pull, size:XS

#61331 [oneDNN] Add BFloat16 Specialization Functor for Mean Op
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
  tensorflow/core/kernels/reduction_ops.h
  tensorflow/core/kernels/reduction_ops_test.cc
  tensorflow/python/kernel_tests/math_ops/reduction_ops_test_big.py
Labels: awaiting review, ready to pull, comp:grappler, size:S

#61704 upgrade curl 8.1.2 -> 8.2.1 which has CVE fixes
  tensorflow/workspace2.bzl
  third_party/curl.BUILD
Labels: awaiting review, ready to pull, size:XS

#61636 TFLite XNNPack Delegate: use kernel size of 5 for correspondingly named tests
  tensorflow/lite/delegates/xnnpack/depthwise_conv_2d_test.cc
Labels: awaiting review, comp:lite, ready to pull, size:XS

#61752 Update rules_python version to 0.25.0
  WORKSPACE
Labels: ready to pull, size:XS

#61758 Select in Generic Pattern Matching for FP8 GEMMs in XLA
  tensorflow/compiler/xla/service/gpu/gemm_rewriter.cc
  tensorflow/compiler/xla/service/gpu/tests/gemm_rewrite_test.cc
Labels: awaiting review, ready to pull, comp:xla, size:L
