Repository tensorflow/tensorflow, pull requests merged in 2023-03, with the labels that each got.

#59606 [tosa] Legalize tfl.real and tfl.imag
  tensorflow/compiler/mlir/tosa/BUILD
  tensorflow/compiler/mlir/tosa/tests/lower-complex-types.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tf_tfl_passes.cc
  tensorflow/compiler/mlir/tosa/tfl_passes.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/lower_complex_types.cc
  tensorflow/compiler/mlir/tosa/transforms/passes.h
  tensorflow/compiler/mlir/tosa/transforms/passes.td
Labels: awaiting review, ready to pull, size:L

#59820 Cache the result of cuModuleGetFunction
  tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc
  tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.h
Labels: awaiting review, ready to pull, size:M

#59823 [Linaro:ARM_CI] Switch to using Docker container with Dual ABI
  tensorflow/tools/ci_build/Dockerfile.cpu.arm64
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_pip.sh
Labels: ready to pull, size:S

#58285 Migrate/Extend Stale management to Github Action
  .github/stale.yml
  .github/workflows/stale-issues.yml
Labels: awaiting review, ready to pull, size:M

#59858 [Linaro:ARM_CI] Use the provided group name for chown
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_pip.sh
Labels: ready to pull, size:XS

#59759 Fix the endianness issue in `//tensorflow/python/framework:tensor_util_test` on s390x
  tensorflow/python/framework/tensor_util_test.py
Labels: awaiting review, ready to pull, size:S

#59808 add end-to-end fuzzer
  tensorflow/security/fuzzing/cc/BUILD
  tensorflow/security/fuzzing/cc/end_to_end_fuzz.cc
Labels: awaiting review, ready to pull, size:M

#59795 Update devel.requirements.txt
  tensorflow/tools/tf_sig_build_dockerfiles/devel.requirements.txt
Labels: awaiting review, ready to pull, size:XS

#58597 Support writing non conversion report to more filesystems
  tensorflow/compiler/tf2tensorrt/segment/segment.cc
Labels: awaiting review, ready to pull, size:S, comp:gpu:tensorrt

#59874 [Linaro:ARM_CI] Fix for patchelf permission denied
  tensorflow/tools/pip_package/build_pip_package.sh
Labels: ready to pull, size:XS

#53265 all_reduce_indexed_slices remove not eager context
  tensorflow/python/distribute/cross_device_utils.py
Labels: cla: yes, awaiting review, ready to pull, size:XS

#59873 [Linaro:ARM_CI] Fix permissions problems on installing Python pkgs
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_pip.sh
Labels: ready to pull, size:S

#59867 [Linaro:ARM_CI] Fix bad interpreter from update_version.py
  tensorflow/tools/ci_build/Dockerfile.cpu.arm64
Labels: ready to pull, size:XS

#59847 Update tensorflow/go/README.md
  tensorflow/go/README.md
Labels: awaiting review, ready to pull, size:M

#59864 Fix the image recognition tutorial links in README.md
  tensorflow/examples/label_image/README.md
Labels: awaiting review, ready to pull, size:XS

#59909 [Linaro:ARM_CI] Clean up exclude list for ARM64 builds
  tensorflow/tools/ci_build/build_scripts/ARM_SKIP_TESTS.sh
Labels: awaiting review, ready to pull, size:S

#59907 Prevent stale issues action from running in forks
  .github/workflows/stale-issues.yml
Labels: ready to pull, size:XS

#59672 [tosa] improved legalization for leaky_relu
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: awaiting review, ready to pull, size:M

#59876 Add override qualifier to Device
  tensorflow/core/framework/device.h
Labels: awaiting review, ready to pull, size:XS, comp:core

#59798 Add s390x support in ParseTensorOp and SerializeTensorOp
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/parse_tensor_op.cc
  tensorflow/core/util/tensor_bundle/byte_swap_tensor.cc
  tensorflow/core/util/tensor_bundle/byte_swap_tensor.h
  tensorflow/python/kernel_tests/io_ops/parsing_ops_test.py
  tensorflow/python/ops/io_ops.py
Labels: awaiting review, ready to pull, size:S, comp:core

#59594 Fix typos in the model maker object detection document
  tensorflow/lite/g3doc/models/modify/model_maker/object_detection.ipynb
Labels: comp:lite, ready to pull, size:S

#59917 [XLA] Compute type for f8 gemm defaults to COMPUTE_32F
  tensorflow/compiler/xla/service/gpu/gemm_rewriter.cc
  tensorflow/compiler/xla/service/gpu/matmul_utils.cc
  tensorflow/compiler/xla/service/gpu/matmul_utils.h
  tensorflow/compiler/xla/service/gpu/tests/gemm_rewrite_test.cc
Labels: awaiting review, ready to pull, comp:xla, size:XS

#59936 [NVIDIA XLA] Disable TF32 evaluation for SelfAdjointEigTest cases.
  tensorflow/compiler/xla/client/lib/BUILD
  tensorflow/compiler/xla/client/lib/self_adjoint_eig_test.cc
Labels: awaiting review, ready to pull, size:S

#59901 Update android audio classifier reference app URL
  tensorflow/lite/g3doc/inference_with_metadata/task_library/audio_classifier.md
Labels: awaiting review, comp:lite, ready to pull, size:XS

#59919 Fixed action workflow error in stale-issue.yaml
  .github/workflows/stale-issues.yml
Labels: ready to pull, size:S

#59466 Disable ARC for signpost_profiler
  tensorflow/lite/CMakeLists.txt
Labels: awaiting review, comp:lite, ready to pull, size:XS

#59859 Fix Add/Sub QInt8 rounding mismatch
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
Labels: awaiting review, ready to pull, size:L

#59945 [ROCm] add reserved gpu memory for rocm libraries with overflow check
  tensorflow/compiler/xla/stream_executor/rocm/rocm_driver.cc
Labels: awaiting review, ready to pull, comp:gpu, size:S

#59955 Remove references to the Bazel flag `--distinct_host_configuration`.
  .bazelrc
  tensorflow/tools/ci_build/Dockerfile.cuda-clang
  tensorflow/tools/ci_build/builds/android_full.sh
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_nonpip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py310_pip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py38_pip.sh
  tensorflow/tools/ci_build/rel/ubuntu/gpu_py39_pip.sh
  tensorflow/tools/ci_build/xla/linux/gpu/run_py3.sh
  tensorflow/tools/tf_sig_build_dockerfiles/devel.usertools/cpu.bazelrc
  tensorflow/tools/tf_sig_build_dockerfiles/devel.usertools/cpu_clang.bazelrc
  tensorflow/tools/tf_sig_build_dockerfiles/devel.usertools/gpu.bazelrc
  tensorflow/tools/tf_sig_build_dockerfiles/devel.usertools/gpu_clang.bazelrc
Labels: awaiting review, ready to pull, size:M

#58494 Add big-endian support to TFLite FlatBuffers
  tensorflow/compiler/mlir/lite/BUILD
  tensorflow/compiler/mlir/lite/flatbuffer_import.cc
  tensorflow/compiler/mlir/lite/flatbuffer_to_string.cc
  tensorflow/lite/core/model_builder.cc
  tensorflow/lite/core/model_builder.h
  tensorflow/lite/experimental/acceleration/mini_benchmark/BUILD
  tensorflow/lite/experimental/acceleration/mini_benchmark/metrics/blazeface_metrics.py
  tensorflow/lite/experimental/acceleration/mini_benchmark/metrics/mobilenet.py
  tensorflow/lite/experimental/acceleration/mini_benchmark/model_modifier/BUILD
  tensorflow/lite/experimental/acceleration/mini_benchmark/model_modifier/embedder_main.cc
  tensorflow/lite/experimental/acceleration/mini_benchmark/validator_test.cc
  tensorflow/lite/testing/zip_test_utils.py
  tensorflow/lite/tools/flatbuffer_utils.py
  tensorflow/lite/tools/flatbuffer_utils_test.py
  tensorflow/lite/tools/model_loader.cc
  tensorflow/lite/tools/serialization/BUILD
  tensorflow/lite/tools/serialization/writer_lib.cc
  tensorflow/lite/tools/test_utils.py
Labels: awaiting review, comp:lite, ready to pull, size:L

#58678 Don't link tensorflow-lite against gemmlowp
  tensorflow/lite/CMakeLists.txt
Labels: comp:lite, ready to pull, size:XS

#59915 [NVIDIA XLA:GPU] Do not show the C stack trace when there is a too old cudnn version.
  tensorflow/compiler/xla/service/gpu/BUILD
  tensorflow/compiler/xla/service/gpu/gpu_compiler.cc
Labels: awaiting review, ready to pull, comp:xla, size:XS

#58601 Fix the endianness issue in v1 frozen graphs in python:lite_test on BE machines
  tensorflow/lite/python/lite.py
  tensorflow/python/framework/BUILD
  tensorflow/python/framework/byte_swap_tensor.py
  tensorflow/python/framework/graph_io.py
  tensorflow/python/framework/meta_graph.py
  tensorflow/python/saved_model/utils_impl.py
Labels: awaiting review, comp:lite, ready to pull, size:M

#59971 Generic Pattern Matching for FP8 GEMMs in XLA
  tensorflow/compiler/xla/service/gpu/gemm_rewriter.cc
  tensorflow/compiler/xla/service/gpu/tests/gemm_rewrite_test.cc
Labels: ready to pull, comp:xla, size:L

#59675 [NVIDIA TF] Update cudnn frontend to v0.8
  tensorflow/workspace2.bzl
  third_party/cudnn_frontend_header_fix.patch
Labels: awaiting review, size:S

#60001 [NVIDIA TF] CollectiveAllToAllV2 + NCCL all-to-all fixes
  tensorflow/core/kernels/collective_nccl_test.cc
  tensorflow/core/kernels/collective_ops.cc
  tensorflow/core/nccl/nccl_manager.cc
Labels: awaiting review, ready to pull, size:S, comp:core

#60039 Improve readability of applied patch files
  tensorflow/workspace2.bzl
Labels: ready to pull, size:XS

#58785 [tosa] Add math.sign legalization
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
Labels: size:M

#60006 Update label_image.py to be compatible with TF 2.x
  tensorflow/examples/label_image/label_image.py
Labels: type:docs-bug, ready to pull, size:S

#60018 [Intel oneDNN][Bug Fix] fix unit test failure with framework::function test
  tensorflow/python/framework/function_test.py
Labels: awaiting review, ready to pull, size:XS

#59947 [oneDNN] Move Mean op back to auto_mixed_precision deny list due to potential a…
  tensorflow/core/grappler/optimizers/auto_mixed_precision_lists.h
Labels: awaiting review, ready to pull, comp:grappler, size:XS

#59567 Add `Tensorflow Forum` as a support group
  README.md
Labels: awaiting review, ready to pull, size:XS

#59280 Update library.md
  tensorflow/lite/g3doc/microcontrollers/library.md
Labels: awaiting review, ready to pull, size:XS, comp:micro

#59895 Updated Broken link for lib_interpreter
  tensorflow/lite/g3doc/examples/object_detection/overview.md
Labels: awaiting review, comp:lite, ready to pull, size:XS

#60025 Remove redundant `static_assert`s
  tensorflow/c/kernels.cc
Labels: ready to pull, size:XS

#57019 [oneDNN] Adding a test for BF16 Round Op
  tensorflow/python/kernel_tests/math_ops/cwise_ops_unary_test.py
Labels: awaiting review, ready to pull, size:XS

#59501 [ROCm] enable rocm for multi_clients_test
  tensorflow/dtensor/python/tests/multi_client_test.py
  tensorflow/dtensor/python/tests/test_backend_util.py
Labels: awaiting review, ready to pull, comp:gpu, size:XS

#60095 [tosa][fix] correct scales of resize to generate right output shape.
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
Labels: awaiting review, size:S

#60066 Update file stale-issues.yml
  .github/workflows/stale-issues.yml
Labels: awaiting review, ready to pull, size:S

#60082 Fix endless loop in tensorflow::wav::DecodeLin16WaveAsFloatVector
  tensorflow/core/lib/wav/wav_io.cc
Labels: awaiting review, ready to pull, size:S, comp:core

#60005 [tosa] Legalize tfl.Rsqrt to tosa.Rsqrt
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
  tensorflow/compiler/mlir/tosa/transforms/tfl_legalize_patterns.td
Labels: awaiting review, size:M

#60107 [NVIDIA TF] Enable GPU bfloat16 casts
  tensorflow/core/kernels/cast_op.cc
  tensorflow/core/kernels/cast_op_gpu.cu.cc
  tensorflow/core/kernels/cast_op_impl.h
  tensorflow/core/kernels/cast_op_impl_bfloat.cc
  tensorflow/core/kernels/cast_op_impl_bool.cc
  tensorflow/core/kernels/cast_op_impl_complex128.cc
  tensorflow/core/kernels/cast_op_impl_complex64.cc
  tensorflow/core/kernels/cast_op_impl_double.cc
  tensorflow/core/kernels/cast_op_impl_half.cc
  tensorflow/core/kernels/cast_op_impl_int16.cc
  tensorflow/core/kernels/cast_op_impl_int32.cc
  tensorflow/core/kernels/cast_op_impl_int64.cc
  tensorflow/core/kernels/cast_op_impl_int8.cc
  tensorflow/core/kernels/cast_op_impl_uint16.cc
  tensorflow/core/kernels/cast_op_impl_uint32.cc
  tensorflow/core/kernels/cast_op_impl_uint64.cc
  tensorflow/core/kernels/cast_op_impl_uint8.cc
Labels: awaiting review, ready to pull, size:M

#56352 [oneDNN] Adding support for QuantizedMaxpool3D
  tensorflow/core/kernels/mkl/BUILD
  tensorflow/core/kernels/mkl/mkl_maxpooling_op.cc
  tensorflow/core/kernels/mkl/mkl_quantized_pooling_ops_test.cc
  tensorflow/core/ops/mkl_nn_ops.cc
Labels: awaiting review, ready to pull, comp:mkl, size:L

#60134 Fixed the broken links in image_classifier.md
  tensorflow/lite/g3doc/inference_with_metadata/task_library/image_classifier.md
Labels: comp:lite, ready to pull, size:XS

#60044 [NVIDIA TF] Prefer NHWC in layout optimizer for bfloat16 on Ampere+ GPUs.
  tensorflow/core/grappler/optimizers/generic_layout_optimizer.cc
Labels: awaiting review, ready to pull, comp:grappler, size:M

#60020 [NVIDIA XLA] Vector BiasAdd Epilogue Fusion for FP8 GEMMs
  tensorflow/compiler/xla/mlir_hlo/lhlo_gpu/IR/lhlo_gpu_ops.td
  tensorflow/compiler/xla/service/gpu/gemm_rewriter.cc
  tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc
  tensorflow/compiler/xla/service/gpu/tests/gemm_rewrite_test.cc
  tensorflow/compiler/xla/translate/mhlo_to_lhlo_with_xla/mhlo_to_lhlo_with_xla.cc
Labels: awaiting review, ready to pull, comp:xla, size:M

#60145 [NVIDIA XLA:GPU] Fused MHA Support in XLA GPU: SE
  tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc
  tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.h
  tensorflow/compiler/xla/stream_executor/dnn.cc
  tensorflow/compiler/xla/stream_executor/dnn.h
  tensorflow/compiler/xla/stream_executor/lazy_op_runner.h
  tensorflow/compiler/xla/stream_executor/stream.h
  tensorflow/tsl/protobuf/dnn.proto
Labels: awaiting review, ready to pull, size:XL

#60110 16 Byte Alignment for FP8 GEMMs in XLA
  tensorflow/compiler/xla/service/gpu/gemm_rewriter.cc
  tensorflow/compiler/xla/service/gpu/tests/gemm_rewrite_test.cc
Labels: awaiting review, ready to pull, comp:xla, size:M

#60143 [NVIDIA TFTRT] Add kFP8 to nvinfer1::DataType enums for TRT 8.6.x
  tensorflow/compiler/tf2tensorrt/common/utils.cc
  tensorflow/compiler/tf2tensorrt/convert/weights.cc
Labels: awaiting review, ready to pull, size:XS, comp:gpu:tensorrt

#60098 Add fuzzer for arbitrary graph execution
  tensorflow/core/common_runtime/BUILD
  tensorflow/core/common_runtime/graph_constructor_fuzz.cc
Labels: awaiting review, ready to pull, size:M, comp:core

#60105 Normalize values during softmax legalization to prevent floating poin…
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
Labels: awaiting review, ready to pull, size:M

#60142 [NVIDIA XLA] Skip TestCudnnConvInt8x32Bias test for sm 6.0 and earlier
  tensorflow/compiler/xla/tests/convolution_cudnn_test.cc
Labels: awaiting review, ready to pull, comp:xla, size:S

#60155 [oneDNN] Enabling optimized implementation for FP32 Eigen Leakyrelu
  tensorflow/core/kernels/BUILD
  tensorflow/core/kernels/cwise_op_leakyrelu.cc
  tensorflow/core/kernels/relu_op.cc
Labels: awaiting review, ready to pull, size:S

#60038 Remove not needed build file
  tensorflow/opensource_only.files
  tensorflow/workspace2.bzl
  third_party/mkl_dnn/mkldnn.BUILD
Labels: ready to pull, size:M

#60173 [Linaro:ARM_CI] Make ARM_CI_EXTENDED run on schedule
  .github/workflows/arm-ci-extended.yml
  tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_nonpip.sh
Labels: awaiting review, ready to pull, comp:mkl, size:S
