Repository tensorflow/tensorflow, pull requests merged in 2024-10, with the labels that each got.

#77115 docs: fix typo
  tensorflow/go/README.md
Labels: ready to pull, size:XS

#77018 fix integer overflow in range
  tensorflow/core/kernels/ragged_range_op.cc
  tensorflow/core/kernels/ragged_range_op_test.cc
  tensorflow/core/kernels/sequence_ops.cc
  tensorflow/core/kernels/sequence_ops_test.cc
  tensorflow/core/ops/math_ops.cc
  tensorflow/python/ops/math_ops_test.py
  tensorflow/python/ops/ragged/BUILD
  tensorflow/python/ops/ragged/ragged_range_op_test.py
Labels: awaiting review, ready to pull, size:M, comp:core

#72232 Switch from `PyEval_CallObject` to `PyObject_Call`
  tensorflow/python/eager/pywrap_tfe_src.cc
  tensorflow/python/lib/core/py_func.cc
Labels: awaiting review, ready to pull, size:S

#78037 Fix documentation
  CONTRIBUTING.md
  SECURITY.md
Labels: awaiting review, ready to pull, size:XS

#76626 Update cpuinfo to enable TF Build on linux ppc64le architecture
  tensorflow/workspace2.bzl
  third_party/cpuinfo/BUILD
  third_party/cpuinfo/cpuinfo_ppc64le_support.patch
Labels: ready to pull, size:S

#62694 Fixing an issue with reflect padding in TfLite GPU delegate
  tensorflow/lite/delegates/gpu/common/tasks/padding.cc
Labels: awaiting review, comp:lite, ready to pull, size:XS

#78711 Update broken link in the Optimize.md
  tensorflow/lite/g3doc/api_docs/python/tf/lite/Optimize.md
Labels: awaiting review, comp:lite, ready to pull, size:XS

#76596 [XLA-CPU] adding a check to handle large constant
  tensorflow/compiler/jit/mark_for_compilation_pass.cc
Labels: awaiting review, ready to pull, size:S

#78793 Remove `maybe_captured`, which was only called recursively.
  tensorflow/python/framework/func_graph.py
Labels: awaiting review, ready to pull, size:S

#77167 Fix `memcpy` call with null data in `SimpleDynamicBuffer`
  tensorflow/compiler/mlir/lite/utils/string_utils.cc
  tensorflow/lite/string_util_test.cc
Labels: awaiting review, comp:lite, ready to pull, size:S

#78838 Include NEON_2_SSE header for XNNPACK in TFLite
  tensorflow/lite/CMakeLists.txt
Labels: awaiting review, ready to pull, size:XS
