Repository tensorflow/tensorflow, pull requests merged in 2024-09, with the labels that each got.

#74013 Correct "seperated" to "separated"
  tensorflow/compiler/mlir/tensorflow/translate/mlir_roundtrip_flags.cc
Labels: ready to pull, size:XS

#75100 Fix typos in documentation strings
  tensorflow/python/checkpoint/async_checkpoint_helper.py
  tensorflow/python/checkpoint/checkpoint.py
  tensorflow/python/checkpoint/checkpoint_adapter.py
  tensorflow/python/checkpoint/checkpoint_management.py
  tensorflow/python/checkpoint/checkpoint_options.py
  tensorflow/python/checkpoint/save_util_v1.py
  tensorflow/python/checkpoint/util.py
Labels: ready to pull, size:S

#73692 Fix typos in documentation strings
  tensorflow/python/autograph/operators/control_flow.py
  tensorflow/python/autograph/tests/loop_basic_test.py
  tensorflow/python/checkpoint/sharding/sharding_policies.py
  tensorflow/python/client/tf_session_helper.cc
  tensorflow/python/compiler/tensorrt/model_tests/model_handler.py
  tensorflow/python/compiler/tensorrt/test/base_test.py
  tensorflow/python/compiler/tensorrt/test/biasadd_matmul_test.py
  tensorflow/python/compiler/tensorrt/test/cast_test.py
  tensorflow/python/compiler/tensorrt/test/dynamic_input_shapes_test.py
  tensorflow/python/compiler/tensorrt/test/int32_test.py
  tensorflow/python/compiler/tensorrt/test/shape_output_test.py
  tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py
Labels: awaiting review, ready to pull, size:S

#74954 Code refactor
  tensorflow/python/framework/byte_swap_tensor.py
Labels: awaiting review, ready to pull, size:XS

#74596 BatchMatrixInverse deprecation notice
  tensorflow/core/api_def/base_api/api_def_BatchMatrixInverse.pbtxt
Labels: awaiting review, ready to pull, size:S, comp:core

#60056 Go: add support for empty tags-set when loading saved model
  tensorflow/go/saved_model.go
  tensorflow/go/saved_model_test.go
  tensorflow/go/testdata/saved_model/half_plus_two_empty_tags/00000123/saved_model.pb
  tensorflow/go/testdata/saved_model/half_plus_two_empty_tags/00000123/variables/variables.data-00000-of-00001
  tensorflow/go/testdata/saved_model/half_plus_two_empty_tags/00000123/variables/variables.index
Labels: ready to pull, size:S

#74666 Fixed the error message in nn_ops.cc
  tensorflow/core/kernels/avgpooling_op.cc
  tensorflow/core/kernels/maxpooling_op.cc
  tensorflow/core/ops/nn_ops.cc
  tensorflow/dtensor/mlir/tests/spmd_squeeze.mlir
  tensorflow/python/kernel_tests/nn_ops/pooling_ops_test.py
Labels: awaiting review, ready to pull, size:XS, comp:core

#75567 Updating the error message in flatbuffer_translate.cc
  tensorflow/compiler/mlir/lite/flatbuffer_translate.cc
  tensorflow/compiler/mlir/lite/tf_tfl_translate_cl.cc
  tensorflow/compiler/mlir/lite/tf_tfl_translate_cl.h
Labels: awaiting review, comp:lite, ready to pull, size:XS

#75698 Fix typos in documentation strings
  tensorflow/python/compiler/tensorrt/model_tests/model_handler.py
  tensorflow/python/compiler/tensorrt/utils.py
Labels: awaiting review, ready to pull, size:S

#74058 Fix : Argument missing in TPUClusterResolver.connect
  tensorflow/python/distribute/cluster_resolver/tpu/tpu_cluster_resolver.py
Labels: awaiting review, ready to pull, size:XS

#76298 Updated tf.compat.as_str API with Args, Returns and Raises in compat.py
  tensorflow/python/util/compat.py
Labels: awaiting review, ready to pull, size:S

#76337 Update lite.py
  tensorflow/lite/python/lite.py
Labels: awaiting review, comp:lite, ready to pull, size:XS

#71580 [oneDNN][BugFix] Prevent AMP exit on supported CPU platforms
  tensorflow/core/grappler/optimizers/auto_mixed_precision.cc
  tensorflow/core/grappler/optimizers/auto_mixed_precision_test.cc
  tensorflow/core/util/util.cc
  tensorflow/core/util/util.h
Labels: awaiting review, ready to pull, comp:grappler, size:S

#75075 [Tosa] Update Sin/Cos operators legalization
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: awaiting review, ready to pull, size:L, comp:lite-tosa

#76252 Fix integer overflow in tf.range
  tensorflow/core/kernels/ragged_range_op.cc
  tensorflow/core/kernels/sequence_ops.cc
  tensorflow/core/ops/math_ops.cc
  tensorflow/python/ops/math_ops_test.py
  tensorflow/python/ops/ragged/BUILD
  tensorflow/python/ops/ragged/ragged_range_op_test.py
Labels: awaiting review, ready to pull, size:M, comp:core
