Repository tensorflow/tensorflow, pull requests merged in 2024-11, with the labels that each got.

#62998 Fix TensorFlowLiteSwift `Interpreter` use-after-free bug
  tensorflow/lite/swift/Sources/Interpreter.swift
Labels: awaiting review, comp:lite, ready to pull, size:XS

#62484 lite: add tensorflowlite_flex to minimal example
  tensorflow/lite/examples/minimal/CMakeLists.txt
  tensorflow/lite/examples/minimal/README.md
Labels: comp:lite, ready to pull, size:S

#79593 Fixing broken link for unicode
  tensorflow/core/api_def/base_api/api_def_AsString.pbtxt
Labels: awaiting review, ready to pull, size:XS, comp:core

#79758 Update broken link for TensorFlow Lite Task Library hyperlink in metadata.md
  tensorflow/lite/g3doc/models/convert/metadata.md
Labels: ready to pull, size:XS

#79759 Update broken link for create the TFLite op hyperlink in convert_mode…
  tensorflow/lite/g3doc/models/convert/convert_models.md
Labels: ready to pull, size:XS

#80022 Update 02 broken links in overview.md
  tensorflow/lite/g3doc/examples/audio_classification/overview.md
Labels: ready to pull, size:XS

#80492 Update broken link in jax_conversion overview.md
  tensorflow/lite/g3doc/examples/jax_conversion/overview.md
Labels: ready to pull, size:XS

#80490 Update broken link in overview.md
  tensorflow/lite/g3doc/examples/bert_qa/overview.md
Labels: ready to pull, size:XS

#80484 Fix typos in documentation strings
  tensorflow/python/distribute/experimental/rpc/rpc_ops.py
  tensorflow/python/distribute/input_lib.py
  tensorflow/python/distribute/integration_test/saved_model_test.py
  tensorflow/python/distribute/tpu_strategy_test.py
  tensorflow/python/distribute/values.py
  tensorflow/python/grappler/layout_optimizer_test.py
  tensorflow/python/grappler/remapper_test.py
Labels: awaiting review, ready to pull, size:S

#79777 Update 02 broken links in gpu.md
  tensorflow/lite/g3doc/performance/gpu.md
Labels: awaiting review, comp:lite, ready to pull, size:XS

#80574 Update graph_info.h to avoid warning: multi-line comment [-Wcomment]
  tensorflow/lite/graph_info.h
Labels: ready to pull, size:XS

#80118 upgrade rules_android_ndk
  tensorflow/workspace2.bzl
Labels: awaiting review, ready to pull, size:XS

#79786 Update ByteSwapTFLiteModel function for s390x
  tensorflow/compiler/mlir/lite/core/model_builder_base.h
Labels: awaiting review, comp:lite, ready to pull, size:XS

#81246 Update a broken link in overview.md
  tensorflow/lite/g3doc/examples/pose_estimation/overview.md
Labels: awaiting review, comp:lite, ready to pull, size:XS

#81245 Update 02 broken links in overview.md
  tensorflow/lite/g3doc/examples/object_detection/overview.md
Labels: awaiting review, comp:lite, ready to pull, size:XS
