Repository tensorflow/tensorflow, pull requests merged in 2025-03, with the labels that each got.

#86840 [oneDNN CPU] Prevent perf penalty due to large constants copy
  tensorflow/compiler/jit/mark_for_compilation_pass.cc
Labels: awaiting review, ready to pull, size:S

#88354 [mlir][tosa] Rename Tosa ReduceProd to ReduceProduct
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
Labels: kokoro:force-run, ready to pull, size:S, comp:lite-tosa

#88492 [mlir][tosa] Remove out_shape from transpose_conv2d and Legalize Pad op's pad_const to be rank-1
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_tf.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
Labels: kokoro:force-run, ready to pull, size:L

#62153 [tosa] fix legalization of mul op for unequal ranks
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
Labels: kokoro:force-run, ready to pull, size:S, comp:lite-tosa

#62453 [TOSA] add tests for legalization of quantized MUL,SUB,ADD operators with unequal ranks
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
Labels: awaiting review, kokoro:force-run, ready to pull, size:M, comp:lite-tosa

#70679 [TOSA] support tfl.batch_matmul with input broadcasting
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
Labels: awaiting review, kokoro:force-run, ready to pull, size:M, comp:lite-tosa

#62452 [tosa] fix legalization of SquaredDifference op for unequal ranks
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
Labels: awaiting review, ready to pull, size:S, comp:lite-tosa

#88737 Fix typos in documentation strings
  tensorflow/python/framework/extension_type_field.py
  tensorflow/python/framework/memory_checker.py
  tensorflow/python/framework/op_allowlist_namespace_test.py
  tensorflow/python/framework/op_callbacks.py
  tensorflow/python/framework/op_def_registry.cc
  tensorflow/python/framework/tensor.py
  tensorflow/python/framework/type_spec.py
Labels: ready to pull, size:S

#88757 [TOSA] fix test_mul_with_unequal_ranks_qi8 LIT test
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
Labels: kokoro:force-run, ready to pull, size:S, comp:lite-tosa

#88987 [mlir][tosa] Update control flow variable names and Fix lit tests for max_pool2d and pad op
  tensorflow/compiler/mlir/tosa/tests/strip-quant-types.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
Labels: kokoro:force-run, ready to pull, size:S, comp:lite-tosa

#89208 Fix typos in documentation strings
  tensorflow/python/feature_column/feature_column_test.py
  tensorflow/python/feature_column/feature_column_v2_test.py
  tensorflow/python/framework/composite_tensor_gradient.py
  tensorflow/python/framework/extension_type.py
  tensorflow/python/framework/test_util.py
  tensorflow/python/framework/type_spec.py
Labels: ready to pull, size:S

#89348 Fixed minor documentation typos
  README.md
Labels: ready to pull, size:XS

#89032 Allow empty configuration values to be supplied from environment
  configure.py
Labels: awaiting review, ready to pull, size:XS

#83717 Adds f16 and bf16 type support for tfl.strided_slice, tfl.gather_nd, tfl.gather and tfl.less ops
  tensorflow/lite/kernels/comparisons.cc
  tensorflow/lite/kernels/comparisons_test.cc
  tensorflow/lite/kernels/gather.cc
  tensorflow/lite/kernels/gather_nd.cc
  tensorflow/lite/kernels/gather_nd_test.cc
  tensorflow/lite/kernels/gather_test.cc
  tensorflow/lite/kernels/strided_slice.cc
  tensorflow/lite/kernels/strided_slice_test.cc
Labels: comp:lite, size:L

#89210 Qualcomm AI Engine Direct - Provide op optimization
  tensorflow/lite/experimental/litert/vendors/qualcomm/compiler/BUILD
  tensorflow/lite/experimental/litert/vendors/qualcomm/compiler/qnn_compose_graph.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/builders/BUILD
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/builders/conv2d_op_builder.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/builders/fully_connected_op_builder.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/builders/fully_connected_op_builder_htp.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/builders/fully_connected_op_builder_htp.h
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/builders/op_builder.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/builders/op_builder.h
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/common.h
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/wrappers/tensor_wrapper.h
Labels: awaiting review, ready to pull, size:L

#89617 Qualcomm AI Engine Direct - Update soc model
  tensorflow/lite/experimental/litert/vendors/qualcomm/supported_soc.csv
Labels: ready to pull, size:M

#89271 Fixing bugs and old code in the tf_env script
  tools/tf_env_collect.sh
Labels: ready to pull, size:M

#89725 Qualcomm AI Engine Direct - Remove Unused Variable
  tensorflow/lite/experimental/litert/vendors/qualcomm/compiler/qnn_compiler_plugin.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/builders/split_op_builder.cc
Labels: ready to pull, size:S

#89907 [mlir][tosa] Update Tensorflow to match TOSA v1.0 specification (part 4)
  tensorflow/compiler/mlir/tosa/tests/convert-tfl-uint8.mlir
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline-filtered.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-stateful.mlir
  tensorflow/compiler/mlir/tosa/transforms/convert_tfl_uint8.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_tfl.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_utils.h
Labels: awaiting review, kokoro:force-run, ready to pull, size:XL, comp:lite-tosa

#89988 [mlir][tosa] Fix Int Floor Div bug for TF/TFL lowering to TOSA
  tensorflow/compiler/mlir/tosa/tests/tf-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tf-unequal-ranks.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-to-tosa-pipeline.mlir
  tensorflow/compiler/mlir/tosa/tests/tfl-unequal-ranks.mlir
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.cc
  tensorflow/compiler/mlir/tosa/transforms/legalize_common.h
Labels: awaiting review, ready to pull, size:M, comp:lite-tosa

#89337 Qualcomm AI Engine Direct - Compile QINT16 as QUINT16
  tensorflow/lite/experimental/litert/vendors/qualcomm/compiler/qnn_compiler_plugin.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/compiler/qnn_compiler_plugin_test.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/compiler/qnn_compose_graph.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/common.h
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/utils/BUILD
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/utils/miscs.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/utils/miscs.h
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/utils/utils_test.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/wrappers/quantize_params_wrapper.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/wrappers/quantize_params_wrapper.h
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/wrappers/tensor_wrapper.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/wrappers/tensor_wrapper.h
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/wrappers/tests/BUILD
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/wrappers/tests/quantize_params_wrapper_test.cc
  tensorflow/lite/experimental/litert/vendors/qualcomm/core/wrappers/tests/tensor_wrapper_test.cc
Labels: ready to pull, size:L

#90103 Fix typos in documentation strings
  tensorflow/python/keras/distribute/distributed_training_utils_v1.py
  tensorflow/python/keras/engine/keras_tensor.py
  tensorflow/python/keras/engine/training.py
  tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py
  tensorflow/python/keras/utils/generic_utils.py
  tensorflow/python/keras/utils/metrics_utils.py
Labels: ready to pull, size:S
